Disable rna sync

diff --git a/actin/local/deployment/do_deploy_actin b/actin/local/deployment/do_deploy_actin
--- a/actin/local/deployment/do_deploy_actin
+++ b/actin/local/deployment/do_deploy_actin
@@ -1,9 +1,15 @@
 #!/bin/bash
 
+source message_functions || exit 1
+
 version=$1 && shift
 vm_name=$1 && shift
 vm_project=$1 && shift
 vm_zone=$1 && shift
+
+if [[ -z "${version}" || -z "${vm_name}" || -z "${vm_project}" || -z "${vm_zone}" ]]; then
+    error "Parameters missing. Exiting.";
+fi
 
 trigger_id="08e2aa2d-33ce-4199-bd3b-3ccf06518483"
 deployed_by=$USER
