Update report generation for QC trending (RETORT)
- Include lab failures (isolation and library preparation)
- Run on ops-vm instead of local computer. Needed packages are installed on the ops-vm system install of R
- Place GIAB resource file in /data/tmp/ instead of /tmp/

diff --git a/qctrending/make_retort_report b/qctrending/make_retort_report
--- a/qctrending/make_retort_report
+++ b/qctrending/make_retort_report
@@ -25,14 +25,21 @@ today=$(date +%Y-%m-%d)
 
 outDir=$(realpath ${outDir})
 outDataFile=${outDir}/RETORT_data_${startDate}_${endDate}_${today}
+outIsoFailFile=${outDir}/RETORT_iso_fail_${startDate}_${endDate}_${today}
+outPrepFailFile=${outDir}/RETORT_prep_fail_${startDate}_${endDate}_${today}
 outReportFile="${outDir}/RETORT_report_${startDate}_${endDate}_${today}.html"
 
 scriptdir=$(dirname $(realpath "$0"))
 
 info "Gather data"
-gsutil cp gs://hmf-ops-data/qctrending/HMF-FOR-096.csv /tmp/HMF-FOR-096.csv || die "Could not fetch GIAB data"
+gsutil cp gs://hmf-ops-data/qctrending/HMF-FOR-096.csv /data/tmp/HMF-FOR-096.csv || die "Could not fetch GIAB data"
 python3 ${scriptdir}/gather_flowcell_sample_data.py -s ${startDate} -e ${endDate} -o ${outDataFile} || die "Could not gather data"
-info "Generate report"
-Rscript -e "rmarkdown::render('${scriptdir}/generate_qc_trends_report.Rmd', output_file='${outReportFile}', params=list(data_file='${outDataFile}'))" || die "Could not generate report"
+echo -e "sample\tsample type\tdate\tisolation status" > ${outIsoFailFile}
+lama statuses | cut -f1,2,5,6 | grep FAILED_FINAL | grep TUMOR_TISSUE | awk -F "\t" -v sDate="$startDate" -v eDate="$endDate" '$3 >= sDate && $3 <= eDate' >> ${outIsoFailFile}
+echo -e "sample\tsample type\tdate\tprep status" > ${outPrepFailFile}
+lama statuses | cut -f1,2,5,7 | grep FAILED_FINAL | grep TUMOR_TISSUE | awk -F "\t" -v sDate="$startDate" -v eDate="$endDate" '$3 >= sDate && $3 <= eDate' >> ${outPrepFailFile}
 
-rm /tmp/HMF-FOR-096.csv
+info "Generate report"
+Rscript -e "rmarkdown::render('${scriptdir}/generate_qc_trends_report.Rmd', output_file='${outReportFile}', params=list(data_file='${outDataFile}', iso_fail_file='${outIsoFailFile}', prep_fail_file='${outPrepFailFile}'))" || die "Could not generate report"
+
+rm /data/tmp/HMF-FOR-096.csv
