Renamed PEACH output dirs and made smaller panel the standard

diff --git a/pgx/create_pgx_venv b/pgx/create_pgx_venv
--- a/pgx/create_pgx_venv
+++ b/pgx/create_pgx_venv
@@ -3,7 +3,7 @@
 source locate_files || exit 1
 source message_functions || exit 1
 
-info "Starting creation of PGX venv"
+info "Starting creation of PEACH venv"
 
 if [[ $# -eq 0 ]]; then
   venv_dir=$(locate_pgx_venv_dir)
@@ -11,15 +11,15 @@ else
   venv_dir=$1 && shift
 fi
 
-pgx_requirements=$(locate_pgx_requirements)
+peach_requirements=$(locate_pgx_requirements)
 
 if [[ -d "${venv_dir}" ]] || [[ -f "${venv_dir}" ]]; then
-    info "Delete existing PGX venv"
-    rm -r  "${venv_dir}" || die "Could not delete existing PGX venv"
+    info "Delete existing PEACH venv"
+    rm -r  "${venv_dir}" || die "Could not delete existing PEACH venv"
 fi
 
-python3 -m venv "${venv_dir}" || die "Could not create PGX venv"
-source "${venv_dir}/bin/activate" || die "Could not activate PGX venv"
-pip install -r "${pgx_requirements}" || die "Could not install PGX pip packages"
+python3 -m venv "${venv_dir}" || die "Could not create PEACH venv"
+source "${venv_dir}/bin/activate" || die "Could not activate PEACH venv"
+pip install -r "${peach_requirements}" || die "Could not install PEACH pip packages"
 
-info "Finished creating PGX venv"
+info "Finished creating PEACH venv"
diff --git a/pgx/run_pgx_pilot b/pgx/run_pgx_pilot
--- a/pgx/run_pgx_pilot
+++ b/pgx/run_pgx_pilot
@@ -18,7 +18,7 @@ main() {
   local optional_recreate_bed_arg
 
   venv_dir=$(locate_pgx_venv_dir)  # default argument
-  panel_name="${FULL_DPYD_PANEL_NAME}"  # default argument
+  panel_name="${MINIMAL_DPYD_PANEL_NAME}"  # default argument
   optional_recreate_bed_arg=""  # default argument
 
   while [[ $# -gt 0 ]]
@@ -50,19 +50,19 @@ main() {
   [[ -n ${panel_name} ]] || die "Variable 'panel' has not been set. Consider using the default argument."
 
   # START VIRTUAL ENV
-  source "${venv_dir}/bin/activate" || die "Could not activate PGX venv"
+  source "${venv_dir}/bin/activate" || die "Could not activate PEACH venv"
 
   if [[ "${panel_name}" == "${FULL_DPYD_PANEL_NAME}" ]]; then
-    local output_dir_name="pgx_pilot"
+    local output_dir_name="peach_pilot_full"
   elif [[ "${panel_name}" == "${MINIMAL_DPYD_PANEL_NAME}" ]]; then
-    local output_dir_name="pgx_pilot_min"
+    local output_dir_name="peach_pilot"
   else
-    die "Unrecognized panel name ${panel_name}. Known panel names: '${FULL_DPYD_PANEL_NAME}', '${MINIMAL_DPYD_PANEL_NAME}'"
+    die "Unrecognized panel name ${panel_name}. Known panel names: '${MINIMAL_DPYD_PANEL_NAME}', '${FULL_DPYD_PANEL_NAME}'"
   fi
   local output_dir="${run_dir}/${output_dir_name}"
 
-  local version_pgx_tool
-  version_pgx_tool=$(echo "pilot" | tr "_" " " | tr "v" " "| awk '{print $1}')
+  local peach_version
+  peach_version=$(echo "pilot" | tr "_" " " | tr "v" " "| awk '{print $1}')
 
   local ref_sample
   ref_sample=$(load_ref_sample_from_metadata "${run_dir}") || die "Could not get ref sample from metadata"
@@ -74,26 +74,26 @@ main() {
   germline_vcf=$(locate_purple_germline_variants "${run_dir}") || die "Could not get purple germline vcf path"
 
   # REFERENCES
-  local pgx_tool
-  pgx_tool=$(locate_pgx_main) || die "Could not get pgx tool path"
-  # pgx_tool=$HOME/repos/scripts/pgx/src/main.py
-  local pgx_resource_dir
-  pgx_resource_dir=$(locate_pgx_resource_dir) || die "Could not get pgx resource dir"
+  local peach_main
+  peach_main=$(locate_pgx_main) || die "Could not get PEACH main.py path"
+  # peach_main=$HOME/repos/scripts/pgx/src/main.py
+  local peach_resource_dir
+  peach_resource_dir=$(locate_pgx_resource_dir) || die "Could not get PEACH resource dir"
   local vcftools_tool
   vcftools_tool=$(locate_vcftools) || die "Could not get vcftools path"
 
-  export PYTHONPATH="${PYTHONPATH}:${pgx_tool}/../"
+  export PYTHONPATH="${PYTHONPATH}:${peach_main}/../"
 
   if [[ -d "${output_dir}" ]]; then
-      info "PGX pilot dir exist. PGX dir will first be removed and then be replaced"
-      rm -r "${output_dir}" || die "Could not remove existing PGX pilot dir"
+      info "PEACH pilot dir exist. PEACH dir will first be removed and then be replaced"
+      rm -r "${output_dir}" || die "Could not remove existing PEACH pilot dir"
   fi
 
   # RUN
-  python "${pgx_tool}" "${germline_vcf}" "${tumor_sample}" "${ref_sample}" "${version_pgx_tool}" "${output_dir}"  \
-      "${pgx_resource_dir}/panelfiles/${panel_name}" "${vcftools_tool}" \
-      --transcript_tsv "${pgx_resource_dir}/panelfiles/all_genes.37.tsv" ${optional_recreate_bed_arg} \
-      || die "PGX pilot failed"
+  python "${peach_main}" "${germline_vcf}" "${tumor_sample}" "${ref_sample}" "${peach_version}" "${output_dir}"  \
+      "${peach_resource_dir}/panelfiles/${panel_name}" "${vcftools_tool}" \
+      --transcript_tsv "${peach_resource_dir}/panelfiles/all_genes.37.tsv" ${optional_recreate_bed_arg} \
+      || die "PEACH pilot failed"
 
   info "Finished ${SCRIPT_NAME}"
 }
diff --git a/pgx/run_pgx_tests b/pgx/run_pgx_tests
--- a/pgx/run_pgx_tests
+++ b/pgx/run_pgx_tests
@@ -1,7 +1,7 @@
 source locate_files || exit 1
 source message_functions || exit 1
 
-info "Run PGX tests"
+info "Run PEACH tests"
 
 if [[ $# -eq 0 ]]; then
   venv_dir=$(locate_pgx_venv_dir)
@@ -9,23 +9,23 @@ else
   venv_dir=$1 && shift
 fi
 
-# pgx_base_dir=$HOME/repos/scripts/pgx
-pgx_base_dir=$(locate_pgx_dir)
+# peach_repo_base_dir=$HOME/repos/scripts/pgx
+peach_repo_base_dir=$(locate_pgx_dir)
 
 # START VIRTUAL ENV
-source "${venv_dir}/bin/activate" || die "Could not activate PGX venv"
+source "${venv_dir}/bin/activate" || die "Could not activate PEACH venv"
 
-export PYTHONPATH="${PYTHONPATH}:${pgx_base_dir}/src/"
-export MYPYPATH="${MYPYPATH}:${pgx_base_dir}/src/"
+export PYTHONPATH="${PYTHONPATH}:${peach_repo_base_dir}/src/"
+export MYPYPATH="${MYPYPATH}:${peach_repo_base_dir}/src/"
 
-python -m unittest discover --buffer --verbose --start-directory "${pgx_base_dir}" || die "Some PGX tests failed"
+python -m unittest discover --buffer --verbose --start-directory "${peach_repo_base_dir}" || die "Some PEACH tests failed"
 
-info "PGX tests succeeded"
+info "PEACH tests succeeded"
 
-mypy_config="${pgx_base_dir}/mypy.ini"
+mypy_config="${peach_repo_base_dir}/mypy.ini"
 
-info "Run PGX type check"
+info "Run PEACH type check"
 
-mypy "${pgx_base_dir}/src" --config-file "${mypy_config}" --namespace-packages --explicit-package-bases || die "PGX type check failed"
+mypy "${peach_repo_base_dir}/src" --config-file "${mypy_config}" --namespace-packages --explicit-package-bases || die "PEACH type check failed"
 
-info "PGX type succeeded"
+info "PEACH type succeeded"
