Improve pgx test run script and make CLI messages more consistent

diff --git a/pgx/create_pgx_venv b/pgx/create_pgx_venv
--- a/pgx/create_pgx_venv
+++ b/pgx/create_pgx_venv
@@ -3,7 +3,7 @@
 source locate_files
 source message_functions
 
-info "Starting creation of pgx venv"
+info "Starting creation of PGX venv"
 
 if [[ $# -eq 0 ]]; then
   venv_dir=$(locate_pgx_venv_dir)
@@ -14,12 +14,12 @@ fi
 pgx_requirements=$(locate_pgx_requirements)
 
 if [[ -d "${venv_dir}" ]] || [[ -f "${venv_dir}" ]]; then
-    info "Delete existing pgx venv"
+    info "Delete existing PGX venv"
     rm -r  "${venv_dir}"
 fi
 
-python3 -m venv "${venv_dir}" || die "Could not create pgx venv"
-source "${venv_dir}/bin/activate" || die "Could not activate pgx venv"
-pip install -r "${pgx_requirements}" || die "Could not install pgx pip packages"
+python3 -m venv "${venv_dir}" || die "Could not create PGX venv"
+source "${venv_dir}/bin/activate" || die "Could not activate PGX venv"
+pip install -r "${pgx_requirements}" || die "Could not install PGX pip packages"
 
-info "Finished creating pgx venv"
+info "Finished creating PGX venv"
diff --git a/pgx/run_pgx_pilot b/pgx/run_pgx_pilot
--- a/pgx/run_pgx_pilot
+++ b/pgx/run_pgx_pilot
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 
 source locate_files
+source message_functions
 source metadata_functions
+
+info "Start running PGX pilot script"
 
 run_dir=$1 && shift
 
@@ -10,10 +13,9 @@ if [[ $# -eq 0 ]]; then
 else
   venv_dir=$1 && shift
 fi
-activate_venv="${venv_dir}/bin/activate"
 
 # START VIRTUAL ENV
-source "${activate_venv}"
+source "${venv_dir}/bin/activate" || die "Could not activate PGX venv"
 
 output_dir=${run_dir}/pgx_pilot
 
@@ -24,7 +26,7 @@ tumor_sample=$(load_tumor_sample_from_metadata "${run_dir}")
 
 if [[ -d "${output_dir}" ]]; then
     rm -r "${output_dir}"
-    echo "[INFO] pgx pilot dir exist. Pgx dir is just removed and will be replaced"
+    info "[INFO] PGX pilot dir exist. PGX dir is just removed and will be replaced"
 fi
 
 germline_vcf=$(locate_germline_variants "${run_dir}" "${ref_sample}")
diff --git a/pgx/run_pgx_tests b/pgx/run_pgx_tests
--- a/pgx/run_pgx_tests
+++ b/pgx/run_pgx_tests
@@ -1,4 +1,18 @@
 source locate_files
+source message_functions
+
+info "Run PGX tests"
+
+if [[ $# -eq 0 ]]; then
+  venv_dir=$(locate_pgx_venv_dir)
+else
+  venv_dir=$1 && shift
+fi
+
+# START VIRTUAL ENV
+source "${venv_dir}/bin/activate" || die "Could not activate PGX venv"
 
 pgx_base_dir=$(locate_pgx_dir)
-python -m unittest discover --verbose --start-directory "${pgx_base_dir}"
+python -m unittest discover --verbose --start-directory "${pgx_base_dir}" || die "Some PGX tests failed"
+
+info "PGX tests succeeded"
