create script for panel flow

diff --git a/hmftools/patientreporter/ops-vm/panel/create_panel_report b/hmftools/patientreporter/ops-vm/panel/create_panel_report
--- a/hmftools/patientreporter/ops-vm/panel/create_panel_report
+++ b/hmftools/patientreporter/ops-vm/panel/create_panel_report
@@ -47,73 +47,73 @@ if [[ $( gsutil ls gs://patient-reporter-manual-prod-1/ | grep ${sample} | grep 
     fi
 fi
 
-### Copy run data from bucket to local in vm
-temp_folder_path=$( pwd )"/temp_cp_${set}"
-mkdir $temp_folder_path
-gsutil -m cp ${set_url}/pipeline.version $temp_folder_path/ &> $temp_folder_path/copy.log
-gsutil -m cp -r ${set_url}/purple/ $temp_folder_path/ &>> $temp_folder_path/copy.log
-
-if [[ $( cat $temp_folder_path/copy.log | grep "CommandException:" | wc -l ) > 0 ]]; then
-    warn "Making the copy gave errors (see below). Exiting."
-    cat $temp_folder_path/copy.log
-    rm -r $temp_folder_path/
-    exit 1
-fi
-# create folder for report
-mkdir ${temp_folder_path}/new_report
-output_dir_report=${temp_folder_path}/new_report
-output_dir_data_report=${temp_folder_path}/new_report
-
-
-do_panel_report_for_run ${temp_folder_path} ${sample} ${barcode}  \
-      -output_dir_report ${output_dir_report} \
-      -output_dir_data ${output_dir_data_report} "$@" &> ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log
-
-if [[ $( ls ${temp_folder_path}/new_report/ | grep ${sample} | grep .pdf | wc -l ) > 0 ]]; then
-    report=$( ls ${temp_folder_path}/new_report | grep ".pdf" )
-    info "The report $report has been created"
-else
-    warn "No report has been created. Please see below the warnings/errors in the panel reporter log:"
-    cat ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log | grep "WARN\|ERROR\|Exception in thread"
-    rm -r ${temp_folder_path}/ 2>&1
-    warn "The script will end here. Exiting"
-    exit 1
-fi
-
-#### check log file of making the report
-if [[ $( cat ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log | grep "WARN \|Exception in thread" | grep -v "has already been reported" |  wc -l ) > 0 ]]; then
-    warn "Running the patient reporter gave warnings/errors, please check using: gsutil cat gs://patient-reporter-manual-prod-1/${sample}_${barcode}_manual_panelreporter.log"
-else
-    cat ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log | grep 'WARN ' | grep "has already been reported"
-    info "No warnings/errors (except possibly already reported) in running the patient reporter. If you still want to inspect the log file you can run: gsutil cat gs://patient-reporter-manual-prod-1/${sample}_${barcode}_manual_panelreporter.log"
-fi
-
-#### cp report to gs://patient-reporter-manual-prod-1/ and remove temporary run folder
-gsutil -q cp -r ${temp_folder_path}/new_report/* gs://patient-reporter-manual-prod-1/
-info "The report and the related log file can be found in gs://patient-reporter-manual-prod-1/:"
-gsutil ls gs://patient-reporter-manual-prod-1/ | grep ${sample}
-
-#### cp report to sharing bucket (gs://oncopanel-result-files-nki/ in hmf-share)
-gsutil -q cp -r ${temp_folder_path}/new_report/*.pdf gs://oncopanel-result-files-nki/
-panel_vcf_name=$(locate_purple_somatic_variants_panel ${temp_folder_path})
-gsutil -q cp -r ${temp_folder_path}/purple/{panel_vcf_name} gs://oncopanel-result-files-nki/
-info "The report and the related vcf file are shared in gs://oncopanel-result-files-nki/:"
-gsutil ls gs://oncopanel-result-files-nki/ | grep ${sample}
-
-### remove temporary folder
-rm -r ${temp_folder_path}/ 2>&1
-
-### Patch reporting created endpoint
-api_update_json=$( gsutil ls gs://patient-reporter-manual-prod-1/ | grep ${sample} | grep "api-update.json")
-echo '[INPUT] Do you want to update the reporting created endpoint? Please answer Y or N.'
-read answer
-if [[ $answer == 'Y' ]]; then
-  post_api_created_report ${api_update_json} ${sample}
-fi
-
-
-echo '[INPUT] Do you want to also do the final processing (since the report has been shared) ? Please answer Y or N.'
-read answer
-if [[ $answer == 'Y' ]]; then
-    copy_panel_report_to_final_reports_gcp ${set}
-fi
+#### Copy run data from bucket to local in vm
+#temp_folder_path=$( pwd )"/temp_cp_${set}"
+#mkdir $temp_folder_path
+#gsutil -m cp ${set_url}/pipeline.version $temp_folder_path/ &> $temp_folder_path/copy.log
+#gsutil -m cp -r ${set_url}/purple/ $temp_folder_path/ &>> $temp_folder_path/copy.log
+#
+#if [[ $( cat $temp_folder_path/copy.log | grep "CommandException:" | wc -l ) > 0 ]]; then
+#    warn "Making the copy gave errors (see below). Exiting."
+#    cat $temp_folder_path/copy.log
+#    rm -r $temp_folder_path/
+#    exit 1
+#fi
+## create folder for report
+#mkdir ${temp_folder_path}/new_report
+#output_dir_report=${temp_folder_path}/new_report
+#output_dir_data_report=${temp_folder_path}/new_report
+#
+#
+#do_panel_report_for_run ${temp_folder_path} ${sample} ${barcode}  \
+#      -output_dir_report ${output_dir_report} \
+#      -output_dir_data ${output_dir_data_report} "$@" &> ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log
+#
+#if [[ $( ls ${temp_folder_path}/new_report/ | grep ${sample} | grep .pdf | wc -l ) > 0 ]]; then
+#    report=$( ls ${temp_folder_path}/new_report | grep ".pdf" )
+#    info "The report $report has been created"
+#else
+#    warn "No report has been created. Please see below the warnings/errors in the panel reporter log:"
+#    cat ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log | grep "WARN\|ERROR\|Exception in thread"
+#    rm -r ${temp_folder_path}/ 2>&1
+#    warn "The script will end here. Exiting"
+#    exit 1
+#fi
+#
+##### check log file of making the report
+#if [[ $( cat ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log | grep "WARN \|Exception in thread" | grep -v "has already been reported" |  wc -l ) > 0 ]]; then
+#    warn "Running the patient reporter gave warnings/errors, please check using: gsutil cat gs://patient-reporter-manual-prod-1/${sample}_${barcode}_manual_panelreporter.log"
+#else
+#    cat ${temp_folder_path}/new_report/${sample}_${barcode}_manual_panelreporter.log | grep 'WARN ' | grep "has already been reported"
+#    info "No warnings/errors (except possibly already reported) in running the patient reporter. If you still want to inspect the log file you can run: gsutil cat gs://patient-reporter-manual-prod-1/${sample}_${barcode}_manual_panelreporter.log"
+#fi
+#
+##### cp report to gs://patient-reporter-manual-prod-1/ and remove temporary run folder
+#gsutil -q cp -r ${temp_folder_path}/new_report/* gs://patient-reporter-manual-prod-1/
+#info "The report and the related log file can be found in gs://patient-reporter-manual-prod-1/:"
+#gsutil ls gs://patient-reporter-manual-prod-1/ | grep ${sample}
+#
+##### cp report to sharing bucket (gs://oncopanel-result-files-nki/ in hmf-share)
+#gsutil -q cp -r ${temp_folder_path}/new_report/*.pdf gs://oncopanel-result-files-nki/
+#panel_vcf_name=$(locate_purple_somatic_variants_panel ${temp_folder_path})
+#gsutil -q cp -r ${temp_folder_path}/purple/{panel_vcf_name} gs://oncopanel-result-files-nki/
+#info "The report and the related vcf file are shared in gs://oncopanel-result-files-nki/:"
+#gsutil ls gs://oncopanel-result-files-nki/ | grep ${sample}
+#
+#### remove temporary folder
+#rm -r ${temp_folder_path}/ 2>&1
+#
+#### Patch reporting created endpoint
+#api_update_json=$( gsutil ls gs://patient-reporter-manual-prod-1/ | grep ${sample} | grep "api-update.json")
+#echo '[INPUT] Do you want to update the reporting created endpoint? Please answer Y or N.'
+#read answer
+#if [[ $answer == 'Y' ]]; then
+#  post_api_created_report ${api_update_json} ${sample}
+#fi
+#
+#
+#echo '[INPUT] Do you want to also do the final processing (since the report has been shared) ? Please answer Y or N.'
+#read answer
+#if [[ $answer == 'Y' ]]; then
+#    copy_panel_report_to_final_reports_gcp ${set}
+#fi
