DEV-2183: dedicated scripts to copy files from and to NAS using secretmanager

diff --git a/nas/copy_file_from_nas b/nas/copy_file_from_nas
--- a/nas/copy_file_from_nas
+++ b/nas/copy_file_from_nas
@@ -2,7 +2,9 @@
 
 source message_functions || exit 1
 
-NAS_CREDS_FILE="/data/common/dbs/nas_credentials/rsyncuser"
+nas_user="rsyncuser"
+creds_name="nas-credentials-rsyncuser"
+password=$(gcloud secrets versions access "latest" --secret="${creds_name}" --project=hmf-secrets) || die "Unable to retrieve password"
 
 if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
@@ -15,6 +17,6 @@ fi
 nas_file_path=$1 && shift
 target_dir_path=$1 && shift
 
-[[ -d "${target_dir_path}" ]] || die "Directory to copy file to not found (${target_dir_path})"
-info "Copying file 'nas:${nas_file_path}' to directory '${target_dir_path}'"
-sshpass -f "${NAS_CREDS_FILE}" rsync --chmod=ugo=rw,-X -s "rsyncuser@nas:${nas_file_path}" "${target_dir_path}/"
+# explicitly add group write and remove execution permission (--chmod)
+info "Copying file 'nas:${nas_file_path}' to local directory '${target_dir_path}'"
+sshpass -f <(cat <<< "${password}") rsync --chmod=ugo=rw,-X --protect-args "${nas_user}@nas:${nas_file_path}" "${target_dir_path}/"
diff --git a/nas/copy_file_to_nas b/nas/copy_file_to_nas
--- a/nas/copy_file_to_nas
+++ b/nas/copy_file_to_nas
@@ -2,20 +2,21 @@
 
 source message_functions || exit 1
 
+nas_user="rsyncuser"
+creds_name="nas-credentials-rsyncuser"
+password=$(gcloud secrets versions access "latest" --secret="${creds_name}" --project=hmf-secrets) || die "Unable to retrieve password"
+
 if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
-    echo " Usage: $(basename $0) \${local-file-path} \${nas-dir-path}"
-    echo " Exmpl: $(basename $0) /path/to/file /volume1/web/playground"
+    echo " Usage: $(basename "$0") \${local-file-path} \${nas-dir-path}"
+    echo " Exmpl: $(basename "$0") /path/to/file /volume1/web/playground"
     echo "---"
     exit 1
 fi
 
-file_path=$1 && shift
-nas_path=$1 && shift
+source_file_path=$1 && shift
+nas_dir_path=$1 && shift
 
-[[ -f "${file_path}" ]] || die "File to copy not found (${file_path})"
-# shellcheck disable=SC2029
-ssh nas "[ -d '${nas_path}' ]" || die "Target directory not found at NAS (nas:${nas_path})"
-
-info "Copying ${file_path} to ${nas_path}"
-scp "${file_path}" "nas:${nas_path}/"
+# explicitly pass on original file permissions (--perms)
+info "Copying local file '${source_file_path}' to 'nas:${nas_dir_path}/'"
+sshpass -f <(cat <<< "${password}") rsync --perms --protect-args "${source_file_path}" "${nas_user}@nas:${nas_dir_path}/"
