DEV-2157: move the secret retrieval to after help msg

diff --git a/nas/sync_dir_from_nas b/nas/sync_dir_from_nas
--- a/nas/sync_dir_from_nas
+++ b/nas/sync_dir_from_nas
@@ -3,9 +3,6 @@
 source message_functions || exit 1
 source secrets_functions || exit 1
 
-password=$(get_nas_rsyncuser_credentials)
-[[ -n "${password}" ]] || die "Was somehow unable to retrieve password"
-
 if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
     echo " Usage: $(basename "$0") \${nas-source-dir-path} \${local-target-dir-path}"
@@ -13,6 +10,9 @@ if [[ "$#" -ne 2 || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
     exit 1
 fi
+
+password=$(get_nas_rsyncuser_credentials)
+[[ -n "${password}" ]] || die "Was somehow unable to retrieve password"
 
 source_dir=$1 && shift
 target_dir=$1 && shift
