DEV-3472 Support LAMA v2

diff --git a/lama/lama b/lama/lama
--- a/lama/lama
+++ b/lama/lama
@@ -3,22 +3,23 @@
 source message_functions || exit 1
 
 get_script="lama_api_get"
-classes=(cohorts hospitals statuses/frbarcodes statuses/cohorts statuses patients/tumorsamples patients/bloodsamples
-queries/consents)
+classes=(contract hospitals status statuses patient tumor-sample reference-sample queries/consents queries/patient-reporter)
 
 print_usage(){
     script=$(basename "$0")
     echo "---"
     echo "Usage: $script [-j] <class> [<filter-value> <filter-key>]"
     echo "Examples:"
-    echo " $script statuses/frbarcodes FR30539000"
-    echo " $script statuses/cohorts ACTIN"
-    echo " $script patients/tumorsamples ACTN01020001T"
-    echo " $script patients/bloodsamples ACTN01020001R"
-    echo " $script queries/consents FR30539000 barcode"
+    echo " $script hospitals"
+    echo " $script tumor-samples"
+    echo " $script queries/consents"
+    echo " $script statuses | grep ACTN01020001"
+    echo " $script tumor-sample sample-id/ACTN01020001T"
+    echo " $script reference-sample sample-id/ACTN01020001R"
+    echo " $script queries/consents sample-id/ACTN01020001T"
     echo "Options:"
-    echo "  -j  Output raw api json content instead of TSV"
-    echo "  -t  Use testing/pilot environment instead of production"
+    echo "  -j  Output raw api json content instead of TSV table"
+    echo "  -t  Use testing/pilot environment as source instead of production"
     echo "Notes:"
     echo "  * Available classes: ${classes[*]}"
     echo "  * Use script ${get_script} instead for all non-interactive use!"
@@ -39,7 +40,7 @@ while getopts ':jt' flag; do
 done
 class=${*:$OPTIND:1} && shift # obligatory
 filter_input=${*:$OPTIND:1} && shift # optional
-filter_field=${*:$OPTIND:1} && shift # optional but required if searching by any field other than the "name" of object
+filter_field=${*:$OPTIND:1} && shift # optional but required if searching by any field other than the "sample-id" of object
 
 if [[ -z "$class" || $1 == "-h" || $1 == "--help" ]]; then
     print_usage >&2
@@ -48,16 +49,16 @@ fi
 main(){
     contains "${class}" "${classes[@]}" || die "Unknown class '${class}' provided."
 
+    if [[ -n "${filter_field}" ]]; then
+        filter_field="${filter_field}"
+    else
+        filter_field="sample-id"
+    fi
+
     json_result=""
     if [[ -n "${filter_input}" ]]; then
-        # Some classes in LAMA use the RESTful notation while others not yet so need to check
-        if [[ "${class}" == "queries/consents" ]]; then
-            # shellcheck disable=SC2086
-            json_result=$($get_script $additional_get_params "${class}?${filter_field}=${filter_input}") || die "No result from API (with filter)"
-        else
-            # shellcheck disable=SC2086
-            json_result=$($get_script $additional_get_params "${class}/${filter_input}") || die "Unable to get result (filter input: ${filter_input})"
-        fi
+        # shellcheck disable=SC2086
+        json_result=$($get_script $additional_get_params "${class}/${filter_input}") || die "Unable to get result (filter input: ${filter_input})"
     else
         # shellcheck disable=SC2086
         json_result=$($get_script $additional_get_params "${class}") || die "Unable to get result (without filter)"
@@ -74,30 +75,38 @@ main(){
         json_result="[${json_result}]"
     fi
 
-    if [[ "${class}" == "cohorts" ]]; then
-        printf "#%s\t%s\t%s\t%s\t%s\n" cohortCode hmfRegEnding addToDatabase addToDatarequests id
-        jq -r '.[] | [.cohortCode, .hmfRegEnding, .addToDatabase, .addToDatarequests, ._id] | @tsv' <<< "${json_result}"
-    elif [[ "${class}" == "hospitals" ]]; then
-        printf "#%s\t%s\t%s\n" hospitalName emailAddresses id
-        jq -r '.[] | [.hospitalName, (.emailAddresses | join(",")), ._id] | @tsv' <<< "${json_result}"
-    elif [[ "${class}" =~ ^statuses ]]; then
-        printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
-        sampleId frBarcodeDNA isTissue isolationStatus prepStatus isolationStatusRNA prepStatusRNA cohort addToDatabase id
-        jq -r '.[] | [.sampleId, .frBarcodeDNA//"NA", .isTissue, .isolationStatus, .prepStatus, .isolationStatusRNA, .prepStatusRNA, .cohort._id, .cohort.addToDatabase, ._id] | @tsv' <<< "${json_result}"
-    elif [[ "${class}" == "patients/tumorsamples" ]]; then
-        printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\n" id submissionNr collectionDate arrivalHmf isCUP primaryTumorType biopsySite
-        jq -r '.[] | [._id, .submissionNr, .collectionDate, .arrivalHmf, .isCUP, .primaryTumorType, .biopsySite] | @tsv' <<< "${json_result}"
-    elif [[ "${class}" == "patients/bloodsamples" ]]; then
-        printf "#%s\t%s\t%s\t%s\t%s\n" id submissionNr collectionDate arrivalHmf sampleBarcode
-        jq -r '.[] | [._id, .submissionNr, .collectionDate, .arrivalHmf, .sampleBarcode] | @tsv' <<< "${json_result}"
-    elif [[ "${class}" == "queries/consents" ]]; then
+    # print result as table
+    if [[ "${class}" == "queries/consents" ]]; then
         printf "#%s\t%s\t%s\t%s\t%s\t%s\n" sampleId barcode storeData intUse extUseWoCheck extUseWithCheck
         jq -r '.[] | [.sampleId,
-          .barcode,
-          .storeDataForReuse,
-          .allowInternalUse,
-          .allowExternalUseWithoutCheck,
-          .allowExternalUseWithCheck] | @tsv' <<< "${json_result}"
+            .barcode,
+            .storeDataForReuse,
+            .allowInternalUse,
+            .allowExternalUseWithoutCheck,
+            .allowExternalUseWithCheck
+        ] | @tsv' <<< "${json_result}"
+    elif [[ "${class}" =~ ^contract ]]; then
+        printf "#%s\t%s\n" code displayName
+        jq -r '.[] | [.code, .displayName] | @tsv' <<< "${json_result}"
+    elif [[ "${class}" =~ ^hospital ]]; then
+        printf "#%s\t%s\t%s\n" name code officialName
+        jq -r '.[] | [.name, .code, .officialName] | @tsv' <<< "${json_result}"
+    elif [[ "${class}" =~ ^status ]]; then
+        printf "#%s\t%s\t%s\t%s\t%s\t%s\n" \
+        sampleId sampleBarcode isolationBarcodes type isolationStatus prepStatus
+        jq -r '.[] | [.sampleId,
+            .sampleBarcode,
+            (.isolationBarcodes|join(",")),
+            .type,
+            .isolationStatus,
+            .prepStatus
+        ] | @tsv' <<< "${json_result}"
+    elif [[ "${class}" =~ ^tumor-sample ]]; then
+        printf "#%s\t%s\t%s\t%s\t%s\t%s\t%s\n" sampleId patientId submissionNr samplingDate arrivalHmf contractCode sampleBarcodes
+        jq -r '.[] | [.sampleId, .patientId, .submissionNr, .samplingDate, .arrivalHmf, .contractCode, (.sampleBarcodes|join(","))] | @tsv' <<< "${json_result}"
+    elif [[ "${class}" =~ ^reference-sample ]]; then
+        printf "#%s\t%s\t%s\t%s\t%s\t%s\n" sampleId patientId submissionNr samplingDate arrivalHmf sampleBarcode
+        jq -r '.[] | [.sampleId, .patientId, .submissionNr, .samplingDate, .arrivalHmf, .sampleBarcode] | @tsv' <<< "${json_result}"
     else
         die "Table print for class ${class} is not supported"
     fi
@@ -106,7 +115,7 @@ main(){
 contains(){
     local e match="$1"
     shift
-    for e; do [[ "$e" == "$match" ]] && return 0; done
+    for e; do [[ "${e}" == "$match" || "${e}s" == "$match" ]] && return 0; done
     return 1
 }
 
