revert back

diff --git a/oncoact/patientreporter/ops-vm/panel/create_panel_report b/oncoact/patientreporter/ops-vm/panel/create_panel_report
--- a/oncoact/patientreporter/ops-vm/panel/create_panel_report
+++ b/oncoact/patientreporter/ops-vm/panel/create_panel_report
@@ -96,39 +96,39 @@ gsutil -q cp -r ${temp_folder_path}/report/* gs://patient-reporter-manual-prod-1
 info "The report and the related json + log file can be found in gs://patient-reporter-manual-prod-1/:"
 gsutil ls gs://patient-reporter-manual-prod-1/ | grep ${sample}
 
-#target_bucket="gs://targeted-pipeline-output-prod-1"
-#run_bucket="${target_bucket}/${set}"
-#
-#### Create coverage plots
-#coverage_plot_path="${temp_folder_path}/reporting/qc_plot"
-#mkdir -p ${coverage_plot_path}
-#
-#Rscript /data/repos/scripts/panel/createSampleQcReport.R ${sample} ${temp_folder_path} "${coverage_plot_path}/" > "${coverage_plot_path}/createSampleQcReport.log"
-#Rscript /data/repos/scripts/panel/createSampleQcReport_Deamination.R ${sample} ${temp_folder_path} "${coverage_plot_path}/" > "${coverage_plot_path}/createSampleQcReport_Deamination.log"
-#
-#### Filter VCFs
-#reporting_vcf_path="${temp_folder_path}/reporting/vcf"
-#mkdir -p ${reporting_vcf_path}
-#panel_vcf_name=$(locate_purple_somatic_variants_panel ${temp_folder_path})
-#if [ ! -f ${temp_folder_path}"/purple/"${panel_vcf_name} ]; then
-#    echo "VCF file not found!"
-#    exit 1
-#else
-#    zcat ${temp_folder_path}"/purple/"${panel_vcf_name} | grep -E '^#|REPORTED' > "${reporting_vcf_path}/${sample}.reported.somatic.vcf"
-#    if [ ! -s "${reporting_vcf_path}/${sample}.reported.somatic.vcf" ]; then
-#        warn "[WARN] Reported VCF file is empty!"
-#    fi
-#fi
-#
-#echo "Written coverage plots to target bucket of ${set}"
-#gsutil -m rsync -r "${temp_folder_path}/reporting/" "${run_bucket}/reporting/"
+target_bucket="gs://targeted-pipeline-output-prod-1"
+run_bucket="${target_bucket}/${set}"
+
+### Create coverage plots
+coverage_plot_path="${temp_folder_path}/reporting/qc_plot"
+mkdir -p ${coverage_plot_path}
+
+Rscript /data/repos/scripts/panel/createSampleQcReport.R ${sample} ${temp_folder_path} "${coverage_plot_path}/" > "${coverage_plot_path}/createSampleQcReport.log"
+Rscript /data/repos/scripts/panel/createSampleQcReport_Deamination.R ${sample} ${temp_folder_path} "${coverage_plot_path}/" > "${coverage_plot_path}/createSampleQcReport_Deamination.log"
+
+### Filter VCFs
+reporting_vcf_path="${temp_folder_path}/reporting/vcf"
+mkdir -p ${reporting_vcf_path}
+panel_vcf_name=$(locate_purple_somatic_variants_panel ${temp_folder_path})
+if [ ! -f ${temp_folder_path}"/purple/"${panel_vcf_name} ]; then
+    echo "VCF file not found!"
+    exit 1
+else
+    zcat ${temp_folder_path}"/purple/"${panel_vcf_name} | grep -E '^#|REPORTED' > "${reporting_vcf_path}/${sample}.reported.somatic.vcf"
+    if [ ! -s "${reporting_vcf_path}/${sample}.reported.somatic.vcf" ]; then
+        warn "[WARN] Reported VCF file is empty!"
+    fi
+fi
+
+echo "Written coverage plots to target bucket of ${set}"
+gsutil -m rsync -r "${temp_folder_path}/reporting/" "${run_bucket}/reporting/"
 
 ### upload report to NC
 
 upload_file_to_nc_new_reports_viewing gs://patient-reporter-manual-prod-1/ $report &> /dev/null
 upload_file_to_nc_new_reports_viewing gs://patient-reporter-manual-prod-1/ $json &> /dev/null
-#upload_file_to_nc_for_viewing "${coverage_plot_path}/sampleQcDeamination/${sample}.sampleQcDeamination.pdf" &> /dev/null
-#upload_file_to_nc_for_viewing "${coverage_plot_path}/sampleQcReports/${sample}.sampleQcReport.pdf" &> /dev/null
+upload_file_to_nc_for_viewing "${coverage_plot_path}/sampleQcDeamination/${sample}.sampleQcDeamination.pdf" &> /dev/null
+upload_file_to_nc_for_viewing "${coverage_plot_path}/sampleQcReports/${sample}.sampleQcReport.pdf" &> /dev/null
 info "Files are uploaded to nextcloud STAGING/New-Reports-Viewing for visual inspection and further processing"
 
 ### Patch reporting created endpoint
