Move to reportable bachelor variants

diff --git a/functions/locate_files b/functions/locate_files
--- a/functions/locate_files
+++ b/functions/locate_files
@@ -660,28 +660,20 @@ locate_germline_variants() {
 
 ########################################### Bachelor ##########################################
 
-locate_bachelor_variants() {
+locate_reportable_bachelor_variants() {
     local run_dir=$1
-    local bachelor_tsv=$(find -L ${run_dir}/bachelor/ -type f -name "*.bachelor.germline_variant.tsv")
-    if [[ -z "${bachelor_tsv}" ]]; then
-        # The germline_variant_tsv will only be found for bachelor v1.9 and higher. Since we cannot rerun bachelor on datastore,
-        # we just blank out bachelor results for every pre-v1.9 bachelor run.
-        echo "[WARN] Cannot find bachelor v1.9+ output. Assuming bachelor has not found any variants for ${run_dir}!" >&2
-        bachelor_tsv=/data/common/dbs/bachelor/empty.bachelor.germline_variant.tsv
+    local reportable_bachelor_tsv=$(find -L ${run_dir}/bachelor/ -type f -name "*.reportable_germline_variant.tsv")
+    if [[ -z "${reportable_bachelor_tsv}" ]]; then
+        # If bachelor v1.10 cannot be found we fall back to v1.9 for reportable bachelor variants.
+        reportable_bachelor_tsv=$(find -L ${run_dir}/bachelor/ -type f -name "*.bachelor.germline_variant.tsv")
+        if [[ -z "${reportable_bachelor_tsv}" ]]; then
+            # The germline_variant_tsv will only be found for bachelor v1.9+. Since we cannot rerun bachelor on datastore,
+            # we just blank out bachelor results for every pre-v1.9 bachelor run.
+            echo "[WARN] Cannot find bachelor v1.9+ output. Assuming bachelor has not found any variants for ${run_dir}!" >&2
+            reportable_bachelor_tsv=/data/common/dbs/bachelor/empty.bachelor.germline_variant.tsv
+        fi
     fi
-    echo ${bachelor_tsv}
-}
-
-locate_bachelor_variants_pilot() {
-    local run_dir=$1
-    local bachelor_tsv=$(find -L ${run_dir}/bachelor_pilot/ -type f -name "*.bachelor.germline_variant.tsv")
-    if [[ -z "${bachelor_tsv}" ]]; then
-        # The germline_variant_tsv will only be found for bachelor v1.9 and higher. Since we cannot rerun bachelor on datastore,
-        # we just blank out bachelor results for every pre-v1.9 bachelor run.
-        echo "[WARN] Cannot find bachelor v1.9+ output. Assuming bachelor has not found any variants for ${run_dir}!" >&2
-        bachelor_tsv=/data/common/dbs/bachelor/empty.bachelor.germline_variant.tsv
-    fi
-    echo ${bachelor_tsv}
+    echo ${reportable_bachelor_tsv}
 }
 
 ############################################# CHORD ###########################################
