use latest (batch) amber directory where possible

diff --git a/functions/locate_files b/functions/locate_files
--- a/functions/locate_files
+++ b/functions/locate_files
@@ -827,3 +827,20 @@ locate_reporting_db_tsv_pilot() {
     echo ${reporting_db_tsv}
 }
 
+############################################# AMBER ###########################################
+locate_amber_directory() {
+    local run_dir=$1
+    local set=$(basename $run_dir)
+    local amber_dir=/data/cpct/gcp/amber/$set/
+
+    if [[ ! -d $amber_dir ]]; then
+        amber_dir=$run_dir/amber/
+    fi;
+
+    if [[ ! -d $amber_dir ]]; then
+        echo "[ERROR] Unable to locate AMBER directory. Exiting." >&2
+        exit 1
+    fi;
+
+    echo $amber_dir
+}
diff --git a/hmftools/purityploidyestimator/do_run_purple b/hmftools/purityploidyestimator/do_run_purple
--- a/hmftools/purityploidyestimator/do_run_purple
+++ b/hmftools/purityploidyestimator/do_run_purple
@@ -13,6 +13,12 @@ credentials=$1 && shift
 
 reference_sample=$(load_ref_sample_from_metadata ${run_dir})
 tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
+amber_dir=$(locate_amber_directory ${run_dir})
+
+if [[ ! -d "${amber_dir}" ]]; then
+    echo "[ERROR] Unable to locate AMBER data. Exiting."
+    exit 1
+fi
 
 if [[ ! -f "${somatic_vcf}" ]]; then
     echo "[ERROR] Unable to locate somatic variants. Exiting."
