Add function to locate flagstats

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -236,6 +236,26 @@ locate_wgs_metrics() {
     echo ${metrics_file}
 }
 
+ocate_flagstats() {
+    local run_dir=$1 && shift
+    local sample=$1 && shift
+
+    local flagstats_file=""
+    local flagstats_dir_pre_v5=${run_dir}/${sample}/mapping
+    local flagstats_dir_v5=${run_dir}/${sample}/flagstat
+
+    if [[ -d "${flagstats_dir_pre_v5}" ]]; then
+        flagstats_file=$(find -L ${flagstats_dir_pre_v5}/ -type f -name "${sample}*_dedup.realigned.flagstat")
+    elif [[ -d "${flagstats_dir_v5}" ]]; then
+        flagstats_file=$(find -L ${flagstats_dir_v5}/ -type f -name "${sample}.flagstat")
+    else
+        echo "[ERROR] Unable to locate flagstats file for ${sample} in run ${run_dir}. Exiting." >& 2
+        exit 1
+    fi
+
+    echo ${flagstats_file}
+}
+
 ################################# Somatic Variants #################################
 
 locate_sage_somatics() {
