load purple somatics into database

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-locate_somatics() {
+##################################### Somatics #####################################
+locate_sage_somatics() {
     local run_dir=$1
     local somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *sage.vcf.gz)
     if [ -z ${somatic_vcf} ]
@@ -15,6 +16,30 @@ locate_somatics() {
     fi
     echo ${somatic_vcf}
 }
+
+locate_purple_somatics() {
+    local run_dir=$1
+    local somatic_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.somatic.vcf.gz")
+    if [ -z ${somatic_vcf} ]
+    then
+        echo "[ERROR] Unable to locate somatic variants. Exiting." >&2
+        exit 1
+    fi
+    echo ${somatic_vcf}
+}
+
+locate_purple_pilot_somatics() {
+    local run_dir=$1
+    local somatic_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.somatic.vcf.gz")
+    if [ -z ${somatic_vcf} ]
+    then
+        echo "[ERROR] Unable to locate somatic variants. Exiting." >&2
+        exit 1
+    fi
+    echo ${somatic_vcf}
+}
+
+##################################### Structural Variants #####################################
 
 locate_purple_structural_variants() {
     local run_dir=$1
