Add support to rerun purple on a Pv5 pipeline

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -60,14 +60,23 @@ locate_hotspot_tsv() {
 locate_sage_somatics() {
     local run_dir=$1
     local somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *sage.vcf.gz)
-    if [ -z ${somatic_vcf} ]
-    then
+    if [ -z ${somatic_vcf} ]; then
         # TODO: Clean up after sage is rerun for every sample
         somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
         if [ -z ${somatic_vcf} ]; then
             echo "[ERROR] Unable to locate somatic variants. Exiting." >&2
             exit 1
         fi
+    fi
+    echo ${somatic_vcf}
+}
+
+locate_pv5_somatic_variants() {
+    local run_dir=$1
+    local somatic_vcf=$(find -L ${run_dir}/somatic_caller/ -type f -name *post_processed.vcf.gz)
+    if [ -z ${somatic_vcf} ]; then
+        echo "[ERROR] Unable to locate Pv5 somatic variants. Exiting." >&2
+        exit 1
     fi
     echo ${somatic_vcf}
 }
@@ -262,11 +271,31 @@ locate_gridss_structural_variants() {
     echo ${structural_vcf}
 }
 
+locate_pv5_gridss_structural_variants() {
+    local run_dir=$1
+	local structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
+    if [ -z ${structural_vcf} ]; then
+    	echo "[ERROR] Unable to locate Pv5 GRIDSS structural variants. Exiting." >&2
+		exit 1
+    fi
+    echo ${structural_vcf}
+}
+
 locate_gridss_recovery_candidates() {
     local run_dir=$1
     local sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.full.vcf.gz")
     if [ -z ${sv_recovery_vcf} ]; then
         echo "[ERROR] Unable to locate GRIDSS sv recovery candidates. Exiting." >&2
+        exit 1
+    fi
+    echo ${sv_recovery_vcf}
+}
+
+locate_pv5_gridss_recovery_candidates() {
+    local run_dir=$1
+    local sv_recovery_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.full.vcf.gz")
+    if [ -z ${sv_recovery_vcf} ]; then
+        echo "[ERROR] Unable to locate Pv5 GRIDSS sv recovery candidates. Exiting." >&2
         exit 1
     fi
     echo ${sv_recovery_vcf}
