Further improvements

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -46,14 +46,13 @@ locate_variant_annotator_fusions() {
     local run_dir=$1
     local variant_annotator_dir=${run_dir}/svAnalysis
     if [ ! -d ${variant_annotator_dir} ]; then
-        echo "[ERROR] Unable to locate variant annotator dir: ${variant_annotator_dir}. Exiting" >&2
-        echo ""
+        echo "[ERROR] Unable to locate variant annotator dir: ${variant_annotator_dir}. Exiting" >& 2
         exit 1
     fi
 
 	local fusion_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_fusions.csv")
 	if [ -z ${fusion_csv} ]; then
-        echo "[ERROR] Unable to locate Variant Annotator fusions csv. Exiting." >&2
+        echo "[ERROR] Unable to locate Variant Annotator fusions csv. Exiting." >& 2
         exit 1
     fi
     echo ${fusion_csv}
@@ -79,13 +78,13 @@ locate_variant_annotator_pilot_fusions() {
     local run_dir=$1
     local variant_annotator_dir=${run_dir}/svAnalysis_pilot
     if [ ! -d ${variant_annotator_dir} ]; then
-        echo "[ERROR] Unable to locate variant annotator pilot dir: ${variant_annotator_dir}. Exiting"
+        echo "[ERROR] Unable to locate variant annotator pilot dir: ${variant_annotator_dir}. Exiting" >&2
         exit 1
     fi
 
 	local fusion_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_fusions.csv")
 	if [ -z ${fusion_csv} ]; then
-        echo "[ERROR] Unable to locate Variant Annotator pilot fusions csv. Exiting."
+        echo "[ERROR] Unable to locate Variant Annotator pilot fusions csv. Exiting." >&2
         exit 1
     fi
     echo ${fusion_csv}
@@ -95,13 +94,13 @@ locate_variant_annotator_pilot_disruptions() {
     local run_dir=$1
     local variant_annotator_dir=${run_dir}/svAnalysis_pilot
     if [ ! -d ${variant_annotator_dir} ]; then
-        echo "[ERROR] Unable to locate variant annotator pilot dir: ${variant_annotator_dir}. Exiting"
+        echo "[ERROR] Unable to locate variant annotator pilot dir: ${variant_annotator_dir}. Exiting" >&2
         exit 1
     fi
 
 	local disruption_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_disruptions.csv")
 	if [ -z ${disruption_csv} ]; then
-        echo "[ERROR] Unable to locate Variant Annotator pilot disruptions csv. Exiting."
+        echo "[ERROR] Unable to locate Variant Annotator pilot disruptions csv. Exiting." >&2
         exit 1
     fi
     echo ${disruption_csv}
