Updated scripts for patient reporter v7.6

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -466,11 +466,21 @@ locate_chord_pilot_prediction() {
 
 ############################################# LIMS ###########################################
 
-locate_reporting_db_tsv_pilot() {
-    local reporting_db_tsv=$(find "/data/lims/report_dates_lims_pilot.tsv")
-    if [ -z ${reporting_db_tsv} ]; then
+locate_reporting_db_tsv() {
+    local reporting_db_tsv=/data/lims/reporting_db.tsv
+    if [ ! -f ${reporting_db_tsv} ]; then
         echo "[ERROR] Unable to locate reporting db TSV. Exiting." >&2
         exit 1
     fi
     echo ${reporting_db_tsv}
 }
+
+locate_reporting_db_tsv_pilot() {
+    local reporting_db_tsv=/data/lims/report_dates_lims_pilot.tsv
+    if [ ! -f ${reporting_db_tsv} ]; then
+        echo "[ERROR] Unable to locate reporting db TSV. Exiting." >&2
+        exit 1
+    fi
+    echo ${reporting_db_tsv}
+}
+
