Various cleanup in locate files

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -72,7 +72,7 @@ locate_sage_somatics() {
         # TODO: Clean up after sage is rerun for every sample
         somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
         if [ -z ${somatic_vcf} ]; then
-            echo "[ERROR] Unable to locate somatic variants. Exiting." >&2
+            echo "[ERROR] Unable to locate sage somatic variants. Exiting." >&2
             exit 1
         fi
     fi
@@ -83,7 +83,7 @@ locate_purple_somatics() {
     local run_dir=$1
     local somatic_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.somatic.vcf.gz")
     if [ -z ${somatic_vcf} ]; then
-        echo "[ERROR] Unable to locate somatic variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple somatic variants. Exiting." >&2
         exit 1
     fi
     echo ${somatic_vcf}
@@ -93,7 +93,7 @@ locate_purple_pilot_somatics() {
     local run_dir=$1
     local somatic_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.somatic.vcf.gz")
     if [ -z ${somatic_vcf} ]; then
-        echo "[ERROR] Unable to locate somatic variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot somatic variants. Exiting." >&2
         exit 1
     fi
     echo ${somatic_vcf}
@@ -115,7 +115,7 @@ locate_purple_pilot_purity() {
     local run_dir=$1
     local purple_purity_file=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.purity.tsv")
     if [ -z ${purple_purity_file} ]; then
-        echo "[ERROR] Unable to locate purple purity. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot purity. Exiting." >&2
         exit 1
     fi
     echo ${purple_purity_file}
@@ -135,7 +135,7 @@ locate_purple_pilot_gene_copynumbers() {
     local run_dir=$1
     local purple_gene_copynumbers=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.cnv.gene.tsv")
     if [ -z ${purple_gene_copynumbers} ]; then
-        echo "[ERROR] Unable to locate purple gene copynumbers. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot gene copynumbers. Exiting." >&2
         exit 1
     fi
     echo ${purple_gene_copynumbers}
@@ -155,7 +155,7 @@ locate_purple_pilot_circos_plot() {
     local run_dir=$1
     local circos_plot=$(find -L ${run_dir}/purple_pilot/plot/ -type f -name "*.circos.png")
     if [ -z ${circos_plot} ]; then
-        echo "[ERROR] Unable to locate purple circos plot. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot circos plot. Exiting." >&2
         exit 1
     fi
     echo ${circos_plot}
@@ -165,11 +165,12 @@ locate_purple_pilot_circos_plot() {
 
 locate_purple_structural_variants() {
     local run_dir=$1
+    # TODO: Remove the "ann" once annotation is all done pre-purple.
     local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.ann.vcf.gz")
 	if [ -z ${structural_vcf} ]; then
 		structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.vcf.gz")
 		if [ -z ${structural_vcf} ]; then
-			echo "[ERROR] Unable to locate PURPLE structural variants. Exiting." >&2
+			echo "[ERROR] Unable to locate purple structural variants. Exiting." >&2
 			exit 1
 		fi
 	fi
@@ -178,79 +179,16 @@ locate_purple_structural_variants() {
 
 locate_purple_pilot_structural_variants() {
     local run_dir=$1
+    # TODO: Remove the "ann" once annotation is all done pre-purple.
 	local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.ann.vcf.gz")
 	if [ -z ${structural_vcf} ]; then
 		structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.vcf.gz")
 		if [ -z ${structural_vcf} ]; then
-			echo "[ERROR] Unable to locate PURPLE structural variants. Exiting." >&2
+			echo "[ERROR] Unable to locate purple pilot structural variants. Exiting." >&2
 			exit 1
 		fi
 	fi
     echo ${structural_vcf}
-}
-
-locate_variant_annotator_fusions() {
-    local run_dir=$1
-    local variant_annotator_dir=${run_dir}/svAnalysis
-    if [ ! -d ${variant_annotator_dir} ]; then
-        echo "[ERROR] Unable to locate variant annotator dir for fusions: ${variant_annotator_dir}. Exiting" >& 2
-        exit 1
-    fi
-
-	local fusion_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_fusions.csv")
-	if [ -z ${fusion_csv} ]; then
-        echo "[ERROR] Unable to locate variant annotator fusions csv. Exiting." >& 2
-        exit 1
-    fi
-    echo ${fusion_csv}
-}
-
-locate_variant_annotator_disruptions() {
-    local run_dir=$1
-    local variant_annotator_dir=${run_dir}/svAnalysis
-    if [ ! -d ${variant_annotator_dir} ]; then
-        echo "[ERROR] Unable to locate variant annotator dir for disruptions: ${variant_annotator_dir}. Exiting" >&2
-        exit 1
-    fi
-
-	local disruption_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_disruptions.csv")
-	if [ -z ${disruption_csv} ]; then
-        echo "[ERROR] Unable to locate variant annotator disruptions csv. Exiting." >&2
-        exit 1
-    fi
-    echo ${disruption_csv}
-}
-
-locate_variant_annotator_pilot_fusions() {
-    local run_dir=$1
-    local variant_annotator_dir=${run_dir}/svAnalysis_pilot
-    if [ ! -d ${variant_annotator_dir} ]; then
-        echo "[ERROR] Unable to locate variant annotator pilot dir for fusions: ${variant_annotator_dir}. Exiting" >&2
-        exit 1
-    fi
-
-	local fusion_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_fusions.csv")
-	if [ -z ${fusion_csv} ]; then
-        echo "[ERROR] Unable to locate variant annotator pilot fusions csv. Exiting." >&2
-        exit 1
-    fi
-    echo ${fusion_csv}
-}
-
-locate_variant_annotator_pilot_disruptions() {
-    local run_dir=$1
-    local variant_annotator_dir=${run_dir}/svAnalysis_pilot
-    if [ ! -d ${variant_annotator_dir} ]; then
-        echo "[ERROR] Unable to locate variant annotator pilot dir for disruptions: ${variant_annotator_dir}. Exiting" >&2
-        exit 1
-    fi
-
-	local disruption_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_disruptions.csv")
-	if [ -z ${disruption_csv} ]; then
-        echo "[ERROR] Unable to locate variant annotator pilot disruptions csv. Exiting." >&2
-        exit 1
-    fi
-    echo ${disruption_csv}
 }
 
 locate_linx_fusions() {
