loading pilot svs should use purple pilot sv

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -26,6 +26,16 @@ locate_purple_structural_variants() {
     echo ${structural_vcf}
 }
 
+locate_purple_pilot_structural_variants() {
+    local run_dir=$1
+    local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.vcf.gz")
+    if [ -z ${structural_vcf} ]; then
+        echo "[ERROR] Unable to locate PURPLE structural variants. Exiting."
+        exit 1
+    fi
+    echo ${structural_vcf}
+}
+
 
 locate_gridss_structural_variants() {
     local run_dir=$1
