do_run_gridss_2_1_0_breakpoint_position_backport: now passing testing gridss_adjust_call_positions.R: new script that only applies the CIPOS nominal positional adjustment made by gridss_somatic_filter.R gridss_somatic_filter.R: rounding BPI_AF to 5 decimal places locate_files: using the gridss positional backport VCF if it exists

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -29,10 +29,14 @@ locate_purple_structural_variants() {
 
 locate_gridss_structural_variants() {
     local run_dir=$1
-    local structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
+	# Use the backport VCF if it exists
+	local structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/breakpoint_position_backport/ -type f -name "*.gridss.somatic.vcf.gz.breakpoint_position_backport.vcf.gz")
     if [ -z ${structural_vcf} ]; then
-        echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting."
-        exit 1
+        structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
+		if [ -z ${structural_vcf} ]; then
+			echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting."
+			exit 1
+		fi
     fi
     echo ${structural_vcf}
 }
