script to run pilot patient report off pilot purple

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -105,7 +105,7 @@ locate_purple_pilot_somatics() {
     echo ${somatic_vcf}
 }
 
-############################################ Purple  ##########################################
+############################################ Purple ##########################################
 
 locate_purple_purity() {
     local run_dir=$1
@@ -130,6 +130,37 @@ locate_purple_gene_copynumbers() {
 locate_purple_circos_plot() {
     local run_dir=$1
     local circos_plot=$(find -L ${run_dir}/purple/plot/ -type f -name "*.circos.png")
+    if [ -z ${circos_plot} ]; then
+        echo "[ERROR] Unable to locate purple circos plot. Exiting." >&2
+        exit 1
+    fi
+    echo ${circos_plot}
+}
+
+############################################ Purple PILOT ##########################################
+locate_purple_purity() {
+    local run_dir=$1
+    local purple_purity_file=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.purity.tsv")
+    if [ -z ${purple_purity_file} ]; then
+        echo "[ERROR] Unable to locate purple purity. Exiting." >&2
+        exit 1
+    fi
+    echo ${purple_purity_file}
+}
+
+locate_purple_gene_copynumbers() {
+    local run_dir=$1
+    local purple_gene_copynumbers=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.cnv.gene.tsv")
+    if [ -z ${purple_gene_copynumbers} ]; then
+        echo "[ERROR] Unable to locate purple gene copynumbers. Exiting." >&2
+        exit 1
+    fi
+    echo ${purple_gene_copynumbers}
+}
+
+locate_purple_circos_plot() {
+    local run_dir=$1
+    local circos_plot=$(find -L ${run_dir}/purple_pilot/plot/ -type f -name "*.circos.png")
     if [ -z ${circos_plot} ]; then
         echo "[ERROR] Unable to locate purple circos plot. Exiting." >&2
         exit 1
