DEV-642: Loading evidence from protect into db

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -603,6 +603,17 @@ locate_chord_pilot_prediction() {
     fi
     echo ${chord_prediction_file}
 }
+############################################# ACTIONABILITY ###########################################
+
+locate_protect_actionability_pilot() {
+    local run_dir=$1
+    local actionability_tsv=$(find -L ${run_dir}/protect_pilot/ -type f -name "actionability_database.tsv")
+    if [ -z ${actionability_tsv} ]; then
+        echo "[ERROR] Unable to locate actionability tsv file in ${run_dir}. Exiting." >&2
+        exit 1
+    fi
+    echo ${actionability_tsv}
+}
 
 ############################################# LIMS ###########################################
 
