locate purple structural variants

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -16,7 +16,18 @@ locate_somatics() {
     echo ${somatic_vcf}
 }
 
-locate_structural_variants() {
+locate_purple_structural_variants() {
+    local run_dir=$1
+    local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name *.purple.sv.vcf.gz)
+    if [ -z ${structural_vcf} ]; then
+        echo "[ERROR] Unable to locate PURPLE structural variants. Exiting."
+        exit 1
+    fi
+    echo ${structural_vcf}
+}
+
+
+locate_gridss_structural_variants() {
     local run_dir=$1
     local structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
     if [ -z ${structural_vcf} ]; then
@@ -26,11 +37,11 @@ locate_structural_variants() {
     echo ${structural_vcf}
 }
 
-locate_recovery_structural_variants() {
+locate_gridss_recovery_candidates() {
     local run_dir=$1
     local sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.full.vcf.gz)
     if [ -z ${sv_recovery_vcf} ]; then
-        echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting."
+        echo "[ERROR] Unable to locate GRIDSS sv recovery candidates. Exiting."
         exit 1
     fi
     echo ${sv_recovery_vcf}
