Support Pv5 gridss backport for structural variants

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -323,10 +323,13 @@ locate_gridss_structural_variants() {
 
 locate_pv5_gridss_structural_variants() {
     local run_dir=$1
-	local structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
+    local structural_vcf=$(find -L ${run_dir}/structural_caller/breakpoint_position_backport/ -type f -name "*.gridss.somatic.vcf.gz.breakpoint_position_backport.vcf.gz")
     if [ -z ${structural_vcf} ]; then
-    	echo "[ERROR] Unable to locate Pv5 GRIDSS structural variants. Exiting." >&2
-		exit 1
+        structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
+		if [ -z ${structural_vcf} ]; then
+			echo "[ERROR] Unable to locate Pv5 GRIDSS structural variants. Exiting." >&2
+			exit 1
+		fi
     fi
     echo ${structural_vcf}
 }
