Support Pv5 in locating pre-purple output

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -72,8 +72,11 @@ locate_sage_somatics() {
         # TODO: Clean up after sage is rerun for every sample
         somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
         if [ -z ${somatic_vcf} ]; then
-            echo "[ERROR] Unable to locate sage somatic variants. Exiting." >&2
-            exit 1
+            somatic_vcf=$(find -L ${run_dir}/somatic_caller/ -type f -name *post_processed.vcf.gz)
+            if [ -z ${somatic_vcf} ]; then
+                echo "[ERROR] Unable to locate sage somatic variants. Exiting." >&2
+                exit 1
+            fi
         fi
     fi
     echo ${somatic_vcf}
@@ -260,8 +263,11 @@ locate_gridss_recovery_candidates() {
     local run_dir=$1
     local sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.full.vcf.gz")
     if [ -z ${sv_recovery_vcf} ]; then
-        echo "[ERROR] Unable to locate GRIDSS sv recovery candidates. Exiting." >&2
-        exit 1
+        sv_recovery_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.full.vcf.gz")
+        if [ -z ${sv_recovery_vcf} ]; then
+            echo "[ERROR] Unable to locate GRIDSS sv recovery candidates. Exiting." >&2
+            exit 1
+        fi
     fi
     echo ${sv_recovery_vcf}
 }
