Add processing script for Pv5 runs
process_finished_run_v5 (and download_set_v5) added to support
processing while not breaking anything for v4 as we transition.

The processing script removes a few workarounds and rerun stages which
are no longer required for p5 (compare with process_finished_run for the
full diff).

Small workaround required for bachelor expectation of germline vcf
naming.

The download script likely won't be required long term, but not sure how
the reruns work yet, so don't want to mess with the main script.

Removed all the copy/paste pv5 stuff from locate_files (now all
functions should fall back to pv4 to support both flavours) and special
scripts.

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -75,16 +75,6 @@ locate_sage_somatics() {
     echo ${somatic_vcf}
 }
 
-locate_pv5_somatic_variants() {
-    local run_dir=$1
-    local somatic_vcf=$(find -L ${run_dir}/somatic_caller/ -type f -name *post_processed.vcf.gz)
-    if [ -z ${somatic_vcf} ]; then
-        echo "[ERROR] Unable to locate Pv5 somatic variants. Exiting." >&2
-        exit 1
-    fi
-    echo ${somatic_vcf}
-}
-
 locate_purple_somatics() {
     local run_dir=$1
     local somatic_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.somatic.vcf.gz")
@@ -314,21 +304,11 @@ locate_gridss_structural_variants() {
     if [ -z ${structural_vcf} ]; then
         structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.vcf.gz")
 		if [ -z ${structural_vcf} ]; then
-			echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting." >&2
-			exit 1
-		fi
-    fi
-    echo ${structural_vcf}
-}
-
-locate_pv5_gridss_structural_variants() {
-    local run_dir=$1
-    local structural_vcf=$(find -L ${run_dir}/structural_caller/breakpoint_position_backport/ -type f -name "*.gridss.somatic.vcf.gz.breakpoint_position_backport.vcf.gz")
-    if [ -z ${structural_vcf} ]; then
-        structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
-		if [ -z ${structural_vcf} ]; then
-			echo "[ERROR] Unable to locate Pv5 GRIDSS structural variants. Exiting." >&2
-			exit 1
+			structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
+			if [ -z ${structural_vcf} ]; then
+				echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting." >&2
+				exit 1
+			fi
 		fi
     fi
     echo ${structural_vcf}
@@ -339,16 +319,6 @@ locate_gridss_recovery_candidates() {
     local sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.full.vcf.gz")
     if [ -z ${sv_recovery_vcf} ]; then
         echo "[ERROR] Unable to locate GRIDSS sv recovery candidates. Exiting." >&2
-        exit 1
-    fi
-    echo ${sv_recovery_vcf}
-}
-
-locate_pv5_gridss_recovery_candidates() {
-    local run_dir=$1
-    local sv_recovery_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.full.vcf.gz")
-    if [ -z ${sv_recovery_vcf} ]; then
-        echo "[ERROR] Unable to locate Pv5 GRIDSS sv recovery candidates. Exiting." >&2
         exit 1
     fi
     echo ${sv_recovery_vcf}
