DEV-645: Explicitly check for existance of sv analysis dir

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -44,7 +44,13 @@ locate_purple_pilot_structural_variants() {
 
 locate_variant_annotator_fusions() {
     local run_dir=$1
-	local fusion_csv=$(find -L ${run_dir}/svAnalysis/ -type f -name "*_fusions.csv")
+    local variant_annotator_dir=${run_dir}/svAnalysis
+    if [ ! -d ${variant_annotator_dir} ]; then
+        echo "[ERROR] Unable to locate variant annotator dir: ${variant_annotator_dir}. Exiting"
+        exit 1
+    fi
+
+	local fusion_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_fusions.csv")
 	if [ -z ${fusion_csv} ]; then
         echo "[ERROR] Unable to locate Variant Annotator fusions csv. Exiting."
         exit 1
@@ -54,7 +60,13 @@ locate_variant_annotator_fusions() {
 
 locate_variant_annotator_disruptions() {
     local run_dir=$1
-	local disruption_csv=$(find -L ${run_dir}/svAnalysis/ -type f -name "*_disruptions.csv")
+    local variant_annotator_dir=${run_dir}/svAnalysis
+    if [ ! -d ${variant_annotator_dir} ]; then
+        echo "[ERROR] Unable to locate variant annotator dir: ${variant_annotator_dir}. Exiting"
+        exit 1
+    fi
+
+	local disruption_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_disruptions.csv")
 	if [ -z ${disruption_csv} ]; then
         echo "[ERROR] Unable to locate Variant Annotator disruptions csv. Exiting."
         exit 1
@@ -64,7 +76,13 @@ locate_variant_annotator_disruptions() {
 
 locate_variant_annotator_pilot_fusions() {
     local run_dir=$1
-	local fusion_csv=$(find -L ${run_dir}/svAnalysis_pilot/ -type f -name "*_fusions.csv")
+    local variant_annotator_dir=${run_dir}/svAnalysis_pilot
+    if [ ! -d ${variant_annotator_dir} ]; then
+        echo "[ERROR] Unable to locate variant annotator pilot dir: ${variant_annotator_dir}. Exiting"
+        exit 1
+    fi
+
+	local fusion_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_fusions.csv")
 	if [ -z ${fusion_csv} ]; then
         echo "[ERROR] Unable to locate Variant Annotator pilot fusions csv. Exiting."
         exit 1
@@ -74,7 +92,13 @@ locate_variant_annotator_pilot_fusions() {
 
 locate_variant_annotator_pilot_disruptions() {
     local run_dir=$1
-	local disruption_csv=$(find -L ${run_dir}/svAnalysis_pilot/ -type f -name "*_disruptions.csv")
+    local variant_annotator_dir=${run_dir}/svAnalysis_pilot
+    if [ ! -d ${variant_annotator_dir} ]; then
+        echo "[ERROR] Unable to locate variant annotator pilot dir: ${variant_annotator_dir}. Exiting"
+        exit 1
+    fi
+
+	local disruption_csv=$(find -L ${variant_annotator_dir}/ -type f -name "*_disruptions.csv")
 	if [ -z ${disruption_csv} ]; then
         echo "[ERROR] Unable to locate Variant Annotator pilot disruptions csv. Exiting."
         exit 1
