Fix error messages when locating bachelor files.

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -437,7 +437,7 @@ locate_bachelor_germline_variants_v1_8() {
         local bachelor_output=$(find -L ${run_dir}/bachelor/ -type f -name "bachelor_output.csv")
         local bachelor_found_nothing=$(find -L ${run_dir}/bachelor/ -type f -name "bachelor_found_no_variants")
         if [ -z ${bachelor_output} ] && [ -z ${bachelor_found_nothing} ]; then
-            echo "[ERROR] Unable to locate any bachelor output in ${run_dir}. Exiting." >&2
+            echo "[ERROR] Unable to locate bachelor v1.8 output in ${run_dir}. Exiting." >&2
             exit 1
         fi
     fi
@@ -448,7 +448,7 @@ locate_bachelor_germline_variants_v1_9() {
     local run_dir=$1
     local bachelor_csv=$(find -L ${run_dir}/bachelor/ -type f -name "*.bachelor.germline_variant.tsv")
     if [ -z ${bachelor_csv} ]; then
-        echo "[ERROR] Unable to locate pilot bachelor tsv output in ${run_dir}. Exiting." >&2
+        echo "[ERROR] Unable to locate bachelor v1.9 tsv output in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${bachelor_csv}
