Add fallback on empty reported fusions and disruptions when linx folder exists but files do not

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -398,8 +398,10 @@ locate_linx_reported_fusions() {
     
     local fusion_tsv=$(find -L ${linx_dir}/ -type f -name "*.linx.reported_fusion.tsv")
     if [ -z ${fusion_tsv} ]; then
-        echo "[ERROR] Unable to locate linx fusions tsv in ${run_dir}. Exiting." >&2
-        exit 1
+        # Assume there were no reported fusions found. This can be removed with linx v1.7. See also DEV-1049
+        fusion_tsv=/data/common/dbs/sv/empty.linx.reported_fusion.tsv
+        #echo "[ERROR] Unable to locate linx fusions tsv in ${run_dir}. Exiting." >&2
+        #exit 1
     fi
     echo ${fusion_tsv}
 }
@@ -414,8 +416,10 @@ locate_linx_disruptions() {
     
     local disruption_tsv=$(find -L ${linx_dir}/ -type f -name "*.linx.disruptions.tsv")
     if [ -z ${disruption_tsv} ]; then
-        echo "[ERROR] Unable to locate linx disruptions tsv in ${run_dir}}. Exiting." >&2
-        exit 1
+        # Assume there were no disruptions found. This can be removed with linx v1.7. See also DEV-1049
+        #echo "[ERROR] Unable to locate linx disruptions tsv in ${run_dir}}. Exiting." >&2
+        #exit 1
+        disruption_tsv=/data/common/dbs/sv/empty.linx.disruptions.tsv
     fi
     echo ${disruption_tsv}
 }
