Add function for locating wgs metrics

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -85,6 +85,28 @@ locate_hotspot_tsv() {
     echo "/data/common/dbs/sage/KnownHotspots.tsv"
 }
 
+########################################### WGS METRICS #########################################
+
+locate_wgs_metrics() {
+    local run_dir=$1 && shift
+    local sample=$1 && shift
+
+    local metrics_file=""
+    local metrics_dir_pre_v5=${run_dir}/QCStats
+    local metrics_dir_v5=${run_dir}/${sample}/bam_metrics
+
+    if [ -d ${metrics_dir_pre_v5} ]; then
+        metrics_file=$(find -L ${metrics_dir_pre_v5}/ -type f -name "${sample}*_WGSMetrics.txt")
+    elif [ -d ${metrics_dir_v5} ]; then
+        metrics_file=$(find -L ${metrics_dir_v5}/ -type f -name "${sample}.wgsmetrics")
+    else
+        echo "[ERROR] Unable to locate metrics file for ${sample} in run ${run_dir}. Exiting." >& 2
+        exit 1
+    fi
+
+    echo ${metrics_file}
+}
+
 ################################# Somatic Variants #################################
 locate_sage_somatics() {
     local run_dir=$1
@@ -95,7 +117,7 @@ locate_sage_somatics() {
         if [ -z ${somatic_vcf} ]; then
             somatic_vcf=$(find -L ${run_dir}/somatic_caller/ -type f -name *post_processed.vcf.gz)
             if [ -z ${somatic_vcf} ]; then
-                echo "[ERROR] Unable to locate sage somatic variants. Exiting." >&2
+                echo "[ERROR] Unable to locate sage somatic variants in ${run_dir}. Exiting." >&2
                 exit 1
             fi
         fi
@@ -107,7 +129,7 @@ locate_purple_somatics() {
     local run_dir=$1
     local somatic_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.somatic.vcf.gz")
     if [ -z ${somatic_vcf} ]; then
-        echo "[ERROR] Unable to locate purple somatic variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple somatic variants in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${somatic_vcf}
@@ -117,7 +139,7 @@ locate_purple_pilot_somatics() {
     local run_dir=$1
     local somatic_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.somatic.vcf.gz")
     if [ -z ${somatic_vcf} ]; then
-        echo "[ERROR] Unable to locate purple pilot somatic variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot somatic variants in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${somatic_vcf}
@@ -129,7 +151,7 @@ locate_purple_purity() {
     local run_dir=$1
     local purple_purity_file=$(find -L ${run_dir}/purple/ -type f -name "*.purple.purity.tsv")
     if [ -z ${purple_purity_file} ]; then
-        echo "[ERROR] Unable to locate purple purity. Exiting." >&2
+        echo "[ERROR] Unable to locate purple purity in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${purple_purity_file}
@@ -139,7 +161,7 @@ locate_purple_pilot_purity() {
     local run_dir=$1
     local purple_purity_file=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.purity.tsv")
     if [ -z ${purple_purity_file} ]; then
-        echo "[ERROR] Unable to locate purple pilot purity. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot purity in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${purple_purity_file}
@@ -149,7 +171,7 @@ locate_purple_gene_copynumbers() {
     local run_dir=$1
     local purple_gene_copynumbers=$(find -L ${run_dir}/purple/ -type f -name "*.purple.cnv.gene.tsv")
     if [ -z ${purple_gene_copynumbers} ]; then
-        echo "[ERROR] Unable to locate purple gene copynumbers. Exiting." >&2
+        echo "[ERROR] Unable to locate purple gene copynumbers in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${purple_gene_copynumbers}
@@ -159,7 +181,7 @@ locate_purple_pilot_gene_copynumbers() {
     local run_dir=$1
     local purple_gene_copynumbers=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.cnv.gene.tsv")
     if [ -z ${purple_gene_copynumbers} ]; then
-        echo "[ERROR] Unable to locate purple pilot gene copynumbers. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot gene copynumbers in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${purple_gene_copynumbers}
@@ -169,7 +191,7 @@ locate_purple_circos_plot() {
     local run_dir=$1
     local circos_plot=$(find -L ${run_dir}/purple/plot/ -type f -name "*.circos.png")
     if [ -z ${circos_plot} ]; then
-        echo "[ERROR] Unable to locate purple circos plot. Exiting." >&2
+        echo "[ERROR] Unable to locate purple circos plot in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${circos_plot}
@@ -179,7 +201,7 @@ locate_purple_pilot_circos_plot() {
     local run_dir=$1
     local circos_plot=$(find -L ${run_dir}/purple_pilot/plot/ -type f -name "*.circos.png")
     if [ -z ${circos_plot} ]; then
-        echo "[ERROR] Unable to locate purple pilot circos plot. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot circos plot in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${circos_plot}
@@ -191,7 +213,7 @@ locate_purple_structural_variants() {
     local run_dir=$1
     local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.ann.vcf.gz")
     if [ -z ${structural_vcf} ]; then
-        echo "[ERROR] Unable to locate purple structural variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple structural variants in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${structural_vcf}
@@ -201,7 +223,7 @@ locate_purple_pre_viral_annotate_structural_variants() {
     local run_dir=$1
     local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.vcf.gz")
     if [ -z ${structural_vcf} ]; then
-        echo "[ERROR] Unable to locate purple pre-viral-annotate structural variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pre-viral-annotate structural variants in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${structural_vcf}
@@ -211,7 +233,7 @@ locate_purple_pilot_structural_variants() {
     local run_dir=$1
 	  local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.ann.vcf.gz")
     if [ -z ${structural_vcf} ]; then
-        echo "[ERROR] Unable to locate purple pilot structural variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot structural variants in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${structural_vcf}
@@ -221,11 +243,47 @@ locate_purple_pilot_pre_viral_annotate_structural_variants() {
     local run_dir=$1
     local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.vcf.gz")
     if [ -z ${structural_vcf} ]; then
-        echo "[ERROR] Unable to locate purple pilot pre-viral-annotate structural variants. Exiting." >&2
+        echo "[ERROR] Unable to locate purple pilot pre-viral-annotate structural variants in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${structural_vcf}
 }
+
+locate_gridss_structural_variants() {
+    local run_dir=$1
+	  # Use the backport VCF if it exists
+	  local structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/breakpoint_position_backport/ -type f -name "*.gridss.somatic.vcf.gz.breakpoint_position_backport.vcf.gz")
+    if [ -z ${structural_vcf} ]; then
+        # Otherwise use v4 naming convention
+        structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.vcf.gz")
+		    if [ -z ${structural_vcf} ]; then
+		        # Otherwise use v5 naming convention
+			      structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
+			      if [ -z ${structural_vcf} ]; then
+				        echo "[ERROR] Unable to locate GRIDSS structural variants in ${run_dir}. Exiting." >&2
+				        exit 1
+			      fi
+		    fi
+    fi
+    echo ${structural_vcf}
+}
+
+locate_gridss_recovery_candidates() {
+    local run_dir=$1
+    # Use v4 naming convention
+    local sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.full.vcf.gz")
+    if [ -z ${sv_recovery_vcf} ]; then
+        # Otherwise use v5 naming convention
+        sv_recovery_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.full.vcf.gz")
+        if [ -z ${sv_recovery_vcf} ]; then
+            echo "[ERROR] Unable to locate GRIDSS sv recovery candidates in ${run_dir}. Exiting." >&2
+            exit 1
+        fi
+    fi
+    echo ${sv_recovery_vcf}
+}
+
+######################################## LINX ########################################
 
 locate_linx_reported_fusions() {
     local run_dir=$1
@@ -240,7 +298,7 @@ locate_linx_reported_fusions() {
 
     fusion_tsv=$(find -L ${linx_dir}/ -type f -name "*.linx.reported_fusion.tsv")
     if [ -z ${fusion_tsv} ]; then
-        echo "[ERROR] Unable to locate linx fusions tsv. Exiting." >&2
+        echo "[ERROR] Unable to locate linx fusions tsv in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${fusion_tsv}
@@ -259,7 +317,7 @@ locate_linx_disruptions() {
 
 	local disruption_tsv=$(find -L ${linx_dir}/ -type f -name "*.linx.disruptions.tsv")
 	if [ -z ${disruption_tsv} ]; then
-        echo "[ERROR] Unable to locate linx disruptions tsv. Exiting." >&2
+        echo "[ERROR] Unable to locate linx disruptions tsv in ${run_dir}}. Exiting." >&2
         exit 1
     fi
     echo ${disruption_tsv}
@@ -277,13 +335,13 @@ locate_linx_viral_integrations() {
     fi
     local viral_integration_tsv=$(find -L ${linx_dir}/ -type f -name "*.linx.viral_inserts.tsv")
     if [ -z ${viral_integration_tsv} ]; then
-        echo "[ERROR] Unable to locate viral integration tsv. Exiting." >&2
+        echo "[ERROR] Unable to locate viral integration tsv in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${viral_integration_tsv}
 }
 
-locate_linx_drivers_tsv() {
+locate_linx_drivers() {
     local run_dir=$1
     local linx_dir=${run_dir}/sv
     if [ ! -d ${linx_dir} ]; then
@@ -296,45 +354,11 @@ locate_linx_drivers_tsv() {
 
     local drivers_tsv=$(find -L ${linx_dir}/ -type f -name "*.driver.catalog.tsv")
     if [ -z ${drivers_tsv} ]; then
-        echo "[ERROR] Unable to locate drivers catalog tsv. Exiting." >&2
+        echo "[ERROR] Unable to locate drivers catalog tsv in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${drivers_tsv}
 
-}
-
-locate_gridss_structural_variants() {
-    local run_dir=$1
-	  # Use the backport VCF if it exists
-	  local structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/breakpoint_position_backport/ -type f -name "*.gridss.somatic.vcf.gz.breakpoint_position_backport.vcf.gz")
-    if [ -z ${structural_vcf} ]; then
-        # Otherwise use v4 naming convention
-        structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.vcf.gz")
-		    if [ -z ${structural_vcf} ]; then
-		        # Otherwise use v5 naming convention
-			      structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
-			      if [ -z ${structural_vcf} ]; then
-				        echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting." >&2
-				        exit 1
-			      fi
-		    fi
-    fi
-    echo ${structural_vcf}
-}
-
-locate_gridss_recovery_candidates() {
-    local run_dir=$1
-    # Use v4 naming convention
-    local sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.full.vcf.gz")
-    if [ -z ${sv_recovery_vcf} ]; then
-        # Otherwise use v5 naming convention
-        sv_recovery_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.full.vcf.gz")
-        if [ -z ${sv_recovery_vcf} ]; then
-            echo "[ERROR] Unable to locate GRIDSS sv recovery candidates. Exiting." >&2
-            exit 1
-        fi
-    fi
-    echo ${sv_recovery_vcf}
 }
 
 ########################################### Bachelor ##########################################
@@ -346,7 +370,7 @@ locate_bachelor_germline_variants() {
         local bachelor_output=$(find -L ${run_dir}/bachelor/ -type f -name "bachelor_output.csv")
         local bachelor_found_nothing=$(find -L ${run_dir}/bachelor/ -type f -name "bachelor_found_no_variants")
         if [ -z ${bachelor_output} ] && [ -z ${bachelor_found_nothing} ]; then
-            echo "[ERROR] Unable to locate any bachelor output. Exiting." >&2
+            echo "[ERROR] Unable to locate any bachelor output in ${run_dir}. Exiting." >&2
             exit 1
         fi
     fi
@@ -357,7 +381,7 @@ locate_bachelor_pilot_germline_variants() {
     local run_dir=$1
     local bachelor_csv=$(find -L ${run_dir}/bachelor/ -type f -name "*.bachelor.germline_variant.tsv")
     if [ -z ${bachelor_csv} ]; then
-        echo "[ERROR] Unable to locate bachelor csv output. Exiting." >&2
+        echo "[ERROR] Unable to locate pilot bachelor tsv output in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${bachelor_csv}
@@ -370,7 +394,7 @@ locate_chord_prediction() {
     local run_dir=$1
     local chord_prediction_file=$(find -L ${run_dir}/chord/ -type f -name "*_chord_prediction.txt")
     if [ -z ${chord_prediction_file} ]; then
-        echo "[ERROR] Unable to locate CHORD prediction file. Exiting." >&2
+        echo "[ERROR] Unable to locate CHORD prediction file in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${chord_prediction_file}
@@ -380,7 +404,7 @@ locate_chord_pilot_prediction() {
     local run_dir=$1
     local chord_prediction_file=$(find -L ${run_dir}/chord_pilot/ -type f -name "*_chord_prediction.txt")
     if [ -z ${chord_prediction_file} ]; then
-        echo "[ERROR] Unable to locate CHORD prediction file. Exiting." >&2
+        echo "[ERROR] Unable to locate pilot CHORD prediction file in ${run_dir}. Exiting." >&2
         exit 1
     fi
     echo ${chord_prediction_file}
