Always expect annotated purple VCF

diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -185,28 +185,20 @@ locate_purple_pilot_circos_plot() {
 
 locate_purple_structural_variants() {
     local run_dir=$1
-    # TODO: Remove the "ann" once annotation is all done pre-purple.
     local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.ann.vcf.gz")
-	  if [ -z ${structural_vcf} ]; then
-		    structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.vcf.gz")
-		    if [ -z ${structural_vcf} ]; then
-			      echo "[ERROR] Unable to locate purple structural variants. Exiting." >&2
-			      exit 1
-		    fi
-	  fi
+    if [ -z ${structural_vcf} ]; then
+        echo "[ERROR] Unable to locate purple structural variants. Exiting." >&2
+        exit 1
+    fi
     echo ${structural_vcf}
 }
 
 locate_purple_pilot_structural_variants() {
     local run_dir=$1
-    # TODO: Remove the "ann" once annotation is all done pre-purple.
 	  local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.ann.vcf.gz")
-	  if [ -z ${structural_vcf} ]; then
-		    structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.vcf.gz")
-		    if [ -z ${structural_vcf} ]; then
-			      echo "[ERROR] Unable to locate purple pilot structural variants. Exiting." >&2
-			      exit 1
-		    fi
+    if [ -z ${structural_vcf} ]; then
+        echo "[ERROR] Unable to locate purple pilot structural variants. Exiting." >&2
+        exit 1
     fi
     echo ${structural_vcf}
 }
@@ -249,25 +241,29 @@ locate_linx_disruptions() {
 
 locate_gridss_structural_variants() {
     local run_dir=$1
-	# Use the backport VCF if it exists
-	local structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/breakpoint_position_backport/ -type f -name "*.gridss.somatic.vcf.gz.breakpoint_position_backport.vcf.gz")
+	  # Use the backport VCF if it exists
+	  local structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/breakpoint_position_backport/ -type f -name "*.gridss.somatic.vcf.gz.breakpoint_position_backport.vcf.gz")
     if [ -z ${structural_vcf} ]; then
+        # Otherwise use v4 naming convention
         structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.vcf.gz")
-		if [ -z ${structural_vcf} ]; then
-			structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
-			if [ -z ${structural_vcf} ]; then
-				echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting." >&2
-				exit 1
-			fi
-		fi
+		    if [ -z ${structural_vcf} ]; then
+		        # Otherwise use v5 naming convention
+			      structural_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.vcf.gz")
+			      if [ -z ${structural_vcf} ]; then
+				        echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting." >&2
+				        exit 1
+			      fi
+		    fi
     fi
     echo ${structural_vcf}
 }
 
 locate_gridss_recovery_candidates() {
     local run_dir=$1
+    # Use v4 naming convention
     local sv_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name "*.gridss.somatic.full.vcf.gz")
     if [ -z ${sv_recovery_vcf} ]; then
+        # Otherwise use v5 naming convention
         sv_recovery_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name "*.gridss.somatic.full.vcf.gz")
         if [ -z ${sv_recovery_vcf} ]; then
             echo "[ERROR] Unable to locate GRIDSS sv recovery candidates. Exiting." >&2
