More consistency updates

diff --git a/snpcheck/create_sample_vcfs_from_csv b/snpcheck/create_sample_vcfs_from_csv
--- a/snpcheck/create_sample_vcfs_from_csv
+++ b/snpcheck/create_sample_vcfs_from_csv
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-CODEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+CODEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 OUTBASE="/data/common/snpcheck"
 SCRIPT="${CODEDIR}/Convert_OpenArray_CSV_to_VCF.py"
 GCPDIR="/data/gcp/snpcheckvcfupload"
@@ -18,43 +18,43 @@ if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     exit 1
 fi
 
-csvFile=$1
-if [[   -z ${csvFile} ]]; then echo "[ERROR] No csv results file provided.."; exit 1; fi
-if [[ ! -f ${csvFile} ]]; then echo "[ERROR] Input csv file does not exist?"; exit 1; fi
-if [[ ! -f ${SCRIPT}  ]]; then echo "[ERROR] Script file does not exist?"; exit 1; fi
-if [[ ! -w ${GCPDIR}  ]]; then echo "[ERROR] Output sync dir not writable ($GCPDIR)"; exit 1; fi
+csv_file=$1
+if [[   -z "${csv_file}" ]]; then echo "[ERROR] No csv results file provided.."; exit 1; fi
+if [[ ! -f "${csv_file}" ]]; then echo "[ERROR] Input csv file does not exist?"; exit 1; fi
+if [[ ! -f "${SCRIPT}"  ]]; then echo "[ERROR] Script file does not exist?"; exit 1; fi
+if [[ ! -w "${GCPDIR}"  ]]; then echo "[ERROR] Output sync dir not writable ($GCPDIR)"; exit 1; fi
 
 ## setup design to use
-oneSample=$( cat ${csvFile} | grep ^FR | cut -d"," -f1 | sort | uniq | head -1 )
-designSize=$( grep -c ^${oneSample} ${csvFile} )
-if [[ ${designSize} -eq 60 ]]; then
-  echo "[INFO] Detected temporary 60SNP panel"
-  SNPCOUNT="60"
+one_sample=$( cat ${csv_file} | grep ^FR | cut -d"," -f1 | sort | uniq | head -1 )
+design_size=$( grep -c ^${one_sample} ${csv_file} )
+if [[ ${design_size} -eq 60 ]]; then
+    echo "[INFO] Detected temporary 60SNP panel"
+    SNPCOUNT="60"
 fi
 DESIGN="${CODEDIR}/${SNPCOUNT}SNPtaq_design.vcf"
 OUTDIR="${OUTBASE}/output/${SNPCOUNT}SNPtaq"
-if [[ ! -f ${DESIGN}  ]]; then echo "[ERROR] Design file does not exist (${DESIGN})?"; exit 1; fi
-if [[ ! -d ${OUTDIR}  ]]; then echo "[ERROR] Output dir does not exist (${OUTDIR})?"; exit 1; fi
+if [[ ! -f "${DESIGN}" ]]; then echo "[ERROR] Design file does not exist (${DESIGN})?"; exit 1; fi
+if [[ ! -d "${OUTDIR}" ]]; then echo "[ERROR] Output dir does not exist (${OUTDIR})?"; exit 1; fi
 
 ## continue with parsing and converting
-experimentName=$( echo $( basename ${csvFile} ) | sed 's/.txt$//' | sed 's/.csv$//' | sed 's/_Results$//' )
-plateName=$( cat ${csvFile} | grep -A1 "^Sample ID" | tail -1 | cut -d, -f2 )
-combiName="${experimentName}_${plateName}"
-vcfOutDir="${OUTDIR}/${combiName}"
+experiment_name=$(echo $(basename ${csv_file}) | sed 's/.txt$//' | sed 's/.csv$//' | sed 's/_Results$//')
+plate_name=$(cat ${csv_file} | grep -A1 "^Sample ID" | tail -1 | cut -d, -f2)
+combi_name="${experiment_name}_${plate_name}"
+vcf_out_dir="${OUTDIR}/${combi_name}"
 
-if [[ -d ${vcfOutDir} ]]; then echo "[ERROR] Output dir already exists (${vcfOutDir})"; exit 1; fi
+if [[ -d "${vcf_out_dir}" ]]; then echo "[ERROR] Output dir already exists (${vcf_out_dir})"; exit 1; fi
 
 echo "[INFO] Starting conversion from CSVs to VCFs"
-echo "[INFO] Output dir will be: ${vcfOutDir}"
-mkdir ${vcfOutDir}
-${SCRIPT} --out ${vcfOutDir} --des ${DESIGN} --csv ${csvFile}
-vcfCount=$(ls ${vcfOutDir} | wc -l)
-echo "[INFO] Total of ${vcfCount} VCFs created"
+echo "[INFO] Output dir will be: ${vcf_out_dir}"
+mkdir ${vcf_out_dir}
+${SCRIPT} --out ${vcf_out_dir} --des ${DESIGN} --csv ${csv_file}
+vcf_count=$(ls ${vcf_out_dir} | wc -l)
+echo "[INFO] Total of ${vcf_count} VCFs created"
 echo ""
 echo "[TODO] Performs plate QC"
-echo "  perform_snpcheck_plate_qc ${vcfOutDir}"
+echo "  perform_snpcheck_plate_qc ${vcf_out_dir}"
 echo ""
 echo "[TODO] Also copy the results to sync dir"
-echo "  cp -r ${vcfOutDir} ${GCPDIR}"
+echo "  cp -r ${vcf_out_dir} ${GCPDIR}"
 echo ""
 
diff --git a/snpcheck/genotype_bam b/snpcheck/genotype_bam
--- a/snpcheck/genotype_bam
+++ b/snpcheck/genotype_bam
@@ -10,22 +10,28 @@ designs=(
     '81SNPmip_design.vcf'
 )
 
-bamPath=$1
+bam_path=$1
 
-if [[ ! -f ${bamPath} ]]; then echo "Provide path to bam"; exit 1; fi
-if [[ ! "${bamPath}" =~ \.bam$ ]]; then echo "Only BAM files as input"; exit 1; fi
+if [[ ! -f "${bam_path}" ]]; then echo "[ERROR] Provide path to bam"; exit 1; fi
+if [[ ! "${bam_path}" =~ \.bam$ ]]; then echo "[ERROR] Only BAM files as input"; exit 1; fi
 
 echo "[INFO] SNPcheck Genotying Starting"
 
-fileName=$( basename $bamPath )
-sampleName=$( echo $fileName | sed 's/\.bam//' )
+file_name=$(basename ${bam_path})
+sample_name=$(echo ${file_name} | sed 's/\.bam//')
 
-for designFile in "${designs[@]}"; do
-    designName=$( echo $designFile | sed 's/_design\.vcf//' )
-    designPath=${DESIGN_DIR}'/'${designFile}
-    outFile="${sampleName}_${designName}_snpcheck.vcf"
-    echo "[INFO] Genotying by ${designName} for ${sampleName} to ${outFile}"
-    java -Xms2g -Xmx9g -jar ${GATK_JAR} -T UnifiedGenotyper -R ${REF_FASTA} -L ${designPath} --output_mode EMIT_ALL_SITES -I ${bamPath} -o ${outFile}
+for design_file in "${designs[@]}"; do
+    design_name=$( echo ${design_file} | sed 's/_design\.vcf//' )
+    design_path=${DESIGN_DIR}'/'${design_file}
+    out_file="${sample_name}_${design_name}_snpcheck.vcf"
+    echo "[INFO] Genotying by ${design_name} for ${sample_name} to ${out_file}"
+    java -Xms2g -Xmx9g -jar ${GATK_JAR} \
+        -T UnifiedGenotyper \
+        -R ${REF_FASTA} \
+        -L ${design_path} \
+        --output_mode EMIT_ALL_SITES \
+        -I ${bam_path} \
+        -o ${out_file}
 done
 
 echo "[INFO] SNPcheck Genotying Done"
diff --git a/snpcheck/perform_snpcheck_plate_qc b/snpcheck/perform_snpcheck_plate_qc
--- a/snpcheck/perform_snpcheck_plate_qc
+++ b/snpcheck/perform_snpcheck_plate_qc
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
-vcfDirPath=$1
+vcf_dir_path=$1
 
 echo "[INFO] START with $(basename $0)"
 
-if [[ -z ${vcfDirPath} || $1 == "-h" || $1 == "--help" ]]; then
+if [[ -z "${vcf_dir_path}" || $1 == "-h" || $1 == "--help" ]]; then
   echo "---"
   echo " Usage: $(basename $0) \${pathToDirWithVCFs}"
   echo "    Eg: $(basename $0) /data/common/snpcheck/output/26SNPtaq/S19-0001_20190103_092420_BDF33/"
@@ -12,21 +12,21 @@ if [[ -z ${vcfDirPath} || $1 == "-h" || $1 == "--help" ]]; then
   exit 1
 fi
 
-if [[ ! -d ${vcfDirPath} ]]; then echo "[ERROR] Dir does not exist (${vcfDirPath})" && exit 1; fi
+if [[ ! -d "${vcf_dir_path}" ]]; then echo "[ERROR] Dir does not exist (${vcf_dir_path})" && exit 1; fi
 
-qcLogsPath="/data/common/snpcheck/qc"
-nasPath="/volume1/web/qc/snpcheck"
+qc_logs_path="/data/common/snpcheck/qc"
+nas_path="/volume1/web/qc/snpcheck"
 
-vcfDirName=$(basename ${vcfDirPath})
-qcLogName="${vcfDirName}.qc"
-qcLogPath="${qcLogsPath}/${qcLogName}"
+vcf_dir_name=$(basename ${vcf_dir_path})
+qc_log_name="${vcf_dir_name}.qc"
+qc_log_path="${qc_logs_path}/${qc_log_name}"
 
-echo "[INFO]  Performing QC (${qcLogName})"
-perform_snpcheck.pl -qc -vcfDir "${vcfDirPath}" > "${qcLogPath}"
+echo "[INFO]  Performing QC (${qc_log_name})"
+perform_snpcheck.pl -qc -vcfDir "${vcf_dir_path}" > "${qc_log_path}"
 if [[ $? != 0 ]]; then echo "[ERROR] perform_snpcheck finished with non-zero exit code ($?)" && exit 1; fi
 
-echo "[INFO]  Syncing log to NAS (${qcLogPath})"
-rsync -ah "${qcLogPath}" "nas:${nasPath}/${qcLogName}"
+echo "[INFO]  Syncing log to NAS (${qc_log_path})"
+rsync -ah "${qc_log_path}" "nas:${nas_path}/${qc_log_name}"
 
 echo "[INFO] DONE with $(basename $0)"
 
diff --git a/sql/execution/execute_sql_on_prod b/sql/execution/execute_sql_on_prod
--- a/sql/execution/execute_sql_on_prod
+++ b/sql/execution/execute_sql_on_prod
@@ -4,9 +4,8 @@ source locate_files
 
 file_with_sql_to_execute=$1
 
-if [[ ! -f ${file_with_sql_to_execute} ]]; then
-    echo "[ERROR] Unable to locate SQL file to execute. Exiting."
-    exit 1
+if [[ ! -f "${file_with_sql_to_execute}" ]]; then
+    echo "[ERROR] Unable to locate SQL file to execute. Exiting." && exit 1
 fi
 
 credentials=$(locate_prod_database_credentials)
diff --git a/validation/compare_v5_runs b/validation/compare_v5_runs
--- a/validation/compare_v5_runs
+++ b/validation/compare_v5_runs
@@ -7,10 +7,10 @@ test_run_path=$2
 
 tools=(amber bachelor chord cobalt health_checker linx purple sage structural_caller)
 
-base_pip_vsn_file="$base_run_path/pipeline.version"
-test_pip_vsn_file="$test_run_path/pipeline.version"
-base_meta_file="$base_run_path/metadata.json"
-test_meta_file="$test_run_path/metadata.json"
+base_pip_vsn_file="${base_run_path}/pipeline.version"
+test_pip_vsn_file="${test_run_path}/pipeline.version"
+base_meta_file="${base_run_path}/metadata.json"
+test_meta_file="${test_run_path}/metadata.json"
 
 if [[ "$#" -ne 2 ]]; then 
     echo "-----"
@@ -20,10 +20,10 @@ if [[ "$#" -ne 2 ]]; then
     echo "-----"
     exit 1
 fi
-if [[ ! -d "${base_run_path}" ]]; then echo "[ERROR] Directory not found ($base_run_path)" && exit 1; fi
-if [[ ! -d "${test_run_path}" ]]; then echo "[ERROR] Directory not found ($test_run_path)" && exit 1; fi
-if [[ ! -f "${base_pip_vsn_file}" ]]; then echo "[ERROR] File not found ($base_pip_vsn_file)" && exit 1; fi
-if [[ ! -f "${test_pip_vsn_file}" ]]; then echo "[ERROR] File not found ($test_pip_vsn_file)" && exit 1; fi
+if [[ ! -d "${base_run_path}" ]]; then echo "[ERROR] Directory not found (${base_run_path})" && exit 1; fi
+if [[ ! -d "${test_run_path}" ]]; then echo "[ERROR] Directory not found (${test_run_path})" && exit 1; fi
+if [[ ! -f "${base_pip_vsn_file}" ]]; then echo "[ERROR] File not found (${base_pip_vsn_file})" && exit 1; fi
+if [[ ! -f "${test_pip_vsn_file}" ]]; then echo "[ERROR] File not found (${test_pip_vsn_file})" && exit 1; fi
 
 base_pip_vsn=$(cat "${base_pip_vsn_file}")
 test_pip_vsn=$(cat "${test_pip_vsn_file}")
@@ -62,7 +62,7 @@ for tool_name in ${tools[*]}; do
     test_tool_path="${test_run_path}/${tool_name}"
     base_file_count=$(find "${base_tool_path}" -maxdepth 1 | wc -l)
     test_file_count=$(find "${test_tool_path}" -maxdepth 1 | wc -l)
-    if [[ $base_file_count -eq $test_file_count ]]; then
+    if [[ ${base_file_count} -eq ${test_file_count} ]]; then
         echo "[INFO] Identical file count (${base_file_count}) for tool ${tool_name}"
     else
         echo "[WARN] DIFFERENT file count (${base_file_count} vs ${test_file_count}) for tool ${tool_name}"
@@ -75,7 +75,7 @@ for tool_name in ${tools[*]}; do
         test_file_path="${test_run_path}/${tool_name}/${file_name}"
         base_count=$(cat "${base_file_path}" | wc -l)
         test_count=$(cat "${test_file_path}" | wc -l)
-        if [[ $base_count -eq $test_count ]]; then
+        if [[ ${base_count} -eq ${test_count} ]]; then
             echo "[INFO]   Identical line count (${base_count}) for file ${file_name}"
         else
             echo "[WARN]   DIFFERENT line count (${base_count} vs ${test_count}) for file ${file_name}"
@@ -112,31 +112,31 @@ echo "[INFO] TEST VIRAL:    ${test_vir_ins}"
 echo "[INFO] BASE BACHELOR: ${base_bach}"
 echo "[INFO] TEST BACHELOR: ${test_bach}"
 
-for file in "$test_grm_vcf" "$base_grm_vcf" "$test_chord" "$base_chord" "$test_vir_ins" "$base_vir_ins" "$test_bach" "$base_bach"; do
+for file in "${test_grm_vcf}" "${base_grm_vcf}" "${test_chord}" "${base_chord}" "${test_vir_ins}" "${base_vir_ins}" "${test_bach}" "${base_bach}"; do
     if [[ ! -f "${file}" ]]; then
         echo "[WARN] File does not exist ($file)" && exit 1
     fi
 done
 
 echo "[INFO] Counting somatic small variants"
-test_som_varCount=$(unpigz -c "$test_som_var" | grep -cv ^#)
-base_som_varCount=$(unpigz -c "$base_som_var" | grep -cv ^#)
-test_som_pass_var_count=$(unpigz -c "$test_som_var" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
-base_som_pass_var_count=$(unpigz -c "$base_som_var" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
+test_som_varCount=$(unpigz -c "${test_som_var}" | grep -cv ^#)
+base_som_varCount=$(unpigz -c "${base_som_var}" | grep -cv ^#)
+test_som_pass_var_count=$(unpigz -c "${test_som_var}" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
+base_som_pass_var_count=$(unpigz -c "${base_som_var}" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
 
 echo "[INFO] Counting somatic structural variants"
-test_sv_varCount=$(unpigz -c "$test_sv_var" | grep -cv ^#)
-base_sv_varCount=$(unpigz -c "$base_sv_var" | grep -cv ^#)
-test_sv_pass_var_count=$(unpigz -c "$test_sv_var" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
-base_sv_pass_var_count=$(unpigz -c "$base_sv_var" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
-test_sv_non_pon_var_count=$(unpigz -c "$test_sv_var" | grep -v ^# | awk '$7 != "PON"' | wc -l)
-base_sv_non_pon_var_count=$(unpigz -c "$base_sv_var" | grep -v ^# | awk '$7 != "PON"' | wc -l)
+test_sv_var_count=$(unpigz -c "${test_sv_var}" | grep -cv ^#)
+base_sv_var_count=$(unpigz -c "${base_sv_var}" | grep -cv ^#)
+test_sv_pass_var_count=$(unpigz -c "${test_sv_var}" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
+base_sv_pass_var_count=$(unpigz -c "${base_sv_var}" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
+test_sv_non_pon_var_count=$(unpigz -c "${test_sv_var}" | grep -v ^# | awk '$7 != "PON"' | wc -l)
+base_sv_non_pon_var_count=$(unpigz -c "${base_sv_var}" | grep -v ^# | awk '$7 != "PON"' | wc -l)
 
 echo "[INFO] Counting germline variants"
-test_grm_var_count=$(unpigz -c "$test_grm_vcf" | grep -cv ^#)
-base_grm_var_count=$(unpigz -c "$base_grm_vcf" | grep -cv ^#)
-test_grm_pass_var_count=$(unpigz -c "$test_grm_vcf" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
-base_grm_pass_var_count=$(unpigz -c "$base_grm_vcf" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
+test_grm_var_count=$(unpigz -c "${test_grm_vcf}" | grep -cv ^#)
+base_grm_var_count=$(unpigz -c "${base_grm_vcf}" | grep -cv ^#)
+test_grm_pass_var_count=$(unpigz -c "${test_grm_vcf}" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
+base_grm_pass_var_count=$(unpigz -c "${base_grm_vcf}" | grep -v ^# | awk '$7 == "PASS"' | wc -l)
 test_tool_vsn=$( cat ${test_run_path}/run.log | awk '/Versions of tools/,/\]/' | awk 'NR>2 {print last} {last=$0}' | cut -d" " -f5,6 | paste -s -d '|')
 base_tool_vsn=$( cat ${base_run_path}/run.log | awk '/Versions of tools/,/\]/' | awk 'NR>2 {print last} {last=$0}' | cut -d" " -f5,6 | paste -s -d '|')
 
@@ -144,66 +144,66 @@ declare -A tool_names
 declare -A tool_versions
 
 while read name_vsn_str; do 
-    tool_name=$(echo "$name_vsn_str" | cut -d":" -f1)
-    tool_vsn=$(echo "$name_vsn_str" | cut -d":" -f2)
-    tool_names[$tool_name]="true"
-    tool_versions["${tool_name}_BASE"]="$tool_vsn"
+    tool_name=$(echo "${name_vsn_str}" | cut -d":" -f1)
+    tool_vsn=$(echo "${name_vsn_str}" | cut -d":" -f2)
+    tool_names[${tool_name}]="true"
+    tool_versions["${tool_name}_BASE"]="${tool_vsn}"
 done < <(cat ${base_run_path}/run.log | awk '/Versions of tools/,/\]/' | awk 'NR>2 {print last} {last=$0}' | cut -d" " -f5,6 | sed 's/ //g')
 
 while read name_vsn_str; do 
-    tool_name=$(echo "$name_vsn_str" | cut -d":" -f1)
-    tool_vsn=$(echo "$name_vsn_str" | cut -d":" -f2)
-    tool_names["$tool_name"]="true"
-    tool_versions["${tool_name}_TEST"]="$tool_vsn"
+    tool_name=$(echo "${name_vsn_str}" | cut -d":" -f1)
+    tool_vsn=$(echo "${name_vsn_str}" | cut -d":" -f2)
+    tool_names["${tool_name}"]="true"
+    tool_versions["${tool_name}_TEST"]="${tool_vsn}"
 done < <(cat ${test_run_path}/run.log | awk '/Versions of tools/,/\]/' | awk 'NR>2 {print last} {last=$0}' | cut -d" " -f5,6 | sed 's/ //g')
 
 echo "[INFO] TOOL VERSIONS"
 for tool_name in "${!tool_names[@]}"; do 
     base_vsn=${tool_versions["${tool_name}_BASE"]}
     test_vsn=${tool_versions["${tool_name}_TEST"]}
-    echo "  $tool_name BASE=$base_vsn" 
-    echo "  $tool_name TEST=$test_vsn" 
+    echo "  ${tool_name} BASE=${base_vsn}" 
+    echo "  ${tool_name} TEST=${test_vsn}" 
 done
 
 echo ""
 echo "===== File content CHECKS"
 
 echo "[INFO] PIPELINE VERSION"
-echo "  BASE: $base_pip_vsn"
-echo "  TEST: $test_pip_vsn"
+echo "  BASE: ${base_pip_vsn}"
+echo "  TEST: ${test_pip_vsn}"
 
 echo "[INFO] TOOL VERSIONS"
-echo "  BASE: $base_tool_vsn"
-echo "  TEST: $test_tool_vsn"
+echo "  BASE: ${base_tool_vsn}"
+echo "  TEST: ${test_tool_vsn}"
 
 echo "[INFO] GERMLINE file checks"
-echo "  BASE VAR TOTAL COUNT: $base_grm_var_count"
-echo "  TEST VAR TOTAL COUNT: $test_grm_var_count"
-echo "  BASE VAR PASS COUNT: $base_grm_pass_var_count"
-echo "  TEST VAR PASS COUNT: $test_grm_pass_var_count"
+echo "  BASE VAR TOTAL COUNT: ${base_grm_var_count}"
+echo "  TEST VAR TOTAL COUNT: ${test_grm_var_count}"
+echo "  BASE VAR PASS COUNT: ${base_grm_pass_var_count}"
+echo "  TEST VAR PASS COUNT: ${test_grm_pass_var_count}"
 
 echo "[INFO] PURPLE file checks"
-echo "  BASE VAR TOTAL COUNT: $base_som_varCount"
-echo "  TEST VAR TOTAL COUNT: $test_som_varCount"
-echo "  BASE VAR PASS COUNT: $base_som_pass_var_count"
-echo "  TEST VAR PASS COUNT: $test_som_pass_var_count"
-echo "  BASE SV VAR TOTAL COUNT: $base_sv_varCount"
-echo "  TEST SV VAR TOTAL COUNT: $test_sv_varCount"
-echo "  BASE SV VAR PASS COUNT: $base_sv_pass_var_count"
-echo "  TEST SV VAR PASS COUNT: $test_sv_pass_var_count"
-echo "  BASE SV VAR NON-PON COUNT: $base_sv_non_pon_var_count"
-echo "  TEST SV VAR NON-PON COUNT: $test_sv_non_pon_var_count"
+echo "  BASE VAR TOTAL COUNT: ${base_som_var}Count"
+echo "  TEST VAR TOTAL COUNT: ${test_som_var}Count"
+echo "  BASE VAR PASS COUNT: ${base_som_pass_var_count}"
+echo "  TEST VAR PASS COUNT: ${test_som_pass_var_count}"
+echo "  BASE SV VAR TOTAL COUNT: ${base_sv_var}_count"
+echo "  TEST SV VAR TOTAL COUNT: ${test_sv_var}_count"
+echo "  BASE SV VAR PASS COUNT: ${base_sv_pass_var_count}"
+echo "  TEST SV VAR PASS COUNT: ${test_sv_pass_var_count}"
+echo "  BASE SV VAR NON-PON COUNT: ${base_sv_non_pon_var_count}"
+echo "  TEST SV VAR NON-PON COUNT: ${test_sv_non_pon_var_count}"
 
 echo "[INFO] CHORD file content"
-cat $base_chord | awk '{print "  BASE: "$0}'
-cat $test_chord | awk '{print "  TEST: "$0}'
+cat ${base_chord} | awk '{print "  BASE: "$0}'
+cat ${test_chord} | awk '{print "  TEST: "$0}'
 
 echo "[INFO] LINX file content"
-cat $base_vir_ins | awk '{print "  BASE: "$0}'
-cat $test_vir_ins | awk '{print "  TEST: "$0}'
+cat ${base_vir_ins} | awk '{print "  BASE: "$0}'
+cat ${test_vir_ins} | awk '{print "  TEST: "$0}'
 
 echo "[INFO] BACHELOR file content"
-cat $base_bach | cut -f 1-2,4-7 | tr "\t" "," | awk '{print "  BASE: "$0}'
-cat $test_bach | cut -f 1-2,4-7 | tr "\t" "," | awk '{print "  TEST: "$0}'
+cat ${base_bach} | cut -f 1-2,4-7 | tr "\t" "," | awk '{print "  BASE: "$0}'
+cat ${test_bach} | cut -f 1-2,4-7 | tr "\t" "," | awk '{print "  TEST: "$0}'
 
 echo ""
