DEV-2183: use copy_file_to_nas and copy_file_from_nas instead of direct rsync

diff --git a/snpcheck/perform_snpcheck_plate_qc b/snpcheck/perform_snpcheck_plate_qc
--- a/snpcheck/perform_snpcheck_plate_qc
+++ b/snpcheck/perform_snpcheck_plate_qc
@@ -4,12 +4,12 @@ source message_functions || exit 1
 
 vcf_dir_path=$1
 
-info "START with $(basename $0)"
+info "START with $(basename "$0")"
 
 if [[ -z "${vcf_dir_path}" || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
-    echo " Usage: $(basename $0) \${pathToDirWithVCFs}"
-    echo "    Eg: $(basename $0) /data/common/snpcheck/output/26SNPtaq/S19-0001_20190103_092420_BDF33/"
+    echo " Usage: $(basename "$0") \${pathToDirWithVCFs}"
+    echo "    Eg: $(basename "$0") /data/common/snpcheck/output/26SNPtaq/S19-0001_20190103_092420_BDF33/"
     echo "---"
     exit 1
 fi
@@ -19,16 +19,15 @@ if [[ ! -d "${vcf_dir_path}" ]]; then error "Dir does not exist (${vcf_dir_path}
 qc_logs_path="/data/common/snpcheck/qc"
 nas_path="/volume1/web/qc/snpcheck"
 
-vcf_dir_name=$(basename ${vcf_dir_path})
+vcf_dir_name=$(basename "${vcf_dir_path}")
 qc_log_name="${vcf_dir_name}.qc"
 qc_log_path="${qc_logs_path}/${qc_log_name}"
 
 info " Performing QC (${qc_log_name})"
-perform_snpcheck.pl -qc -vcfDir "${vcf_dir_path}" > "${qc_log_path}"
-if [[ $? != 0 ]]; then error "perform_snpcheck finished with non-zero exit code ($?)"; fi
+perform_snpcheck.pl -qc -vcfDir "${vcf_dir_path}" > "${qc_log_path}" || die "Processing of snp plate results failed ($?)"
 
 info " Syncing log to NAS (${qc_log_path})"
-rsync -ah "${qc_log_path}" "nas:${nas_path}/${qc_log_name}"
+copy_file_to_nas "${qc_log_path}" "${nas_path}" || die "Copying of qc to NAS failed ($?)"
 
-info "DONE with $(basename $0)"
+info "DONE with $(basename "$0")"
 
diff --git a/snpcheck/process_snpgenotyping_file_from_nas b/snpcheck/process_snpgenotyping_file_from_nas
--- a/snpcheck/process_snpgenotyping_file_from_nas
+++ b/snpcheck/process_snpgenotyping_file_from_nas
@@ -1,10 +1,11 @@
 #!/usr/bin/env bash
 
 source message_functions || exit 1
+command -v copy_file_from_nas > /dev/null || die "Missing dependency copy_file_from_nas"
 
-SOURCE='/volume1/machines/Experimenten/SNP\ check'
-TARGET='/data/common/snpcheck/input'
-SUFFIX='Results.csv'
+nas_dir='/volume1/machines/Experimenten/SNP\ check'
+target_dir='/data/common/snpcheck/input'
+file_suffix='Results.csv'
 
 plate_id=$1
 
@@ -17,11 +18,11 @@ if [[ -z "${plate_id}" || $1 == "-h" || $1 == "--help" ]]; then
 fi
 
 ## find at NAS
-info "Searching for \"${plate_id}*${SUFFIX}\" results file in \"nas:${SOURCE}\""
+info "Searching for \"${plate_id}*${file_suffix}\" results file in \"nas:${nas_dir}\""
 result_files=()
 while IFS=  read -r -d $'\0'; do
     result_files+=("$REPLY")
-done < <(ssh nas find "${SOURCE}" -name "${plate_id}*${SUFFIX}" -print0)
+done < <(ssh nas find "${nas_dir}" -name "${plate_id}*${file_suffix}" -print0)
 if [[ ${#result_files[@]} -eq 0 ]]; then 
     error "No file found for '${plate_id}'!"
 elif [[ ${#result_files[@]} -gt 1 ]]; then
@@ -31,14 +32,15 @@ fi
 ## sync and process
 result_file_path="${result_files[0]}"
 result_file_name=$(basename "${result_file_path}")
-target_file_path="${TARGET}/${result_file_name}"
+target_file_path="${target_dir}/${result_file_name}"
 
 info "Found SNPcheck file at NAS ($result_file_name)"
 info " syncing to datastore"
-rsync --protect-args -ah "nas:${result_file_path}" "${target_file_path}"
-if [[ $? != 0 ]]; then error "Rsync finished with non-zero exit code ($?)"; fi
+#rsync --protect-args -ah "nas:${result_file_path}" "${target_file_path}"
+copy_file_from_nas "${result_file_path}" "${target_dir}/" || die "Rsync finished with non-zero exit code ($?)"
+#if [[ $? != 0 ]]; then error "Rsync finished with non-zero exit code ($?)"; fi
 
 info "  converting file VCFs"
-create_sample_vcfs_from_csv "${target_file_path}"
-if [[ $? != 0 ]]; then error "Conversion to VCF finished with non-zero exit code ($?)"; fi
+create_sample_vcfs_from_csv "${target_file_path}" || die "Conversion to VCF finished with non-zero exit code ($?)"
+#if [[ $? != 0 ]]; then error "Conversion to VCF finished with non-zero exit code ($?)"; fi
 
