Some clean up of health checker scripts. Do not pass output dir when not writing output file

diff --git a/hmftools/healthchecker/run_health_checker_pilot b/hmftools/healthchecker/run_health_checker_pilot
--- a/hmftools/healthchecker/run_health_checker_pilot
+++ b/hmftools/healthchecker/run_health_checker_pilot
@@ -1,13 +1,12 @@
 #!/usr/bin/env bash
 
-source locate_files
-source metadata_functions
+source locate_files || exit 1
+source metadata_functions || exit 1
 
 run_dir=$1 && shift
 
 if [[ -z "${run_dir}" ]]; then
-    echo "[ERROR] No rundir is provided to $(basename $0). Exiting."
-    exit 1
+    echo "[ERROR] No rundir is provided to $(basename $0). Exiting." && exit 1
 fi
 
 # Load metadata
@@ -20,7 +19,6 @@ ref_flagstat=$(locate_flagstats "${run_dir}" "${ref_sample}")
 tum_flagstat=$(locate_flagstats "${run_dir}" "${tumor_sample}")
 ref_wgs_metrics=$(locate_wgs_metrics "${run_dir}" "${ref_sample}")
 tum_wgs_metrics=$(locate_wgs_metrics "${run_dir}" "${tumor_sample}")
-output_dir=/data/cpct/pilot_health_check_logs
 
 java -Xmx8G -Xms4G -jar /data/common/tools/healthchecker_pilot/health-checker.jar \
     -reference ${ref_sample} \
@@ -30,5 +28,4 @@ java -Xmx8G -Xms4G -jar /data/common/tools/healthchecker_pilot/health-checker.ja
     -ref_flagstat_file ${ref_flagstat} \
     -tum_flagstat_file ${tum_flagstat} \
     -purple_dir ${purple_dir} \
-    -do_not_write_evaluation_file \
-    -output_dir ${output_dir}
+    -do_not_write_evaluation_file
diff --git a/hmftools/healthchecker/run_health_checker_pilot_single_sample b/hmftools/healthchecker/run_health_checker_pilot_single_sample
--- a/hmftools/healthchecker/run_health_checker_pilot_single_sample
+++ b/hmftools/healthchecker/run_health_checker_pilot_single_sample
@@ -1,23 +1,20 @@
 #!/usr/bin/env bash
 
-source locate_files
-source metadata_functions
+source locate_files || exit 1
+source metadata_functions || exit 1
 
 run_dir=$1 && shift
 
 if [[ -z "${run_dir}" ]]; then
-    echo "[ERROR] No rundir is provided to $(basename $0). Exiting."
-    exit 1
+    echo "[ERROR] No rundir is provided to $(basename $0). Exiting." && exit 1
 fi
 
 sample=$(basename "${run_dir}" | cut -d"_" -f4)
 flagstat=$(locate_flagstats "${run_dir}" "${sample}")
 wgs_metrics=$(locate_wgs_metrics "${run_dir}" "${sample}")
-output_dir=/data/cpct/pilot_health_check_logs
 
 java -Xmx8G -Xms4G -jar /data/common/tools/healthchecker_pilot/health-checker.jar \
     -reference ${sample} \
     -ref_wgs_metrics_file ${wgs_metrics} \
     -ref_flagstat_file ${flagstat} \
-    -do_not_write_evaluation_file \
-    -output_dir ${output_dir}
+    -do_not_write_evaluation_file
diff --git a/hmftools/healthchecker/run_health_checker_prod b/hmftools/healthchecker/run_health_checker_prod
--- a/hmftools/healthchecker/run_health_checker_prod
+++ b/hmftools/healthchecker/run_health_checker_prod
@@ -1,13 +1,12 @@
 #!/usr/bin/env bash
 
-source locate_files
-source metadata_functions
+source locate_files || exit 1
+source metadata_functions || exit 1
 
 run_dir=$1 && shift
 
 if [[ -z "${run_dir}" ]]; then
-    echo "[ERROR] No rundir is provided to $(basename $0). Exiting."
-    exit 1
+    echo "[ERROR] No rundir is provided to $(basename $0). Exiting." && exit 1
 fi
 
 # Load metadata
