Use message functions in health checker scripts

diff --git a/hmftools/healthchecker/run_health_checker_pilot_single_sample b/hmftools/healthchecker/run_health_checker_pilot_single_sample
--- a/hmftools/healthchecker/run_health_checker_pilot_single_sample
+++ b/hmftools/healthchecker/run_health_checker_pilot_single_sample
@@ -2,18 +2,19 @@
 
 source locate_files || exit 1
 source metadata_functions || exit 1
+source message_functions || exit 1
 
 run_dir=$1 && shift
 
 if [[ -z "${run_dir}" ]]; then
-    echo "[ERROR] No rundir is provided to $(basename $0). Exiting." && exit 1
+    error "[ERROR] No rundir is provided to $(basename $0). Exiting."
 fi
 
 sample=$(basename "${run_dir}" | cut -d"_" -f4)
 flagstat=$(locate_flagstats "${run_dir}" "${sample}")
 wgs_metrics=$(locate_wgs_metrics "${run_dir}" "${sample}")
 
-java -Xmx8G -Xms4G -jar /data/common/tools/healthchecker_pilot/health-checker.jar \
+java -Xmx4G -jar /data/common/tools/healthchecker_pilot/health-checker.jar \
     -reference ${sample} \
     -ref_wgs_metrics_file ${wgs_metrics} \
     -ref_flagstat_file ${flagstat} \
