ACTIN-2627: Update scripts to reflect removal of the hash (#116)

diff --git a/actin/hashing/lookup_nki_actin_id_for_hospital_id b/actin/hashing/lookup_nki_actin_id_for_hospital_id
--- a/actin/hashing/lookup_nki_actin_id_for_hospital_id
+++ b/actin/hashing/lookup_nki_actin_id_for_hospital_id
@@ -3,9 +3,9 @@
 source message_functions || exit 1
 source actin_config || exit 1
 
-hashed_id=$1 && shift
+hospital_id=$1 && shift
 
-if [[ -z ${hashed_id} ]]; then
+if [[ -z ${hospital_id} ]]; then
     error "Missing parameters. Exiting"
 fi
 
@@ -15,8 +15,8 @@ gs_url="gs://${gcp_project}-id-state/id.state"
 gsutil -q stat ${gs_url}
 [[ $? -ne 0 ]] && echo "Cannot find ${gs_url}" >&2 && exit 1
 
-actin_id=$(gsutil cat ${gs_url} | jq -er ".[\"${hashed_id}\"]")
+actin_id=$(gsutil cat ${gs_url} | jq -er ".[\"${hospital_id}\"]")
 
-[[ $? -ne 0 ]] && echo "Could not find mapping for ${hashed_id}" >&2 && exit 1
+[[ $? -ne 0 ]] && echo "Could not find mapping for ${hospital_id}" >&2 && exit 1
 
 echo "${actin_id}"
