Bunch of consistency improvements + remove workaround for linx pre v1.7

diff --git a/hmftools/amber/do_download_amber_bams b/hmftools/amber/do_download_amber_bams
--- a/hmftools/amber/do_download_amber_bams
+++ b/hmftools/amber/do_download_amber_bams
@@ -2,8 +2,12 @@
 
 source metadata_functions
 
-prefix=$(dirname $(readlink $0 || echo $0))
 run_dir=$1 && shift
+if [[ -z "${run_dir}" ]]; then
+    echo "[ERROR] Run dir not provided. Exiting."
+    exit 1
+fi
+
 set=$(basename ${run_dir})
 
 amber_bed=/data/common/dbs/germline_het_pon_hg19/GermlineHetPon.hg19.bed
@@ -15,10 +19,10 @@ out_dir=/data/gcp/bam_downloads
 
 #sample_bam=${out_dir}/${sample}.amber.bam
 #if [[ ! -f ${sample_bam} ]]; then
-#    ${prefix}/../bamslicer/do_slice_bam_on_gcp ${set} ${sample} ${amber_bed} ${sample_bam}
+#    do_slice_bam_on_gcp ${set} ${sample} ${amber_bed} ${sample_bam}
 #fi
 
 normal_bam=${out_dir}/${normal}.amber.bam
 if [[ ! -f ${normal_bam} ]]; then
-    ${prefix}/../bamslicer/slice_ref_sample_bam_on_gcp ${set} ${sample} ${amber_bed} ${normal_bam}
+    slice_ref_sample_bam_on_gcp ${set} ${sample} ${amber_bed} ${normal_bam}
 fi
diff --git a/hmftools/gridss/do_run_gridss_lib b/hmftools/gridss/do_run_gridss_lib
--- a/hmftools/gridss/do_run_gridss_lib
+++ b/hmftools/gridss/do_run_gridss_lib
@@ -7,7 +7,7 @@ gridss_jar=$1 && shift
 threads=$1 && shift
 
 if [[ ! -f ${gridss_jar} ]] ; then
-	  echo "Missing GRIDSS jar $gridss_jar. Aborting" 1>&2
+	  echo "[ERROR] Missing GRIDSS jar $gridss_jar. Aborting" 1>&2
 	  exit 1
 fi
 
@@ -29,14 +29,14 @@ export PATH=$PATH:${base_path}/tools/samtools_v1.2/
 if which bwa > /dev/null ; then
 	  echo -n
 else
-	  echo "Missing bwa. Aborting"
+	  echo "[ERROR] Missing bwa. Aborting"
 	  exit 1
 fi
 
 if which samtools > /dev/null ; then
 	  echo -n
 else
-	  echo "Missing samtools. Aborting"
+	  echo "[ERROR] Missing samtools. Aborting"
 	  exit 1
 fi
 
@@ -85,26 +85,26 @@ mkdir -p ${gridss_dir} ${log_dir}
 
 function assert_preprocessing_complete() {
 	  if [[ ! -f ${gridss_dir}/$(basename ${normal_bam}).gridss.working/$(basename ${normal_bam}).sv.bam ]] ; then
-		    echo "Normal bam preprocessing not complete. Terminating." 1>&2
+		    echo "[ERROR] Normal bam preprocessing not complete. Terminating." 1>&2
 		    exit 1
 	  fi
 	  
 	  if [[ ! -f ${gridss_dir}/$(basename ${tumor_bam}).gridss.working/$(basename ${tumor_bam}).sv.bam ]] ; then
-		    echo "Tumor bam preprocessing not complete. Terminating." 1>&2
+		    echo "[ERROR] Tumor bam preprocessing not complete. Terminating." 1>&2
 		    exit 1
 	  fi
 }
 
 function assert_assembly_complete() {
 	  if [[ ! -f ${gridss_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_bam}).sv.bam ]] ; then
-		    echo "Assembly not complete. Terminating." 1>&2
+		    echo "[ERROR] Assembly not complete. Terminating." 1>&2
 		    exit 1
 	  fi
 }
 
 function assert_calling_complete() {
 	  if [[ ! -f ${gridss_raw_vcf}.unannotated.vcf ]] ; then
-		    echo "Variant calling not complete. Terminating." 1>&2
+		    echo "[ERROR] Variant calling not complete. Terminating." 1>&2
 		    exit 1
 	  fi
 }
