Use CKB in PROTECT pilot mode

diff --git a/hmftools/protect/do_run_protect_pilot b/hmftools/protect/do_run_protect_pilot
--- a/hmftools/protect/do_run_protect_pilot
+++ b/hmftools/protect/do_run_protect_pilot
@@ -2,16 +2,17 @@
 
 # TODO: File can go once linx_driver_catalog_tsv param change is in production and params germline_reporting_tsv ,bachelor_tsv and linx_viral_insertion_tsv removed!
 
-source locate_files
-source metadata_functions
-source lims_functions
+source locate_files || exit 1
+source metadata_functions || exit 1
+source lims_functions || exit 1
+source message_functions || exit 1
 
 run_dir=$1 && shift
 output_dir=$1 && shift
 protect_jar=$1 && shift
 
 if [[ -z "${run_dir}" || -z "${output_dir}" || -z "${protect_jar}" ]]; then
-    echo "[ERROR] Missing input parameters. Exiting" && exit 1;
+    error "Missing input parameters. Exiting";
 fi
 
 tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
@@ -26,7 +27,7 @@ if [[ ! -z "${primary_tumor_doids}" ]]; then
     primary_tumor_argument="-primary_tumor_doids ${primary_tumor_doids}"
 fi
 
-serve_actionability_dir=/data/common/dbs/serve/prod_output
+serve_actionability_dir=/data/common/dbs/serve/pilot_output_ckb_only
 doid_json=/data/common/dbs/disease_ontology/201015_doid.json
 
 purple_purity_tsv=$(locate_purple_purity ${run_dir})
