upgrade to protect v1.3

diff --git a/hmftools/protect/do_run_protect b/hmftools/protect/do_run_protect
--- a/hmftools/protect/do_run_protect
+++ b/hmftools/protect/do_run_protect
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
-source locate_files
-source metadata_functions
-source lims_functions
+source locate_files || exit 1
+source metadata_functions || exit 1
+source lims_functions || exit 1
+source message_functions || exit 1
 
 run_dir=$1 && shift
 output_dir=$1 && shift
 protect_jar=$1 && shift
-serve_actionability_dir=$1 && shift
 
-if [[ -z "${run_dir}" || -z "${output_dir}" || -z "${protect_jar}" || -z "${serve_actionability_dir}" ]]; then
-    echo "[ERROR] Missing input parameters. Exiting" && exit 1;
+if [[ -z "${run_dir}" || -z "${output_dir}" || -z "${protect_jar}" ]]; then
+    error "Missing input parameters. Exiting";
 fi
 
 tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
@@ -25,19 +25,17 @@ if [[ ! -z "${primary_tumor_doids}" ]]; then
     primary_tumor_argument="-primary_tumor_doids ${primary_tumor_doids}"
 fi
 
+serve_actionability_dir=/data/common/dbs/serve/prod_output
 doid_json=/data/common/dbs/disease_ontology/201015_doid.json
-germline_reporting_tsv=/data/common/dbs/germline_reporting/germline_reporting.tsv
 
 purple_purity_tsv=$(locate_purple_purity ${run_dir})
 purple_qc_file=$(locate_purple_qc ${run_dir})
-purple_driver_catalog_somatic_tsv=$(locate_purple_somatic_driver_catalog ${run_dir})
-purple_driver_catalog_germline_tsv=$(locate_purple_germline_driver_catalog ${run_dir})
+purple_somatic_driver_catalog_tsv=$(locate_purple_somatic_driver_catalog ${run_dir})
+purple_germline_driver_catalog_tsv=$(locate_purple_germline_driver_catalog ${run_dir})
 purple_somatic_variant_vcf=$(locate_purple_somatic_variants ${run_dir})
 purple_germline_variant_vcf=$(locate_purple_germline_variants ${run_dir})
-bachelor_tsv=$(locate_reportable_bachelor_variants ${run_dir})
 linx_fusion_tsv=$(locate_linx_fusions ${run_dir})
 linx_breakend_tsv=$(locate_linx_breakends ${run_dir})
-linx_viral_insertion_tsv=$(locate_linx_viral_insertions ${run_dir})
 linx_driver_catalog_tsv=$(locate_linx_driver_catalog ${run_dir})
 chord_prediction_txt=$(locate_chord_prediction ${run_dir})
 
@@ -47,18 +45,15 @@ java -Xms2G -Xmx8G -jar ${protect_jar} \
     -output_dir ${output_dir} \
     -serve_actionability_dir ${serve_actionability_dir} \
     -doid_json ${doid_json} \
-    -germline_reporting_tsv ${germline_reporting_tsv} \
     -purple_purity_tsv ${purple_purity_tsv} \
     -purple_qc_file ${purple_qc_file} \
-    -purple_driver_catalog_somatic_tsv ${purple_driver_catalog_somatic_tsv} \
-    -purple_driver_catalog_germline_tsv ${purple_driver_catalog_germline_tsv} \
+    -purple_somatic_driver_catalog_tsv ${purple_somatic_driver_catalog_tsv} \
+    -purple_germline_driver_catalog_tsv ${purple_germline_driver_catalog_tsv} \
     -purple_somatic_variant_vcf ${purple_somatic_variant_vcf} \
     -purple_germline_variant_vcf ${purple_germline_variant_vcf} \
-    -bachelor_tsv ${bachelor_tsv} \
     -linx_fusion_tsv ${linx_fusion_tsv} \
     -linx_breakend_tsv ${linx_breakend_tsv} \
-    -linx_viral_insertion_tsv ${linx_viral_insertion_tsv} \
-    -linx_drivers_tsv ${linx_driver_catalog_tsv} \
+    -linx_driver_catalog_tsv ${linx_driver_catalog_tsv} \
     -chord_prediction_txt ${chord_prediction_txt} \
     -log_debug \
     "$@"
