PURPLE automatically creates CIRCOS plot

diff --git a/hmftools/purityploidyestimator/do_create_circos_plot b/hmftools/purityploidyestimator/do_create_circos_plot
--- a/hmftools/purityploidyestimator/do_create_circos_plot
+++ b/hmftools/purityploidyestimator/do_create_circos_plot
@@ -1,19 +1,17 @@
 #!/bin/bash
-sample=$1
+run_dir=$1
+sample=$(ls ${run_dir} | grep -E '^(CPCT|DRUP)[0-9]{8}[^R]')
 
-credentials=/data/common/tools/patient-db_v1.0/credentials
-db_user=$(awk '/^user/ {print $2}' ${credentials})
-db_pass=$(awk '/^pass/ {print $2}' ${credentials})
-db_url=mysql://localhost:3306/hmfpatients?serverTimezone=CET
-purple_jar=/data/common/tools/purple_v1.0/purple-1.0.jar
-output_dir=/data/cpct/plot
 circos_bin=/data/common/tools/circos_v0.69.5/bin
-
-echo "Generating circos data"
-mkdir -p ${output_dir}/data
-mkdir -p ${output_dir}/plot
-mkdir -p ${output_dir}/etc
-java -Dorg.jooq.no-logo=true -cp ${purple_jar} com.hartwig.hmftools.purple.GenerateCircosData -output_dir ${output_dir} -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url} -sample ${sample}
+circos_conf=${run_dir}/purple/circos/${sample}.circos.conf
+if [[ ! -e ${circos_conf} ]]; then
+    echo "Unable to locate circos configuration " ${circos_conf}
+    exit 1
+fi
 
 echo "Generating plot"
-${circos_bin}/circos -conf ${output_dir}/etc/${sample}.circos.conf -nosvg -outputdir ${output_dir}/ -outputfile ${sample}.circos.png -debug_group summary,timer > ${output_dir}/log/run.out
+${circos_bin}/circos -nosvg \
+    -conf ${circos_conf} \
+    -outputdir ${run_dir}/purple/plot/ \
+    -outputfile ${sample}.circos.png \
+    -debug_group summary,timer > ${run_dir}/purple/circos/run.out
