Add check for dir existence when running purple

diff --git a/hmftools/purityploidyestimator/do_run_purple b/hmftools/purityploidyestimator/do_run_purple
--- a/hmftools/purityploidyestimator/do_run_purple
+++ b/hmftools/purityploidyestimator/do_run_purple
@@ -8,33 +8,36 @@ purple_jar=$1 && shift
 somatic_vcf=$1 && shift
 structural_vcf=$1 && shift
 sv_recovery_vcf=$1 && shift
-purple_output=$1 && shift
+purple_output_dir=$1 && shift
 credentials=$1 && shift
 
 reference_sample=$(load_ref_sample_from_metadata ${run_dir})
 tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
 
-if [[ ! -f ${somatic_vcf} ]]; then
+if [[ ! -f "${somatic_vcf}" ]]; then
     echo "[ERROR] Unable to locate somatic variants. Exiting."
     exit 1
 fi
 
-if [[ ! -f ${structural_vcf} ]]; then
+if [[ ! -f "${structural_vcf}" ]]; then
     echo "[ERROR] Unable to locate structural variants. Exiting."
     exit 1
 fi
 
-if [[ ! -f ${sv_recovery_vcf} ]]; then
+if [[ ! -f "${sv_recovery_vcf}" ]]; then
     echo "[ERROR] Unable to locate sv recovery variants. Exiting."
     exit 1
 fi
 
-mkdir -p ${purple_output}
-if [[ $? = 1 ]]; then
-    echo "[ERROR] Could not create directory ${purple_output}. Exiting."
-    exit 1
+if [[ -d "${purple_output_dir}" ]]; then
+    rm -r "${purple_output_dir}"/*
+else
+    mkdir -p "${purple_output_dir}"
+    if [[ $? = 1 ]]; then
+        echo "[ERROR] Could not create directory ${purple_output_dir}. Exiting."
+        exit 1
+    fi
 fi
-rm -r ${purple_output}/*
 
 base_path="/data/common"
 if [[ -z "$(hostname | grep datastore)" ]]; then
@@ -64,9 +67,10 @@ java -Dorg.jooq.no-logo=true -Xmx16G -Xms4G \
     -amber ${run_dir}/amber \
     -cobalt ${run_dir}/cobalt \
     -ref_genome ${ref_genome} \
-    -output_dir ${purple_output} \
+    -output_dir ${purple_output_dir} \
     -gc_profile ${gc_profile} \
     -sv_recovery_vcf ${sv_recovery_vcf} \
-    -driver_catalog -hotspots ${hotspot_vcf} \
+    -driver_catalog \
+    -hotspots ${hotspot_vcf} \
     ${db_args} \
     "$@"
