Apply pon on process_finished_sbp_run

diff --git a/hmftools/purityploidyestimator/do_run_purple_experiment b/hmftools/purityploidyestimator/do_run_purple_experiment
--- a/hmftools/purityploidyestimator/do_run_purple_experiment
+++ b/hmftools/purityploidyestimator/do_run_purple_experiment
@@ -31,7 +31,18 @@ else
 fi
 
 somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*melted_consensus_filtered_pon.vcf)
+if [ $? -ne 0 ]
+then
+	echo "Unable to locate somatic VCF. Exiting"
+	exit 1
+fi
+
 structural_vcf=$(ls ${run_dir}/structuralVariants/manta/*/results/variants/somaticSV.vcf.gz)
+if [ $? -ne 0 ]
+then
+	echo "Unable to locate structural VCF. Exiting"
+	exit 1
+fi
 
 exec java -Dorg.jooq.no-logo=true -Xmx8G -Xms4G \
     -jar ${purple_jar} \
