SVs can come from different sources

diff --git a/hmftools/purityploidyestimator/do_run_purple_gridss_prod b/hmftools/purityploidyestimator/do_run_purple_gridss_prod
--- a/hmftools/purityploidyestimator/do_run_purple_gridss_prod
+++ b/hmftools/purityploidyestimator/do_run_purple_gridss_prod
@@ -23,16 +23,11 @@ then
     fi
 fi
 
-structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf)
+structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.vcf.gz)
 if [ -z ${structural_vcf} ]
 then
-    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-    structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf.gz)
-    if [ -z ${structural_vcf} ]
-    then
-        echo "Unable to locate bpi structural variants. Exiting."
-        exit 1
-    fi
+    echo "Unable to locate gridss structural variants. Exiting."
+    exit 1
 fi
 
 ${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} $@
diff --git a/hmftools/purityploidyestimator/do_run_purple_low_coverage b/hmftools/purityploidyestimator/do_run_purple_low_coverage
--- a/hmftools/purityploidyestimator/do_run_purple_low_coverage
+++ b/hmftools/purityploidyestimator/do_run_purple_low_coverage
@@ -13,4 +13,16 @@ purple_output=${run_dir}/purple_pilot
 credentials=/data/common/dbs/mysql_credentials/low_coverages
 somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
 
-${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${purple_output} ${credentials} $@
+structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf)
+if [ -z ${structural_vcf} ]
+then
+    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
+    structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf.gz)
+    if [ -z ${structural_vcf} ]
+    then
+        echo "Unable to locate bpi structural variants. Exiting."
+        exit 1
+    fi
+fi
+
+${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} ${credentials} $@
