Add params to low coverage run

diff --git a/hmftools/purityploidyestimator/do_run_purple_low_coverage b/hmftools/purityploidyestimator/do_run_purple_low_coverage
--- a/hmftools/purityploidyestimator/do_run_purple_low_coverage
+++ b/hmftools/purityploidyestimator/do_run_purple_low_coverage
@@ -13,16 +13,23 @@ purple_output=${run_dir}/purple_pilot
 credentials=/data/common/dbs/mysql_credentials/low_coverages
 somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
 
-structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf)
+# TODO (KODU): Clean up after pipeline v4.4 does not exist anymore.
+structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
 if [ -z ${structural_vcf} ]
 then
-    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-    structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf.gz)
+    structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf)
     if [ -z ${structural_vcf} ]
     then
-        echo "Unable to locate bpi structural variants. Exiting."
-        exit 1
+        structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf.gz)
+        if [ -z ${structural_vcf} ]
+        then
+            echo "[ERROR] Unable to locate gridss or bpi structural variants. Exiting."
+            exit 1
+        fi
     fi
 fi
 
-${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} ${credentials} $@
+${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} ${credentials} \
+    -highly_diploid_percentage 0.88 \
+    -somatic_min_total 100 \
+    -somatic_min_purity_spread 0.1
