Use BPI VCF where available

diff --git a/hmftools/purityploidyestimator/do_run_purple b/hmftools/purityploidyestimator/do_run_purple
--- a/hmftools/purityploidyestimator/do_run_purple
+++ b/hmftools/purityploidyestimator/do_run_purple
@@ -34,16 +34,23 @@ fi
 somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*melted_consensus_filtered_pon.vcf)
 if [ $? -ne 0 ]
 then
-	echo "Unable to locate somatic VCF. Exiting"
+	echo "Unable to locate somatic VCF. Exiting."
 	exit 1
 fi
 
-structural_vcf=$(ls ${run_dir}/structuralVariants/manta/*/results/variants/somaticSV.vcf.gz)
+structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf)
 if [ $? -ne 0 ]
 then
-	echo "Unable to locate structural VCF. Exiting"
-	exit 1
+	echo "Unable to locate BPI VCF. Reverting to MANTA."
+	structural_vcf=$(ls ${run_dir}/structuralVariants/manta/*/results/variants/somaticSV.vcf.gz)
+    if [ $? -ne 0 ]
+    then
+    	echo "Unable to locate structural variants. Exiting."
+    	exit 1
+    fi
 fi
+
+
 
 java -Dorg.jooq.no-logo=true -Xmx8G -Xms4G \
     -jar ${purple_jar} \
