updated paths

diff --git a/hmftools/purityploidyestimator/do_run_purple_gridss_pilot b/hmftools/purityploidyestimator/do_run_purple_gridss_pilot
--- a/hmftools/purityploidyestimator/do_run_purple_gridss_pilot
+++ b/hmftools/purityploidyestimator/do_run_purple_gridss_pilot
@@ -9,7 +9,7 @@ if [ -z "`hostname | grep datastore`" ]; then
 fi
 
 purple_jar=${base_path}/tools/purple_pilot/purple.jar
-purple_output=${run_dir}/purple
+purple_output=${run_dir}/purple_gridss
 credentials=${base_path}/dbs/mysql_credentials/gridss_test
 somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed_v2.2.vcf.gz)
 if [ -z ${somatic_vcf} ]
@@ -23,29 +23,21 @@ then
     fi
 fi
 
-structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.somatic.vcf.bgz)
+# TODO (KODU): Clean up after pipeline v3 does not exist anymore.
+structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
 if [ -z ${structural_vcf} ]
 then
-    echo "Unable to locate gridss structural variants. Exiting."
-    exit 1
+    structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf)
+    if [ -z ${structural_vcf} ]
+    then
+        structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf.gz)
+        if [ -z ${structural_vcf} ]
+        then
+            echo "Unable to locate bpi structural variants. Exiting."
+            exit 1
+        fi
+    fi
 fi
 
-old_recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.somatic.vcf.full.vcf.bgz)
-if [ ! -z ${old_recovery_vcf} ]
-then
-    new_recovery_vcf=$(dirname ${old_recovery_vcf})/$(basename -s .vcf.full.vcf.bgz ${old_recovery_vcf}).full.vcf.bgz
-    mv ${old_recovery_vcf} ${new_recovery_vcf}
-    mv ${old_recovery_vcf}.tbi ${new_recovery_vcf}.tbi
-fi
-
-
-recovery_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.somatic.full.vcf.bgz)
-if [ -z ${recovery_vcf} ]
-then
-    echo "Unable to locate gridss recovery vcf. Exiting."
-    exit 1
-fi
-
-
-${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} ${credentials} -sv_recovery_vcf ${recovery_vcf} $@
+${prefix}/do_run_purple ${run_dir} ${purple_jar} ${somatic_vcf} ${structural_vcf} ${purple_output} ${credentials} $@
 do_run_sv_loader_gridss ${run_dir}
