DEV-2026: Refactor sql execution scripts

diff --git a/sql/execution/do_execute_sql_on_database b/sql/execution/do_execute_sql_on_database
--- a/sql/execution/do_execute_sql_on_database
+++ b/sql/execution/do_execute_sql_on_database
@@ -1,22 +1,25 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 file_with_sql_to_execute=$1 && shift
 database_name=$1 && shift
 credentials=$1 && shift
 
 if [[ ! -f "${file_with_sql_to_execute}" ]]; then
-    echo "[ERROR] Unable to locate SQL file to execute. Exiting." && exit 1
+    error "Unable to locate SQL file to execute. Exiting."
 fi
 
 if [[ -z "${database_name}" ]]; then
-    echo "[ERROR] No database name provided. Exiting." && exit 1
+    error "No database name provided. Exiting."
 fi
 
 if [[ ! -f "${credentials}" ]]; then
-    echo "[ERROR] Unable to locate MySQL credentials. Exiting." && exit 1
+    error "Unable to locate MySQL credentials. Exiting."
 fi
 
+db_host=$(locate_gcp_prod_database_host)
 db_user=$(awk '/^user/ {print $2}' ${credentials})
 db_pass=$(awk '/^pass/ {print $2}' ${credentials})
 
-mysql ${database_name} --user="${db_user}" --password="${db_pass}" < ${file_with_sql_to_execute}
+mysql ${database_name} --host="${db_host}" --user="${db_user}" --password="${db_pass}" < ${file_with_sql_to_execute}
diff --git a/sql/execution/execute_sql_on_old_prod b/sql/execution/execute_sql_on_old_prod
--- a/sql/execution/execute_sql_on_old_prod
+++ b/sql/execution/execute_sql_on_old_prod
@@ -1,14 +1,18 @@
 #!/usr/bin/env bash
 
-source locate_files
+source locate_files || exit 1
+source message_functions || exit 1
 
 file_with_sql_to_execute=$1
 
 if [[ ! -f "${file_with_sql_to_execute}" ]]; then
-    echo "[ERROR] Unable to locate SQL file to execute. Exiting." && exit 1
+    error "Unable to locate SQL file to execute. Exiting."
 fi
 
 database_name="hmfpatients"
 credentials=$(locate_old_prod_database_credentials)
 
-do_execute_sql_on_database ${file_with_sql_to_execute} ${database_name} ${credentials}
+db_user=$(awk '/^user/ {print $2}' ${credentials})
+db_pass=$(awk '/^pass/ {print $2}' ${credentials})
+
+mysql ${database_name} --user="${db_user}" --password="${db_pass}" < ${file_with_sql_to_execute}
