Improved error checking in patient reporting scripts

diff --git a/hmftools/patientreporter/corrected_patient_reporter b/hmftools/patientreporter/corrected_patient_reporter
--- a/hmftools/patientreporter/corrected_patient_reporter
+++ b/hmftools/patientreporter/corrected_patient_reporter
@@ -3,14 +3,12 @@
 run_dir=$1 && shift
 comments=$1 && shift
 
-if [[ -z ${run_dir} ]]; then
-    echo "[ERROR] No run dir provided. Exiting"
-    exit 1;
+if [[ -z "${run_dir}" ]]; then
+    echo "[ERROR] No run dir provided. Exiting" && exit 1;
 fi
 
-if [[ -z ${comments} ]]; then
-    echo "[ERROR] No comments provided. Exiting"
-    exit 1;
+if [[ -z "${comments}" ]]; then
+    echo "[ERROR] No comments provided. Exiting" && exit 1;
 fi
 
 patient_report_for_run ${run_dir} -comments "${comments}" -corrected_report "$@"
diff --git a/hmftools/patientreporter/pilot_below_detection_threshold_report b/hmftools/patientreporter/pilot_below_detection_threshold_report
--- a/hmftools/patientreporter/pilot_below_detection_threshold_report
+++ b/hmftools/patientreporter/pilot_below_detection_threshold_report
@@ -4,13 +4,13 @@ source locate_files
 
 run_dir=$1 && shift
 
-if [[ -z ${run_dir} ]]; then
-    echo "[ERROR] No run dir provided. Exiting"
-    exit 1;
+if [[ -z "${run_dir}" ]]; then
+    echo "[ERROR] No run dir provided. Exiting" && exit 1;
 fi
 
 comments="This is a pilot patient report and is not meant for production purpose."
 
 purple_purity_tsv=$(locate_purple_purity ${run_dir})
 
-pilot_do_run_qc_fail_patient_reporter ${run_dir} "below_detection_threshold" -comments "${comments}" -purple_purity_tsv ${purple_purity_tsv} "$@"
+pilot_do_run_qc_fail_patient_reporter \
+    ${run_dir} "below_detection_threshold" -comments "${comments}" -purple_purity_tsv ${purple_purity_tsv} "$@"
diff --git a/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter b/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
--- a/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
+++ b/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
@@ -6,33 +6,30 @@ source metadata_functions
 sample=$1 && shift
 qc_fail_reason=$1 && shift
 
-if [[ ${qc_fail_reason} == "post_analysis_fail" || ${qc_fail_reason} == "below_detection_threshold" ]];
-then
+if [[ ${qc_fail_reason} == "post_analysis_fail" || ${qc_fail_reason} == "below_detection_threshold" ]]; then
     tumor_sample=$(load_tumor_sample_from_metadata ${sample})
 else
     tumor_sample=${sample}
 fi
 
-if [[ -z ${tumor_sample} ]]; then
-    echo "[ERROR] No tumor sample provided. Exiting"
-    exit 1;
+if [[ -z "${tumor_sample}" ]]; then
+    echo "[ERROR] No tumor sample provided. Exiting" && exit 1;
 fi
 
-if [[ -z ${qc_fail_reason} ]]; then
-    echo "[ERROR] No QC fail reason provided. Exiting"
-    exit 1;
+if [[ -z "${qc_fail_reason}" ]]; then
+    echo "[ERROR] No QC fail reason provided. Exiting" && exit 1;
 fi
 
 ref_sample=$(imply_ref_sample_from_tumor_sample ${tumor_sample})
 ref_sample_barcode=$(find_ref_barcode_for_sample_name ${tumor_sample})
 tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})
 
-if [[ -z ${tumor_sample_barcode} ]]; then
+if [[ -z "${tumor_sample_barcode}" ]]; then
     echo "[INFO] Could not find tumor sample barcode from metadata. Attempt to resolve from LIMS."
     tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})
 fi
 
-if [[ -z ${ref_sample} || -z ${ref_sample_barcode} || -z ${tumor_sample_barcode} ]]; then
+if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" || -z "${tumor_sample_barcode}" ]]; then
     echo "[ERROR] Incomplete information for reporter. Exiting"
     echo "  ref_sample name: ${ref_sample}"
     echo "  ref sample barcode: ${ref_sample_barcode}"
diff --git a/hmftools/patientreporter/pilot_lab_failure_report b/hmftools/patientreporter/pilot_lab_failure_report
--- a/hmftools/patientreporter/pilot_lab_failure_report
+++ b/hmftools/patientreporter/pilot_lab_failure_report
@@ -2,9 +2,8 @@
 
 tumor_sample=$1 && shift
 
-if [[ -z ${tumor_sample} ]]; then
-    echo "[ERROR] No tumor sample provided. Exiting"
-    exit 1;
+if [[ -z "${tumor_sample}" ]]; then
+    echo "[ERROR] No tumor sample provided. Exiting" && exit 1;
 fi
 
 comments="This is a pilot patient report and is not meant for production purpose."
diff --git a/hmftools/patientreporter/pilot_post_analysis_fail_report b/hmftools/patientreporter/pilot_post_analysis_fail_report
--- a/hmftools/patientreporter/pilot_post_analysis_fail_report
+++ b/hmftools/patientreporter/pilot_post_analysis_fail_report
@@ -4,9 +4,8 @@ source locate_files
 
 run_dir=$1 && shift
 
-if [[ -z ${run_dir} ]]; then
-    echo "[ERROR] No run dir provided. Exiting"
-    exit 1;
+if [[ -z "${run_dir}" ]]; then
+    echo "[ERROR] No run dir provided. Exiting" && exit 1;
 fi
 
 comments="This is a pilot patient report and is not meant for production purpose."
