Update patient reporter pilot to use virus interpreter

diff --git a/hmftools/patientreporter/corrected_qc_fail_report b/hmftools/patientreporter/corrected_qc_fail_report
--- a/hmftools/patientreporter/corrected_qc_fail_report
+++ b/hmftools/patientreporter/corrected_qc_fail_report
@@ -1,19 +1,21 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 tumor_sample_or_run_dir=$1 && shift
 qc_fail_reason=$1 && shift
 comments=$1 && shift
 
 if [[ -z "${tumor_sample_or_run_dir}" ]]; then
-    echo "[ERROR] No tumor sample or run dir provided. Exiting" && exit 1;
+    error "No tumor sample or run dir provided. Exiting"
 fi
 
 if [[ -z "${qc_fail_reason}" ]]; then
-    echo "[ERROR] No QC fail reason provided. Exiting" && exit 1;
+    error "No QC fail reason provided. Exiting"
 fi
 
 if [[ -z "${comments}" ]]; then
-    echo "[ERROR] No comments provided. Exiting" && exit 1;
+    error "No comments provided. Exiting"
 fi
 
 if [[ ${qc_fail_reason} == "insufficient_dna" ]]; then
@@ -27,5 +29,5 @@ elif [[ ${qc_fail_reason} == "insufficient_tcp_deep_wgs" ]]; then
 elif [[ ${qc_fail_reason} == "technical_failure" ]]; then
     technical_failure_report ${tumor_sample_or_run_dir} -comments "${comments}" -corrected_report "$@"
 else
-    echo "[WARN] Did not recognize QC Fail reason: ${qc_fail_reason}. Skipping"
+    warn "Did not recognize QC Fail reason: ${qc_fail_reason}. Skipping"
 fi
diff --git a/hmftools/patientreporter/do_run_qc_fail_patient_reporter b/hmftools/patientreporter/do_run_qc_fail_patient_reporter
--- a/hmftools/patientreporter/do_run_qc_fail_patient_reporter
+++ b/hmftools/patientreporter/do_run_qc_fail_patient_reporter
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
 
+source lims_functions || exit 1
+source metadata_functions || exit 1
 source message_functions || exit 1
-
-source lims_functions
-source metadata_functions
 
 tumor_sample=$1 && shift
 qc_fail_reason=$1 && shift
@@ -11,7 +10,7 @@ ref_sample_mandatory=$1 && shift
 output_dir_report=/data/cpct/patient_reports
 
 if [[ -z "${tumor_sample}" || -z "${qc_fail_reason}" ]]; then
-    echo "[ERROR] No tumor sample and/or QC fail reason provided. Exiting" && exit 1;
+    error "No tumor sample and/or QC fail reason provided. Exiting"
 fi
 
 ref_sample=$(imply_ref_sample_from_tumor_sample ${tumor_sample})
@@ -19,27 +18,27 @@ ref_sample_barcode=$(find_ref_barcode_for_sample_name ${tumor_sample})
 tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})
 
 if [[ -z "${tumor_sample_barcode}" ]]; then
-    echo "[INFO] Could not find tumor sample barcode from metadata. Attempt to resolve from LIMS."
+    info "Could not find tumor sample barcode from metadata. Attempt to resolve from LIMS."
     tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})
 fi
 
 if [[ -z "${tumor_sample_barcode}" ]]; then
-    echo "[ERROR] Incomplete information for reporter. Exiting"
-    echo "  tumor_sample name: ${tumor_sample}"
-    echo "  tum sample barcode: ${tumor_sample_barcode}"
+    warn "Incomplete information for reporter. Exiting"
+    warn "  tumor_sample name: ${tumor_sample}"
+    warn "  tum sample barcode: ${tumor_sample_barcode}"
     exit 1;
 fi
 
 if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" ]]; then
     if [[ ${ref_sample_mandatory} == "1" ]]; then
-        echo "[ERROR] Incomplete information for reporter. Exiting"
-        echo "  ref_sample name: ${ref_sample}"
-        echo "  ref_sample barcode: ${ref_sample_barcode}"
-        echo "  tumor_sample name: ${tumor_sample}"
-        echo "  tumor_sample barcode: ${tumor_sample_barcode}"
-        exit 1;
+        warn "Incomplete information for reporter. Exiting"
+        warn "  ref_sample name: ${ref_sample}"
+        warn "  ref_sample barcode: ${ref_sample_barcode}"
+        warn "  tumor_sample name: ${tumor_sample}"
+        warn "  tumor_sample barcode: ${tumor_sample_barcode}"
+        exit 1
     else
-        echo "[WARN] Ref sample information is incomplete!"
+        warn "Ref sample information is incomplete!"
 
         do_run_base_patient_reporter \
             -output_dir_report ${output_dir_report} \
