select only relevant folders to copy (took too long)

diff --git a/hmftools/patientreporter/create_patient_report b/hmftools/patientreporter/create_patient_report
--- a/hmftools/patientreporter/create_patient_report
+++ b/hmftools/patientreporter/create_patient_report
@@ -31,14 +31,22 @@ set_url="gs://${bucket}/${set}"
 
 temp_folder_path=$( pwd )"/temp_cp_${set}"
 mkdir $temp_folder_path
-gsutil -m cp ${set_url}/pipeline.version $temp_folder_path/
-gsutil -m cp -r ${set_url}/purple/ $temp_folder_path/
-gsutil -m cp -r ${set_url}/linx/ $temp_folder_path/
-gsutil -m cp -r ${set_url}/chord/ $temp_folder_path/
-gsutil -m cp -r ${set_url}/cuppa/ $temp_folder_path/
-gsutil -m cp -r ${set_url}/virusbreakend/ $temp_folder_path/
-gsutil -m cp -r ${set_url}/peach/ $temp_folder_path/
-gsutil -m cp -r ${set_url}/protect/ $temp_folder_path/
+gsutil -m cp ${set_url}/pipeline.version $temp_folder_path/ &> $temp_folder_path/copy.log
+gsutil -m cp ${set_url}/metadata.json $temp_folder_path/ &>> $temp_folder_path/copy.log
+gsutil -m cp -r ${set_url}/purple/ $temp_folder_path/ &>> $temp_folder_path/copy.log
+gsutil -m cp -r ${set_url}/linx/ $temp_folder_path/ &>> $temp_folder_path/copy.log
+gsutil -m cp -r ${set_url}/chord/ $temp_folder_path/ &>> $temp_folder_path/copy.log
+gsutil -m cp -r ${set_url}/cuppa/ $temp_folder_path/ &>> $temp_folder_path/copy.log
+gsutil -m cp -r ${set_url}/virusbreakend/ $temp_folder_path/ &>> $temp_folder_path/copy.log
+gsutil -m cp -r ${set_url}/peach/ $temp_folder_path/  &>> $temp_folder_path/copy.log
+gsutil -m cp -r ${set_url}/protect/ $temp_folder_path/ &>> $temp_folder_path/copy.log
+
+if [[ $( cat $temp_folder_path/copy.log | grep "CommandException:" | wc -l ) > 0 ]]; then
+    warn "Making the copy gave errors (see below). Exiting."
+    cat $temp_folder_path/copy.log
+    rm -r $temp_folder_path/
+    exit 1
+fi
 
 ###
 
@@ -46,6 +54,7 @@ mkdir ${temp_folder_path}/new_report
 output_dir_report=${temp_folder_path}/new_report
 
 #Normal report
-do_patient_report_for_run ${temp_folder_path} -output_dir_report ${output_dir_report} &> ${temp_folder_path}/new_report/manual_patientreporter_${set}.log
+do_patient_report_for_run ${temp_folder_path} -output_dir_report ${output_dir_report}
+#do_patient_report_for_run ${temp_folder_path} -output_dir_report ${output_dir_report} &> ${temp_folder_path}/new_report/manual_patientreporter_${set}.log
 
 gsutil cp -r ${temp_folder_path}/new_report* gs://patient-reporter-manual-prod-1/
