fix pilot patient report arguments for version 7.2

diff --git a/hmftools/patientreporter/dna_yield_insufficient_report b/hmftools/patientreporter/dna_yield_insufficient_report
--- a/hmftools/patientreporter/dna_yield_insufficient_report
+++ b/hmftools/patientreporter/dna_yield_insufficient_report
@@ -2,7 +2,22 @@
 
 prefix=`dirname $(readlink $0 || echo $0)`
 
+tumor_sample=$1 && shift
+ref_sample=$1 && shift
+
+if [ -z ${tumor_sample} ]; then
+    echo "[ERROR] No tumor sample provided"
+    exit 1;
+fi
+
+if [ -z ${ref_sample} ]; then
+    echo "[ERROR] No ref sample provided"
+    exit 1;
+fi
+
 ${prefix}/do_run_base_patient_reporter \
     -qc_fail \
     -qc_fail_reason low_dna_yield \
-    -qc_fail_sample "$@"
+    -tumor_sample ${tumor_sample} \
+    -ref_sample ${ref_sample} \
+     "$@"
