Update to patient reporter v7.5

diff --git a/hmftools/patientreporter/patient_report_for_run b/hmftools/patientreporter/patient_report_for_run
--- a/hmftools/patientreporter/patient_report_for_run
+++ b/hmftools/patientreporter/patient_report_for_run
@@ -2,11 +2,23 @@
 
 source locate_files
 source metadata_functions
+source lims_functions
 
 run_dir=$1 && shift
 
 tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
-ref_sample=$(load_ref_sample_from_metadata ${run_dir})
+tumor_sample_barcode=$(load_tumor_sample_barcode_from_metadata ${run_dir})
+
+ref_sample=$(imply_ref_sample_from_tumor_sample ${tumor_sample})
+ref_sample_barcode=$(find_ref_barcode_for_sample_name ${tumor_sample})
+
+if [[ -z ${ref_sample} || -z ${ref_sample_barcode} || -z ${tumor_sample_barcode} ]]; then
+    echo "[ERROR] Incomplete information for reporter. Exiting"
+    echo "  ref_sample name: ${ref_sample}"
+    echo "  ref sample barcode: ${ref_sample_barcode}"
+    echo "  tur sample barcode: ${tumor_sample_barcode}"
+    exit 1;
+fi
 
 purple_purity_tsv=$(locate_purple_purity ${run_dir})
 purple_gene_cnv_tsv=$(locate_purple_gene_copynumbers ${run_dir})
@@ -28,7 +40,10 @@ if [ ! -z ${bachelor_csv} ]; then
 fi
 
 do_run_base_patient_reporter \
-    -tumor_sample ${tumor_sample} \
+    -ref_sample_id ${ref_sample} \
+    -ref_sample_barcode ${ref_sample_barcode} \
+    -tumor_sample_id ${tumor_sample} \
+    -tumor_sample_barcode ${tumor_sample_barcode} \
     -purple_purity_tsv ${purple_purity_tsv} \
     -purple_gene_cnv_tsv ${purple_gene_cnv_tsv} \
     -somatic_variant_vcf ${somatic_variant_vcf} \
@@ -37,7 +52,6 @@ do_run_base_patient_reporter \
     ${bachelor_cmd} \
     -chord_prediction_file ${chord_prediction_file} \
     -circos_file ${circos_file} \
-    -ref_sample ${ref_sample} \
     -knowledgebase_dir ${knowledgebase_dir} \
     -germline_genes_csv ${germline_genes_csv} \
     -sample_summary_tsv ${sample_summary_tsv} \
