DEV-1472: update pilot patient reports

diff --git a/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter b/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
--- a/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
+++ b/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
@@ -29,18 +29,28 @@ if [[ -z "${tumor_sample_barcode}" ]]; then
     echo "[INFO] Could not find tumor sample barcode from metadata. Attempt to resolve from LIMS."
     tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})
 fi
+if [[ ${qc_fail_reason} == "post_analysis_fail" || ${qc_fail_reason} == "below_detection_threshold" ]]; then
+    if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" || -z "${tumor_sample_barcode}" ]]; then
+        echo "[ERROR] Incomplete information for reporter. Exiting"
+        echo "  ref_sample name: ${ref_sample}"
+        echo "  ref_sample barcode: ${ref_sample_barcode}"
+        echo "  tumor_sample name: ${tumor_sample}"
+        echo "  tumor_sample barcode: ${tumor_sample_barcode}"
+        exit 1;
+    fi
+else
+    if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" ]]; then
+        echo "[WARN] Ref sample information is incomplete!"
+        ref_sample=""
+        ref_sample_barcode=""
+    fi
 
-if [[ -z "${ref_sample}" || -z "${ref_sample_barcode}" ]]; then
-    echo "[WARN] Ref sample information is incomplete!"
-    ref_sample="N/A"
-    ref_sample_barcode="N/A"
-fi
-
-if [[ -z "${tumor_sample_barcode}" ]]; then
-    echo "[ERROR] Incomplete information for reporter. Exiting"
-    echo "  tumor_sample name: ${tumor_sample}"
-    echo "  tum sample barcode: ${tumor_sample_barcode}"
-    exit 1;
+    if [[ -z "${tumor_sample_barcode}" ]]; then
+        echo "[ERROR] Incomplete information for reporter. Exiting"
+        echo "  tumor_sample name: ${tumor_sample}"
+        echo "  tum sample barcode: ${tumor_sample_barcode}"
+        exit 1;
+    fi
 fi
 
 pilot_do_run_base_patient_reporter \
