added completeness check

diff --git a/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter b/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
--- a/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
+++ b/hmftools/patientreporter/pilot_do_run_qc_fail_patient_reporter
@@ -20,6 +20,14 @@ ref_sample=$(imply_ref_sample_from_tumor_sample ${tumor_sample})
 ref_sample_barcode=$(find_ref_barcode_for_sample_name ${ref_sample})
 tumor_sample_barcode=$(find_barcode_for_sample_name ${tumor_sample})
 
+if [[ -z ${ref_sample} || -z ${ref_sample_barcode} || -z ${tumor_sample_barcode} ]]; then
+    echo "[ERROR] Incomplete information for reporter. Exiting"
+    echo "  ref_sample name: ${ref_sample}"
+    echo "  ref sample barcode: ${ref_sample_barcode}"
+    echo "  tur sample barcode: ${tumor_sample_barcode}"
+    exit 1;
+fi
+
 pilot_do_run_base_patient_reporter \
     -qc_fail \
     -qc_fail_reason ${qc_fail_reason} \
