cleanup

diff --git a/crunch/check_systems b/crunch/check_systems
--- a/crunch/check_systems
+++ b/crunch/check_systems
@@ -1,23 +1,27 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 MAX_DF_PERC=95
 NA="NA"
+script=$(basename "$0")
 
 function main {
-    if [[ ! "$(hostname)" =~ datastore ]]; then
-        echo "[ERROR] Only run this script at datastore!" && exit 1
-    fi
+    [[ "$(hostname)" =~ datastore ]] || die "[ERROR] Only run this script at datastore!"
+    info "Starting with ${script}"
+    check_datastore
+    check_crunches
+    info "Finished with ${script}"
+}
 
-    title "SYSTEMS CHECK"
+function check_datastore {
     header "datastore"
     diskUsage "/home"
     diskUsage "/data"
     toolVsn "gsutil" ""
-    crunches
-    echo ""
 }
 
-function crunches {
+function check_crunches {
     for crunch in crunch00{2,3}; do
         header ${crunch}
         diskUsage "/home"  "ssh ${crunch}"
@@ -28,14 +32,9 @@ function crunches {
     done
 }
 
-function title {
-    local msg=$1
-    echo "=== ${msg} ==="
-}
-
 function header {
     local msg=$1
-    echo -e "\n[${msg}]"
+    info "=== ${msg} ==="
 }
 
 function toolVsn {
@@ -45,7 +44,7 @@ function toolVsn {
     local location=${NA}
     version=$(${cmd_prefix} "${tool_name}" --version)
     location=$(${cmd_prefix} which "${tool_name}")
-    echo "TOOL: ${version} (${location})"
+    info "TOOL: ${version} (${location})"
 }
 
 function gitRepVsn {
@@ -56,9 +55,9 @@ function gitRepVsn {
     commit=$(${cmd_prefix} "cd ${repos_dir}; git log | head -1")
     dryrun=$(${cmd_prefix} "cd ${repos_dir}; git pull --dry-run 2>&1 | wc -l")
     if [[ "${dryrun}" -gt 0 ]]; then
-        echo "REPO: ${repos_dir} is OUTDATED (${commit})"
+        info "REPO: ${repos_dir} is OUTDATED (${commit})"
     else
-        echo "REPO: ${repos_dir} is at most recent commit"
+        info "REPO: ${repos_dir} is at most recent commit"
     fi
 }
 
@@ -71,20 +70,10 @@ function diskUsage {
     available=$(${cmd_prefix} df -h "${mount}" | tail -1 | tr -s ' ' | cut -d" " -f 4)
     percentage_string=$(${cmd_prefix} df -h "${mount}" | tail -1 | tr -s ' ' | cut -d" " -f 5)
     percentage=${percentage_string/\%/}
-    echo "${percentage_string} used with ${available} space left for mount ${mount}"
+    info "${percentage_string} used with ${available} space left for mount ${mount}"
     if [[ "${percentage}" -gt "${MAX_DF_PERC}" ]]; then
-        warn "Disk usage (${percentage}%) for mount ${mount} higher than ${MAX_DF_PERC}!"
+        warn "  Disk usage (${percentage}%) for mount ${mount} higher than ${MAX_DF_PERC}!"
     fi
-}
-
-function log {
-    local level=$1
-    local msg=$2
-    echo "[${level}] ${msg}"
-}
-
-function warn {
-    log "WARN" "$1"
 }
 
 main
