Consistently use ERROR rather than a mix of ERROR and EXIT in case a script errors out

diff --git a/crunch/check_systems b/crunch/check_systems
--- a/crunch/check_systems
+++ b/crunch/check_systems
@@ -4,7 +4,7 @@ MAX_DF_PERC=95
 
 function main {
     if [[ ! "$(hostname)" =~ datastore ]]; then
-        echo "[EXIT] Only run this script at datastore!" && exit 1
+        echo "[ERROR] Only run this script at datastore!" && exit 1
     fi
 
     title "SYSTEMS CHECK"
diff --git a/crunch/perform_shallow_qc b/crunch/perform_shallow_qc
--- a/crunch/perform_shallow_qc
+++ b/crunch/perform_shallow_qc
@@ -76,7 +76,7 @@ for runDir in "${runPaths[@]}"; do
       allFilesOk="no"
     fi
   done
-  if [[ ! $allFilesOk == "yes" ]]; then echo "[EXIT] Something wrong with required files" && exit 1; fi 
+  if [[ ! $allFilesOk == "yes" ]]; then echo "[ERROR] Something wrong with required files" && exit 1; fi
 
   ## gather WgsMetrics
     head=$( cat $wgsFileR | grep GENOME_T )
diff --git a/crunch/pull_scripts_repo b/crunch/pull_scripts_repo
--- a/crunch/pull_scripts_repo
+++ b/crunch/pull_scripts_repo
@@ -5,7 +5,7 @@ repo_root="/data/repos"
 work_path=$(pwd)
 
 if [[ "$USER" == "root" ]]; then
-    echo "[EXIT] This script should not be executed as user root" && exit 1
+    echo "[ERROR] This script should not be executed as user root" && exit 1
 fi
 
 if [[ "$(hostname)" == "datastore" ]]; then
@@ -15,7 +15,7 @@ fi
 repo_path="${repo_root}/${repo_name}"
 
 if [[ ! -d ${repo_path} ]]; then
-    echo "[EXIT] Dir does not exist (${repo_path})" && exit 1
+    echo "[ERROR] Dir does not exist (${repo_path})" && exit 1
 fi
 
 echo "[INFO] Change dir (to ${repo_path})"
diff --git a/crunch/rename_sample_name_of_fastq_files b/crunch/rename_sample_name_of_fastq_files
--- a/crunch/rename_sample_name_of_fastq_files
+++ b/crunch/rename_sample_name_of_fastq_files
@@ -64,11 +64,11 @@ while IFS=  read -r -d $'\0'; do
 done < <(find "${dirPath}" -maxdepth ${maxFindDepth} -name "$oldName*.fastq.gz" -print0)
 
 ## sanity checks
-if [[ ${#filesToRename[@]} -lt 1 ]]; then echo "[EXIT] No fastq files found (with find-depth ${maxFindDepth})" && exit 1; fi
-if [[ -z ${oldName} ]]; then echo "[EXIT] Param oldName (-o) not set" && exit 1; fi
-if [[ -z ${newName} ]]; then echo "[EXIT] Param newName (-n) not set" && exit 1; fi
-if [[ -z ${dirPath} ]]; then echo "[EXIT] Param dirPath (-d) not set" && exit 1; fi
-if [[ ! -d ${dirPath} ]]; then echo "[EXIT] dirPath (${dirPath}) does not exist?" && exit 1; fi
+if [[ ${#filesToRename[@]} -lt 1 ]]; then echo "[ERROR] No fastq files found (with find-depth ${maxFindDepth})" && exit 1; fi
+if [[ -z ${oldName} ]]; then echo "[ERROR] Param oldName (-o) not set" && exit 1; fi
+if [[ -z ${newName} ]]; then echo "[ERROR] Param newName (-n) not set" && exit 1; fi
+if [[ -z ${dirPath} ]]; then echo "[ERROR] Param dirPath (-d) not set" && exit 1; fi
+if [[ ! -d ${dirPath} ]]; then echo "[ERROR] dirPath (${dirPath}) does not exist?" && exit 1; fi
 
 
 ## print info
diff --git a/crunch/update_submission_overview b/crunch/update_submission_overview
--- a/crunch/update_submission_overview
+++ b/crunch/update_submission_overview
@@ -10,7 +10,7 @@ reportsTarget="/volume1/web/overviews/submissions/pdf_reports"
 reportsTargetDs="/data/data_archive/overviews/submissions/pdf_reports"
 
 ## Sanity checks
-if [[ ! -d ${srcDir} ]]; then echo "[EXIT] INPUT DIR does not exist (${srcDir})" && exit 1; fi
+if [[ ! -d ${srcDir} ]]; then echo "[ERROR] INPUT DIR does not exist (${srcDir})" && exit 1; fi
 
 ## Action
 echo "[INFO] START with ${taskId} ($YYMMDD)"
diff --git a/hmftools/gridss/do_run_gridss_preprocess b/hmftools/gridss/do_run_gridss_preprocess
--- a/hmftools/gridss/do_run_gridss_preprocess
+++ b/hmftools/gridss/do_run_gridss_preprocess
@@ -10,7 +10,7 @@ if [[ "$tum_normal_arg" == "normal" ]] ; then
 elif [[ "$tum_normal_arg" == "tumor" ]] ; then
 	  bam_sample=${tumor_sample}
 else
-	  echo "Please specify \"normal\" or \"tumor\" to indicate which BAM to preprocessing. Aborting" 1>&2
+	  echo "[ERROR] Please specify \"normal\" or \"tumor\" to indicate which BAM to preprocessing. Aborting" 1>&2
 	  exit 1
 fi
 bam=${run_dir}/${bam_sample}/mapping/${bam_sample}_dedup.realigned.bam
@@ -21,12 +21,12 @@ if [[ ! -f ${bam}.bai ]] ; then
 fi
 
 if [[ ! -f ${insert_size_metrics} ]] ; then
-	echo "Missing insert size metrics file $insert_size_metrics. Aborting" 1>&2
+	echo "[ERROR] Missing insert size metrics file $insert_size_metrics. Aborting" 1>&2
 	exit 1
 fi
 
 if [[ ! -f "$bam" ]] ; then
-	  echo "Missing input bam $bam. Aborting" 1>&2
+	  echo "[ERROR] Missing input bam $bam. Aborting" 1>&2
 	  exit 1
 fi
 
@@ -106,8 +106,8 @@ fi
 wait
 
 if [[ ! -f  ${sv_bam} ]] ; then
-	  echo "$(date) Preprocessing failed. Missing $sv_bam " 1>&2
+	  echo "[ERROR] $(date) Preprocessing failed. Missing $sv_bam " 1>&2
 	  exit 1
 else
-	  echo "$(date) Preprocessing complete"
+	  echo "[INFO] $(date) Preprocessing complete"
 fi
diff --git a/hmftools/mnvdetector/mnv_detector_and_merger b/hmftools/mnvdetector/mnv_detector_and_merger
--- a/hmftools/mnvdetector/mnv_detector_and_merger
+++ b/hmftools/mnvdetector/mnv_detector_and_merger
@@ -26,9 +26,9 @@ somatic_input_vcf=$(find ${run_dir} -wholename "*/somaticVariants/*_post_process
 tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
 
 ## Some sanity checks
-if [[ ! -d "${run_dir}" ]]; then echo "[EXIT] Run (${run_dir}) not found" && exit 1; fi
-if [[ ! -f "${somatic_input_vcf}" ]]; then echo "[EXIT] Vcf not found" && exit 1; fi
-if [[ -z "${tumor_sample}" ]]; then echo "[EXIT] Sample not found" && exit 1; fi
+if [[ ! -d "${run_dir}" ]]; then echo "[ERROR] Run (${run_dir}) not found" && exit 1; fi
+if [[ ! -f "${somatic_input_vcf}" ]]; then echo "[ERROR] Vcf not found" && exit 1; fi
+if [[ -z "${tumor_sample}" ]]; then echo "[ERROR] Sample not found" && exit 1; fi
 
 sliced_tumor_bam="${tumor_sample}_dedup.realigned.sliced.bam"
 somatic_vcf_file_name=$(basename ${somatic_input_vcf})
diff --git a/lims/check_submission_status b/lims/check_submission_status
--- a/lims/check_submission_status
+++ b/lims/check_submission_status
@@ -4,7 +4,7 @@ submission=$1
 submissionDir="/data/submissions/${submission}"
 sopRegex='QC[0-9]+V[0-9]+-SEQ[0-9]+V[0-9]+'
 
-if [[ -z "${submission}" ]]; then echo "[EXIT] Provide submission (eg HMFreg0001)" && exit 1; fi
+if [[ -z "${submission}" ]]; then echo "[ERROR] Provide submission (eg HMFreg0001)" && exit 1; fi
 
 lmsSubJsn=$(query_lims.pl -type submissions -filter "submission=${submission}" -json)
 lmsSmpJsn=$(query_lims.pl -type samples -filter "submission=${submission}" -json)
diff --git a/lims/gather_submission b/lims/gather_submission
--- a/lims/gather_submission
+++ b/lims/gather_submission
@@ -28,7 +28,7 @@ flwJson=$(echo ${flwFile} | sed 's/txt$/json/')
 dateString=$(date)
 
 ## create dirs
-if [[ -e ${outPath} ]] ; then echo "[EXIT] Dir exists already (${outPath})"; exit 1; fi
+if [[ -e ${outPath} ]] ; then echo "[ERROR] Dir exists already (${outPath})"; exit 1; fi
 mkdir -p ${outPath} || exit 1
 
 ## gather submission info from LAB LIMS
@@ -40,7 +40,7 @@ rMail=$(cat ${subJson} | jq -r '.report_contact_email')
 dName=$(cat ${subJson} | jq -r '.data_contact_name')
 dMail=$(cat ${subJson} | jq -r '.data_contact_email')
 pType=$(cat ${subJson} | jq -r '.analysis_type')
-if [[ -z ${pName+x} ]]; then echo "[EXIT] Unable to find project for submission"; exit 1; fi
+if [[ -z ${pName+x} ]]; then echo "[ERROR] Unable to find project for submission"; exit 1; fi
 
 ## get all samples involved from LAB LIMS
 echo "[INFO] Querying HMF LIMS to get sample list"
diff --git a/lims/gather_submission_aria_config b/lims/gather_submission_aria_config
--- a/lims/gather_submission_aria_config
+++ b/lims/gather_submission_aria_config
@@ -13,10 +13,10 @@ create_log="${output_dir}/create_aria_configs.log"
 out_config="${output_dir}/${submission}.aria.txt"
 
 ## sanity checks
-if [[ ! -d ${submission_dir} ]] ; then echo "[EXIT] Submission dir does not exist (${submission_dir})"; exit 1; fi
-if [[ ! -w ${submission_dir} ]] ; then echo "[EXIT] Submission dir is not writable (${submission_dir})"; exit 1; fi
-if [[ ! -f ${runs_json} ]] ; then echo "[EXIT] Runs json does not exist (${runs_json})"; exit 1; fi
-if [[   -d ${output_dir} ]] ; then echo "[EXIT] Output dir already exists (${output_dir})"; exit 1; fi
+if [[ ! -d ${submission_dir} ]] ; then echo "[ERROR] Submission dir does not exist (${submission_dir})"; exit 1; fi
+if [[ ! -w ${submission_dir} ]] ; then echo "[ERROR] Submission dir is not writable (${submission_dir})"; exit 1; fi
+if [[ ! -f ${runs_json} ]] ; then echo "[ERROR] Runs json does not exist (${runs_json})"; exit 1; fi
+if [[   -d ${output_dir} ]] ; then echo "[ERROR] Output dir already exists (${output_dir})"; exit 1; fi
 
 ## setup actual job
 mkdir "${output_dir}"
diff --git a/lims/sync_lab_lims_from_nas b/lims/sync_lab_lims_from_nas
--- a/lims/sync_lab_lims_from_nas
+++ b/lims/sync_lab_lims_from_nas
@@ -22,13 +22,13 @@ SAMP_NAS_PATH_2019="${NAS_DIR}/${SAMP_FILE_2019}"
 PROC_NAS_PATH_2019="${NAS_DIR}/${PROC_FILE_2019}"
 
 ## File and dir sanity checks
-if ssh nas "[[ ! -d ${NAS_DIR} ]]"; then echo "[EXIT] Error: dir does not exist (nas:${NAS_DIR})" && exit 1; fi
+if ssh nas "[[ ! -d ${NAS_DIR} ]]"; then echo "[ERROR] Dir does not exist (nas:${NAS_DIR})" && exit 1; fi
 for nasFilePath in "$CPCT_NAS_PATH" "$SAMP_NAS_PATH" "$PROC_NAS_PATH" "$SAMP_NAS_PATH_2019" "$PROC_NAS_PATH_2019"; do
-    if ssh nas "[[ ! -f '${nasFilePath}' ]]"; then echo "[EXIT] Error: file does not exist (nas:${nasFilePath})" && exit 1; fi
+    if ssh nas "[[ ! -f '${nasFilePath}' ]]"; then echo "[ERROR] File does not exist (nas:${nasFilePath})" && exit 1; fi
 done
 for outdir in $OUT_DIR $LAB_DIR $SYM_DIR; do
-    if [[ ! -d ${outdir} ]]; then echo "[EXIT] Error: dir does not exist (${outdir})" && exit 1; fi
-    if [[ ! -w ${outdir} ]]; then echo "[EXIT] Error: no write permission (${outdir})" && exit 1; fi
+    if [[ ! -d ${outdir} ]]; then echo "[ERROR] Dir does not exist (${outdir})" && exit 1; fi
+    if [[ ! -w ${outdir} ]]; then echo "[ERROR] No write permission (${outdir})" && exit 1; fi
 done
 mkdir -p ${DAY_DIR}
 
@@ -73,11 +73,11 @@ rsync -s "nas:${SAMP_NAS_PATH_2019}" ${DAY_DIR}
 rsync -s "nas:${PROC_NAS_PATH_2019}" ${DAY_DIR}
 
 ## Make sure all required files are present
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] Error with RSYNC from NAS, please check " && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] Error with RSYNC from NAS, please check " && exit 1; fi
 
 for inputFile in "${cpctSource}" "${sampSource}" "${procSource}"; do
     if [[ ! -f "${inputFile}" ]]; then
-        echo "[EXIT] Error: input file from NAS not present (${inputFile})" && exit 1;
+        echo "[ERROR] Input file from NAS not present (${inputFile})" && exit 1;
     fi
 done
 
@@ -94,31 +94,31 @@ ln -sfn "${procSource2019}" "${procTarget2019}"
 echo "[INFO] Converting input files to CSV/TSV"
 echo "[INFO]   Converting $( basename ${cpctTarget} )"
 ${ACC2CSV} --with-header --input "${cpctTarget}" --output ${DAY_DIR} --table tblSamples --quote-all false
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] CPCT export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] CPCT export to csv FAILED" && exit 1; fi
 mv ${DAY_DIR}/tblSamples.csv ${cpctTxt}
 echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "submissions")"
 xlsx2csv -d "\t" "${sampTarget}" -s 1 | tail -n +5 > ${submTxt}
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] SUBM export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] SUBM export to csv FAILED" && exit 1; fi
 echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "samples")"
 xlsx2csv -d "\t" "${sampTarget}" -s 2 | tail -n +2 > ${sampTxt}
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] SAMP export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] SAMP export to csv FAILED" && exit 1; fi
 echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "Contact")"
 xlsx2csv -d "\t" "${sampTarget}" -s 3 | tail -n +1 > ${contTxt}
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] CONT export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] CONT export to csv FAILED" && exit 1; fi
 echo "[INFO]   Converting $( basename ${procTarget} )"
 xlsx2csv -d "\t" "${procTarget}" -s 1 | tail -n +5 > ${procTxt}
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] PROC export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] PROC export to csv FAILED" && exit 1; fi
 
 ## Convert to text format for 2019 files
 echo "[INFO]   Converting $( basename ${sampTarget2019} ) (sheet "submissions")"
 xlsx2csv -d "\t" "${sampTarget2019}" -s 1 | tail -n +5 > ${submTxt2019}
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] SUBM export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] SUBM export to csv FAILED" && exit 1; fi
 echo "[INFO]   Converting $( basename ${sampTarget2019} ) (sheet "samples")"
 xlsx2csv -d "\t" "${sampTarget2019}" -s 2 | tail -n +2 > ${sampTxt2019}
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] SAMP export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] SAMP export to csv FAILED" && exit 1; fi
 echo "[INFO]   Converting $( basename ${procTarget2019} )"
 xlsx2csv -d "\t" "${procTarget2019}" -s 1 | tail -n +5 > ${procTxt2019}
-if [[ ! $? -eq 0 ]]; then echo "[EXIT] PROC export to csv FAILED" && exit 1; fi
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] PROC export to csv FAILED" && exit 1; fi
 
 ## Create latest symlinks
 echo "[INFO] Symlinking to latest files"
diff --git a/sbpext/create_set_jsons_for_samplesheets_on_date b/sbpext/create_set_jsons_for_samplesheets_on_date
--- a/sbpext/create_set_jsons_for_samplesheets_on_date
+++ b/sbpext/create_set_jsons_for_samplesheets_on_date
@@ -8,10 +8,10 @@ createLog="${HOME}/logs/${currDate}_create_jsons_for_${ssheetDate}"
 registerLog="${HOME}/logs/${currDate}_register_sets_from_${ssheetDate}_flowcells"
 
 ## Sanity checks
-if [[ ! $( whoami ) =~ ^sbpext$ ]]; then echo "[EXIT] Script can currently only be ran as user sbpext" && exit 1; fi
-if [[ ! ${ssheetDate} =~ ^[0-9]{6}$ ]]; then echo "[EXIT] Wrong input date: run with \"$(basename $0) YYMMDD\"" && exit 1; fi
-if [[ -f ${createLog} ]]; then echo "[EXIT] Log already exists: ${createLog}" && exit 1; fi
-if [[ -f ${registerLog} ]]; then echo "[EXIT] Log already exists: ${registerLog}" && exit 1; fi
+if [[ ! $( whoami ) =~ ^sbpext$ ]]; then echo "[ERROR] Script can currently only be ran as user sbpext" && exit 1; fi
+if [[ ! ${ssheetDate} =~ ^[0-9]{6}$ ]]; then echo "[ERROR] Wrong input date: run with \"$(basename $0) YYMMDD\"" && exit 1; fi
+if [[ -f ${createLog} ]]; then echo "[ERROR] Log already exists: ${createLog}" && exit 1; fi
+if [[ -f ${registerLog} ]]; then echo "[ERROR] Log already exists: ${registerLog}" && exit 1; fi
 echo "[INFO] JsonCreation started with input date: ${ssheetDate}"
 
 ## Actual work
diff --git a/sbpext/manual_fastq_register b/sbpext/manual_fastq_register
--- a/sbpext/manual_fastq_register
+++ b/sbpext/manual_fastq_register
@@ -24,13 +24,13 @@ SAMPLE_NAME=""
 SAMPLE_ID=$(curl -s --cert-type pem --cert "${apiCrt}" --key "${apiKey}" "${apiUrl}/hmf/v1/samples?barcode=${BARCODE}" | jq '.[].id')
 
 if [[ -z "$SAMPLE_ID" ]]; then
-    echo "[EXIT] Barcode not found at SBP ($BARCODE)" && exit 1
+    echo "[ERROR] Barcode not found at SBP ($BARCODE)" && exit 1
 fi
 
 ## make sure the FASTQ files contain only ONE sample
 SAMPLE_COUNT=$(find ${FASTQ_DIR} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq | wc -l)
 if [[ $SAMPLE_COUNT -ne 1 ]]; then 
-    echo "[EXIT] FASTQ files in dir should be from one sample (found $SAMPLE_COUNT samples in dir \"$FASTQ_DIR\")" && exit 1;
+    echo "[ERROR] FASTQ files in dir should be from one sample (found $SAMPLE_COUNT samples in dir \"$FASTQ_DIR\")" && exit 1;
 else
     SAMPLE_NAME=$(find ${FASTQ_DIR} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq)
 fi
diff --git a/sbpext/register_set_by_json_to_acc b/sbpext/register_set_by_json_to_acc
--- a/sbpext/register_set_by_json_to_acc
+++ b/sbpext/register_set_by_json_to_acc
@@ -7,9 +7,9 @@ api_crt_file="${api_cred_dir}/api.crt"
 api_key_file="${api_cred_dir}/api.key"
 api_url='https://api.acc.hartwigmedicalfoundation.nl/hmf/v1/action/register'
 
-if [[ -z ${json+x} ]]; then echo "[EXIT] No json given" && exit 1; fi
-if [[ ! -f ${api_crt_file} ]]; then echo "[EXIT] File does not exist (${api_crt_file})" && exit 1; fi
-if [[ ! -f ${api_key_file} ]]; then echo "[EXIT] File does not exist (${api_key_file})" && exit 1; fi
-if [[ ! -f ${json} ]]; then echo "[EXIT] File does not exist (${json})" && exit 1; fi
+if [[ -z ${json+x} ]]; then echo "[ERROR] No json given" && exit 1; fi
+if [[ ! -f ${api_crt_file} ]]; then echo "[ERROR] File does not exist (${api_crt_file})" && exit 1; fi
+if [[ ! -f ${api_key_file} ]]; then echo "[ERROR] File does not exist (${api_key_file})" && exit 1; fi
+if [[ ! -f ${json} ]]; then echo "[ERROR] File does not exist (${json})" && exit 1; fi
 
 /usr/bin/curl -s -v --cert-type pem --cert ${api_crt_file} --key ${api_key_file} ${api_url} -XPOST -H "Content-Type: application/json" -d @${json}
diff --git a/snpcheck/create_sample_vcfs_from_csv b/snpcheck/create_sample_vcfs_from_csv
--- a/snpcheck/create_sample_vcfs_from_csv
+++ b/snpcheck/create_sample_vcfs_from_csv
@@ -19,10 +19,10 @@ if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
 fi
 
 csvFile=$1
-if [[   -z ${csvFile} ]]; then echo "[EXIT] No csv results file provided.."; exit 1; fi
-if [[ ! -f ${csvFile} ]]; then echo "[EXIT] Input csv file does not exist?"; exit 1; fi
-if [[ ! -f ${SCRIPT}  ]]; then echo "[EXIT] Script file does not exist?"; exit 1; fi
-if [[ ! -w ${GCPDIR}  ]]; then echo "[EXIT] Output sync dir not writable ($GCPDIR)"; exit 1; fi
+if [[   -z ${csvFile} ]]; then echo "[ERROR] No csv results file provided.."; exit 1; fi
+if [[ ! -f ${csvFile} ]]; then echo "[ERROR] Input csv file does not exist?"; exit 1; fi
+if [[ ! -f ${SCRIPT}  ]]; then echo "[ERROR] Script file does not exist?"; exit 1; fi
+if [[ ! -w ${GCPDIR}  ]]; then echo "[ERROR] Output sync dir not writable ($GCPDIR)"; exit 1; fi
 
 ## setup design to use
 oneSample=$( cat ${csvFile} | grep ^FR | cut -d"," -f1 | sort | uniq | head -1 )
@@ -33,8 +33,8 @@ if [[ ${designSize} -eq 60 ]]; then
 fi
 DESIGN="${CODEDIR}/${SNPCOUNT}SNPtaq_design.vcf"
 OUTDIR="${OUTBASE}/output/${SNPCOUNT}SNPtaq"
-if [[ ! -f ${DESIGN}  ]]; then echo "[EXIT] Design file does not exist (${DESIGN})?"; exit 1; fi
-if [[ ! -d ${OUTDIR}  ]]; then echo "[EXIT] Output dir does not exist (${OUTDIR})?"; exit 1; fi
+if [[ ! -f ${DESIGN}  ]]; then echo "[ERROR] Design file does not exist (${DESIGN})?"; exit 1; fi
+if [[ ! -d ${OUTDIR}  ]]; then echo "[ERROR] Output dir does not exist (${OUTDIR})?"; exit 1; fi
 
 ## continue with parsing and converting
 experimentName=$( echo $( basename ${csvFile} ) | sed 's/.txt$//' | sed 's/.csv$//' | sed 's/_Results$//' )
@@ -42,7 +42,7 @@ plateName=$( cat ${csvFile} | grep -A1 "^Sample ID" | tail -1 | cut -d, -f2 )
 combiName="${experimentName}_${plateName}"
 vcfOutDir="${OUTDIR}/${combiName}"
 
-if [[ -d ${vcfOutDir} ]]; then echo "[EXIT] Output dir already exists (${vcfOutDir})"; exit 1; fi
+if [[ -d ${vcfOutDir} ]]; then echo "[ERROR] Output dir already exists (${vcfOutDir})"; exit 1; fi
 
 echo "[INFO] Starting conversion from CSVs to VCFs"
 echo "[INFO] Output dir will be: ${vcfOutDir}"
diff --git a/snpcheck/perform_snpcheck_plate_qc b/snpcheck/perform_snpcheck_plate_qc
--- a/snpcheck/perform_snpcheck_plate_qc
+++ b/snpcheck/perform_snpcheck_plate_qc
@@ -15,7 +15,7 @@ if [[ -z ${vcfDirPath} || $1 == "-h" || $1 == "--help" ]]; then
   exit 1
 fi
 
-if [[ ! -d ${vcfDirPath} ]]; then echo "[EXIT] Dir does not exist (${vcfDirPath})" && exit 1; fi
+if [[ ! -d ${vcfDirPath} ]]; then echo "[ERROR] Dir does not exist (${vcfDirPath})" && exit 1; fi
 
 vcfDirName=$(basename ${vcfDirPath})
  qcLogName="${vcfDirName}.qc"
@@ -23,7 +23,7 @@ vcfDirName=$(basename ${vcfDirPath})
 
 echo "[INFO]  Performing QC (${qcLogName})"
 perform_snpcheck.pl -qc -vcfDir "${vcfDirPath}" > "${qcLogPath}"
-if [[ $? != 0 ]]; then echo "[EXIT] perform_snpcheck finished with non-zero exit code ($?)" && exit 1; fi
+if [[ $? != 0 ]]; then echo "[ERROR] perform_snpcheck finished with non-zero exit code ($?)" && exit 1; fi
 
 echo "[INFO]  Syncing log to NAS (${qcLogPath})"
 rsync -ah "${qcLogPath}" "nas:${nasPath}/${qcLogName}"
diff --git a/snpcheck/process_snpgenotyping_file_from_nas b/snpcheck/process_snpgenotyping_file_from_nas
--- a/snpcheck/process_snpgenotyping_file_from_nas
+++ b/snpcheck/process_snpgenotyping_file_from_nas
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-SCRIPT=$(basename $0)
 SOURCE='/volume1/machines/Experimenten/SNP\ check'
 TARGET='/data/common/snpcheck/input'
 SUFFIX='Results.csv'
@@ -9,8 +8,8 @@ plateID=$1
 
 if [[ -z ${plateID} || $1 == "-h" || $1 == "--help" ]]; then
   echo "---"
-  echo " Usage: $SCRIPT \${plateID}"
-  echo "    Eg: $SCRIPT S19-0001"
+  echo " Usage: $(basename $0) \${plateID}"
+  echo "    Eg: $(basename $0) S19-0001"
   echo "---"
   exit 1
 fi
@@ -22,9 +21,9 @@ while IFS=  read -r -d $'\0'; do
     resultFiles+=("$REPLY")
 done < <(ssh nas find ${SOURCE} -name "${plateID}*${SUFFIX}" -print0)
 if [[ ${#resultFiles[@]} -eq 0 ]]; then 
-  echo "[EXIT] No ${plateID} ${SUFFIX} files found!" && exit 1
+    echo "[ERROR] No ${plateID} ${SUFFIX} files found!" && exit 1
 elif [[ ${#resultFiles[@]} -gt 1 ]]; then
-  echo "[EXIT] More than 1 ${plateID} ${SUFFIX} files found!" && exit 1
+    echo "[ERROR] More than 1 ${plateID} ${SUFFIX} files found!" && exit 1
 fi
 
 ## sync and process
@@ -35,9 +34,9 @@ targetFilePath="${TARGET}/${resultFileName}"
 echo "[INFO] Found SNPcheck file at NAS ($resultFileName)"
 echo "[INFO]   syncing to datastore"
 rsync --protect-args -ah "nas:${resultFilePath}" "${targetFilePath}"
-if [[ $? != 0 ]]; then echo "[EXIT] Rsync finished with non-zero exit code ($?)" && exit 1; fi
+if [[ $? != 0 ]]; then echo "[ERROR] Rsync finished with non-zero exit code ($?)" && exit 1; fi
 
 echo "[INFO]   converting file VCFs"
 create_sample_vcfs_from_csv "${targetFilePath}"
-if [[ $? != 0 ]]; then echo "[EXIT] Conversion to VCF finished with non-zero exit code ($?)" && exit 1; fi
+if [[ $? != 0 ]]; then echo "[ERROR] Conversion to VCF finished with non-zero exit code ($?)" && exit 1; fi
 
diff --git a/utilityscripts/create_aria2_config_by_set_name b/utilityscripts/create_aria2_config_by_set_name
--- a/utilityscripts/create_aria2_config_by_set_name
+++ b/utilityscripts/create_aria2_config_by_set_name
@@ -64,7 +64,7 @@ function main() {
     ## sanity check on data location in API
     ## TODO once all at gcp then remove the ini check
     if [[ $cluster != "gcp" && $ini != "FastQ.ini" ]]; then
-       echo "[EXIT] Error: unexpected cluster ($cluster)." && exit 1
+       echo "[ERROR] Error: unexpected cluster ($cluster)." && exit 1
     fi
 
     ## cleanup existing files
@@ -92,7 +92,7 @@ function main() {
     elif [[ $ini == "SingleSample.ini" ]]; then
         create_run_specific_files "$files_json" "$out_md5" "$out_aria" "$out_url" "$name" "$bucket" "$ref" "$tum" "SingleSample"
     else
-        echo "[EXIT] Unknown ini ($ini)" && exit 1
+        echo "[ERROR] Unknown ini ($ini)" && exit 1
     fi
 
     ## sanity checks on final files
@@ -157,7 +157,7 @@ create_run_specific_files () {
     elif [[ $run_type == "Fastq" ]]; then
         file_selection="${all_files[@]}"
     else
-        echo "[EXIT] Unknown run type ($run_type)" && exit 1
+        echo "[ERROR] Unknown run type ($run_type)" && exit 1
     fi
 
     ## output aria2 config file
@@ -178,8 +178,8 @@ create_run_specific_files () {
         gsutil -u "${gcp_project}" -q stat "${internal_url}"
         if [[ $? -eq 1 ]]; then
             msg=$(gsutil -u "${gcp_project}" ls "${internal_url}" 2>&1)
-            echo "[EXIT] Cannot access file (${internal_url})"
-            echo "[EXIT] ErrCode=${?} ErrMsg=\"${msg}\""
+            echo "[ERROR] Cannot access file (${internal_url})"
+            echo "[ERROR] ErrCode=${?} ErrMsg=\"${msg}\""
             exit 1
         fi
 
diff --git a/utilityscripts/tar_nextseq_flowcells_for_bcl_output b/utilityscripts/tar_nextseq_flowcells_for_bcl_output
--- a/utilityscripts/tar_nextseq_flowcells_for_bcl_output
+++ b/utilityscripts/tar_nextseq_flowcells_for_bcl_output
@@ -20,12 +20,12 @@ tar_log="${HOME}/logs/${YYMMDD}_tar_create_${output_tar_name}.log"
 
 ## some sanity checks
 if [[ -e "${output_tar_path}" ]]; then
-    echo "[EXIT] Provided output tar file already exists (${output_tar_path})" && exit 1
+    echo "[ERROR] Provided output tar file already exists (${output_tar_path})" && exit 1
 fi
 
 for inputPath in "${flowcell_paths[@]}"; do
     if [[ ! -d "${inputPath}" ]]; then
-        echo "[EXIT] Provided input directory does not exist (${inputPath})" && exit 1
+        echo "[ERROR] Provided input directory does not exist (${inputPath})" && exit 1
     fi
 done
 
diff --git a/utilityscripts/upload_files_to_nextcloud_directory b/utilityscripts/upload_files_to_nextcloud_directory
--- a/utilityscripts/upload_files_to_nextcloud_directory
+++ b/utilityscripts/upload_files_to_nextcloud_directory
@@ -27,7 +27,7 @@ pass=$(awk '/^pass/ {print $2}' ${cred})
 echo "[INFO] Checking input files"
 for file in "${files_to_upload[@]}"; do
     if [[ ! -f "${file}" ]]; then
-        echo >&2 "[EXIT] Error: File not found (${file})"
+        echo >&2 "[ERROR] Error: File not found (${file})"
         exit 1
     fi
 done
diff --git a/validation/compare_v5_runs b/validation/compare_v5_runs
--- a/validation/compare_v5_runs
+++ b/validation/compare_v5_runs
@@ -20,10 +20,10 @@ if [[ "$#" -ne 2 ]]; then
     echo "-----"
     exit 1
 fi
-if [[ ! -d "$base_run_path" ]]; then echo "[EXIT] Directory not found ($base_run_path)" && exit 1; fi
-if [[ ! -d "$test_run_path" ]]; then echo "[EXIT] Directory not found ($test_run_path)" && exit 1; fi
-if [[ ! -f "$base_pip_vsn_file" ]]; then echo "[EXIT] File not found ($base_pip_vsn_file)" && exit 1; fi
-if [[ ! -f "$test_pip_vsn_file" ]]; then echo "[EXIT] File not found ($test_pip_vsn_file)" && exit 1; fi
+if [[ ! -d "$base_run_path" ]]; then echo "[ERROR] Directory not found ($base_run_path)" && exit 1; fi
+if [[ ! -d "$test_run_path" ]]; then echo "[ERROR] Directory not found ($test_run_path)" && exit 1; fi
+if [[ ! -f "$base_pip_vsn_file" ]]; then echo "[ERROR] File not found ($base_pip_vsn_file)" && exit 1; fi
+if [[ ! -f "$test_pip_vsn_file" ]]; then echo "[ERROR] File not found ($test_pip_vsn_file)" && exit 1; fi
 
 base_pip_vsn=$(cat "$base_pip_vsn_file")
 test_pip_vsn=$(cat "$test_pip_vsn_file")
diff --git a/validation/validate_giab_mixin_sage b/validation/validate_giab_mixin_sage
--- a/validation/validate_giab_mixin_sage
+++ b/validation/validate_giab_mixin_sage
@@ -19,9 +19,9 @@ truth_vcf_path="${truth_dir_path}/${truth_vcf_name}"
 truth_bed_path="${truth_dir_path}/${truth_bed_name}"
 
 ## init checks
-if [[ ! -w ${val_base} ]]; then echo "[EXIT] validation base not writable (${val_base})"; exit 1; fi
-if [[ ! -f ${truth_vcf_path} ]]; then echo "[EXIT] truth VCF not available (${truth_vcf_path})"; exit 1; fi
-if [[ ! -f ${truth_bed_path} ]]; then echo "[EXIT] truth BED not available (${truth_bed_path})"; exit 1; fi
+if [[ ! -w ${val_base} ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
+if [[ ! -f ${truth_vcf_path} ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
+if [[ ! -f ${truth_bed_path} ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
 if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     echo "-----"
     echo " Descr: Validate GIAB run"
@@ -51,7 +51,7 @@ else
     elif [[ -f ${pv5_path} ]]; then
         run_som_vcf_path=${pv5_path}
     else
-        echo "[EXIT] Unable to find somatic VCF" && exit 1; 
+        echo "[ERROR] Unable to find somatic VCF" && exit 1;
     fi
 fi
 run_som_vcf_name=$(basename ${run_som_vcf_path})
@@ -69,7 +69,7 @@ fi
 out_path="${val_base}/${out_name}"
 tmp_path="${out_path}/vcfeval"
 if [[ -e ${out_path} ]]; then
-    echo "[EXIT] Output dir exists remove first: ${out_path}" && exit 1
+    echo "[ERROR] Output dir exists remove first: ${out_path}" && exit 1
 else 
     echo "[INFO] Using output dir (${out_path})"
     mkdir ${out_path}
diff --git a/validation/validate_giab_pipeline_run b/validation/validate_giab_pipeline_run
--- a/validation/validate_giab_pipeline_run
+++ b/validation/validate_giab_pipeline_run
@@ -15,11 +15,12 @@ truth_vcf_path="${truth_dir_path}/${truth_vcf_name}"
 truth_vcf_path_snv=$(echo ${truth_vcf_path} | sed 's/\.vcf\.gz/_SNP\.vcf.\gz/')
 
 ## init checks
-if [[ ! -w ${val_base} ]]; then echo "[EXIT] validation base not writable (${val_base})"; exit 1; fi
-if [[ ! -f ${gatk_path} ]]; then echo "[EXIT] GATK JAR not available (${gatk_path})"; exit 1; fi
-if [[ ! -f ${ref_genome_fasta} ]]; then echo "[EXIT] Ref fasta not available (${ref_genome_fasta})"; exit 1; fi
-if [[ ! -f ${truth_vcf_path} ]]; then echo "[EXIT] truth VCF not available (${truth_vcf_path})"; exit 1; fi
-if [[ ! -f ${truth_bed_path} ]]; then echo "[EXIT] truth BED not available (${truth_bed_path})"; exit 1; fi
+if [[ ! -w ${val_base} ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
+if [[ ! -f ${gatk_path} ]]; then echo "[ERROR] GATK JAR not available (${gatk_path})"; exit 1; fi
+if [[ ! -f ${ref_genome_fasta} ]]; then echo "[ERROR] Ref fasta not available (${ref_genome_fasta})"; exit 1; fi
+if [[ ! -f ${truth_vcf_path} ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
+if [[ ! -f ${truth_bed_path} ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
+
 if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     echo "-----"
     echo " Descr: Validate GIAB run"
@@ -34,18 +35,18 @@ run_path=$1 && shift
 ## -----
 ## Checks and Setup
 ## -----
-if [[ ! -d $run_path ]]; then echo "[EXIT] Provided run path does not exist?"; exit 1; fi
+if [[ ! -d $run_path ]]; then echo "[ERROR] Provided run path does not exist?"; exit 1; fi
 
 ## Name of germline VCF differs betwee Pv4 and Pv5
 input_vcf_path=$(find ${run_path} -wholename "*/germline_caller/*.germline.vcf.gz")
 if [[ ! -f ${input_vcf_path} ]]; then input_vcf_path=$(find ${run_path} -maxdepth 1 -name "*.annotated.vcf.gz"); fi
-if [[ ! -f ${input_vcf_path} ]]; then echo "[EXIT] No germline VCF found ($run_path)" && exit 1; fi
+if [[ ! -f ${input_vcf_path} ]]; then echo "[ERROR] No germline VCF found ($run_path)" && exit 1; fi
 
 run_name=$(basename ${run_path})
 output_dir="${val_base}/${run_name}_Validation"
 tmp_dir="${output_dir}/tmp"
 
-if [[ -d ${output_dir} ]]; then echo "[EXIT] output_dir already exists (${output_dir})"; exit 1; fi
+if [[ -d ${output_dir} ]]; then echo "[ERROR] output_dir already exists (${output_dir})"; exit 1; fi
 
 echo "[INFO] Creating output dir (${output_dir})"
 mkdir -p ${output_dir}
@@ -66,7 +67,7 @@ elif [[ ${input_vcf_path} =~ .gz$ ]]; then
     echo "[INFO] Germline VCF is compressed: gunzippig to ${start_vcf_path}"
     gunzip -c ${input_vcf_path} > ${start_vcf_path}
 else
-    echo "[EXIT] Germline VCF of unsupported extension" && exit 1
+    echo "[ERROR] Germline VCF of unsupported extension" && exit 1
 fi
 
 echo "[INFO] Running RTGTools bgzip on ${start_vcf_name}"
@@ -87,7 +88,7 @@ if [[ -f $snp_vcf_path ]]; then
 else
     echo "[INFO] Running GATK to create SNP vcf (${snp_vcf_name})"
     java -Djava.io.tmp_dir=${tmp_dir} -jar ${gatk_path} -T SelectVariants -R ${ref_genome_fasta} -L ${truth_bed_path} --excludeNonVariants --removeUnusedAlternates -V ${start_vcf_path} -selectType SNP -o ${snp_vcf_path}
-    if [[ $? -ne 0 ]]; then { echo "[EXIT] GATK SelectVariants Failed"; exit 1; } fi
+    if [[ $? -ne 0 ]]; then { echo "[ERROR] GATK SelectVariants Failed"; exit 1; } fi
 fi
 
 ## no INDELs for now
