Add exit code/failure count

diff --git a/crunch/check_pipeline_output b/crunch/check_pipeline_output
--- a/crunch/check_pipeline_output
+++ b/crunch/check_pipeline_output
@@ -2,33 +2,41 @@
 # shellcheck disable=SC2155
 
 function main() {
-    local runDirs=("$@");
+    local runDirs=("$@")
+    local totalFailures=0
+
     echo
+    # shellcheck disable=SC2015
     for runDir in "${runDirs[@]}"; do
         info "-----------------------"
         info " Checking Rundir path:  ${runDir}"
         info "-----------------------"
 
-        DirsizeCheck "${runDir}"
-        PipelineCheckLogCheck "${runDir}"
+        DirsizeCheck "${runDir}" || ((failures++))
+        PipelineCheckLogCheck "${runDir}" || ((failures++))
         iniEnabled CNV_FREEC "${runDir}" &&
-            FreecPngCheck "${runDir}"
+            FreecPngCheck "${runDir}" || ((failures++))
         iniEnabled SOMATIC_VARIANTS "${runDir}" &&
-            SomaticsMergedCheck "${runDir}"
+            SomaticsMergedCheck "${runDir}" || ((failures++))
         iniEnabled SOMATIC_VARIANTS "${runDir}" &&
-            SomaticsMeltedCheck "${runDir}"
+            SomaticsMeltedCheck "${runDir}" || ((failures++))
         iniEnabled INDELREALIGNMENT "${runDir}" &&
-            BamSliceCheck "${runDir}"
+            BamSliceCheck "${runDir}" || ((failures++))
         iniEnabled INDELREALIGNMENT "${runDir}" &&
-            PrePostRealignDiffCheck "${runDir}"
+            PrePostRealignDiffCheck "${runDir}" || ((failures++))
         iniEnabled ANNOTATE_VARIANTS "${runDir}" &&
-            VcfSliceCheck "${runDir}"
-        WGSMetricsCheck "${runDir}"
+            VcfSliceCheck "${runDir}" || ((failures++))
+        WGSMetricsCheck "${runDir}" || ((failures++))
         iniEnabled KINSHIP "${runDir}" &&
-            KinshipCheck "${runDir}"
-        ReadMeCheck "${runDir}"
-        echo
+            KinshipCheck "${runDir}" || ((failures++))
+        ReadMeCheck "${runDir}" || ((failures++))
+
+        [[ $failures -gt 0 ]] && warn "${failures} FAILURES IN ${runDir}"
+        ((totalFailures += failures))
+        failures=0
     done
+    echo
+    [[ $totalFailures -gt 0 ]] && error "${totalFailures} TOTAL FAILURES"
     ShowCommands "${runDir}"
 }
 
@@ -54,6 +62,7 @@ function FreecPngCheck() {
         ok
     else
         fail "No non-empty Freec copy number PNG present!"
+        return 1
     fi
 }
 
@@ -80,6 +89,7 @@ function PipelineCheckLogCheck() {
         else
             fail "Pipeline Error!"
             cat "${checkFile}"
+            return 1
         fi
     fi
 }
@@ -91,6 +101,7 @@ function SomaticsMergedCheck() {
         ok
     else
         fail "No non-empty merged somatics VCF found!"
+        return 1
     fi
 }
 
@@ -103,6 +114,7 @@ function SomaticsMeltedCheck() {
         ok "(${meltedCount} lines in file)"
     else
         fail "No non-empty melted somatics VCF found!"
+        return 1
     fi
 }
 
@@ -112,6 +124,7 @@ function BamSliceCheck() {
         ok
     else
         fail "No non-empty BAM slice found!"
+        return 1
     fi
 }
 
@@ -121,6 +134,7 @@ function PrePostRealignDiffCheck() {
         ok
     else
         fail "No PrePostRealignDiff found!"
+        return 1
     fi
 }
 
@@ -130,6 +144,7 @@ function VcfSliceCheck() {
         ok
     else
         fail "No non-empty VCF slice found!"
+        return 1
     fi
 }
 
@@ -141,6 +156,7 @@ function WGSMetricsCheck() {
         maybeOk "$(cut -f 1,3,4,5,8,13 "${wgsmetricsFile}" | column -t)"
     else
         fail "No non-empty WGSMetrics file found!"
+        return 1
     fi
 }
 
@@ -151,6 +167,7 @@ function KinshipCheck() {
         maybeOk "$(cut -f 2,4,6,7,8 "${kinshipFile}" | column -t)"
     else
         fail "No non-empty kinship file found!"
+        return 1
     fi
 }
 
