Use new crunch names

diff --git a/crunch/crunches_flowcells b/crunch/crunches_flowcells
--- a/crunch/crunches_flowcells
+++ b/crunch/crunches_flowcells
@@ -6,8 +6,11 @@ for i in {2,3}; do
     if [[ "$(hostname)" == "crunch00${i}" ]]; then
       sample_sheets_info=$(check_samplesheets) \
           || die "Could not check samplesheets from crunch00${i} directly"
-    else
+    elif [[ "$(hostname)" == "datastore" ]]; then
       sample_sheets_info=$(ssh "crunch00${i}" check_samplesheets) \
+          || die "Could not check samplesheets info over ssh from crunch00${i}"
+    else
+      sample_sheets_info=$(ssh "crunch${i}.prod-1" check_samplesheets) \
           || die "Could not check samplesheets info over ssh from crunch00${i}"
     fi
     echo "${sample_sheets_info}" | \
