DEV-2369 Use new aliases for crunches

diff --git a/crunch/crunches_flowcells b/crunch/crunches_flowcells
--- a/crunch/crunches_flowcells
+++ b/crunch/crunches_flowcells
@@ -5,10 +5,10 @@ source message_functions || exit 1
 for i in {1,2}; do
     if [[ "$(hostname)" == "crunch00${i}" ]]; then
       sample_sheets_info=$(check_samplesheets) \
-          || die "Could not check samplesheets from crunch00${i} directly"
+          || die "Could not check samplesheets from crunch${i}.prod-1 directly"
     else
-      sample_sheets_info=$(ssh "crunch00${i}" check_samplesheets) \
-          || die "Could not check samplesheets info over ssh from crunch00${i}"
+      sample_sheets_info=$(ssh "crunch${i}.prod-1" check_samplesheets) \
+          || die "Could not check samplesheets info over ssh from crunch${i}.prod-1"
     fi
     echo "${sample_sheets_info}" | \
     grep -Po "(X|NO|NS|IS)\d{2}\-.+_.+_.+_.+" | \
