Add snpcheck related directories to locate_files

diff --git a/crunch/find_snpcheck_vcf b/crunch/find_snpcheck_vcf
--- a/crunch/find_snpcheck_vcf
+++ b/crunch/find_snpcheck_vcf
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
 
 source message_functions || exit 1
+source locate_files || exit 1
 source locate_gcp_files || exit 1
 
 search_remote=FALSE
-dir1='/data/common/snpcheck/'
-dir2='/data/gcp/snpcheckvcfupload/'
+dir1=$(locate_snpcheck_dir) || die "Could not find local snpcheck dir"
+dir2=$(locate_snpcheck_vcf_upload_dir) || die "Could not get snpcheck upload dir"
 vcf_gcp_bucket=$(locate_snpcheck_vcfs_at_gcp) || die "Could not get snpcheck vcf location at GCP"
 
 print_usage(){
@@ -34,14 +35,14 @@ search=$1 # eg FR12345678
 
 echo ""
 info "Searching for snpcheck files matching '${search}'"
-count1=$(find ${dir1} -name "*${search}*.vcf" | wc -l)
+count1=$(find "${dir1}" -name "*${search}*.vcf" | wc -l)
 info "Found ${count1} local VCFs in archive at ops-vm (${dir1})"
-find ${dir1} -name "*${search}*.vcf"
+find "${dir1}" -name "*${search}*.vcf"
 echo ""
 
-count2=$(find ${dir2} -name "*${search}*.vcf" | wc -l)
+count2=$(find "${dir2}" -name "*${search}*.vcf" | wc -l)
 info "Found ${count2} local VCFs in sync location at ops-vm (${dir2})"
-find ${dir2} -name "*${search}*.vcf"
+find "${dir2}" -name "*${search}*.vcf"
 echo ""
 
 if [[ "${search_remote}" == "TRUE" ]]; then
diff --git a/snpcheck/create_sample_vcfs_from_csv b/snpcheck/create_sample_vcfs_from_csv
--- a/snpcheck/create_sample_vcfs_from_csv
+++ b/snpcheck/create_sample_vcfs_from_csv
@@ -1,18 +1,19 @@
 #!/usr/bin/env bash
 
 source message_functions || exit 1
+source locate_files || exit 1
 
 CODEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-OUTBASE="/data/common/snpcheck"
+OUTBASE=$(locate_snpcheck_dir) || die "Could not find local snpcheck dir"
 SCRIPT="${CODEDIR}/Convert_OpenArray_CSV_to_VCF.py"
-GCPDIR="/data/gcp/snpcheckvcfupload"
+GCPDIR=$(locate_snpcheck_vcf_upload_dir) || die "Could not get snpcheck upload dir"
 SNPCOUNT="26"
 
 if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     echo "-----"
     echo " Descr: Reads the output of genotyping machine and converts to vcf"
     echo " Usage: $(basename $0) <path-to-snpgenotyping-csv-results-file"
-    echo "        $(basename $0) /data/common/snpcheck/input/<design>/file.csv"
+    echo "        $(basename $0) ${OUTBASE}input/<design>/file.csv"
     echo " Confg:"
     echo "   CODEDIR = ${CODEDIR}"
     echo "   GCPDIR  = ${GCPDIR}"
@@ -34,7 +35,7 @@ if [[ ${design_size} -eq 60 ]]; then
     SNPCOUNT="60"
 fi
 DESIGN="${CODEDIR}/${SNPCOUNT}SNPtaq_design.vcf"
-OUTDIR="${OUTBASE}/output/${SNPCOUNT}SNPtaq"
+OUTDIR="${OUTBASE}output/${SNPCOUNT}SNPtaq"
 if [[ ! -f "${DESIGN}" ]]; then error "Design file does not exist (${DESIGN})?"; fi
 if [[ ! -d "${OUTDIR}" ]]; then error "Output dir does not exist (${OUTDIR})?"; fi
 
