More consistency changes

diff --git a/crunch/find_patient_reports b/crunch/find_patient_reports
--- a/crunch/find_patient_reports
+++ b/crunch/find_patient_reports
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 
-search_string=$1 # eg CPCT02010001
-name_pattern="${search_string}*.pdf"
+search=$1 # eg CPCT02010001
+
+if [[ -z "${search}" ]]; then
+    echo "[ERROR] No search string specified. Exiting." && exit 1
+fi
+
+name_pattern="${search}*.pdf"
 
 directory1='/data/cpct/old_cpct_reports'
 directory2='/data/cpct/final_reports'
diff --git a/crunch/find_snpcheck_vcf b/crunch/find_snpcheck_vcf
--- a/crunch/find_snpcheck_vcf
+++ b/crunch/find_snpcheck_vcf
@@ -2,6 +2,10 @@
 
 search=$1 # eg FR12345678
 
+if [[ -z "${search}" ]]; then
+    echo "[ERROR] No search string specified. Exiting." && exit 1
+fi
+
 dir1='/data/common/snpcheck/'
 dir2='/data/gcp/snpcheckvcfupload/'
 gcp_bucket='hmf-snpcheck'
diff --git a/crunch/perform_bcl2fastq_qc b/crunch/perform_bcl2fastq_qc
--- a/crunch/perform_bcl2fastq_qc
+++ b/crunch/perform_bcl2fastq_qc
@@ -30,10 +30,10 @@ function printHeader() {
 for seq_run in "${seq_runs[@]}"; do
     ## remove trailing slash if present
     seq_run=$(echo ${seq_run%/})
-    if [[ $seq_run =~ ^\/ ]]; then
+    if [[ ${seq_run} =~ ^\/ ]]; then
         seq_dirs+=(${seq_run})
     else
-        seq_dirs+=("$PWD/${seq_run}" )
+        seq_dirs+=("${PWD}/${seq_run}" )
     fi
 done
 
@@ -43,17 +43,17 @@ for seq_dir in "${seq_dirs[@]}"; do
     ssheet_path="${seq_dir}/${SSHEET_FILE}"
     errlog_path="${seq_dir}/${ERRLOG_FILE}"
     report_path="${seq_dir}/${REPORT_ROOT}/{Reports,Stats}"
-    seqdir_name="$(basename $seq_dir | tr -d '\r')"
+    seqdir_name="$(basename ${seq_dir} | tr -d '\r')"
     hmfrun_name="$(cat ${ssheet_path} | grep -P '^Experiment' | cut -d',' -f 2 | tr -d '\r')"
     nasrun_name="${hmfrun_name}__${seqdir_name}"
     
     ## anything wrong with any seqrun: exit the whole thing
     if [[ ! -d ${seq_dir} ]]; then
-        echo "[ERROR] dir does not exist ($seq_dir)" && exit 1; 
+        echo "[ERROR] dir does not exist (${seq_dir})" && exit 1; 
     elif [[ ! $(cat ${errlog_path} | tail -1 | grep "with 0 errors and") ]]; then 
         echo "[ERROR] Errlog does not say 0 errors (${errlog_path})" && exit 1; 
     elif [[ -z ${hmfrun_name} ]]; then
-        echo "[ERROR] Have not been able to parse hmfrun_name from sheet ($ssheet_path)" && exit 1; 
+        echo "[ERROR] Have not been able to parse hmfrun_name from sheet (${ssheet_path})" && exit 1; 
     fi
     
     ## store further cmds so we can print all together at the end
@@ -76,9 +76,9 @@ for seq_dir in "${seq_dirs[@]}"; do
         sample_id=$(echo ${line} | cut -d" " -f9)
         sample_nm=$(echo ${line} | cut -d" " -f10)
         set_name="NA"
-        fc_status_info="$yld_seq q=$q30_seq"
+        fc_status_info="${yld_seq} q=${q30_seq}"
         if [[ "${HOSTNAME}" == "datastore" ]]; then 
-            api_jsn=$(cat "${API_SAMPLES_JSON}" | jq -r --arg barcode "$sample_id" '.[] | select(.barcode == $barcode)')
+            api_jsn=$(cat "${API_SAMPLES_JSON}" | jq -r --arg barcode "${sample_id}" '.[] | select(.barcode == $barcode)')
             api_sts=$(echo "${api_jsn}" | jq -r ".status")
             api_yld=$(echo "${api_jsn}" | jq -r ".yld")
             api_req=$(echo "${api_jsn}" | jq -r ".yld_req")
@@ -90,7 +90,7 @@ for seq_dir in "${seq_dirs[@]}"; do
             api_status_info="(run at datastore for added API info)"
         fi
         final_status_info="${fc_status_info} ${api_status_info}"
-        echo -e "$submission\t$sample_id\t$sample_nm\t$final_status_info\t$set_name"
+        echo -e "${submission}\t${sample_id}\t${sample_nm}\t${final_status_info}\t${set_name}"
    done | sort -k1,1 -k3,3
 done
 
diff --git a/crunch/rename_sample_name_of_fastq_files b/crunch/rename_sample_name_of_fastq_files
--- a/crunch/rename_sample_name_of_fastq_files
+++ b/crunch/rename_sample_name_of_fastq_files
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 
-maxFindDepth=1
+max_find_depth=1
 
-dirPath=$PWD # directory that contains fastq files
-oldName='' # string of current sample name
-newName='' # string of new sample name
-doRenameFiles=''
-doSymlinkFiles=''
-commandLine=$( basename ${0} )" $@"
+dir_path=${PWD} # directory that contains fastq files
+old_name='' # string of current sample name
+new_name='' # string of new sample name
+do_rename_files=''
+do_symlink_files=''
+command_line=$(basename ${0})" $@"
 
 if [[ $# -eq 0 || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
@@ -20,84 +20,83 @@ if [[ $# -eq 0 || $1 == "-h" || $1 == "--help" ]]; then
     echo " Options:"
     echo "   -r      Perform actual renaming"
     echo "   -s      Symlink instead of rename"
-    echo "   -d <s>  Directory with fastq files [$dirPath]"
-    echo "   -f <i>  Max depth for find to search [$maxFindDepth]"
+    echo "   -d <s>  Directory with fastq files [${dir_path}]"
+    echo "   -f <i>  Max depth for find to search [${max_find_depth}]"
     echo "---"
     exit 1
 fi
 
 while getopts ":o:n:d:rsf:" opt; do
-  case $opt in
+  case ${opt} in
     o)
-      oldName=$OPTARG
+      old_name=${OPTARG}
       ;;
     n)
-      newName=$OPTARG
+      new_name=${OPTARG}
       ;;
     d)
-      dirPath=$OPTARG
+      dir_path=${OPTARG}
       ;;
     r)
-      doRenameFiles='true'
+      do_rename_files='true'
       ;;
     s)
-      doSymlinkFiles='true'
+      do_symlink_files='true'
       ;;
     f)
-      maxFindDepth=$OPTARG
+      max_find_depth=${OPTARG}
       ;;
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+      echo "Invalid option: -${OPTARG}" >&2
       exit 1
       ;;
     :)
-      echo "Option -$OPTARG requires an argument." >&2
+      echo "Option -${OPTARG} requires an argument." >&2
       exit 1
       ;;
   esac
 done
 
 ## store rest of params as files to rename
-filesToRename=()
+files_to_rename=()
 while IFS=  read -r -d $'\0'; do
-    filesToRename+=("$REPLY")
-done < <(find "${dirPath}" -maxdepth ${maxFindDepth} -name "$oldName*.fastq.gz" -print0)
+    files_to_rename+=("${REPLY}")
+done < <(find "${dir_path}" -maxdepth ${max_find_depth} -name "${old_name}*.fastq.gz" -print0)
 
 ## sanity checks
-if [[ ${#filesToRename[@]} -lt 1 ]]; then echo "[ERROR] No fastq files found (with find-depth ${maxFindDepth})" && exit 1; fi
-if [[ -z ${oldName} ]]; then echo "[ERROR] Param oldName (-o) not set" && exit 1; fi
-if [[ -z ${newName} ]]; then echo "[ERROR] Param newName (-n) not set" && exit 1; fi
-if [[ -z ${dirPath} ]]; then echo "[ERROR] Param dirPath (-d) not set" && exit 1; fi
-if [[ ! -d ${dirPath} ]]; then echo "[ERROR] dirPath (${dirPath}) does not exist?" && exit 1; fi
-
+if [[ ${#files_to_rename[@]} -lt 1 ]]; then echo "[ERROR] No fastq files found (with find-depth ${max_find_depth})" && exit 1; fi
+if [[ -z "${old_name}" ]]; then echo "[ERROR] Param old_name (-o) not set" && exit 1; fi
+if [[ -z "${new_name}" ]]; then echo "[ERROR] Param new_name (-n) not set" && exit 1; fi
+if [[ -z "${dir_path}" ]]; then echo "[ERROR] Param dir_path (-d) not set" && exit 1; fi
+if [[ ! -d "${dir_path}" ]]; then echo "[ERROR] dir_path (${dir_path}) does not exist?" && exit 1; fi
 
 ## print info
-echo "[INFO] Setting FastqDirectory: ${dirPath}"
-echo "[INFO] Setting OldName: \"${oldName}\""
-echo "[INFO] Setting NewName: \"${newName}\""
+echo "[INFO] Setting FastqDirectory: ${dir_path}"
+echo "[INFO] Setting OldName: \"${old_name}\""
+echo "[INFO] Setting NewName: \"${new_name}\""
 
 ## renaming action
-for oldFile in "${filesToRename[@]}"; do
-    fileDir=$( dirname ${oldFile} )
-    oldBase=$( basename ${oldFile} )
-    newBase=$( echo ${oldBase} | sed "s/${oldName}/${newName}/" )
-    newFile="${fileDir}/${newBase}" 
+for old_file in "${files_to_rename[@]}"; do
+    file_dir=$(dirname ${old_file})
+    old_base=$(basename ${old_file})
+    new_base=$(echo ${old_base} | sed "s/${old_name}/${new_name}/")
+    new_file="${file_dir}/${new_base}" 
 
-    if [[ ${doSymlinkFiles} ]]; then
-        echo "[INFO] Symlinking ${oldBase} to ${newBase} )"
-        ln -s ${oldFile} ${newBase}
-    elif [[ ${doRenameFiles} ]]; then
-        echo "[INFO] Renaming ${oldBase} to ${newBase} in ${fileDir}"
-        mv ${oldFile} ${newFile} 
+    if [[ ${do_symlink_files} ]]; then
+        echo "[INFO] Symlinking ${old_base} to ${new_base} )"
+        ln -s ${old_file} ${new_base}
+    elif [[ ${do_rename_files} ]]; then
+        echo "[INFO] Renaming ${old_base} to ${new_base} in ${file_dir}"
+        mv ${old_file} ${new_file} 
     else
-        echo "[INFO] Would rename $oldBase to $newBase in ${fileDir}"
+        echo "[INFO] Would rename ${old_base} to ${new_base} in ${file_dir}"
     fi
 done
 
-if [[ ! ${doRenameFiles} ]]; then
-    logFilePath="${dirPath}/fastqrename.log"
+if [[ ! ${do_rename_files} ]]; then
+    log_file_path="${dir_path}/fastqrename.log"
     echo "[INFO] Option -r not set so only printed the potential rename actions"
-    echo "[INFO] Cmd to rename: ${commandLine} -r > ${logFilePath}"
-    if [[ -f ${logFilePath} ]]; then echo "[WARN] Logfile (${logFilePath}) already exists!"; fi
+    echo "[INFO] Cmd to rename: ${command_line} -r > ${log_file_path}"
+    if [[ -f ${log_file_path} ]]; then echo "[WARN] Logfile (${log_file_path}) already exists!"; fi
 fi
 
diff --git a/crunch/update_report_date_overview b/crunch/update_report_date_overview
--- a/crunch/update_report_date_overview
+++ b/crunch/update_report_date_overview
@@ -1,17 +1,17 @@
 #!/usr/bin/env bash
 
 YYMMDD=$(date '+%y%m%d')
-taskId="updateReportingOverview"
+task_id="updateReportingOverview"
 
-srcDir="/data/lims"
-nasLoc="/volume1/web/overviews/reporting"
+src_dir="/data/lims"
+nas_loc="/volume1/web/overviews/reporting"
 
 ## Sanity checks
-if [[ ! -d "${srcDir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${srcDir})" && exit 1; fi
+if [[ ! -d "${src_dir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${src_dir})" && exit 1; fi
 
 ## Action
-echo "[INFO] START with ${taskId} ($YYMMDD)"
-echo "[INFO]   Syncing from datastore to NAS intranet (to ${nasLoc})"
-scp "/data/lims/reporting_db.tsv" "nas:${nasLoc}"
-scp "/data/lims/reporting_db.tsv" "nas:${nasLoc}/reporting_db.txt"
-echo "[INFO] DONE with ${taskId}"
+echo "[INFO] START with ${task_id} ($YYMMDD)"
+echo "[INFO]   Syncing from datastore to NAS intranet (to ${nas_loc})"
+scp "/data/lims/reporting_db.tsv" "nas:${nas_loc}"
+scp "/data/lims/reporting_db.tsv" "nas:${nas_loc}/reporting_db.txt"
+echo "[INFO] DONE with ${task_id}"
diff --git a/crunch/update_rna_overview b/crunch/update_rna_overview
--- a/crunch/update_rna_overview
+++ b/crunch/update_rna_overview
@@ -1,57 +1,57 @@
 #!/usr/bin/env bash
 
 YYMMDD=$(date '+%y%m%d')
-datDir="/data/data_archive"
-seqTyp="rna_seq"
-taskId="Overview ${seqTyp}"
+dat_dir="/data/data_archive"
+seq_typ="rna_seq"
+task_id="Overview ${seq_typ}"
 
-nasLoc="nas:/volume1/web/overviews/rnaseq/"
-seqDir="${datDir}/${seqTyp}/fastq"
-outDir="${datDir}/${seqTyp}/overview"
+nas_loc="nas:/volume1/web/overviews/rnaseq/"
+seq_dir="${dat_dir}/${seq_typ}/fastq"
+out_dir="${dat_dir}/${seq_typ}/overview"
 
-outTsv="${outDir}/overview.tsv"
-outSmp="${outDir}/samples.tsv"
-outSum="${outDir}/summary.log"
-errLog="${outDir}/error.log"
+out_tsv="${out_dir}/overview.tsv"
+out_smp="${out_dir}/samples.tsv"
+out_sum="${out_dir}/summary.log"
+err_log="${out_dir}/error.log"
 
 ## sanity checks
-if [[ ! -d "${outDir}" ]]; then echo "[ERROR] OUTPUT DIR does not exist (${outDir})" && exit 1; fi
-if [[ ! -w "${outDir}" ]]; then echo "[ERROR] OUTPUT DIR not writable (${outDir})" && exit 1; fi
-if [[ ! -d "${seqDir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${seqDir})" && exit 1; fi
+if [[ ! -d "${out_dir}" ]]; then echo "[ERROR] OUTPUT DIR does not exist (${out_dir})" && exit 1; fi
+if [[ ! -w "${out_dir}" ]]; then echo "[ERROR] OUTPUT DIR not writable (${out_dir})" && exit 1; fi
+if [[ ! -d "${seq_dir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${seq_dir})" && exit 1; fi
 
 ## startup
-echo "[INFO] START ${taskId} ($YYMMDD)" | tee ${outSum}
-echo "[INFO] Writing err log to ${errLog}" | tee -a ${outSum}
+echo "[INFO] START ${task_id} ($YYMMDD)" | tee ${out_sum}
+echo "[INFO] Writing err log to ${err_log}" | tee -a ${out_sum}
 
 # gather info
-fastq_disk_usage=$(du -sh ${seqDir} | cut -f1)
-echo -e "#sample\tbarcode\tsize\tpath\tflowcells" > "${outTsv}"
-for fastqDirPath in ${seqDir}/*; do 
-    fastqDirName=$( basename ${fastqDirPath} )
-    barcode=$( echo ${fastqDirName} | cut -d"_" -f1 )
-    sample=$( echo ${fastqDirName} | cut -d"_" -f2 )
-    size=$( du -sh ${fastqDirPath} | cut -f1 )
-    flowcells=$( find ${fastqDirPath} -name "*fastq.gz" -exec basename {} \; | cut -d"_" -f2 | sort | uniq | tr "\n" "," | sed 's/,$//' )
-    printf "%s\t%s\t%s\t%s\t%s\n" "${sample}" "${barcode}" "${size}" "${fastqDirPath}" "${flowcells}"
-done | sort -k1 >>"${outTsv}" 2>"${errLog}"
+fastq_disk_usage=$(du -sh ${seq_dir} | cut -f1)
+echo -e "#sample\tbarcode\tsize\tpath\tflowcells" > "${out_tsv}"
+for fastq_dir_path in ${seq_dir}/*; do 
+    fastq_dir_name=$(basename ${fastq_dir_path})
+    barcode=$(echo ${fastq_dir_name} | cut -d"_" -f1)
+    sample=$(echo ${fastq_dir_name} | cut -d"_" -f2)
+    size=$(du -sh ${fastq_dir_path} | cut -f1)
+    flowcells=$(find ${fastq_dir_path} -name "*fastq.gz" -exec basename {} \; | cut -d"_" -f2 | sort | uniq | tr "\n" "," | sed 's/,$//')
+    printf "%s\t%s\t%s\t%s\t%s\n" "${sample}" "${barcode}" "${size}" "${fastq_dir_path}" "${flowcells}"
+done | sort -k1 >>"${out_tsv}" 2>"${err_log}"
 
 ## create sample name list
-cat ${outTsv} | grep -v "^#" | cut -f1 | sort | uniq > ${outSmp}
-sampleCount=$( grep -cv "^#" ${outSmp} )
+cat ${out_tsv} | grep -v "^#" | cut -f1 | sort | uniq > ${out_smp}
+sample_count=$(grep -cv "^#" ${out_smp})
 
- uniqSampleCount=$( cat ${outTsv} | grep -v ^# | cut -f1 | sort | uniq | wc -l )
-uniqBarcodeCount=$( cat ${outTsv} | grep -v ^# | cut -f2 | sort | uniq | wc -l )
+uniq_sample_count=$(cat ${out_tsv} | grep -v ^# | cut -f1 | sort | uniq | wc -l)
+uniq_barcode_count=$(cat ${out_tsv} | grep -v ^# | cut -f2 | sort | uniq | wc -l)
 
-echo "[INFO] FASTQ data footprint: ${fastq_disk_usage}" | tee -a ${outSum}
-echo "[INFO] Number of samples: ${sampleCount}" | tee -a ${outSum}
-echo "[INFO] Number of unique sample names: ${uniqSampleCount}" | tee -a ${outSum}
-echo "[INFO] Number of unique sample barcodes: ${uniqBarcodeCount}" | tee -a ${outSum}
-echo "[INFO] Complete table in: ${outTsv}" | tee -a ${outSum}
-echo "[INFO]   Sample table in: ${outSmp}" | tee -a ${outSum}
+echo "[INFO] FASTQ data footprint: ${fastq_disk_usage}" | tee -a ${out_sum}
+echo "[INFO] Number of samples: ${sample_count}" | tee -a ${out_sum}
+echo "[INFO] Number of unique sample names: ${uniq_sample_count}" | tee -a ${out_sum}
+echo "[INFO] Number of unique sample barcodes: ${uniq_barcode_count}" | tee -a ${out_sum}
+echo "[INFO] Complete table in: ${out_tsv}" | tee -a ${out_sum}
+echo "[INFO]   Sample table in: ${out_smp}" | tee -a ${out_sum}
 
-echo "[INFO] Starting NAS sync (to ${nasLoc})"
-rsync ${outTsv} ${nasLoc}/overview.txt
-rsync ${outSmp} ${nasLoc}/samples.txt
-rsync ${outSum} ${nasLoc}/summary.txt
+echo "[INFO] Starting NAS sync (to ${nas_loc})"
+rsync ${out_tsv} ${nas_loc}/overview.txt
+rsync ${out_smp} ${nas_loc}/samples.txt
+rsync ${out_sum} ${nas_loc}/summary.txt
 
-echo "[INFO] DONE ${taskId}" | tee -a $outSum
+echo "[INFO] DONE ${task_id}" | tee -a ${out_sum}
