Make gen_tool_aliases more robust and flexible

diff --git a/crunch/gen_tool_aliases b/crunch/gen_tool_aliases
--- a/crunch/gen_tool_aliases
+++ b/crunch/gen_tool_aliases
@@ -1,30 +1,43 @@
 #!/usr/bin/env bash
 
 set -o errexit
+set -o pipefail
 set -o nounset
 
-ALIAS_FILE=~/tool_aliases
-TOOL_DIR=/data/tools
-
 function main() {
-    local temp_file="${ALIAS_FILE}.tmp"
+    local tool_dir=${1:-/data/tools} && shift
+    local alias_file=${1:-~/tool_aliases} && shift
+
+    if [[ ! -d "${tool_dir}" ]]; then
+        echo "ERROR: ${tool_dir} is not a directory"
+        exit 1
+    fi
+
+    local temp_file="${alias_file}.tmp"
     while IFS= read -r -d '' tool_bin; do
-        local tool_name=$(basename "${tool_bin}")
+        local tool_name
+        tool_name=$(basename "${tool_bin}")
         if [[ ${tool_name} == "configure" ]]; then
             echo "ignoring ${tool_bin}"
         else
             echo "alias ${tool_name}='${tool_bin}'" >> "${temp_file}"
         fi
-    done < <(find "${TOOL_DIR}" -maxdepth 3 -type f -executable -print0)
-    local dups=$(cut -d= -f1 "${temp_file}" | sort | uniq -d)
-    if [[ -n $dups ]]; then
-        echo "WARN: duplicate tools found (not replacing ${ALIAS_FILE}):"
-        echo
-        echo "$dups"
+    done < <(find "${tool_dir}" -maxdepth 3 -type f -executable -print0)
+
+    if [[ -s "${temp_file}" ]]; then
+        local dups
+        dups=$(cut -d= -f1 "${temp_file}" | sort | uniq -d)
+        if [[ -n $dups ]]; then
+            echo "WARN: duplicate tools found (not replacing ${alias_file}):"
+            echo
+            echo "$dups"
+        else
+            mv "${temp_file}" "${alias_file}"
+        fi
+        rm -f "${temp_file}"
     else
-        mv "${temp_file}" "${ALIAS_FILE}"
+        echo "WARN: no tools found"
     fi
-    rm -f "${temp_file}"
 }
 
 main "$@"
