should only be run on datastore

diff --git a/crunch/pull_all_scripts_repos b/crunch/pull_all_scripts_repos
--- a/crunch/pull_all_scripts_repos
+++ b/crunch/pull_all_scripts_repos
@@ -2,6 +2,11 @@
 
 pull_script="pull_scripts_repo"
 
+if [[ "$(hostname)" != "datastore" ]]; then
+    echo "[ERROR] This script is meant to be executed at datastore. Exiting."
+    exit 1
+fi
+
 for server in crunch00{2,3}; do
     echo "---"
     echo "[INFO] Executing \"${pull_script}\" at server ${server}"
