Improve consistency of scripts

diff --git a/crunch/rename_sample_name_of_fastq_files b/crunch/rename_sample_name_of_fastq_files
--- a/crunch/rename_sample_name_of_fastq_files
+++ b/crunch/rename_sample_name_of_fastq_files
@@ -47,11 +47,11 @@ while getopts ":o:n:d:rsf:" opt; do
       max_find_depth=${OPTARG}
       ;;
     \?)
-      echo "Invalid option: -${OPTARG}" >&2
+      echo "[ERROR] Invalid option: -${OPTARG}" >&2
       exit 1
       ;;
     :)
-      echo "Option -${OPTARG} requires an argument." >&2
+      echo "[ERROR] Option -${OPTARG} requires an argument." >&2
       exit 1
       ;;
   esac
diff --git a/lims/gather_submission b/lims/gather_submission
--- a/lims/gather_submission
+++ b/lims/gather_submission
@@ -7,9 +7,9 @@ HMF_LIMS_JSON='/data/lims/lims.json'
 submission=$1
 
 ## sanity checks
-if [[ $# -eq 0 ]] ; then echo "run with eg: $0 HMFreg0000"; exit 1; fi
-if [[ -z "${submission+x}" ]]; then echo "Missing submission id as input"; exit 1; fi
-if [[ ! ${submission} =~ ^HMFreg ]]; then echo "Submission should start with \"HMFreg\""; exit 1; fi
+if [[ $# -eq 0 ]] ; then echo "[ERROR] Run with eg: $0 HMFreg0000"; exit 1; fi
+if [[ -z "${submission+x}" ]]; then echo "[ERROR] Missing submission id as input"; exit 1; fi
+if [[ ! ${submission} =~ ^HMFreg ]]; then echo "[ERROR] Submission should start with \"HMFreg\""; exit 1; fi
 
 ## setting up variables
 out_path=${SUBMISSIONS_DIR}'/'${submission}
