Upload from VM instead of from crunch

diff --git a/crunch/sync_samplesheets_from_crunches_to_bucket b/crunch/sync_samplesheets_from_crunches_to_bucket
--- a/crunch/sync_samplesheets_from_crunches_to_bucket
+++ b/crunch/sync_samplesheets_from_crunches_to_bucket
@@ -1,14 +1,17 @@
 #!/usr/bin/env bash
 
 source gcp_functions || exit 1
+source io_functions || exit 1
 source message_functions || exit 1
-source locate_files || exit 1
 source locate_gcp_files || exit 1
 
 crunch_seq_runs_dir=/data1/illumina_data
+tmp_dir=/tmp/samplesheets/
 samplesheets_bucket=$(locate_samplesheets_at_gcp) || die "Could not find samplesheets bucket path"
 
 switch_to_hmf_ops_service_account || die "Could not switch to hmf ops"
+
+create_or_cleanup_dir "${tmp_dir}" || die "Could not create temporary dir"
 
 for i in {2,3}; do
     crunch_name="crunch00${i}"
@@ -18,10 +21,19 @@ for i in {2,3}; do
     while read -r sheet_path; do
         run_path=$(dirname "${sheet_path}")
         run_name=$(basename "${run_path}")
+        tmp_local_path="${tmp_dir%/}/${run_name}_SampleSheet.csv"
+        info "  Executing rsync for ${run_name}"
+        rsync_log_line_count=$(rsync -rtv "${crunch_name}:${sheet_path}" "${tmp_local_path}" | wc -l)
+        if [[ "${rsync_log_line_count}" -gt 4 ]]; then
+            info "   Synced to ${tmp_local_path}"
+        fi
         in_bucket_path="${samplesheets_bucket%/}/${run_name}_SampleSheet.csv"
         info "  Copying to bucket ${samplesheets_bucket} for ${run_name}"
-        info "  Sample"
-        ssh -n ${crunch_name} "source gcp_functions && switch_to_hmf_ops_service_account && gsutil cp ${sheet_path} ${in_bucket_path}"
+        gsutil cp "${tmp_local_path}" "${in_bucket_path}"
         gsutil -q stat "${in_bucket_path}" || die "Could not upload samplesheet for ${run_name} to ${samplesheets_bucket}"
     done
 done
+
+info "Syncs were successful"
+rm -r "${tmp_dir}" || die "Failed to delete temporary local dir"
+info "Deleted temp dir ${tmp_dir}"
