More param shifts moved after the checking and some other consistency updates

diff --git a/crunch/update_report_date_overview b/crunch/update_report_date_overview
--- a/crunch/update_report_date_overview
+++ b/crunch/update_report_date_overview
@@ -7,7 +7,7 @@ srcDir="/data/lims"
 nasLoc="/volume1/web/overviews/reporting"
 
 ## Sanity checks
-if [[ ! -d ${srcDir} ]]; then echo "[ERROR] INPUT DIR does not exist (${srcDir})" && exit 1; fi
+if [[ ! -d "${srcDir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${srcDir})" && exit 1; fi
 
 ## Action
 echo "[INFO] START with ${taskId} ($YYMMDD)"
diff --git a/crunch/update_rna_overview b/crunch/update_rna_overview
--- a/crunch/update_rna_overview
+++ b/crunch/update_rna_overview
@@ -15,9 +15,9 @@ outSum="${outDir}/summary.log"
 errLog="${outDir}/error.log"
 
 ## sanity checks
-if [[ ! -d ${outDir} ]]; then echo "[ERROR] OUTPUT DIR does not exist (${outDir})" && exit 1; fi
-if [[ ! -w ${outDir} ]]; then echo "[ERROR] OUTPUT DIR not writable (${outDir})" && exit 1; fi
-if [[ ! -d ${seqDir} ]]; then echo "[ERROR] INPUT DIR does not exist (${seqDir})" && exit 1; fi
+if [[ ! -d "${outDir}" ]]; then echo "[ERROR] OUTPUT DIR does not exist (${outDir})" && exit 1; fi
+if [[ ! -w "${outDir}" ]]; then echo "[ERROR] OUTPUT DIR not writable (${outDir})" && exit 1; fi
+if [[ ! -d "${seqDir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${seqDir})" && exit 1; fi
 
 ## startup
 echo "[INFO] START ${taskId} ($YYMMDD)" | tee ${outSum}
diff --git a/crunch/update_submission_overview b/crunch/update_submission_overview
--- a/crunch/update_submission_overview
+++ b/crunch/update_submission_overview
@@ -10,12 +10,12 @@ reportsTarget="/volume1/web/overviews/submissions/pdf_reports"
 reportsTargetDs="/data/data_archive/overviews/submissions/pdf_reports"
 
 ## Sanity checks
-if [[ ! -d ${srcDir} ]]; then echo "[ERROR] INPUT DIR does not exist (${srcDir})" && exit 1; fi
+if [[ ! -d "${srcDir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${srcDir})" && exit 1; fi
 
 ## Action
 echo "[INFO] START with ${taskId} ($YYMMDD)"
 echo "[INFO]   Listing all submissions in $srcDir" 
-dirsToSync=$( find ${srcDir} -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex ".*/HMFreg[0-9]{4}$" )
+dirsToSync=$(find ${srcDir} -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex ".*/HMFreg[0-9]{4}$")
 
 echo "[INFO]   Syncing logs from datastore to NAS intranet (to ${nasLoc})"
 rsync -ah --exclude "*/data/" --include "*/" --include "*.txt" --include *README --exclude "*" ${dirsToSync} "nas:${nasLoc}"
