Using NAS Rsync user allows adding to ops cron

diff --git a/crunch/update_submission_overview b/crunch/update_submission_overview
--- a/crunch/update_submission_overview
+++ b/crunch/update_submission_overview
@@ -1,29 +1,54 @@
 #!/usr/bin/env bash
 
+# This script is expected to be run as a cronjob so loading bashrc
+source "${HOME}/.bashrc"
+
 YYMMDD=$(date '+%y%m%d')
 task_id="updateSubmissionOverview"
 
-src_dir="/data/submissions"
-nas_loc="/volume1/web/overviews/submissions"
-reports_source="/volume1/machines/BFX/dataReports"
-reports_target="/volume1/web/overviews/submissions/pdf_reports"
-reports_target_ds="/data/data_archive/overviews/submissions/pdf_reports"
+nas_tgt_dir="/volume1/web/overviews/submissions"
+ ds_src_dir="/data/submissions"
+
+nas_reports_source="/volume1/machines/BFX/dataReports"
+nas_reports_target="/volume1/web/overviews/submissions/pdf_reports"
+ ds_reports_target="/data/data_archive/overviews/submissions/pdf_reports"
+
+pwd_loc="/data/common/dbs/nas_credentials/rsyncuser"
 
 ## Sanity checks
-if [[ ! -d "${src_dir}" ]]; then echo "[ERROR] INPUT DIR does not exist (${src_dir})" && exit 1; fi
+if [[ ! -d "${ds_src_dir}" ]]; then
+    echo "[ERROR] INPUT DIR does not exist (${ds_src_dir})" && exit 1
+fi
 
-## Action
-echo "[INFO] START with ${task_id} ($YYMMDD)"
-echo "[INFO]   Listing all submissions in ${src_dir}" 
-dirs_to_sync=$(find ${src_dir} -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex ".*/HMFreg[0-9]{4}$")
+echo "[INFO] Starting task ${task_id} ($YYMMDD)"
+echo "[INFO]   Finding all submissions in ${ds_src_dir}"
+dirs_to_sync=$(find ${ds_src_dir} -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex ".*/HMFreg[0-9]{4}$")
 
-echo "[INFO]   Syncing logs from datastore to NAS intranet (to ${nas_loc})"
-rsync -ah --exclude "*/data/" --include "*/" --include "*.txt" --include *README --exclude "*" ${dirs_to_sync} "nas:${nas_loc}"
+echo "[INFO]   Syncing logs from datastore to NAS intranet (to ${nas_tgt_dir})"
+sshpass -p "$(cat ${pwd_loc})" rsync -ah \
+  --omit-dir-times \
+  --exclude "*/data/" \
+  --include "*/" \
+  --include "*.txt" \
+  --include *README \
+  --exclude "*" \
+  ${dirs_to_sync} \
+  "rsyncuser@nas:${nas_tgt_dir}"
 
-echo "[INFO]   Syncing pdfs from NAS share to NAS intranet (to ${reports_target})"
-ssh nas "rsync -ah --include '*.pdf' --exclude '*' ${reports_source}/ ${reports_target}/"
+echo "[INFO]   Syncing pdfs from NAS share to Datastore (to ${ds_reports_target})"
+sshpass -p "$(cat ${pwd_loc})" rsync -trh \
+  --omit-dir-times \
+  --include '*.pdf' \
+  --exclude '*' \
+  "rsyncuser@nas:${nas_reports_source}/" \
+  "${ds_reports_target}/"
 
-echo "[INFO]   Syncing pdfs from NAS share to Datastore (to ${reports_target_ds})"
-rsync -trh --include '*.pdf' --exclude '*' "nas:${reports_source}/" "${reports_target_ds}/"
+echo "[INFO]   Syncing back pdfs from Datastore to NAS intranet (to ${nas_reports_target})"
+sshpass -p "$(cat ${pwd_loc})" rsync -trh \
+  --omit-dir-times \
+  --include '*.pdf' \
+  --exclude '*' \
+  "${ds_reports_target}/" \
+  "rsyncuser@nas:${nas_reports_target}/"
 
-echo "[INFO] DONE with ${task_id}"
+echo "[INFO] Finished with task ${task_id}"
