Make V38 run possible from scripts

diff --git a/peach/compare_peach_output b/peach/compare_peach_output
--- a/peach/compare_peach_output
+++ b/peach/compare_peach_output
@@ -22,6 +22,8 @@ main() {
   local optional_peach_main_arg
   local panel_name
   local optional_panel_arg
+  local optional_reference_assembly_version_arg
+
   while [[ $# -gt 0 ]]
   do
   key=$1 && shift
@@ -42,6 +44,9 @@ main() {
       ;;
       -o|--original)
       original=true  # Optional argument
+      ;;
+      -a|--vcf_reference_assembly_version)
+      optional_reference_assembly_version_arg=" --vcf_reference_assembly_version $1" && shift  # Optional argument
       ;;
       *)    # Unknown option
       OTHER_OPTIONS+=("$key") # Save it in an array for later
@@ -71,13 +76,17 @@ main() {
   if [[ -z ${optional_panel_arg} ]]; then
     optional_panel_arg=""
   fi
+  if [[ -z ${optional_reference_assembly_version_arg} ]]; then
+    optional_reference_assembly_version_arg=""
+  fi
   
   # Sanity checks
   [[ "${#OTHER_OPTIONS[@]}" -eq 0 ]] || die "Unrecognized options! : ${OTHER_OPTIONS[*]}"
   [[ -d ${base_dir} ]] || die "base_dir should be a dir: ${base_dir}."
   
   info "Run PEACH pilot"
-  run_peach_pilot_on_subdirs "${base_dir}" "${optional_panel_arg}" "${optional_peach_main_arg}" \
+  run_peach_pilot_on_subdirs "${base_dir}" "${optional_panel_arg}" \
+      "${optional_peach_main_arg}" "${optional_reference_assembly_version_arg}" \
       || die "Could not run PEACH pilot"
   
   info "Compare PEACH output"
@@ -92,6 +101,7 @@ run_peach_pilot_on_subdirs() {
   local optional_panel_arg=$1 && shift
   local optional_recreate_bed_arg=$1 && shift
   local optional_peach_main_arg=$1 && shift
+  local optional_reference_assembly_version_arg=$1 && shift
 
   if [[ -z "${base_dir}" ]]; then
     die "Not enough arguments to ${FUNCNAME[0]}"
@@ -100,7 +110,9 @@ run_peach_pilot_on_subdirs() {
   info "Subdirs: $(ls "${base_dir}")"
   find "${base_dir}" -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 -n 1 -P "${MAX_THREADS}" -I {} \
       run_peach_pilot --rundir {} \
-      ${optional_panel_arg} ${optional_recreate_bed_arg} ${optional_peach_main_arg} || die "Could not run PEACH pilot"
+      ${optional_panel_arg} ${optional_recreate_bed_arg} \
+      ${optional_peach_main_arg} ${optional_reference_assembly_version_arg} \
+      || die "Could not run PEACH pilot"
 }
 
 compare_peach_pilot_output_to_control() {
