Clean up and adjust for separate PEACH repo

diff --git a/peach/run_peach_tests b/peach/run_peach_tests
--- a/peach/run_peach_tests
+++ b/peach/run_peach_tests
@@ -8,34 +8,35 @@ SCRIPT_NAME="$(basename "$0")"
 main() {
   info "Started ${SCRIPT_NAME}"
 
+  # Parse args
+  local key
   local peach_repo_base_dir
   local venv_dir
-
   while [[ $# -gt 0 ]]
   do
   key="$1" && shift
   case $key in
       -r|--repodir)
-      peach_repo_base_dir="$1" && shift  # optional argument
+      peach_repo_base_dir="$1" && shift  # Optional argument
       ;;
       -v|--venv)
-      venv_dir="$1" && shift  # optional argument
+      venv_dir="$1" && shift  # Optional argument
       ;;
-      *)    # unknown option
-      OTHER_OPTIONS+=("$key") # save it in an array for later
+      *)    # Unknown option
+      OTHER_OPTIONS+=("$key") # Save it in an array for later
       ;;
   esac
   done
 
-  # default values for arguments
+  # Default values for arguments
   if [[ -z ${venv_dir} ]]; then
-    venv_dir=$(locate_peach_venv_dir) || die "Could not get default venv dir" # default value
+    venv_dir=$(locate_peach_venv_dir) || die "Could not get default venv dir"
   fi
   if [[ -z ${peach_repo_base_dir} ]]; then
-    peach_repo_base_dir=$(locate_peach_repo_dir) || die "Could not get default peach repo base dir" # default value
+    peach_repo_base_dir=$(locate_peach_repo_dir) || die "Could not get default peach repo base dir"
   fi
 
-  # sanity checks
+  # Sanity checks
   [[ "${#OTHER_OPTIONS[@]}" -eq 0 ]] || die "Unrecognized options! : ${OTHER_OPTIONS[*]}"
   [[ -d ${peach_repo_base_dir} ]] || die "peach_repo_base_dir should be a dir: ${peach_repo_base_dir}."
   [[ -d ${venv_dir} ]] || die "venv_dir should be a dir: ${venv_dir}."
@@ -43,22 +44,18 @@ main() {
   info "Activate PEACH venv"
   source "${venv_dir}/bin/activate" || die "Could not activate PEACH venv"
 
+  # Add paths to environment variables
   export PYTHONPATH="${PYTHONPATH}:${peach_repo_base_dir}/src/"
   export MYPYPATH="${MYPYPATH}:${peach_repo_base_dir}/src/"
 
   info "Run PEACH tests"
-
   python -m unittest discover --buffer --verbose --start-directory "${peach_repo_base_dir}" || die "Some PEACH tests failed"
-
   info "PEACH tests succeeded"
 
-  local mypy_config="${peach_repo_base_dir}/mypy.ini"
-
   info "Run PEACH type check"
-
+  local mypy_config="${peach_repo_base_dir}/mypy.ini"
   mypy "${peach_repo_base_dir}/src" --config-file "${mypy_config}" --namespace-packages --explicit-package-bases \
           || die "PEACH type check failed"
-
   info "PEACH type check succeeded"
 
   info "Finished ${SCRIPT_NAME}"
