Use api functions to locate tumor and ref bams

diff --git a/sbp/check_storage_status_for_tumor_bam_for_set b/sbp/check_storage_status_for_tumor_bam_for_set
--- a/sbp/check_storage_status_for_tumor_bam_for_set
+++ b/sbp/check_storage_status_for_tumor_bam_for_set
@@ -2,11 +2,34 @@
 
 source api_functions
 
-set=$1 && shift
+script=$( basename $0 )
+
+usage() {
+    echo "---"
+    echo "Usage: $script -s <set> " 1>&2;
+    echo "       $script -s 170101_HMFregCPCT_etc" 1>&2;
+    echo "---"
+    exit 1
+}
+
+while getopts ":s:" o; do
+    case "${o}" in
+        s)
+            set=${OPTARG} || usage
+            ;;
+        *)
+            usage
+            ;;
+    esac
+done
+
+if [[ -z "${set}" ]]; then
+    usage
+fi
 
 run_info=$(load_run_info_for_set ${set})
 if [ -z "$run_info" ]; then
-    echo "[WARN] No run info found for set ${set}. Exiting"
+    echo "[ERROR] No run info found for set ${set}. Exiting"
     exit 1
 fi
 
diff --git a/sbp/restore_tumor_bam_from_cold_storage b/sbp/restore_tumor_bam_from_cold_storage
--- a/sbp/restore_tumor_bam_from_cold_storage
+++ b/sbp/restore_tumor_bam_from_cold_storage
@@ -2,18 +2,40 @@
 
 source api_functions
 
-set=$1 && shift
+script=$( basename $0 )
+
+usage() {
+    echo "---"
+    echo "Usage: $script -s <set> " 1>&2;
+    echo "       $script -s 170101_HMFregCPCT_etc" 1>&2;
+    echo "---"
+    exit 1
+}
+
+while getopts ":s:" o; do
+    case "${o}" in
+        s)
+            set=${OPTARG} || usage
+            ;;
+        *)
+            usage
+            ;;
+    esac
+done
+
+if [[ -z "${set}" ]]; then
+    usage
+fi
 
 run_info=$(load_run_info_for_set ${set})
 if [ -z "$run_info" ]; then
-    echo "[WARN] No run info found for set ${set}. Exiting"
+    echo "[ERROR] No run info found for set ${set}. Exiting"
     exit 1
 fi
 
 run_bucket=`echo ${run_info} | cut -d ' ' -f5`
 
-s3path="s3://${run_bucket}/${set}"
-bampath_in_bucket=$( sbp s3 ls ${s3path}/ --profile download --recursive | grep -Po "[^\s]*mapping.*T[IVX]*(_dedup)?.realigned.bam$" )
+bampath_in_bucket=$(locate_tumor_bam_for_set_in_bucket ${run_bucket} ${set})
 path_to_check=${run_bucket}/${bampath_in_bucket}
 
 echo "[INFO] Issuing restore for ${path_to_check}"
