Various changes to linx scripts and move linx running up the chain

diff --git a/sbp/process_finished_run b/sbp/process_finished_run
--- a/sbp/process_finished_run
+++ b/sbp/process_finished_run
@@ -11,19 +11,27 @@ download_path=/data/schuberg/downloaded_runs
 echo "[INFO] Downloading set ${set} to ${download_path}"
 download_set -s ${set} -p ${download_path}
 
+if [ ! -f ${download_path}/${set}/metadata ]; then
+    echo "[ERROR] No metadata file found. Probably something wrong with the downloading of the run. Exiting"
+    exit 1;
+fi
+
 processed_path=/data/schuberg/processed_runs
 echo "[INFO] Copying set ${set} to processed path ${processed_path}"
 set_path=${processed_path}/${set}
 cp -r ${download_path}/${set} ${set_path}
 
-# echo "[INFO] Running purple on ${set}"
-# do_run_purple_no_db ${set_path}
+echo "[INFO] Running purple on ${set}"
+do_run_purple_no_db ${set_path}
 
 echo "[INFO] Running viral annotation ${set}"
 do_run_gridss_viral_annotate_prod ${set_path}
 
 echo "[INFO] Running repeatmasker annotation ${set}"
 do_run_gridss_repeatmasker_insertion_annotate_prod ${set_path}
+
+echo "[INFO] Running linx for ${set}"
+do_run_linx_no_db ${set_path}
 
 echo "[INFO] Symlinking germline VCF for bachelor"
 germline_vcf_path=$( find "${set_path}" -name "*.germline.vcf.gz" )
@@ -48,9 +56,6 @@ do_load_somatic_variants_prod ${set_path}
 
 echo "[INFO] Loading structural variants into database for ${set}"
 do_run_load_sv_prod ${set_path}
-
-echo "[INFO] Running linx for ${set}"
-do_run_linx_no_db ${set_path}
 
 echo "[INFO] Loading linx into database for ${set}"
 do_run_load_linx_prod ${set_path}
