Add fallback to new somatic VCF when loading somatic variants

diff --git a/hmftools/patientdb/do_load_somatic_variants_pilot b/hmftools/patientdb/do_load_somatic_variants_pilot
--- a/hmftools/patientdb/do_load_somatic_variants_pilot
+++ b/hmftools/patientdb/do_load_somatic_variants_pilot
@@ -10,8 +10,12 @@ patient_db_jar=/data/common/tools/purple_pilot/purple.jar
 somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
 if [ $? -ne 0 ]
 then
-    echo "Unable to locate post processed somatic variants. Exiting."
-    exit 1
+    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
+    if [ $? -ne 0 ]
+    then
+        echo "Unable to locate post processed somatic variants. Exiting."
+        exit 1
+    fi
 fi
 
 sample=$(load_tumor_sample_from_metadata ${run_dir})
