remove dependency of meta data for loading somatics

diff --git a/hmftools/patientdb/load_genomic_data_for_run_into_db b/hmftools/patientdb/load_genomic_data_for_run_into_db
--- a/hmftools/patientdb/load_genomic_data_for_run_into_db
+++ b/hmftools/patientdb/load_genomic_data_for_run_into_db
@@ -8,26 +8,22 @@ prefix=`dirname $(readlink $0 || echo $0)`
 
 patient_db_jar=/data/common/tools/purple_pilot/purple.jar
 
+# TODO (KODU): Clean up after pipeline v3 does not exist anymore.
+somatic_vcf=$(ls ${run_dir}/*post_processed_v2.2.vcf.gz)
+if [ $? -ne 0 ]
+then
+    echo "Unable to locate post processed somatic variants. Exiting."
+    exit 1
+fi
+
 echo "[INFO] Loading purple data for sample ${sample} from run_dir ${run_dir}"
 ${prefix}/do_load_purple_data_request ${run_dir} ${credentials} ${patient_db_jar} ${sample}
 
-# TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
-if [ $? -ne 0 ]
-then
-    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
-    if [ $? -ne 0 ]
-    then
-        echo "Unable to locate post processed somatic variants. Exiting."
-        exit 1
-    fi
-fi
+echo "[INFO] Loading somatic variants"
+${prefix}/do_load_somatic_variants ${run_dir} ${credentials} ${patient_db_jar} ${somatic_vcf} ${sample}
 
 #echo "[INFO] Loading metrics"
 #${prefix}/do_load_metrics_data ${run_dir} ${credentials} ${patient_db_jar}
-
-#echo "[INFO] Loading somatic variants"
-#${prefix}/do_load_somatic_variants ${run_dir} ${credentials} ${patient_db_jar} ${somatic_vcf}
 
 # KODU: Skip loading SV until sv loader can use local ensembl db
 #sv_jar=/data/common/tools/variantannotator_v1.3/variant-annotator.jar
