Bump variant annotator for other databases

diff --git a/hmftools/patientdb/load_genomic_data_for_run_into_db b/hmftools/patientdb/load_genomic_data_for_run_into_db
--- a/hmftools/patientdb/load_genomic_data_for_run_into_db
+++ b/hmftools/patientdb/load_genomic_data_for_run_into_db
@@ -7,7 +7,7 @@ sample=$1 && shift
 prefix=`dirname $(readlink $0 || echo $0)`
 
 patient_db_jar=/data/common/tools/purple_v2.17/purple.jar
-sv_jar=/data/common/tools/variantannotator_v1.6/variant-annotator.jar
+sv_jar=/data/common/tools/variantannotator_v2.1/variant-annotator.jar
 
 # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
 somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
@@ -21,16 +21,17 @@ then
     fi
 fi
 
-# TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf )
-if [ $? -ne 0 ]
+gridss_filtered_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
+if [ -z ${gridss_filtered_vcf} ]; then
+    echo "[ERROR] No GRIDSS filtered somatic vcf found. Exiting."
+    exit 1
+fi
+
+structural_vcf=$(find -L ${run_dir}/purple/ -type f -name *.purple.sv.vcf.gz)
+if [ -z ${structural_vcf} ]
 then
-    structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf.gz)
-    if [ $? -ne 0 ]
-    then
-        echo "Unable to locate bpi structural variants. Exiting."
-        exit 1
-    fi
+    echo "[ERROR] Unable to locate gridss structural variants. Exiting."
+    exit 1
 fi
 
 echo "[INFO] Loading purple data"
