Update chord scripts for switch to GRIDSS

diff --git a/chord/run_chord_pilot b/chord/run_chord_pilot
--- a/chord/run_chord_pilot
+++ b/chord/run_chord_pilot
@@ -25,12 +25,18 @@ if [ $? -ne 0 ]; then
     fi
 fi
 
-mode="manta"
+mode=""
 if [ -d ${run_dir}/structuralVariants/gridss ]; then
+    filtered_somatic_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
+    if [ -z ${filtered_somatic_vcf} ]; then
+        echo "[ERROR] Gridss exists but seems like somatic filter didn't run yet. Exiting"
+        exit 1
+    fi
     mode="gridss"
     structural_vcf=$(ls ${run_dir}/purple/*.purple.sv.vcf.gz)
     echo "[INFO] Using GRIDSS mode for chord on ${structural_vcf}"
 else
+    mode="manta"
     structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf)
     if [ $? -ne 0 ]; then
         # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
@@ -40,6 +46,7 @@ else
             exit 1
         fi
     fi
+    echo "[INFO] Using MANTA mode for chord on ${structural_vcf}"
 fi
 
 # KODU: Below creates "ID_sample_mut_signatures.txt in the working_dir that is passed.
