DEV-512: Remove references to bpi and old somatic vcf

diff --git a/chord/run_chord_prod b/chord/run_chord_prod
--- a/chord/run_chord_prod
+++ b/chord/run_chord_prod
@@ -15,42 +15,27 @@ chord_dir=/data/common/tools/chord_v1.1
 working_dir="${run_dir}/chord"
 mkdir -p ${working_dir}
 
-somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
-if [ $? -ne 0 ]; then
-    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
-    if [ $? -ne 0 ]; then
-        echo "Unable to locate post processed somatic variants. Exiting."
-        exit 1
-    fi
+somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
+if [ -z ${somatic_vcf} ]; then
+    echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
+    exit 1
 fi
 
-mode=""
 if [ -d ${run_dir}/structuralVariants/gridss ]; then
     filtered_somatic_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
     if [ -z ${filtered_somatic_vcf} ]; then
         echo "[ERROR] Gridss exists but seems like somatic filter didn't run yet. Exiting"
         exit 1
     fi
-    mode="gridss"
     structural_vcf=$(ls ${run_dir}/purple/*.purple.sv.vcf.gz)
     echo "[INFO] Using GRIDSS mode for chord on ${structural_vcf}"
 else
-    mode="manta"
-    structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf)
-    if [ $? -ne 0 ]; then
-        # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-        structural_vcf=$(ls ${run_dir}/structuralVariants/bpi/*/*_somaticSV_bpi.vcf.gz)
-        if [ $? -ne 0 ]; then
-            echo "Unable to locate bpi structural variants. Exiting."
-            exit 1
-        fi
-    fi
-    echo "[INFO] Using MANTA mode for chord on ${structural_vcf}"
+    echo "[ERROR] No GRIDSS output found. Exiting"
+    exit 1
 fi
 
 # KODU: Below creates "ID_sample_mut_signatures.txt in the working_dir that is passed.
-${prefix}/extractHRDsample.R ${chord_dir} ${working_dir} ${sample} ${somatic_vcf} ${structural_vcf} ${mode}
+${prefix}/extractHRDsample.R ${chord_dir} ${working_dir} ${sample} ${somatic_vcf} ${structural_vcf}
 
 sample_mut_signatures="${sample}_sample_mut_signatures.txt"
 ${prefix}/predictHRDsample.R ${chord_dir} ${working_dir} ${sample} ${sample_mut_signatures}
diff --git a/hmftools/patientdb/do_load_somatic_variants_pilot b/hmftools/patientdb/do_load_somatic_variants_pilot
--- a/hmftools/patientdb/do_load_somatic_variants_pilot
+++ b/hmftools/patientdb/do_load_somatic_variants_pilot
@@ -7,16 +7,10 @@ run_dir=$1 && shift
 credentials=/data/common/dbs/mysql_credentials/pilot
 patient_db_jar=/data/common/tools/purple_pilot/purple.jar
 
-somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
-if [ $? -ne 0 ]
-then
-    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
-    if [ $? -ne 0 ]
-    then
-        echo "Unable to locate post processed somatic variants. Exiting."
-        exit 1
-    fi
+somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
+if [ -z ${somatic_vcf} ]; then
+    echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
+    exit 1
 fi
 
 sample=$(load_tumor_sample_from_metadata ${run_dir})
diff --git a/hmftools/patientdb/load_genomic_data_for_run_into_db b/hmftools/patientdb/load_genomic_data_for_run_into_db
--- a/hmftools/patientdb/load_genomic_data_for_run_into_db
+++ b/hmftools/patientdb/load_genomic_data_for_run_into_db
@@ -9,16 +9,10 @@ prefix=`dirname $(readlink $0 || echo $0)`
 
 sv_jar=/data/common/tools/variantannotator_v2.4/variant-annotator.jar
 
-# TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
-if [ $? -ne 0 ]
-then
-    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
-    if [ $? -ne 0 ]
-    then
-        echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
-        exit 1
-    fi
+somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
+if [ -z ${somatic_vcf} ]; then
+    echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
+    exit 1
 fi
 
 gridss_filtered_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
diff --git a/hmftools/purityploidyestimator/do_run_purple_no_db b/hmftools/purityploidyestimator/do_run_purple_no_db
--- a/hmftools/purityploidyestimator/do_run_purple_no_db
+++ b/hmftools/purityploidyestimator/do_run_purple_no_db
@@ -11,32 +11,16 @@ fi
 purple_jar=${base_path}/tools/purple_v2.17/purple.jar
 purple_output=${run_dir}/purple
 
-somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed_v2.2.vcf.gz)
-if [ -z ${somatic_vcf} ]
-then
-    # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-    somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
-    if [ -z ${somatic_vcf} ]
-    then
-        echo "Unable to locate post processed somatic variants. Exiting."
-        exit 1
-    fi
+somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
+if [ -z ${somatic_vcf} ]; then
+    echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
+    exit 1
 fi
 
-# TODO (KODU): Clean up after pipeline v3 does not exist anymore.
 structural_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
-if [ -z ${structural_vcf} ]
-then
-    structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf)
-    if [ -z ${structural_vcf} ]
-    then
-        structural_vcf=$(find -L ${run_dir}/structuralVariants/bpi/*/ -type f -name *_somaticSV_bpi.vcf.gz)
-        if [ -z ${structural_vcf} ]
-        then
-            echo "Unable to locate bpi structural variants. Exiting."
-            exit 1
-        fi
-    fi
+if [ -z ${structural_vcf} ]; then
+    echo "[ERROR] Unable to locate GRIDSS structural variants. Exiting."
+    exit 1
 fi
 
 # (LISC): Empty string is credentials of db
diff --git a/hmftools/sage/do_run_hotspot_caller b/hmftools/sage/do_run_hotspot_caller
--- a/hmftools/sage/do_run_hotspot_caller
+++ b/hmftools/sage/do_run_hotspot_caller
@@ -86,16 +86,10 @@ final_vcf=${out_dir}/../${sample}.sage.vcf.gz
 if [ ! -f ${final_vcf} ]; then
     echo "[INFO] Merging hotspot with processed -" $(date)
 
-    somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed_v2.2.vcf.gz)
-    if [ $? -ne 0 ]
-    then
-        # TODO (KODU): Clean up after pipeline v3 does not exist anymore.
-        somatic_vcf=$(ls ${run_dir}/somaticVariants/*/*post_processed.vcf.gz)
-        if [ $? -ne 0 ]
-        then
-            echo "[FATAL] Unable to locate post processed somatic variants. Exiting."
-            exit 1
-        fi
+    somatic_vcf=$(find -L ${run_dir}/somaticVariants/*/ -type f -name *post_processed.vcf.gz)
+    if [ -z ${somatic_vcf} ]; then
+        echo "[ERROR] Unable to locate post processed somatic variants. Exiting."
+        exit 1
     fi
 
     java -Xmx8G -Xms4G \
