Some cleanup

diff --git a/utilityscripts/analyze_gcp_archive_log_file b/utilityscripts/analyze_gcp_archive_log_file
--- a/utilityscripts/analyze_gcp_archive_log_file
+++ b/utilityscripts/analyze_gcp_archive_log_file
@@ -3,8 +3,7 @@
 log_file=$1 && shift
 
 if [[ -z "${log_file}" ]]; then
-    echo "[ERROR] No log file provided. Exiting"
-    exit 1
+    echo "[ERROR] No log file provided. Exiting" && exit 1
 fi
 
 echo "[INFO] Printing all log messages minus symlinks"
diff --git a/utilityscripts/monthly_patient_report_overview b/utilityscripts/monthly_patient_report_overview
--- a/utilityscripts/monthly_patient_report_overview
+++ b/utilityscripts/monthly_patient_report_overview
@@ -5,8 +5,7 @@ source locate_files
 month=$1
 
 if [[ -z "${month}" ]]; then
-    echo "[ERROR] No month provided. Exiting"
-    exit 1
+    echo "[ERROR] No month provided. Exiting" && exit 1
 fi
 
 reporting_db_tsv=$(locate_reporting_db_tsv)
