Improve sourcing of functions and use message functions

diff --git a/utilityscripts/health_check_processed_runs b/utilityscripts/health_check_processed_runs
--- a/utilityscripts/health_check_processed_runs
+++ b/utilityscripts/health_check_processed_runs
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
-source metadata_functions
+source metadata_functions || exit 1
+source message_functions || exit 1
 
 path=/data/gcp/processed_runs
 process_runs=$(ls ${path})
@@ -10,14 +11,14 @@ for run in ${process_runs}; do
 
     tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
     if [[ -f "${run_dir}/health_checker/${tumor_sample}.HealthCheckSucceeded" ]]; then
-        echo "[INFO] HealthChecker has succeeded for ${run}"
+        info "HealthChecker has succeeded for ${run}"
     elif [[ -f "${run_dir}/health_checker/${tumor_sample}.HealthCheckFailed" ]]; then
-        echo "[WARN] HealthChecker has failed for ${run}!!"
+        warn "HealthChecker has failed for ${run}!!"
     else
-        echo "[ERROR] HealthChecker has not been run for ${run}"
+        warn "HealthChecker has not been run for ${run}"
     fi
 
     # Printing purple version just for double-checking!
     purple_version=$(cat ${run_dir}/purple/purple.version | grep version)
-    echo "[INFO] This analysis has been done with purple ${purple_version}"
+    info "This analysis has been done with purple ${purple_version}"
 done
diff --git a/utilityscripts/post_process_finished_runs_failed b/utilityscripts/post_process_finished_runs_failed
--- a/utilityscripts/post_process_finished_runs_failed
+++ b/utilityscripts/post_process_finished_runs_failed
@@ -1,15 +1,16 @@
 #!/usr/bin/env bash
 
-source lims_functions
-source metadata_functions
+source lims_functions || exit 1
+source metadata_functions || exit 1
+source message_functions || exit 1
 
 health_check_processed_runs
 
-echo "[INFO] Count HealthChecker succeeded"
+info "Count HealthChecker succeeded"
 health_check_processed_runs | grep -c "HealthChecker has succeeded for"
 
 purple_version=2.53
-echo "[INFO] Count analysis purple version v${purple_version}"
+info "Count analysis purple version v${purple_version}"
 health_check_processed_runs | grep -c "This analysis has been done with purple version=${purple_version}"
 
 source_path=/data/gcp/processed_runs
@@ -21,30 +22,30 @@ for run in ${process_runs}; do
     cohort=$(find_cohort_type ${tumor_barcode})
 
     # do some jobs for all runs
-    echo "[INFO] Running PROTECT"
+    info "Running PROTECT"
     run_protect_prod ${source_path}/${run}
 
     if [[ -z ${cohort} ]]; then
-        echo "[ERROR] Could not resolve cohort for ${run}."
+        warn "Could not resolve cohort for ${run}."
     elif [[ ${cohort} == "CORELR02" || ${cohort} == "CORERI02" ]]; then
-        echo "[INFO] Moving set ${run} to /data/core/runs"
+        info "Moving set ${run} to /data/core/runs"
         mv ${source_path}/${run} /data/core/runs/
     elif [[ ${cohort} == "CPCT" || ${cohort} == "CPCTpancreas" || ${cohort} == "DRUP" || ${cohort} == "DRUPstage3" || ${cohort} == "COREDB" ]]; then
-        echo "[INFO] Moving set ${run} to /data/cpct/runs"
+        info "Moving set ${run} to /data/cpct/runs"
         mv ${source_path}/${run} /data/cpct/runs/
-        echo "[INFO] Copy run to hmf-crunch at GCP"
+        info "Copy run to hmf-crunch at GCP"
         copy_run_to_gcp_crunch_project ${run}
     else
         # This is for patients that require a summary (WIDE, some CORE)
-        echo "[INFO] Copying set ${run} to /data/cpct/reportable_runs"
+        info "Copying set ${run} to /data/cpct/reportable_runs"
         cp -R ${source_path}/${run} /data/cpct/reportable_runs/
         if [[ ${cohort} == "CORE" || ${cohort} == "CORELR11" || ${cohort} == "CORESC11" ]]; then
-            echo "[INFO] Moving set ${run} to /data/core/runs"
+            info "Moving set ${run} to /data/core/runs"
             mv ${source_path}/${run} /data/core/runs/
         elif [[ ${cohort} == "WIDE" ]]; then
-            echo "[INFO] Moving set ${run} to /data/cpct/runs"
+            info "Moving set ${run} to /data/cpct/runs"
             mv ${source_path}/${run} /data/cpct/runs/
-            echo "[INFO] Copy run to hmf-crunch at GCP"
+            info "Copy run to hmf-crunch at GCP"
             copy_run_to_gcp_crunch_project ${run}
         fi
     fi
