Bunch of consistency improvements in scripts and cleanup of SBP

diff --git a/utilityscripts/inspect_header b/utilityscripts/inspect_header
--- a/utilityscripts/inspect_header
+++ b/utilityscripts/inspect_header
@@ -2,6 +2,11 @@
 
 input_file=$1
 
+if [[ -z "${input_file}" ]]; then
+    echo "[ERROR] No input file provided. Exiting"
+    exit 1
+fi
+
 delim_char=${2:-"\t"}
 
 ## retrieve header line
diff --git a/utilityscripts/monthly_patient_report_overview b/utilityscripts/monthly_patient_report_overview
--- a/utilityscripts/monthly_patient_report_overview
+++ b/utilityscripts/monthly_patient_report_overview
@@ -4,6 +4,11 @@ source locate_files
 
 month=$1
 
+if [[ -z "${month}" ]]; then
+    echo "[ERROR] No month provided. Exiting"
+    exit 1
+fi
+
 reporting_db_tsv=$(locate_reporting_db_tsv)
 
 echo " [INFO] Creating 20_${month}_overview_tmp.tsv file"
