made out_root configurable

diff --git a/utilityscripts/tar_flowcell_bcl b/utilityscripts/tar_flowcell_bcl
--- a/utilityscripts/tar_flowcell_bcl
+++ b/utilityscripts/tar_flowcell_bcl
@@ -1,8 +1,7 @@
 #!/usr/bin/env bash
 
 path_of_dir_to_tar=$1
-
-out_root="/data2/processed"
+out_root="${2:-/data2/processed}"
 
 if [[ -z $1 || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
@@ -37,6 +36,9 @@ out_cnt_path="${out_tar_path}.content"
 out_md5_path="${out_tar_path}.md5"
 
 ## sanity checks
+if [[ ! -d "${out_root}" ]]; then
+    echo "[ERROR] Output root dir does not exist (${out_root})" && exit 1
+fi
 if [[ -e "${out_tar_path}" ]]; then
     echo "[ERROR] Provided output tar file already exists (${out_tar_path})" && exit 1
 fi
