More consistency improvements to scripts

diff --git a/datarequest/scripts/check_logs_datarequest_job b/datarequest/scripts/check_logs_datarequest_job
--- a/datarequest/scripts/check_logs_datarequest_job
+++ b/datarequest/scripts/check_logs_datarequest_job
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 
-print_usage(){
+source message_functions || exit 1
+
+print_usage() {
     echo "-----"
     echo " Descr: Checks the logs of the datarequest job"
     echo " Usage: $(basename $0) -m <metadata_tsv> -p <request_logs_path> "
@@ -19,7 +21,7 @@ while getopts ':m:p:' flag; do
 done
 
 if [[  -z "${metadata_tsv}" || -z "${request_logs_path}" ]]; then
-    echo "[ERROR] script check_logs_datarequest_job did not run, check usage below:"
+    warn "script check_logs_datarequest_job did not run, check usage below:"
     print_usage
 fi
 
@@ -37,8 +39,8 @@ request_tar_files_path=$( echo ${request_logs_path} | cut -f1,2,3,4,5 -d'/')
 request_name=$( echo ${request_logs_path} | cut -f6 -d'/')
 
 
-if [[ $( cat ${log_job} | grep "request_name_selection=" | wc -l ) >0 ]]; then
-    echo "[INFO] DATA REQUEST PREPARED FROM OLD SELECTION - EXTRA CHECK DONE:"
+if [[ $( cat ${log_job} | grep "request_name_selection=" | wc -l ) -gt 0 ]]; then
+    info "DATA REQUEST PREPARED FROM OLD SELECTION - EXTRA CHECK DONE:"
     echo "Request used for selection:"
     cat ${log_job} | grep "request_name_selection=" | cut -d "=" -f2
     dr_name=$( cat ${log_job} | grep "dr_name=" | cut -d "=" -f2 )
@@ -53,36 +55,36 @@ if [[ $( cat ${log_job} | grep "request_name_selection=" | wc -l ) >0 ]]; then
     echo ""
 fi
 
-echo "[INFO] PREPARED METADATA CHECK"
+info "PREPARED METADATA CHECK"
 if [[ $(cat ${log_job}  | grep "=1" | grep -v "somatics" | grep -v "germline" | grep -v "version=" | wc -l ) >0 ]]; then
     requested_metadata=$( cat ${log_job}  | grep "=1" | grep -v "somatics" | grep -v "germline" | grep -v "version=" |wc -l )
     log_metadata_name=$( ls ${request_logs_path} | grep 'metadata.log' )
     log_metadata=$"${request_logs_path}${log_metadata_name}"
     entries_metadata=$( expr $( cat ${log_job} | grep ".metadata.tar" | grep "entries"| sed -nr 's/.*( |^)([0-9]+) entries.*/\2/p' ) - 1 )
     lines_metadata_tar_log=$( expr $( cat ${log_metadata} | wc -l) - 1 )
-    if [[ $( cat ${log_job}  | grep "include_patient_clinical_data=1" | wc -l ) >0 ]]; then
+    if [[ $(cat ${log_job}  | grep -c "include_patient_clinical_data=1") -gt 0 ]]; then
         entries_metadata=$( expr $( echo ${entries_metadata} ) + 1 )
         lines_metadata_tar_log=$( expr $( echo ${lines_metadata_tar_log}) + 1 )
     fi
-    if [[ $( cat ${log_job}  | grep "include_treatment_response_clinical_data=1" | wc -l ) >0 ]]; then
+    if [[ $(cat ${log_job}  | grep -c "include_treatment_response_clinical_data=1") -gt 0 ]]; then
         entries_metadata=$( expr $( echo ${entries_metadata} ) - 1 )
         lines_metadata_tar_log=$( expr $( echo ${lines_metadata_tar_log}) - 1 )
     fi
-    echo "[INFO] ${requested_metadata}  types of metadata requested:"
+    info "${requested_metadata}  types of metadata requested:"
     cat ${log_job}  | grep "=1" | grep -v "somatics" | grep -v "germline" | grep -v "version="
     #check numbers.
     if [[ ${requested_metadata} != ${entries_metadata} || ${requested_metadata} != ${lines_metadata_tar_log} ]]; then
-        echo "[ERROR] The number of extra types of requested metadata (${requested_metadata}) does not match the number of extra entries created during the datarequest job. Check the log  file(s) (log of the create job and/or tar_DR-XXX_somatics.log) under: ${request_logs_path}."
+        warn "The number of extra types of requested metadata (${requested_metadata}) does not match the number of extra entries created during the datarequest job. Check the log  file(s) (log of the create job and/or tar_DR-XXX_somatics.log) under: ${request_logs_path}."
     else
-        echo "[INFO] The number of extra types of requested metadata (${requested_metadata}) matches the number of entries created during the datarequest job."
+        info "The number of extra types of requested metadata (${requested_metadata}) matches the number of entries created during the datarequest job."
     fi
     du -sh "${request_tar_files_path}/${request_name}.metadata.tar"
 else
-    echo "[INFO] No metadata prepared in datarequest job"
+    info "No metadata prepared in datarequest job"
 fi
 echo ""
 
-echo "[INFO] PREPARED SOMATIC DATA CHECK"
+info "PREPARED SOMATIC DATA CHECK"
 if [[ $(cat ${log_job}  | grep "=1" | grep "somatics") != "" ]]; then
     cat ${log_job} | grep ". Found" | grep "samples" | grep "somatics"
     entries_somatic=$( expr $( cat ${log_job} | grep ".somatics.tar" | grep "entries"| sed -nr 's/.*( |^)([0-9]+) entries.*/\2/p' ) - 1 )
@@ -91,25 +93,25 @@ if [[ $(cat ${log_job}  | grep "=1" | grep "somatics") != "" ]]; then
     log_somatic=$"${request_logs_path}${log_somatic_name}"
     lines_somatic_tar_log=$(expr  $( cat ${log_somatic} | wc -l) - 1)
     calc_somatic_tar_log=$(expr  ${lines_somatic_tar_log} / 30 )
-    echo "[INFO] ${number_samples_metadata} number of samples requested"
-    echo "[INFO] 30 entries (1 base folder + 2 subfolders (linx,purple) + 27 files) per sample."
+    info "${number_samples_metadata} number of samples requested"
+    info "30 entries (1 base folder + 2 subfolders (linx,purple) + 27 files) per sample."
     #check numbers.
     if [[ ${number_samples_metadata} != ${calc_somatic} || ${number_samples_metadata} != ${calc_somatic_tar_log} ]]; then
-        echo "[ERROR] The number of samples requested (${number_samples_metadata}) does not match the number of somatic entries created during the datarequest job (${calc_somatic} (${entries_somatic} entries log) / ${calc_somatic_tar_log} (${lines_somatic_tar_log} entries tar log)). Check the log file(s) under: ${request_logs_path}."
+        warn "The number of samples requested (${number_samples_metadata}) does not match the number of somatic entries created during the datarequest job (${calc_somatic} (${entries_somatic} entries log) / ${calc_somatic_tar_log} (${lines_somatic_tar_log} entries tar log)). Check the log file(s) under: ${request_logs_path}."
     else
-        echo "[INFO] The number of samples requested (${number_samples_metadata}) matches the number of somatic entries created during the datarequest job."
+        info "The number of samples requested (${number_samples_metadata}) matches the number of somatic entries created during the datarequest job."
     fi
     if [[ $(cat ${log_somatic} | grep germline) != "" ]]; then
-        echo "[ERROR] In the somatic data there is a file  included with germline in the name, please check below:"
+        warn "In the somatic data there is a file  included with germline in the name, please check below:"
         cat ${log_somatic} | grep germline
     fi
     du -sh "${request_tar_files_path}/${request_name}.somatics.tar"
 else
-    echo "[INFO] No somatic data prepared in datarequest job"
+    info "No somatic data prepared in datarequest job"
 fi
 echo ""
 
-echo "[INFO] PREPARED GERMLINE DATA CHECK"
+info "PREPARED GERMLINE DATA CHECK"
 if [[ $(cat ${log_job}  | grep "=1" | grep "germline") != "" ]]; then
     cat ${log_job} | grep ". Found" | grep "samples" | grep "germline"
     entries_germline=$( expr $( cat ${log_job} | grep ".germline.tar" | grep "entries"| sed -nr 's/.*( |^)([0-9]+) entries.*/\2/p' ) - 1 )
@@ -118,28 +120,28 @@ if [[ $(cat ${log_job}  | grep "=1" | grep "germline") != "" ]]; then
     log_germline=$"${request_logs_path}${log_germline_name}"
     lines_germline_tar_log=$(expr  $( cat ${log_germline} | wc -l) - 1)
     calc_germline_tar_log=$(expr  ${lines_germline_tar_log} / 6)
-    echo "[INFO] ${number_samples_metadata} number of samples requested"
-    echo "[INFO] 6 entries (1 base folder + 2 subfolders (gatk,purple) + 3 files) per sample."
+    info "${number_samples_metadata} number of samples requested"
+    info "6 entries (1 base folder + 2 subfolders (gatk,purple) + 3 files) per sample."
     #check numbers.
     if [[ ${number_samples_metadata} != ${calc_germline} || ${number_samples_metadata} != ${calc_germline_tar_log} ]]; then
-        echo "[ERROR] The number of samples requested (${number_samples_metadata}) does not match the number of germline entries created during the datarequest job (${calc_germline} (${entries_germline} entries log) / ${calc_germline_tar_log} (${lines_germline_tar_log} entries tar log)). Check the log file(s) under: ${request_logs_path}."
+        warn "The number of samples requested (${number_samples_metadata}) does not match the number of germline entries created during the datarequest job (${calc_germline} (${entries_germline} entries log) / ${calc_germline_tar_log} (${lines_germline_tar_log} entries tar log)). Check the log file(s) under: ${request_logs_path}."
     else
-        echo "[INFO] The number of samples requested (${number_samples_metadata}) matches the number of germline entries created during the datarequest job."
+        info "The number of samples requested (${number_samples_metadata}) matches the number of germline entries created during the datarequest job."
     fi
     du -sh "${request_tar_files_path}/${request_name}.germline.tar"
 else
-    echo "[INFO] No germline data prepared in datarequest job"
+    info "No germline data prepared in datarequest job"
 fi
 echo ""
 
-
 if [[ $( cat ${log_job} | grep "tar: " ) != "" || $( cat ${log_job} | grep "WARN" ) != "" || $( cat ${log_job} | grep "ERROR" ) != "" ]]; then
-    echo "[ERROR] WARNINGS/ERRORS IN LOG FILES:"
+    warn "WARNINGS/ERRORS IN LOG FILES:"
     cat ${log_job} | grep "tar: "
     cat ${log_job} | grep "WARN"
     cat ${log_job} | grep "ERROR"
 else
-    echo "[INFO] NO WARNINGS/ERRORS IN LOG FILES."
+    info "NO WARNINGS/ERRORS IN LOG FILES."
 fi
+
 echo ""
 echo ""
diff --git a/datarequest/scripts/collect_all_amber_data_for_request b/datarequest/scripts/collect_all_amber_data_for_request
--- a/datarequest/scripts/collect_all_amber_data_for_request
+++ b/datarequest/scripts/collect_all_amber_data_for_request
@@ -2,6 +2,8 @@
 
 # NOTE: This script is not used typically in production. Has been added as one-off.
 
+source message_functions || exit 1
+
 metadata_tsv=$1 && shift
 amber_dir=$1 && shift
 
@@ -14,18 +16,18 @@ cat ${metadata_tsv} | grep -v "^#" | cut -f3 | while read set_name; do
     if [[ ! -f "${amber_baf_file}" ]]; then
         amber_baf_file=$(find -L ${source_set_path}/amber -type f -name "*.amber.baf")
         if [[ ! -f "${amber_baf_file}" ]]; then
-            echo "[WARN] Could not resolve amber BAF file for ${set_name}"
+            warn "Could not resolve amber BAF file for ${set_name}"
         fi
     fi
 
     ## start symlinking
-    echo "[DEBUG] Symlinking amber files for ${set_name}"
+    info "Symlinking amber files for ${set_name}"
     ln -s ${amber_baf_file} ${dest_set_path}
     ln -s ${source_set_path}/amber/*.amber.baf.pcf ${dest_set_path}
 
     amber_file_count=$(ls ${dest_set_path} | wc -l)
 
     if [[ ${amber_file_count} -ne 2 ]]; then
-        echo "[WARN]: Mismatch in expected file count. Expected 2 files but got ${amber_file_count} files for ${set_name}. Please inspect manually!"
+        warn "Mismatch in expected file count. Expected 2 files but got ${amber_file_count} files for ${set_name}. Please inspect manually!"
     fi
 done
diff --git a/datarequest/scripts/collect_all_cobalt_data_for_request b/datarequest/scripts/collect_all_cobalt_data_for_request
--- a/datarequest/scripts/collect_all_cobalt_data_for_request
+++ b/datarequest/scripts/collect_all_cobalt_data_for_request
@@ -2,6 +2,8 @@
 
 # NOTE: This script is not used typically in production. Has been added as one-off.
 
+source message_functions || exit 1
+
 metadata_tsv=$1 && shift
 cobalt_dir=$1 && shift
 
@@ -14,18 +16,18 @@ cat ${metadata_tsv} | grep -v "^#" | cut -f3 | while read set_name; do
     if [[ ! -f "${cobalt_ratio_file}" ]]; then
         cobalt_ratio_file=$(find -L ${source_set_path}/cobalt -type f -name "*.cobalt")
         if [[ ! -f "${cobalt_ratio_file}" ]]; then
-            echo "[WARN] Could not resolve cobalt ratio file for ${set_name}"
+            warn "Could not resolve cobalt ratio file for ${set_name}"
         fi
     fi
 
     ## start symlinking
-    echo "[DEBUG] Symlinking cobalt files for ${set_name}"
+    info "Symlinking cobalt files for ${set_name}"
     ln -s ${cobalt_ratio_file} ${dest_set_path}
     ln -s ${source_set_path}/cobalt/*.cobalt.ratio.pcf ${dest_set_path}
 
     cobalt_file_count=$(ls ${dest_set_path} | wc -l)
 
     if [[ ${cobalt_file_count} -ne 3 ]]; then
-        echo "[WARN]: Mismatch in expected file count. Expected 3 files but got ${cobalt_file_count} files for ${set_name}. Please inspect manually!"
+        warn "Mismatch in expected file count. Expected 3 files but got ${cobalt_file_count} files for ${set_name}. Please inspect manually!"
     fi
 done
diff --git a/datarequest/scripts/collect_all_flagstats_for_request b/datarequest/scripts/collect_all_flagstats_for_request
--- a/datarequest/scripts/collect_all_flagstats_for_request
+++ b/datarequest/scripts/collect_all_flagstats_for_request
@@ -2,8 +2,9 @@
 
 # NOTE: This script is not used typically in production. Has been added as one-off.
 
-source metadata_functions;
-source locate_files;
+source locate_files || exit 1
+source metadata_functions || exit 1
+source message_functions || exit 1
 
 metadata_tsv=$1 && shift
 flagstat_dir=$1 && shift
@@ -17,18 +18,18 @@ cat ${metadata_tsv} | grep -v "^#" | cut -f3 | while read set_name; do
     tumor_sample=$(load_tumor_sample_from_metadata ${source_set_path})
 
     flagstat_ref_file=$(locate_flagstats ${source_set_path} ${ref_sample})
-    if [[ $? = 1 ]]; then echo "[WARN]  Could not locate flagstat ref file for ${source_set_path}"; fi
+    if [[ $? = 1 ]]; then warn " Could not locate flagstat ref file for ${source_set_path}"; fi
     flagstat_tumor_file=$(locate_flagstats ${source_set_path} ${tumor_sample})
-    if [[ $? = 1 ]]; then echo "[WARN]  Could not locate flagstat tumor file for ${source_set_path}"; fi
+    if [[ $? = 1 ]]; then warn " Could not locate flagstat tumor file for ${source_set_path}"; fi
 
     ## start symlinking
-    echo "[DEBUG] Symlinking flagstats files for ${set_name}"
+    info "Symlinking flagstats files for ${set_name}"
     ln -s ${flagstat_ref_file} ${dest_set_path}
     ln -s ${flagstat_tumor_file} ${dest_set_path}
 
     flagstats_file_count=$(ls ${dest_set_path} | wc -l)
 
     if [[ ${flagstats_file_count} -ne 2 ]]; then
-        echo "[WARN] Mismatch in expected file count. Expected 2 files but got ${flagstats_file_count} files for ${set_name}. Please inspect manually!"
+        warn "Mismatch in expected file count. Expected 2 files but got ${flagstats_file_count} files for ${set_name}. Please inspect manually!"
     fi
 done
diff --git a/datarequest/scripts/collect_all_isofox_data_for_request b/datarequest/scripts/collect_all_isofox_data_for_request
--- a/datarequest/scripts/collect_all_isofox_data_for_request
+++ b/datarequest/scripts/collect_all_isofox_data_for_request
@@ -2,6 +2,8 @@
 
 # NOTE: This script is not used typically in production. Has been added as one-off.
 
+source message_functions || exit 1
+
 metadata_tsv=$1 && shift
 isofox_dir=$1 && shift
 
@@ -20,16 +22,16 @@ cat ${metadata_tsv} | grep -v "^#" | cut -f2 | while read sample_name; do
             mkdir -p ${dest_set_path}
 
             ## start symlinking
-            echo "[DEBUG] Symlinking isofox files for ${sample_name}"
+            info "Symlinking isofox files for ${sample_name}"
             ln -s ${gene_data_csv} ${dest_set_path}
             ln -s ${transcript_data_csv} ${dest_set_path}
             ln -s ${fusions_csv} ${dest_set_path}
             #ln -s ${alt_splice_junc_csv} ${dest_set_path}
             #ln -s ${retained_intron_csv} ${dest_set_path}
         else
-            echo "[WARN] Either gene or transcript data missing for ${sample_name}"
+            warn "Either gene or transcript data missing for ${sample_name}"
         fi
     else
-        echo "[DEBUG] No isofox files found for ${sample_name}. Skipping."
+        info "No isofox files found for ${sample_name}. Skipping."
     fi
 done
diff --git a/datarequest/scripts/collect_all_linx_data_for_request b/datarequest/scripts/collect_all_linx_data_for_request
--- a/datarequest/scripts/collect_all_linx_data_for_request
+++ b/datarequest/scripts/collect_all_linx_data_for_request
@@ -2,6 +2,8 @@
 
 # NOTE: This script is not used typically in production. Has been added as one-off.
 
+source message_functions || exit 1
+
 metadata_tsv=$1 && shift
 linx_dir=$1 && shift
 
@@ -15,7 +17,7 @@ cat ${metadata_tsv} | grep -v "^#" | cut -f3 | while read set_name; do
         linx_version=$(cat ${linx_version_file} | grep version)
 
         ## start symlinking
-        echo "[DEBUG] Symlinking linx files for ${set_name} having linx '${linx_version}'"
+        info "Symlinking linx files for ${set_name} having linx '${linx_version}'"
         ln -s ${source_set_path}/linx/linx.version ${dest_set_path}
 
         linx_driver_catalog_file=$(find -L ${source_set_path}/linx -type f -name "*.driver.catalog.tsv")
@@ -44,6 +46,6 @@ cat ${metadata_tsv} | grep -v "^#" | cut -f3 | while read set_name; do
         ln -s ${source_set_path}/linx/*.linx.vis_segments.tsv ${dest_set_path}
         ln -s ${source_set_path}/linx/*.linx.vis_sv_data.tsv ${dest_set_path}
     else
-        echo "[WARN] Could not determine linx version for ${set_name}. Skipping."
+        warn "Could not determine linx version for ${set_name}. Skipping."
     fi
 done
diff --git a/datarequest/scripts/compose_datarequest b/datarequest/scripts/compose_datarequest
--- a/datarequest/scripts/compose_datarequest
+++ b/datarequest/scripts/compose_datarequest
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 if [[ "$#" -ne 15 ]]; then
     echo "Usage: $(basename $0)"
     echo "      - dr_name (eg DR-028)"
@@ -42,36 +44,36 @@ base_path=/data/data_archive/datarequests
 dr_base_path=${base_path}/${dr_name}
 dr_path=${dr_base_path}/${request_name}
 
-echo "[INFO] Composing data request ${request_name} in ${dr_path}"
-echo "[INFO]    dr_name=${dr_name}"
-echo "[INFO]    request_name=${request_name}"
-echo "[INFO]    patient_selection_sql=${patient_selection_sql}"
-echo "[INFO]    include_somatics=${include_somatics}"
-echo "[INFO]    include_germline=${include_germline}"
-echo "[INFO]    include_tumor_bam_jsons=${include_tumor_bam_jsons}"
-echo "[INFO]    include_ref_bam_jsons=${include_ref_bam_jsons}"
-echo "[INFO]    include_rna=${include_rna}"
-echo "[INFO]    build_rna_tar=${build_rna_tar}"
-echo "[INFO]    include_tumor_clinical_data=${include_tumor_clinical_data}"
-echo "[INFO]    include_patient_clinical_data=${include_patient_clinical_data}"
-echo "[INFO]    include_treatment_response_clinical_data=${include_treatment_response_clinical_data}"
-echo "[INFO]    include_pre_treatment_clinical_data=${include_pre_treatment_clinical_data}"
-echo "[INFO]    include_rano_measurement_by_patient=${include_rano_measurement_by_patient}"
-echo "[INFO]    include_tumor_markers_by_patient=${include_tumor_markers_by_patient}"
+info "Composing data request ${request_name} in ${dr_path}"
+info "   dr_name=${dr_name}"
+info "   request_name=${request_name}"
+info "   patient_selection_sql=${patient_selection_sql}"
+info "   include_somatics=${include_somatics}"
+info "   include_germline=${include_germline}"
+info "   include_tumor_bam_jsons=${include_tumor_bam_jsons}"
+info "   include_ref_bam_jsons=${include_ref_bam_jsons}"
+info "   include_rna=${include_rna}"
+info "   build_rna_tar=${build_rna_tar}"
+info "   include_tumor_clinical_data=${include_tumor_clinical_data}"
+info "   include_patient_clinical_data=${include_patient_clinical_data}"
+info "   include_treatment_response_clinical_data=${include_treatment_response_clinical_data}"
+info "   include_pre_treatment_clinical_data=${include_pre_treatment_clinical_data}"
+info "   include_rano_measurement_by_patient=${include_rano_measurement_by_patient}"
+info "   include_tumor_markers_by_patient=${include_tumor_markers_by_patient}"
 
 create_base_directory_for_datarequest ${dr_path}
 if [[ $? = 0 ]]; then
     log_dir=${dr_path}/logs
     mkdir -p ${log_dir}
 
-    echo "[INFO] Selecting patients to include for ${request_name}..."
+    info "Selecting patients to include for ${request_name}..."
     cp ${patient_selection_sql} ${log_dir}/selectPatients.sql
     patient_selection_tsv=${log_dir}/selectPatients.tsv
     execute_sql_on_old_prod ${log_dir}/selectPatients.sql > ${patient_selection_tsv}
     patient_count=$(grep -cv "^#" ${patient_selection_tsv})
-    echo "[INFO] Created ${patient_selection_tsv} with ${patient_count} patients"
+    info "Created ${patient_selection_tsv} with ${patient_count} patients"
 
-    echo "[INFO] Creating metadata for ${request_name}..."
+    info "Creating metadata for ${request_name}..."
     metadata_dir_name=metadata
     metadata_dir=${dr_path}/${metadata_dir_name}
     mkdir -p ${metadata_dir}
@@ -90,120 +92,120 @@ if [[ $? = 0 ]]; then
     fi
 
     sample_count=$(grep -cv "^#" ${metadata_tsv})
-    echo "[INFO] Created ${metadata_tsv} with ${sample_count} samples"
+    info "Created ${metadata_tsv} with ${sample_count} samples"
 
     if [[ ${include_somatics} == "1" ]]; then
-        echo "[INFO] Collecting somatic data for ${request_name}..."
+        info "Collecting somatic data for ${request_name}..."
         somatic_dir_name=somatics
         somatics_dir=${dr_path}/${somatic_dir_name}
         mkdir -p ${somatics_dir}
         collect_all_somatic_set_data_for_request ${metadata_tsv} ${somatics_dir} ${include_germline}
         somatics_sample_count=$(ls ${somatics_dir} | wc -l)
         somatic_tar_file=${dr_base_path}/${request_name}.somatics.tar
-        echo "[INFO] Done collecting somatics for DR. Found ${somatics_sample_count} samples. Creating TAR at ${somatic_tar_file}"
+        info "Done collecting somatics for DR. Found ${somatics_sample_count} samples. Creating TAR at ${somatic_tar_file}"
         create_tar_file ${somatic_tar_file} ${dr_path} ./${somatic_dir_name} ${log_dir}/tar_${request_name}_somatics.log
     else
-        echo "[INFO] Skipped somatics collection as not deemed relevant for ${request_name}"
+        info "Skipped somatics collection as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_germline} == "1" ]]; then
-        echo "[INFO] Collecting germline data for ${request_name}..."
+        info "Collecting germline data for ${request_name}..."
         germline_dir_name=germline
         germline_dir=${dr_path}/${germline_dir_name}
         mkdir -p ${germline_dir}
         collect_all_germline_set_data_for_request ${metadata_tsv} ${germline_dir}
         germline_sample_count=$(ls ${germline_dir} | wc -l)
         germline_tar_file=${dr_base_path}/${request_name}.germline.tar
-        echo "[INFO] Done collecting germline data for DR. Found ${germline_sample_count} samples. Creating TAR at ${germline_tar_file}"
+        info "Done collecting germline data for DR. Found ${germline_sample_count} samples. Creating TAR at ${germline_tar_file}"
         create_tar_file ${germline_tar_file} ${dr_path} ./${germline_dir_name} ${log_dir}/tar_${request_name}_germline.log
     else
-        echo "[INFO] Skipped germline collection as not deemed relevant for ${request_name}"
+        info "Skipped germline collection as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_tumor_bam_jsons} == "1" ]]; then
-        echo "[INFO] Creating tumor bam share jsons for ${request_name}..."
+        info "Creating tumor bam share jsons for ${request_name}..."
         base_json_dir=${dr_path}/logs/json
         mkdir -p ${base_json_dir}
         create_tumor_bam_share_jsons_for_datarequest ${metadata_tsv} ${dr_name} ${base_json_dir}
-        echo "[INFO] Done creating tumor bam share jsons for DR."
+        info "Done creating tumor bam share jsons for DR."
     else
-        echo "[INFO] Skipped tumor bam share json creation as not deemed relevant for ${request_name}"
+        info "Skipped tumor bam share json creation as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_ref_bam_jsons} == "1" ]]; then
-        echo "[INFO] Creating reference bam share jsons for ${request_name}..."
+        info "Creating reference bam share jsons for ${request_name}..."
         base_json_dir=${dr_path}/logs/json
         mkdir -p ${base_json_dir}
         create_reference_bam_share_jsons_for_datarequest ${metadata_tsv} ${dr_name} ${base_json_dir}
-        echo "[INFO] Done creating reference bam share jsons for DR"
+        info "Done creating reference bam share jsons for DR"
     else
-        echo "[INFO] Skipped reference bam share json creation as not deemed relevant for ${request_name}"
+        info "Skipped reference bam share json creation as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_rna} == "1" ]]; then
-        echo "[INFO] Collecting RNA seq for ${request_name}..."
+        info "Collecting RNA seq for ${request_name}..."
         rnaseq_dir_name=rnaseq
         rnaseq_dir=${dr_path}/${rnaseq_dir_name}
         mkdir -p ${rnaseq_dir}
         collect_all_rna_data_for_request ${metadata_tsv} ${rnaseq_dir}
         rna_sample_count=$(ls ${rnaseq_dir} | wc -l)
-        echo "[INFO] Done collecting RNA seq for DR. Found ${rna_sample_count} samples"
+        info "Done collecting RNA seq for DR. Found ${rna_sample_count} samples"
 
         if [[ ${build_rna_tar} == "1" ]]; then
             rna_tar_file=${dr_base_path}/${request_name}.rnaseq.tar
-            echo "[INFO] Creating RNA TAR file at ${rna_tar_file}"
+            info "Creating RNA TAR file at ${rna_tar_file}"
             create_tar_file ${rna_tar_file} ${dr_path} ./${rnaseq_dir_name} ${log_dir}/tar_${request_name}_rnaseq.log
         else
-            echo "[INFO] Skipping RNA TAR file creation!"
+            info "Skipping RNA TAR file creation!"
         fi
     else
-        echo "[INFO] Skipped RNA selection as not deemed relevant for ${request_name}"
+        info "Skipped RNA selection as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_treatment_response_clinical_data} == "1" ]]; then
-        echo "[INFO] Creating treatment and response clinical data for ${request_name}..."
+        info "Creating treatment and response clinical data for ${request_name}..."
         generate_post_biopsy_drugs_by_sample ${patient_selection_tsv} ${log_dir} ${metadata_dir}
         generate_responses_by_sample ${patient_selection_tsv} ${log_dir} ${metadata_dir}
-        echo "[INFO] Done creating response clinical data for DR"
+        info "Done creating response clinical data for DR"
     else
-        echo "[INFO] Skipped generation of response clinical data as not deemed relevant for ${request_name}"
+        info "Skipped generation of response clinical data as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_pre_treatment_clinical_data} == "1" ]]; then
-        echo "[INFO] Creating pre-biopsy treatment data for ${request_name}..."
+        info "Creating pre-biopsy treatment data for ${request_name}..."
         generate_pre_biopsy_drugs_by_patient ${patient_selection_tsv} ${log_dir} ${metadata_dir}
-        echo "[INFO] Done creating pre-biopsy treatment data for DR"
+        info "Done creating pre-biopsy treatment data for DR"
     else
-        echo "[INFO] Skipped generation of pre-biopsy treatment data as not deemed relevant for ${request_name}"
+        info "Skipped generation of pre-biopsy treatment data as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_rano_measurement_by_patient} == "1" ]]; then
-        echo "[INFO] Creating RANO measurements for ${request_name}..."
+        info "Creating RANO measurements for ${request_name}..."
         generate_rano_measurements_by_patient ${patient_selection_tsv} ${log_dir} ${metadata_dir}
-        echo "[INFO] Done creating RANO measurements for DR"
+        info "Done creating RANO measurements for DR"
     else
-        echo "[INFO] Skipped generation of RANO measurement data as not deemed relevant for ${request_name}"
+        info "Skipped generation of RANO measurement data as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_tumor_markers_by_patient} == "1" ]]; then
-        echo "[INFO] Creating tumor markers for ${request_name}..."
+        info "Creating tumor markers for ${request_name}..."
         generate_tumor_markers_by_patient ${patient_selection_tsv} ${log_dir} ${metadata_dir}
-        echo "[INFO] Done creating tumor markers for DR"
+        info "Done creating tumor markers for DR"
     else
-        echo "[INFO] Skipped generation of tumor markers as not deemed relevant for ${request_name}"
+        info "Skipped generation of tumor markers as not deemed relevant for ${request_name}"
     fi
 
     metadata_tar_file=${dr_base_path}/${request_name}.metadata.tar
-    echo "[INFO] Creating metadata TAR file at ${metadata_tar_file}"
+    info "Creating metadata TAR file at ${metadata_tar_file}"
     create_tar_file ${metadata_tar_file} ${dr_path} ./${metadata_dir_name} ${log_dir}/tar_${request_name}_metadata.log
 
     if [[ ${include_ref_bam_jsons} == "1" || ${include_tumor_bam_jsons} == "1" ]]; then
-        echo "[INFO] Make sure to run 'refresh_all_shares_for_datarequest ${dr_name} ${request_name}' as sbpext to register the JSONs!"
+        info "Make sure to run 'refresh_all_shares_for_datarequest ${dr_name} ${request_name}' as sbpext to register the JSONs!"
     fi
 
-    echo "[INFO] Composing datarequest for ${request_name} completed!"
+    info "Composing datarequest for ${request_name} completed!"
 else
-    echo "[ERROR] Could not create base directory structure for DR ${dr_name}"
+    error "Could not create base directory structure for DR ${dr_name}"
 fi
 
 
diff --git a/datarequest/scripts/create_reference_bam_share_jsons_for_datarequest b/datarequest/scripts/create_reference_bam_share_jsons_for_datarequest
--- a/datarequest/scripts/create_reference_bam_share_jsons_for_datarequest
+++ b/datarequest/scripts/create_reference_bam_share_jsons_for_datarequest
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 metadata_tsv=$1 && shift
 # Entity name should generally match dr name (eg "DR-028")
 entity_name=$1 && shift
@@ -11,10 +13,10 @@ cat ${metadata_tsv} | grep -v "^#" | cut -f3 | while read set_name; do
 
     if [[ ! -z "${set_id}" ]]; then
         reference_bam_json=${base_json_dir}/${set_name}_ref_bam.json
-        echo "[DEBUG] Creating ${reference_bam_json}"
+        info "Creating ${reference_bam_json}"
 
         create_share_json_for_reference_bam ${set_id} ${entity_id} > ${reference_bam_json}
     else
-        echo "[WARN] Could not find set_id for ${set_name}. Skipping reference bam share creation!"
+        warn "Could not find set_id for ${set_name}. Skipping reference bam share creation!"
     fi
 done
diff --git a/datarequest/scripts/generate_metadata b/datarequest/scripts/generate_metadata
--- a/datarequest/scripts/generate_metadata
+++ b/datarequest/scripts/generate_metadata
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 prefix=$(dirname $(readlink $0 || echo $0))
 
 patient_selection_tsv=$1 && shift
@@ -13,26 +15,26 @@ sql=""
 
 if [[ ${include_patient_clinical_data} == "1" ]]; then
     if [[ ${include_tumor_clinical_data} == "0" ]]; then
-        echo "[DEBUG] Generating metadata with patient fields"
+        info "Generating metadata with patient fields"
         sql="sql_metadata_patient.sql"
     elif [[ ${include_treatment_response_clinical_data} == "1" ]]; then
-        echo "[DEBUG] Generating metadata with tumor, patient and treatment fields"
+        info "Generating metadata with tumor, patient and treatment fields"
         sql="sql_metadata_tumor_patient_treatment.sql"
     else
-        echo "[DEBUG] Generating metadata for with tumor and patient fields"
+        info "Generating metadata for with tumor and patient fields"
         sql="sql_metadata_tumor_patient.sql"
     fi
 #elif [[ ${include_treatment_response_clinical_data} == "1" ]]; then
-#    echo "[ERROR] Cannot include treatment data without including patient data! Exiting."
+#    error "Cannot include treatment data without including patient data! Exiting."
 #    exit 1
 elif [[ ${include_treatment_response_clinical_data} == "1" ]]; then
-        echo "[DEBUG] Generating metadata with tumor and treatment fields"
-        sql="sql_metadata_tumor_treatment.sql"
+    info "Generating metadata with tumor and treatment fields"
+    sql="sql_metadata_tumor_treatment.sql"
 elif [[ ${include_tumor_clinical_data} == "1" ]]; then
-    echo "[DEBUG] Generating metadata for with tumor fields"
+    info "Generating metadata for with tumor fields"
     sql="sql_metadata_tumor.sql"
 else
-    echo "[INFO] Generating metadata for with no clinical fields"
+    info "Generating metadata for with no clinical fields"
     sql="sql_metadata_none.sql"
 fi
 
diff --git a/hmftools/purple/do_run_purple b/hmftools/purple/do_run_purple
--- a/hmftools/purple/do_run_purple
+++ b/hmftools/purple/do_run_purple
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
-source locate_files
-source metadata_functions
+source locate_files || exit 1
+source metadata_functions || exit 1
+source message_functions || exit 1
 
 run_dir=$1 && shift
 purple_jar=$1 && shift
@@ -16,23 +17,19 @@ tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
 amber_dir=$(locate_amber_directory ${run_dir})
 
 if [[ ! -d "${amber_dir}" ]]; then
-    echo "[ERROR] Unable to locate AMBER data. Exiting."
-    exit 1
+    error "Unable to locate AMBER data. Exiting."
 fi
 
 if [[ ! -f "${somatic_vcf}" ]]; then
-    echo "[ERROR] Unable to locate somatic variants. Exiting."
-    exit 1
+    error "Unable to locate somatic variants. Exiting."
 fi
 
 if [[ ! -f "${structural_vcf}" ]]; then
-    echo "[ERROR] Unable to locate structural variants. Exiting."
-    exit 1
+    error "Unable to locate structural variants. Exiting."
 fi
 
 if [[ ! -f "${sv_recovery_vcf}" ]]; then
-    echo "[ERROR] Unable to locate sv recovery variants. Exiting."
-    exit 1
+    error "Unable to locate sv recovery variants. Exiting."
 fi
 
 if [[ -d "${purple_output_dir}" ]]; then
@@ -40,8 +37,7 @@ if [[ -d "${purple_output_dir}" ]]; then
 else
     mkdir -p "${purple_output_dir}"
     if [[ $? = 1 ]]; then
-        echo "[ERROR] Could not create directory ${purple_output_dir}. Exiting."
-        exit 1
+        error "Could not create directory ${purple_output_dir}. Exiting."
     fi
 fi
 
@@ -65,7 +61,7 @@ if [[ ! -z "${credentials}" ]]; then
     db_args="-db_enabled -db_user ${db_user} -db_pass ${db_pass} -db_url ${db_url}"
 fi
 
-echo "[INFO] Running purple for ${tumor_sample}"
+info "Running purple for ${tumor_sample}"
 
 java -Dorg.jooq.no-logo=true -Xmx16G -Xms4G \
     -jar ${purple_jar} \
