Usage added to check_numbers_metadata script

diff --git a/datarequest/scripts/check_numbers_metadata b/datarequest/scripts/check_numbers_metadata
--- a/datarequest/scripts/check_numbers_metadata
+++ b/datarequest/scripts/check_numbers_metadata
@@ -1,13 +1,36 @@
 #!/usr/bin/env bash
 
-#put metadata file path at $1.
+print_usage(){
+    echo "-----"
+    echo " Descr: Prints numbers in metadata file"
+    echo " Usage: $(basename $0) -m <metadata_tsv>"
+    echo " Exmpl: $(basename $0) -m '/data/data_archive/datarequests/DR-XXX/DR-XXX/metadata/metadata.tsv'"
+    echo "-----"
+    exit 1
+}
+
+while getopts ':m:' flag; do
+    case "${flag}" in
+        m) metadata_tsv=${OPTARG} ;;
+        *) print_usage
+        exit 1 ;;
+    esac
+done
+
+if [[ -z "${metadata_tsv}" ]]; then
+    echo "[ERROR] script check_numbers_metadata did not run, check usage below:"
+    print_usage
+fi
+
+echo ""
+echo "# [INFO] START check_numbers_metadata: $(date +"%y%m%d (%T)")"
 
 # make dir for temporary files
 mkdir temp_number_check
 
 ### Read in patients and samples selected for DR
-csvcut -t -e iso-8859-1 -c '#patientId' $1  | csvformat -T | tail -n +2 | sort | uniq > temp_number_check/patientId_metadata.tsv
-csvcut -t -e iso-8859-1 -c 'sampleId' $1  | csvformat -T | tail -n +2 | sort | uniq > temp_number_check/sampleId_metadata.tsv
+csvcut -t -e iso-8859-1 -c '#patientId' ${metadata_tsv}  | csvformat -T | tail -n +2 | sort | uniq > temp_number_check/patientId_metadata.tsv
+csvcut -t -e iso-8859-1 -c 'sampleId' ${metadata_tsv}  | csvformat -T | tail -n +2 | sort | uniq > temp_number_check/sampleId_metadata.tsv
 
 echo ""
 echo "[INFO] Number of patients (based on study number) in metadata file:"
