renew composing hospital requests

diff --git a/datarequest/scripts/compose_request_hospital b/datarequest/scripts/compose_request_hospital
--- a/datarequest/scripts/compose_request_hospital
+++ b/datarequest/scripts/compose_request_hospital
@@ -4,17 +4,27 @@ if [[ "$#" -ne 5 ]]; then
     echo "Usage: $(basename $0)"
     echo "      - dr_name (eg LUMC)"
     echo "      - request_name (eg request_20200303)"
-    echo "      - set_selection_sql (eg /home/sandra/jobs/SQL_scripts/LUMC_request_20200303.sql)"
+    echo "      - patient_selection_sql (eg /home/sandra/jobs/SQL_scripts/LUMC_request_20200303.sql)"
     echo "      - include_somatics (1 or 0)"
     echo "      - include_germline (1 or 0)"
+    echo "      - include_tumor_patient_treatment_response_metadata (1 or 0)"
+    echo "      - include_treatment_response_clinical_data (1 or 0)"
+    echo "      - include_pre_treatment_clinical_data (1 or 0)"
+    echo "      - include_rano_measurement_by_patient (1 or 0)"
+    echo "      - include_tumor_markers_by_patient (1 or 0)"
     exit 1
 fi
 
 dr_name=$1 && shift
 request_name=$1 && shift
-set_selection_sql=$1 && shift
+patient_selection_sql=$1 && shift
 include_somatics=$1 && shift
 include_germline=$1 && shift
+include_tumor_patient_treatment_response_metadata=$1 && shift # This will become non-optional at some point.
+include_treatment_response_clinical_data=$1 && shift
+include_pre_treatment_clinical_data=$1 && shift
+include_rano_measurement_by_patient=$1 && shift
+include_tumor_markers_by_patient=$1 && shift
 
 base_path=/data/data_archive/datarequests
 
@@ -24,51 +34,113 @@ dr_path=${dr_base_path}/${request_name}
 echo "[INFO] Composing data request ${request_name} in ${dr_path}"
 echo "[INFO]    dr_name=${dr_name}"
 echo "[INFO]    request_name=${request_name}"
-echo "[INFO]    set_selection_sql=${set_selection_sql}"
+echo "[INFO]    set_selection_sql=${patient_selection_sql}"
 echo "[INFO]    include_somatics=${include_somatics}"
 echo "[INFO]    include_germline=${include_germline}"
+echo "[INFO]    include_tumor_patient_treatment_response_metadata=${include_tumor_patient_treatment_response_metadata}"
+echo "[INFO]    include_treatment_response_clinical_data=${include_treatment_response_clinical_data}"
+echo "[INFO]    include_pre_treatment_clinical_data=${include_pre_treatment_clinical_data}"
+echo "[INFO]    include_rano_measurement_by_patient=${include_rano_measurement_by_patient}"
+echo "[INFO]    include_tumor_markers_by_patient=${include_tumor_markers_by_patient}"
 
 create_base_directory_for_datarequest ${dr_path}
 if [[ $? = 0 ]]; then
     log_dir=${dr_path}/logs
     mkdir -p ${log_dir}
 
-    echo "[INFO] Selecting patients to include for hospital Request ${request_name}."
-    cp ${set_selection_sql} ${log_dir}/selectSets.sql
-    set_selection_tsv=${log_dir}/selectSets.tsv
-    execute_sql_on_prod ${log_dir}/selectSets.sql > ${set_selection_tsv}
-    set_count=$(grep -cv "^#" ${set_selection_tsv})
-    echo "[INFO] Created ${set_selection_tsv} with ${set_count} sets"
+    echo "[INFO] Selecting patients to include for ${request_name}..."
+    cp ${patient_selection_sql} ${log_dir}/selectPatients.sql
+    patient_selection_tsv=${log_dir}/selectPatients.tsv
+    execute_sql_on_prod ${log_dir}/selectPatients.sql > ${patient_selection_tsv}
+    patient_count=$(grep -cv "^#" ${patient_selection_tsv})
+    echo "[INFO] Created ${patient_selection_tsv} with ${patient_count} patients"
+
+    echo "[INFO] Creating metadata for ${request_name}..."
+    metadata_dir_name=metadata
+    metadata_dir=${dr_path}/${metadata_dir_name}
+    mkdir -p ${metadata_dir}
+    metadata_tsv=${metadata_dir}/metadata.tsv
+    generate_metadata_hospital_request \
+        ${patient_selection_tsv} \
+        ${log_dir} \
+        ${metadata_tsv} \
+        ${include_tumor_patient_treatment_response_metadata}
+
+    if [[ $? = 1 ]]; then
+        # Propogate error upstream to caller of this function.
+        exit 1;
+    fi
+
+    sample_count=$(grep -cv "^#" ${metadata_tsv})
+    echo "[INFO] Created ${metadata_tsv} with ${sample_count} samples"
 
     if [[ ${include_somatics} == "1" ]]; then
-        echo "[INFO] Collecting somatic data for hospital Request ${request_name}."
+        echo "[INFO] Collecting somatic data for ${request_name}..."
         somatic_dir_name=somatics
         somatics_dir=${dr_path}/${somatic_dir_name}
         mkdir -p ${somatics_dir}
-        collect_all_somatic_set_data_for_request ${set_selection_tsv} ${somatics_dir} ${include_germline}
+        collect_all_somatic_set_data_for_request ${metadata_tsv} ${somatics_dir} ${include_germline}
         somatics_sample_count=$(ls ${somatics_dir} | wc -l)
         somatic_tar_file=${dr_base_path}/${request_name}.somatics.tar
-        echo "[INFO] Done collecting somatics for hospital Request. Found ${somatics_sample_count} samples. Creating TAR at ${somatic_tar_file}"
+        echo "[INFO] Done collecting somatics for DR. Found ${somatics_sample_count} samples. Creating TAR at ${somatic_tar_file}"
         create_tar_file ${somatic_tar_file} ${dr_path} ./${somatic_dir_name} ${log_dir}/tar_${request_name}_somatics.log
     else
-        echo "[INFO] Skipped somatics collection as not deemed relevant for hospital Request ${request_name}"
+        echo "[INFO] Skipped somatics collection as not deemed relevant for ${request_name}"
     fi
 
     if [[ ${include_germline} == "1" ]]; then
-        echo "[INFO] Collecting germline data for hospital Request ${request_name}..."
+        echo "[INFO] Collecting germline data for ${request_name}..."
         germline_dir_name=germline
         germline_dir=${dr_path}/${germline_dir_name}
         mkdir -p ${germline_dir}
-        collect_all_germline_set_data_for_request ${set_selection_tsv} ${germline_dir}
+        collect_all_germline_set_data_for_request ${metadata_tsv} ${germline_dir}
         germline_sample_count=$(ls ${germline_dir} | wc -l)
         germline_tar_file=${dr_base_path}/${request_name}.germline.tar
-        echo "[INFO] Done collecting germline data for hospital Request. Found ${germline_sample_count} samples. Creating TAR at ${germline_tar_file}"
+        echo "[INFO] Done collecting germline data for DR. Found ${germline_sample_count} samples. Creating TAR at ${germline_tar_file}"
         create_tar_file ${germline_tar_file} ${dr_path} ./${germline_dir_name} ${log_dir}/tar_${request_name}_germline.log
     else
-        echo "[INFO] Skipped germline collection as not deemed relevant for hospital Request ${request_name}"
+        echo "[INFO] Skipped germline collection as not deemed relevant for ${request_name}"
     fi
 
-    echo "[INFO] Composing hospital Request for ${request_name} completed!"
+    if [[ ${include_treatment_response_clinical_data} == "1" ]]; then
+        echo "[INFO] Creating treatment and response clinical data for ${request_name}..."
+        generate_post_biopsy_drugs_by_sample ${patient_selection_tsv} ${log_dir} ${metadata_dir}
+        generate_responses_by_sample ${patient_selection_tsv} ${log_dir} ${metadata_dir}
+        echo "[INFO] Done creating response clinical data for DR"
+    else
+        echo "[INFO] Skipped generation of response clinical data as not deemed relevant for ${request_name}"
+    fi
+
+    if [[ ${include_pre_treatment_clinical_data} == "1" ]]; then
+        echo "[INFO] Creating pre-biopsy treatment data for ${request_name}..."
+        generate_pre_biopsy_drugs_by_patient ${patient_selection_tsv} ${log_dir} ${metadata_dir}
+        echo "[INFO] Done creating pre-biopsy treatment data for DR"
+    else
+        echo "[INFO] Skipped generation of pre-biopsy treatment data as not deemed relevant for ${request_name}"
+    fi
+
+    if [[ ${include_rano_measurement_by_patient} == "1" ]]; then
+        echo "[INFO] Creating RANO measurements for ${request_name}..."
+        generate_rano_measurements_by_patient ${patient_selection_tsv} ${log_dir} ${metadata_dir}
+        echo "[INFO] Done creating RANO measurements for DR"
+    else
+        echo "[INFO] Skipped generation of RANO measurement data as not deemed relevant for ${request_name}"
+    fi
+
+    if [[ ${include_tumor_markers_by_patient} == "1" ]]; then
+        echo "[INFO] Creating tumor markers for ${request_name}..."
+        generate_tumor_markers_by_patient ${patient_selection_tsv} ${log_dir} ${metadata_dir}
+        echo "[INFO] Done creating tumor markers for DR"
+    else
+        echo "[INFO] Skipped generation of tumor markers as not deemed relevant for ${request_name}"
+    fi
+
+    metadata_tar_file=${dr_base_path}/${request_name}.metadata.tar
+    echo "[INFO] Creating metadata TAR file at ${metadata_tar_file}"
+    create_tar_file ${metadata_tar_file} ${dr_path} ./${metadata_dir_name} ${log_dir}/tar_${request_name}_metadata.log
+
+    echo "[INFO] Composing datarequest for ${request_name} completed!"
 else
-    echo "[ERROR] Could not create base directory structure for for hospital Request for ${dr_name}"
+    echo "[ERROR] Could not create base directory structure for DR ${dr_name}"
 fi
+
