Add extra checks in bam scripts

diff --git a/bam/downsample_bam_file b/bam/downsample_bam_file
--- a/bam/downsample_bam_file
+++ b/bam/downsample_bam_file
@@ -4,6 +4,11 @@ in_bam=$1 && shift
 out_bam=$1 && shift
 ratio_to_keep=$1 && shift
 
+if [[ ! -f "${in_bam}" || -z "${out_bam}" || -z "${ratio_to_keep}" ]]; then
+    echo "[ERROR] Missing input files for downslicing"
+    exit 1
+fi
+
 picard_dir=/data/tools/picard-tools_v1.141
 mem_use=50
 
diff --git a/bam/gridss_metrics_for_bam b/bam/gridss_metrics_for_bam
--- a/bam/gridss_metrics_for_bam
+++ b/bam/gridss_metrics_for_bam
@@ -2,4 +2,9 @@
 
 bam=$1 && shift
 
+if [[ ! -f "${bam}" ]]; then
+    echo "[ERROR] Bam is not a file: ${bam}. Exiting"
+    exit 1
+fi
+
 java -cp /data/common/tools/gridss_v2.0.1/gridss.jar gridss.analysis.CollectGridssMetrics I=${bam} O=${bam} THRESHOLD_COVERAGE=50000
diff --git a/bam/take_qc_testing_bam_slice b/bam/take_qc_testing_bam_slice
--- a/bam/take_qc_testing_bam_slice
+++ b/bam/take_qc_testing_bam_slice
@@ -2,6 +2,11 @@
 
 bam=$1 && shift
 
+if [[ ! -f "${bam}" ]]; then
+    echo "[ERROR] Bam is not a file: ${bam}. Exiting"
+    exit 1
+fi
+
 sliced_bam=$(echo "${bam}" | sed 's/\(.*\).bam/\1.sliced.bam/')
 
 sambamba=/data/common/tools/sambamba_v0.6.5/sambamba
