Some consistency improvements

diff --git a/bam/downsample_bam_file b/bam/downsample_bam_file
--- a/bam/downsample_bam_file
+++ b/bam/downsample_bam_file
@@ -5,8 +5,7 @@ out_bam=$1 && shift
 ratio_to_keep=$1 && shift
 
 if [[ ! -f "${in_bam}" || -z "${out_bam}" || -z "${ratio_to_keep}" ]]; then
-    echo "[ERROR] Missing input files for downslicing"
-    exit 1
+    echo "[ERROR] Missing input files for downslicing" && exit 1
 fi
 
 picard_dir=/data/tools/picard-tools_v1.141
diff --git a/bam/inspect_bam_file b/bam/inspect_bam_file
--- a/bam/inspect_bam_file
+++ b/bam/inspect_bam_file
@@ -3,8 +3,7 @@
 bam=$1 && shift
 
 if [[ ! -f "${bam}" ]]; then
-    echo "[ERROR] Bam is not a file: ${bam}. Exiting"
-    exit 1
+    echo "[ERROR] Bam is not a file: ${bam}. Exiting" && exit 1
 fi
 
 samtools=/data/common/tools/samtools_v1.9/samtools
