Update for new c2f using HAWE workflows

diff --git a/bam/finish_cram2fastq_registration b/bam/finish_cram2fastq_registration
--- a/bam/finish_cram2fastq_registration
+++ b/bam/finish_cram2fastq_registration
@@ -22,17 +22,17 @@ fi
 new_barcode_lower=$(echo "new_barcode" | tr '[:upper:]' '[:lower:]')
 
 info "Renaming newly generated fastq to correct barcodes"
-for fastq_file in $(gcloud storage ls "gs://hmf-cram2fastq/${new_barcode_lower}_FASTQ/cram2fastq/output_fq/*.fastq.gz")
+for fastq_file in $(gcloud storage ls "gs://hmf-cram2fastq/${new_barcode_lower}/cram2fastq/output_fq/*.fastq.gz")
 do
   echo ${fastq_file}
   gcloud storage mv "${fastq_file}" "${fastq_file//SAMPLE/${new_barcode}}"
 done
 
 info "Moving newly generated fastq to fastq-input-prod-1 bucket"
-gcloud storage cp "gs://hmf-cram2fastq/${new_barcode_lower}_FASTQ/cram2fastq/output_fq/*fastq.gz" "gs://fastq-input-prod-1/" || die "Could not move fastq"
+gcloud storage cp "gs://hmf-cram2fastq/${new_barcode_lower}/cram2fastq/output_fq/*.fastq.gz" "gs://fastq-input-prod-1/" || die "Could not move fastq"
 
 info "register new barcode fastq in api"
-manual_fastq_register_like "${new_barcode}" "gs://hmf-cram2fastq/${new_barcode_lower}_FASTQ/cram2fastq/output_fq" "${org_barcode}" || die "Could not register new fastq"
+manual_fastq_register_like "${new_barcode}" "gs://hmf-cram2fastq/${new_barcode_lower}/cram2fastq/output_fq" "${org_barcode}" || die "Could not register new fastq"
 
 info "Patching new barcode q30 and yield with original barcode values in api"
 patch_api_sample_q30_yld_from_source_sample "${org_barcode}" "${new_barcode}" || die "Could not patch api"
