More consistency improvements to various scripts

diff --git a/ascat/ascat_for_paper b/ascat/ascat_for_paper
--- a/ascat/ascat_for_paper
+++ b/ascat/ascat_for_paper
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
-source metadata_functions
+source metadata_functions || exit 1
+source message_functions || exit 1
 
 prefix=$(dirname $(readlink $0 || echo $0))
 
@@ -12,14 +13,14 @@ normal=$(load_ref_sample_from_metadata ${run_dir})
 
 amber=${run_dir}/amber_v2/${sample}.amber.baf
 if [[ ! -f "${amber}" ]]; then
-    echo "[ERROR] Unable to locate AMBER file: ${amber}" && exit 1
+    error "Unable to locate AMBER file: ${amber}"
 fi
 
 amber_column_count=$(head -1 ${amber} | wc -w)
 if [[ ${amber_column_count} -ne 8 ]]; then
-    echo "[ERROR] ASCAT requires latest AMBER output" && exit 1
+    error "ASCAT requires latest AMBER output"
 fi
 
-echo "[INFO] Running ASCAT on ${sample}"
+info "Running ASCAT on ${sample}"
 Rscript ${prefix}/ascatForPaper.R ${run_dir} ${out_dir} ${sample} ${normal}
-echo "[INFO] ASCAT complete"
+info "ASCAT complete"
diff --git a/ascat/prep_for_ascat b/ascat/prep_for_ascat
--- a/ascat/prep_for_ascat
+++ b/ascat/prep_for_ascat
@@ -2,6 +2,7 @@
 
 source metadata_functions || exit 1
 source locate_files || exit 1
+source message_functions || exit 1
 
 prefix=$(dirname $(readlink $0 || echo $0))
 
@@ -17,13 +18,12 @@ normal=$(load_ref_sample_from_metadata ${run_dir})
 
 old_amber=${run_dir}/amber/${sample}.amber.baf
 if [[ ! -f "${old_amber}" ]]; then
-    echo "[ERROR] Unable to locate old AMBER file ${old_amber}. Exiting"
-    exit 1
+    error "Unable to locate old AMBER file ${old_amber}. Exiting"
 fi
 
 new_amber=${out_dir}/${sample}.amber.baf
 if [[ -f "${new_amber}" ]]; then
-    echo "[INFO] Amber already rerun: ${new_amber}"
+    info "Amber already rerun: ${new_amber}"
     exit 0
 fi
 
@@ -32,8 +32,7 @@ if [[ ! -f "${bed}" ]]; then
     cat ${old_amber} | grep -v Chrom | awk '{print $1 "\t" $2 - 1 "\t" $2}' > ${bed}
 fi
 
-echo "[ERROR] BAM slicer no longer supported".
-exit 1
+error "BAM slicer no longer supported".
 
 sample_bam=${out_dir}/${sample}.amber.bam
 if [[ ! -f "${sample_bam}" ]]; then
diff --git a/bam/bam2fastq b/bam/bam2fastq
--- a/bam/bam2fastq
+++ b/bam/bam2fastq
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 in_bam=$1 && shift
 
 ## use 90 percent of available threads
@@ -32,43 +34,42 @@ fi
 
 ## ---------------
 ## sanity checks
-if [[ ! -d "${picard_dir}" ]]; then echo "[ERROR] Picard dir not found (${picard_dir})"; exit 1; fi
-if [[ ! -d "${samtools_dir}" ]]; then echo "[ERROR] Samtools dir not found (${samtools_dir})"; exit 1; fi
-if [[ ! -f "${in_bam}" ]]; then echo "[ERROR] Bam file not found (${in_bam})"; exit 1; fi
-if [[ ! -w "$(dirname "${out_dir}")" ]]; then echo "[ERROR] Output dir not writable?"; exit 1; fi
+if [[ ! -d "${picard_dir}" ]]; then error "Picard dir not found (${picard_dir})"; fi
+if [[ ! -d "${samtools_dir}" ]]; then error "Samtools dir not found (${samtools_dir})"; fi
+if [[ ! -f "${in_bam}" ]]; then error "Bam file not found (${in_bam})"; fi
+if [[ ! -w "$(dirname "${out_dir}")" ]]; then error "Output dir not writable?"; fi
 
 ## ---------------
 
 ## Check format of RG/ID tags in header
 correct_lane_count=$(${samtools_dir}/samtools view -H "${in_bam}" | grep ^@RG | grep -vcP "_L00[1-8]_" )
 if [[ ${correct_lane_count} -gt 1 ]]; then
-    echo "[ERROR] There are RG ID header lines in BAM without the expected pattern (_L00[1-8]_):"
+    warn "There are RG ID header lines in BAM without the expected pattern (_L00[1-8]_):"
     ${samtools_dir}/samtools view -H "${in_bam}" | grep ^@RG
     exit 1
 fi
 
 if [[ -d "${out_dir}" ]]; then
-    echo "[ERROR] output dir exists, will not overwrite"
-    exit 1
+    error "Output dir exists, will not overwrite"
 else
-    echo "[INFO] Creating output dir (${out_dir})";
-    mkdir "${out_dir}";
+    info "Creating output dir (${out_dir})"
+    mkdir "${out_dir}"
 fi
 
-echo "[INFO] Running SamToFastq for bam file: $(basename "${in_bam}")"
+info "Running SamToFastq for bam file: $(basename "${in_bam}")"
 java -Xmx50G -jar "${picard_dir}"/picard.jar SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${in_bam}"
 
-echo "[INFO] About to rename fastq files"
+info "About to rename fastq files"
 for fastq_path in "${out_dir}"/*fastq; do
     fastq_old=$(basename "${fastq_path}")
     fastq_new=$(echo "${fastq_old}" | sed 's#\.fastq##g' - | awk 'BEGIN { FS = "_" } ; { print $1"_"$2"_"$3"_"$4"_R"$6"_"$5".fastq" }')
    
     mv "${fastq_path}" "${out_dir}"/"${fastq_new}"
-    echo "[INFO] ${fastq_old} renamed to ${fastq_new}"
+    info "${fastq_old} renamed to ${fastq_new}"
 done
 
-echo "[INFO] gzipping fastq files...(using pigz)"
+info "gzipping fastq files...(using pigz)"
 pigz -p ${threads} "${out_dir}"/*.fastq
 
-echo "[INFO] Output fastq can be found in ${out_dir}"
+info "Output fastq can be found in ${out_dir}"
 ls "${out_dir}"
diff --git a/bam/downsample_bam_file b/bam/downsample_bam_file
--- a/bam/downsample_bam_file
+++ b/bam/downsample_bam_file
@@ -1,23 +1,25 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 in_bam=$1 && shift
 out_bam=$1 && shift
 ratio_to_keep=$1 && shift
 
 if [[ ! -f "${in_bam}" || -z "${out_bam}" || -z "${ratio_to_keep}" ]]; then
-    echo "[ERROR] Missing input files for downslicing" && exit 1
+    error"Missing input files for downslicing"
 fi
 
 picard_dir=/data/tools/picard-tools_v1.141
 mem_use=50
 
-echo "[INFO] Input bam file: ${in_bam}"
-echo "[INFO] Output bam file: ${out_bam}"
-echo "[INFO] Ratio to keep between 0 and 1: ${ratio_to_keep}"
+info "Input bam file: ${in_bam}"
+info "Output bam file: ${out_bam}"
+info "Ratio to keep between 0 and 1: ${ratio_to_keep}"
 
 java -Xmx${mem_use}G -jar ${picard_dir}/picard.jar DownsampleSam \
     I=${in_bam} \
     O=${out_bam} \
     P=${ratio_to_keep}
 
-echo "[INFO] Finished!"
+info "Finished!"
diff --git a/gcp/presign_share_url b/gcp/presign_share_url
--- a/gcp/presign_share_url
+++ b/gcp/presign_share_url
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 gcp_url=$1
 gcp_key_file="/data/common/dbs/gcp_credentials/hmf-ops"
 
 if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
-    echo "Usage: $(basename $0) gs://bucket/path/to_file" && exit 1
+    error "Usage: $(basename $0) gs://bucket/path/to_file"
 fi
 
 ## first check object existance
 gsutil -q stat "${gcp_url}"
 if [[ $? -ne 0 ]]; then
-    echo "[ERROR] Unable to locate file (${gcp_url})" >&2
-    exit 1
+    error "Unable to locate file (${gcp_url})"
 fi
 
 ## retrieve presigned URL
 signurl_response=$( gsutil signurl -d 7d "${gcp_key_file}" "${gcp_url}")
 if [[ $? -ne 0 ]]; then
-    echo "[ERROR] Unable to generate URL for file" >&2
-    exit 1
+    error "Unable to generate URL for file"
 fi
 
 ## response has data header line and multiple fields
diff --git a/gcp/process_shallow_run b/gcp/process_shallow_run
--- a/gcp/process_shallow_run
+++ b/gcp/process_shallow_run
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
-source gcp_functions
+source gcp_functions || exit 1
+source message_functions || exit 1
 
 set=$1 && shift
 
 if [[ -z "${set}" ]]; then
-    echo "[ERROR] No set provided to $(basename $0). Exiting"
-    exit 1
+    error "No set provided to $(basename $0). Exiting"
 fi
 
 archive_path="/data/data_archive/shallow_seq_pipelines"
@@ -15,16 +15,15 @@ archive_set_path=${archive_path}/${set}
 
 run_bucket=$(hmf_api_get "runs?set_name=${set}&ini=ShallowSeq.ini" | jq -r '.[-1].bucket')
 if [[ -z $run_bucket ]]; then
-    echo "[WARN] SKIPPING: Could not resolve bucket for \"${set}\""
-    exit
+    error "SKIPPING: Could not resolve bucket for \"${set}\""
 fi
 
 if [[ -d "${archive_set_path}" ]]; then
-    echo "[WARN] SKIPPING: Set already archived locally (${archive_set_path})"
+    warn "SKIPPING: Set already archived locally (${archive_set_path})"
 else
-    echo "[INFO] Syncing ShallowSeq GCP run ${set}"
+    info "Syncing ShallowSeq GCP run ${set}"
     dest_path=${download_path}/${set}
-    echo "[INFO]   Creating directory ${dest_path}"
+    info "  Creating directory ${dest_path}"
     mkdir -p ${dest_path}
 
     switch_to_hmf_ops_service_account
diff --git a/hmftools/cuppa/run_nina_cohort_cup_analysis b/hmftools/cuppa/run_nina_cohort_cup_analysis
--- a/hmftools/cuppa/run_nina_cohort_cup_analysis
+++ b/hmftools/cuppa/run_nina_cohort_cup_analysis
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
-source locate_files
+source locate_files || exit 1
+source message_functions || exit 1
 
 sample_ids_file=$1
 cup_ref_dir=$2
@@ -33,13 +34,11 @@ pos_freq_counts_file=${output_dir}/snv_position_freq_500000.csv
 snv_matrix_file=${output_dir}/sample_counts.${run_id}.csv
 
 if [[ ! -f $pos_freq_counts_file ]] ; then
-    echo "Error creating $pos_freq_counts_file, aborting"
-    exit 1
+    error "Error creating $pos_freq_counts_file, aborting"
 fi
 
 if [[ ! -f $snv_matrix_file ]] ; then
-    echo "Error creating $snv_matrix_file, aborting"
-    exit 1
+    error "Error creating $snv_matrix_file, aborting"
 fi
 
 java -cp ${siga_jar} com.hartwig.hmftools.sig_analyser.loaders.PositionFreqBuilder \
@@ -53,8 +52,7 @@ java -cp ${siga_jar} com.hartwig.hmftools.sig_analyser.loaders.PositionFreqBuild
 pos_freq_matrix_file=${output_dir}/pos_freq_matrix.${run_id}.csv
 
 if [[ ! -f $pos_freq_matrix_file ]] ; then
-    echo "Error creating $pos_freq_matrix_file, aborting"
-    exit 1
+    error "Error creating $pos_freq_matrix_file, aborting"
 fi
 
 rm ${pos_freq_counts_file}
