Add trial creator for NKI and fix sync issue

diff --git a/actin/trial_database/do_run_actin_trial_creation b/actin/trial_database/do_run_actin_trial_creation
--- a/actin/trial_database/do_run_actin_trial_creation
+++ b/actin/trial_database/do_run_actin_trial_creation
@@ -2,23 +2,32 @@
 
 source locate_files || exit 1
 source io_functions || exit 1
+source message_functions || exit 1
 
-trial_config_directory="$(locate_actin_cohort_trial_config_directory)"
+trial_status_directory_param=$1 && shift
+
+if [[ -z "${trial_status_directory_param}" ]]; then
+    error "Missing parameters. Exiting"
+fi
+
+trial_config_directory="$(locate_actin_trial_config_directory)"
 trial_status_directory="$(locate_actin_trial_status_directory)"
 treatment_directory="$(locate_actin_treatment_db_directory)"
 doid_json="$(locate_doid_json)"
+atc_tsv="$(locate_atc_tsv)"
 known_genes_tsv="$(locate_actin_known_genes_tsv)"
-output_directory="$(locate_actin_cohort_trial_database_directory)"
+output_directory="$(locate_actin_trial_database_directory)"
 
 create_or_cleanup_dir "${output_directory}"
 
-actin_jar="$(locate_cohort_actin)"
+actin_jar="$(locate_actin_jar_on_vm)"
 
 java -cp ${actin_jar} com.hartwig.actin.trial.TrialCreatorApplicationKt \
+    -${trial_status_directory_param} ${trial_status_directory} \
     -trial_config_directory ${trial_config_directory} \
-    -ctc_config_directory ${trial_status_directory} \
     -treatment_directory ${treatment_directory} \
     -doid_json ${doid_json} \
+    -atc_tsv ${atc_tsv} \
     -known_genes_tsv ${known_genes_tsv} \
     -output_directory ${output_directory} \
     "$@"
