Error out on usage of BAM slicing

diff --git a/hmftools/sage/do_download_hotspot_bams b/hmftools/sage/do_download_hotspot_bams
--- a/hmftools/sage/do_download_hotspot_bams
+++ b/hmftools/sage/do_download_hotspot_bams
@@ -18,6 +18,9 @@ mkdir -p ${out_dir}
 sample_bam=${out_dir}/${sample}.sage.bam
 normal_bam=${out_dir}/${normal}.sage.bam
 
+echo "[ERROR] BAM slicer no longer supported".
+exit 1
+
 if [[ ! -f "${sample_bam}" ]]; then
     ${prefix}/../bamslicer/do_slice_bam_on_gcp ${set} ${sample} ${hotspot_bed} ${sample_bam}
 else
diff --git a/hmftools/sage/do_run_sage_experiment b/hmftools/sage/do_run_sage_experiment
--- a/hmftools/sage/do_run_sage_experiment
+++ b/hmftools/sage/do_run_sage_experiment
@@ -22,11 +22,17 @@ pon2_vcf=${out_dir}/${sample}.pon2.vcf.gz
 snpeff_vcf=${out_dir}/${sample}.snpeff.vcf
 final_vcf=${out_dir}/${sample}.final.vcf.gz
 
+echo "[ERROR] BAM slicer no longer supported".
+exit 1
+
 if [[ ! -f "${sample_bam}" ]]; then
     ${prefix}/../bamslicer/slice_tumor_sample_bam_bam_on_gcp ${set} ${hotspot_bed} ${sample_bam}
 else
     echo "[INFO] Skipping tumor BAM slicing. HotSpot BAM already exists: ${sample_bam}"
 fi
+
+echo "[ERROR] BAM slicer no longer supported".
+exit 1
 
 if [[ ! -f "${normal_bam}" ]]; then
     ${prefix}/../bamslicer/slice_ref_sample_bam_on_gcp ${set} ${hotspot_bed} ${normal_bam}
