Validate assigned variables

diff --git a/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki b/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki
--- a/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki
+++ b/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki
@@ -15,11 +15,21 @@ if [[ -z "${patient}" ]]; then
     exit 1
 fi
 
-gcp_project=$(production_actin_nki_project)
-target_bucket=$(bash -c "locate_actin_shared_data_external_bucket ${gcp_project}") || exit 1
-report=$(bash -c "locate_actin_report_pdf_gcp ${gcp_project} ${patient}") || exit 1
-treatment_match=$(bash -c "locate_actin_treatment_match_json_gcp ${gcp_project} ${patient}") || exit 1
-record=$(bash -c "locate_actin_patient_record_json_gcp ${gcp_project} ${patient}") || exit 1
+assign_and_validate_variable() {
+    local result
+    result=$1
+    if [[ "${result}" == *"[ERROR]"* ]]; then
+        echo "[ERROR] ${result}" >&2
+        exit 1
+    fi
+    echo "$result"
+}
+
+gcp_project=$(assign_and_validate_variable "$(production_actin_nki_project)")
+target_bucket=$(assign_and_validate_variable "$(locate_actin_shared_data_external_bucket "${gcp_project}")")
+report=$(assign_and_validate_variable "$(locate_actin_report_pdf_gcp "${gcp_project}" "${patient}")")
+treatment_match=$(assign_and_validate_variable "$(locate_actin_treatment_match_json_gcp "${gcp_project}" "${patient}")")
+record=$(assign_and_validate_variable "$(locate_actin_patient_record_json_gcp "${gcp_project}" "${patient}")")
 
 hash="$(lookup_nki_hash_for_actin_id "${patient}")"
 
