ACTIN-1448: PR

diff --git a/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki b/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki
--- a/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki
+++ b/actin/local/operational/share_report_and_clinical_and_matching_snapshot_with_nki
@@ -1,11 +1,16 @@
 #!/usr/bin/env bash
 
+set -e
+
 source actin_config || exit 1
+
+trap 'echo "ERROR, exiting." >&2; exit 1' ERR
 
 patient=$1 && shift
 
 if [[ -z "${patient}" ]]; then
-    error "Missing parameters. Exiting"
+    error "Missing parameters. Exiting" >&2
+    exit 1
 fi
 
 gcp_project=$(production_actin_nki_project)
@@ -18,23 +23,27 @@ treatment_match="${analysis_pipeline_bucket}/algo/${patient}.treatment_match.jso
 clinical="${clinical_pipeline_bucket}/${patient}.clinical.json"
 
 hash="$(lookup_nki_hash_for_actin_id "${patient}")"
-bn="$(basename ${report})"
-ext="${bn#*.}"
-gsutil -q stat ${report}
-[[ $? -ne 0 ]] && echo "Cannot find \"${report}\"" >&2 && exit 1
 
-gsutil -q stat ${treatment_match}
-[[ $? -ne 0 ]] && echo "Cannot find \"${treatment_match}\"" >&2 && exit 1
+check_and_copy_file() {
+    local file_path=$1
+    local sub_dir=$2
+    local bn="$(basename ${file_path})"
+    local ext="${bn#*.}"
 
-gsutil -q stat ${clinical}
-[[ $? -ne 0 ]] && echo "Cannot find \"${clinical}\"" >&2 && exit 1
+    if ! gsutil -q stat "${file_path}"; then
+        echo "Cannot find \"${file_path}\"" >&2
+        return 1
+    fi
 
-gsutil cp -n "${report}" "${target_bucket}/reports/${hash}.${ext}" && exit 0
-echo "Failed copying ${report} to ${hash}.${ext}" && exit 1
+    if ! gsutil cp -n "${file_path}" "${target_bucket}/${sub_dir}/${hash}.${ext}"; then
+        echo "Failed copying ${file_path} to ${target_bucket}/${sub_dir}/${hash}.${ext}" >&2
+        return 1
+    fi
+}
 
-gsutil cp -n "${treatment_match}" "${target_bucket}/algo/${hash}.${ext}" && exit 0
-echo "Failed copying ${treatment_match} to ${hash}.${ext}" && exit 1
+check_and_copy_file "${report}" "reports"
+check_and_copy_file "${treatment_match}" "algo"
+check_and_copy_file "${clinical}" "clinical"
 
-gsutil cp -n "${clinical}" "${target_bucket}/clinical/${hash}.${ext}" && exit 0
-echo "Failed copying ${clinical} to ${hash}.${ext}" && exit 1
-
+echo "Copied files to ${target_bucket}"
+exit 0
