INN-320: Add optional tumor sample ID argument

diff --git a/innovation/hawe-workflows/oncoact-panel-remarks-workflow.yaml b/innovation/hawe-workflows/oncoact-panel-remarks-workflow.yaml
--- a/innovation/hawe-workflows/oncoact-panel-remarks-workflow.yaml
+++ b/innovation/hawe-workflows/oncoact-panel-remarks-workflow.yaml
@@ -1,10 +1,10 @@
 apiVersion: hartwigmedicalfoundation.nl/v1
 kind: WorkflowDefinitionCustomResource
 metadata:
-  name: oncoact-panel-remarks-1.1.2
+  name: oncoact-panel-remarks-1.2.0
 spec:
   name: "oncoact-panel-remarks"
-  version: "1.1.2"
+  version: "1.2.1"
   storagePath: "gs://oncoact-panel-remarks-output"
   externalInputs:
     - name: input-bucket
@@ -14,7 +14,7 @@ spec:
   stages:
     - name: "hotspot"
       image: "europe-west4-docker.pkg.dev/hmf-build/hmf-docker-crunch/oncoact-panel-remarks"
-      version: "1.1.2"
+      version: "1.2.2"
       options:
         backoffLimit: "2"
         stageTimeoutMinutes: "120"
@@ -36,7 +36,11 @@ spec:
           HOTSPOT_VCF="/data/resources/ops/panel/KnownHotspots.somatic.38.vcf.gz"
           
           echo "[$(date +"%Y-%m-%d %H:%M:%S")] Extract Sample ID from: $INPUT_DIR/metadata.json"
-          SAMPLE_ID=$(cat "$INPUT_DIR/metadata.json" | jq -r .tumor.sampleName) || { echo "Could not get sample ID from metadata JSON"; exit 1; }
+          SAMPLE_ID="${optional_sample_id}"
+          if [ -z "$SAMPLE_ID" ]; then
+            SAMPLE_ID=$(cat "$INPUT_DIR/metadata.json" | jq -r .tumor.sampleName) \
+              || { echo "Could not get sample ID from metadata JSON"; exit 1; }
+          fi
           echo "[$(date +"%Y-%m-%d %H:%M:%S")] Sample ID: $SAMPLE_ID"
           
           INPUT="$INPUT_DIR/$SAMPLE_ID/aligner/$SAMPLE_ID.bam"
@@ -97,7 +101,7 @@ spec:
           echo "[$(date +"%Y-%m-%d %H:%M:%S")] Finished hotspot coverage check"
     - name: "remarks"
       image: "europe-west4-docker.pkg.dev/hmf-build/hmf-docker-crunch/oncoact-panel-remarks"
-      version: "1.1.2"
+      version: "1.2.2"
       options:
         backoffLimit: "2"
         stageTimeoutMinutes: "120"
@@ -108,6 +112,7 @@ spec:
         - hotspot
       arguments: >-
         --pipeline-input-directory /in/input-bucket
+        --optional-sample-id "${optional_sample_id}"
         --hotspot-coverage-input-directory /in/hotspot
         --excluded-exons /data/resources/ops/panel/excludedExons.tsv
         --output-file /out/remarks.txt
