Various minor cleanups in scripts

diff --git a/actin/operational/share_report_with_nki b/actin/operational/share_report_with_nki
--- a/actin/operational/share_report_with_nki
+++ b/actin/operational/share_report_with_nki
@@ -1,19 +1,28 @@
 #!/usr/bin/env bash
 
-PROJECT="actin-nki"
-SOURCE_BUCKET="gs://${PROJECT}-analysis-pipeline-output"
-TARGET_BUCKET="gs://${PROJECT}-shared-data-external"
-LOOKUP_CMD="$(dirname "$0")/lookup_hash_for_actin_id"
+source actin_config || exit 1
+
+patient=$1 && shift
+
+if [[ -z "${patient}" ]]; then
+    error "Missing parameters. Exiting"
+fi
+
+gcp_project=$(production_actin_nki_project)
+source_bucket="gs://${gcp_project}-analysis-pipeline-output"
+target_bucket="gs://${gcp_project}-shared-data-external"
+lookup_cmd="$(dirname "$0")/lookup_nki_hash_for_actin_id"
 
 [[ $# -ne 1 ]] && echo "Provide the ACTIN id for the report" >&2 && exit 1
 
-report="${SOURCE_BUCKET}/report/${1}.actin.pdf"
+report="${source_bucket}/report/${patient}.actin.pdf"
 
-hash="$($LOOKUP_CMD "$1")"
-bn="$(basename $report)"
+hash="$(lookup_cmd "${patient}")"
+bn="$(basename ${report})"
 ext="${bn#*.}"
-gsutil -q stat $report 
-[[ $? -ne 0 ]] && echo "Cannot find \"$report\"" >&2 && exit 1
-gsutil cp -n "$report" "${TARGET_BUCKET}/reports/${hash}.${ext}" && exit 0
-echo "Failed copying $report to ${hash}.${ext}" && exit 1
+gsutil -q stat ${report}
+[[ $? -ne 0 ]] && echo "Cannot find \"${report}\"" >&2 && exit 1
+
+gsutil cp -n "${report}" "${target_bucket}/reports/${hash}.${ext}" && exit 0
+echo "Failed copying ${report} to ${hash}.${ext}" && exit 1
 
