Use WARN rather than WARNING

diff --git a/validation/compare_v5_runs b/validation/compare_v5_runs
--- a/validation/compare_v5_runs
+++ b/validation/compare_v5_runs
@@ -20,10 +20,10 @@ if [[ "$#" -ne 2 ]]; then
     echo "-----"
     exit 1
 fi
-if [[ ! -d "$base_run_path" ]]; then echo "[ERROR] Directory not found ($base_run_path)" && exit 1; fi
-if [[ ! -d "$test_run_path" ]]; then echo "[ERROR] Directory not found ($test_run_path)" && exit 1; fi
-if [[ ! -f "$base_pip_vsn_file" ]]; then echo "[ERROR] File not found ($base_pip_vsn_file)" && exit 1; fi
-if [[ ! -f "$test_pip_vsn_file" ]]; then echo "[ERROR] File not found ($test_pip_vsn_file)" && exit 1; fi
+if [[ ! -d "${base_run_path}" ]]; then echo "[ERROR] Directory not found ($base_run_path)" && exit 1; fi
+if [[ ! -d "${test_run_path}" ]]; then echo "[ERROR] Directory not found ($test_run_path)" && exit 1; fi
+if [[ ! -f "${base_pip_vsn_file}" ]]; then echo "[ERROR] File not found ($base_pip_vsn_file)" && exit 1; fi
+if [[ ! -f "${test_pip_vsn_file}" ]]; then echo "[ERROR] File not found ($test_pip_vsn_file)" && exit 1; fi
 
 base_pip_vsn=$(cat "${base_pip_vsn_file}")
 test_pip_vsn=$(cat "${test_pip_vsn_file}")
@@ -37,21 +37,21 @@ test_tum_reads_file="${test_run_path}/${test_tum_sample_name}/cram/${test_tum_sa
 
 echo ""
 echo "===== Overview"
-echo "[INFO] BASE run path: $base_run_path"
-echo "[INFO] TEST run path: $test_run_path"
-echo "[INFO] BASE version: $base_pip_vsn"
-echo "[INFO] TEST version: $test_pip_vsn"
+echo "[INFO] BASE run path: ${base_run_path}"
+echo "[INFO] TEST run path: ${test_run_path}"
+echo "[INFO] BASE version: ${base_pip_vsn}"
+echo "[INFO] TEST version: ${test_pip_vsn}"
 
 
 echo ""
 echo "===== CRAM CHECK"
-echo "[INFO] TEST ref sample CRAM: $test_ref_reads_file"
-echo "[INFO] TEST tum sample CRAM: $test_tum_reads_file"
-if [[ ! -f "$test_ref_reads_file" ]]; then
-    echo "[ERROR] File does not exist ($test_ref_reads_file)"
+echo "[INFO] TEST ref sample CRAM: ${test_ref_reads_file}"
+echo "[INFO] TEST tum sample CRAM: ${test_tum_reads_file}"
+if [[ ! -f "${test_ref_reads_file}" ]]; then
+    echo "[ERROR] File does not exist (${test_ref_reads_file})"
     exit 1
-elif [[ ! -f "$test_tum_reads_file" ]]; then
-    echo "[ERROR] File does not exist ($test_tum_reads_file)"
+elif [[ ! -f "${test_tum_reads_file}" ]]; then
+    echo "[ERROR] File does not exist (${test_tum_reads_file})"
     exit 1
 fi
 
@@ -86,35 +86,35 @@ done
 echo ""
 echo "===== File CHECKS"
 echo "[INFO] Locating all relevant files"
-test_grm_vcf=$(locate_germline_variants "$test_run_path" "$test_ref_sample_name")
-base_grm_vcf=$(locate_germline_variants "$base_run_path" "$base_ref_sample_name")
-  test_chord=$(locate_chord_prediction "$test_run_path")  
-  base_chord=$(locate_chord_prediction "$base_run_path")
-test_vir_ins=$(locate_linx_viral_insertions "$test_run_path")
-base_vir_ins=$(locate_linx_viral_insertions "$base_run_path")
-test_som_var=$(locate_purple_somatics "$test_run_path")
-base_som_var=$(locate_purple_somatics "$base_run_path")
- test_sv_var=$(locate_purple_structural_variants "$test_run_path")
- base_sv_var=$(locate_purple_structural_variants "$base_run_path")
-   test_bach=$(locate_bachelor_variants "$test_run_path")
-   base_bach=$(locate_bachelor_variants "$base_run_path")
+test_grm_vcf=$(locate_germline_variants "${test_run_path}" "${test_ref_sample_name}")
+base_grm_vcf=$(locate_germline_variants "${base_run_path}" "${base_ref_sample_name}")
+  test_chord=$(locate_chord_prediction "${test_run_path}")
+  base_chord=$(locate_chord_prediction "${base_run_path}")
+test_vir_ins=$(locate_linx_viral_insertions "${test_run_path}")
+base_vir_ins=$(locate_linx_viral_insertions "${base_run_path}")
+test_som_var=$(locate_purple_somatics "${test_run_path}")
+base_som_var=$(locate_purple_somatics "${base_run_path}")
+ test_sv_var=$(locate_purple_structural_variants "${test_run_path}")
+ base_sv_var=$(locate_purple_structural_variants "${base_run_path}")
+   test_bach=$(locate_bachelor_variants "${test_run_path}")
+   base_bach=$(locate_bachelor_variants "${base_run_path}")
 
-echo "[INFO] BASE GERMLINE: $base_grm_vcf"
-echo "[INFO] TEST GERMLINE: $test_grm_vcf"
-echo "[INFO] BASE SOMATIC:  $base_som_var"
-echo "[INFO] TEST SOMATIC:  $test_som_var"
-echo "[INFO] BASE SV:       $base_sv_var"
-echo "[INFO] TEST SV:       $test_sv_var"
-echo "[INFO] BASE CHORD:    $base_chord"
-echo "[INFO] TEST CHORD:    $test_chord"
-echo "[INFO] BASE VIRAL:    $base_vir_ins"
-echo "[INFO] TEST VIRAL:    $test_vir_ins"
-echo "[INFO] BASE BACHELOR: $base_bach"
-echo "[INFO] TEST BACHELOR: $test_bach"
+echo "[INFO] BASE GERMLINE: ${base_grm_vcf}"
+echo "[INFO] TEST GERMLINE: ${test_grm_vcf}"
+echo "[INFO] BASE SOMATIC:  ${base_som_var}"
+echo "[INFO] TEST SOMATIC:  ${test_som_var}"
+echo "[INFO] BASE SV:       ${base_sv_var}"
+echo "[INFO] TEST SV:       ${test_sv_var}"
+echo "[INFO] BASE CHORD:    ${base_chord}"
+echo "[INFO] TEST CHORD:    ${test_chord}"
+echo "[INFO] BASE VIRAL:    ${base_vir_ins}"
+echo "[INFO] TEST VIRAL:    ${test_vir_ins}"
+echo "[INFO] BASE BACHELOR: ${base_bach}"
+echo "[INFO] TEST BACHELOR: ${test_bach}"
 
 for file in "$test_grm_vcf" "$base_grm_vcf" "$test_chord" "$base_chord" "$test_vir_ins" "$base_vir_ins" "$test_bach" "$base_bach"; do
-    if [[ ! -f "$file" ]]; then 
-        echo "[WARNING] File does not exist ($file)" && exit 1
+    if [[ ! -f "${file}" ]]; then
+        echo "[WARN] File does not exist ($file)" && exit 1
     fi
 done
 
