fix mix of string and array

diff --git a/validation/install_verified_colo_run b/validation/install_verified_colo_run
--- a/validation/install_verified_colo_run
+++ b/validation/install_verified_colo_run
@@ -96,14 +96,14 @@ copy_file() {
 }
 
 die() { 
-    echo "[ERROR] $(date +"%y%m%d %T") $@" >&2
+    echo "[ERROR] $(date +"%y%m%d %T")" "$@" >&2
     exit 1 
 }
 warn() { 
-    echo "[WARN] $(date +"%y%m%d %T") $@" >&2
+    echo "[WARN] $(date +"%y%m%d %T")" "$@" >&2
 }
 info() { 
-    echo "[INFO] $(date +"%y%m%d %T") $@"
+    echo "[INFO] $(date +"%y%m%d %T")" "$@"
 }
 
 main
