Some consistency improvements to scripts

diff --git a/validation/validate_giab_mixin_sage b/validation/validate_giab_mixin_sage
--- a/validation/validate_giab_mixin_sage
+++ b/validation/validate_giab_mixin_sage
@@ -3,7 +3,6 @@
 run_dir=$1 && shift
 out_name=$1 && shift # optional
 
-this_script=$(basename $0)
 val_base='/data/giab/validation/mixin'
 gatk_jar='/data/common/tools/gatk_v3.8.0/GenomeAnalysisTK.jar'
 rtg_exec='/data/common/tools/rtg-tools_v3.9.1/rtg'
@@ -19,21 +18,21 @@ truth_vcf_path="${truth_dir_path}/${truth_vcf_name}"
 truth_bed_path="${truth_dir_path}/${truth_bed_name}"
 
 ## init checks
-if [[ ! -w ${val_base} ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
-if [[ ! -f ${truth_vcf_path} ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
-if [[ ! -f ${truth_bed_path} ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
+if [[ ! -w "${val_base}" ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
+if [[ ! -f "${truth_vcf_path}" ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
+if [[ ! -f "${truth_bed_path}" ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
 if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     echo "-----"
     echo " Descr: Validate GIAB run"
-    echo " Usage: ${this_script} <path-to-pipeline-dir-or-vcf>"
-    echo "        ${this_script} <path-to-pipeline-dir-or-vcf> [<output-name>]"
-    echo "        ${this_script} /data/experiments/giab-mixin/mixin-run/"
-    echo "        ${this_script} /data/experiments/giab-mixin/mixin-run/ \"hmf-mixin-v4-final\""
+    echo " Usage: $(basename $0) <path-to-pipeline-dir-or-vcf>"
+    echo "        $(basename $0) <path-to-pipeline-dir-or-vcf> [<output-name>]"
+    echo "        $(basename $0) /data/experiments/giab-mixin/mixin-run/"
+    echo "        $(basename $0)/data/experiments/giab-mixin/mixin-run/ \"hmf-mixin-v4-final\""
     echo "-----"
     exit 1
 fi
 
-echo "[INFO] START with ${this_script}"
+echo "[INFO] START with $(basename $0)"
 
 ## -----
 ## Find somatic VCF
@@ -145,5 +144,5 @@ done > ${out_path}/rtg_summary.tsv
 
 echo "[INFO] Output in ${out_path}"
 echo "[INFO] Counts in ${metrics_out_file}"
-echo "[INFO] DONE with ${this_script}"
+echo "[INFO] DONE with $(basename $0)"
 
