Correct formatting

diff --git a/validation/verify_pipeline_run b/validation/verify_pipeline_run
--- a/validation/verify_pipeline_run
+++ b/validation/verify_pipeline_run
@@ -40,21 +40,21 @@ main() {
 
     info "Constructing variables"
     run_name=$(basename "${gcp_url}")
-    runs_dir="$out_dir/runs"
-    jobs_dir="$out_dir/jobs"
-    logs_dir="$out_dir/logs"
+    runs_dir="${out_dir}/runs"
+    jobs_dir="${out_dir}/jobs"
+    logs_dir="${out_dir}/logs"
     run_dir="${runs_dir}/${run_name}"
-    download_log="$logs_dir/download.log"
+    download_log="${logs_dir}/download.log"
     
     info "Creating directory structure"
-    info "Run name: $run_name" 
-    info "Out path: $out_dir"
-    info "Runs directory: $runs_dir"
-    info "Jobs directory: $jobs_dir"
-    info "Logs directory: $logs_dir"
+    info "Run name: ${run_name}" 
+    info "Out path: ${out_dir}"
+    info "Runs directory: ${runs_dir}"
+    info "Jobs directory: ${jobs_dir}"
+    info "Logs directory: ${logs_dir}"
     
-    mkdir $out_dir $runs_dir $run_dir $jobs_dir $logs_dir || die "Unable to create dirs"
-    cd $out_dir || die "Unable to move to output directory"
+    mkdir ${out_dir} ${runs_dir} ${run_dir} ${jobs_dir} ${logs_dir} || die "Unable to create dirs"
+    cd ${out_dir} || die "Unable to move to output directory"
 
     info "Gathering script and sql job files"
     jobs_source_path="/data/common/repos/scripts/validation/"
@@ -99,13 +99,13 @@ main() {
     find "${new_run}" -name "run.log" -exec grep -Pi "err|warn|exit|excep" {} + | grep -v germline_caller > "${logs_dir}/runlogs_check.txt"
 
     info "Executing locate_files test"
-    ${jobs_dir}/locate_files_test "$new_run" > "${logs_dir}/locate_files_test.log" 2>&1
+    ${jobs_dir}/locate_files_test "${new_run}" > "${logs_dir}/locate_files_test.log" 2>&1
 
     info "Executing compare_v5_runs"
-    ${jobs_dir}/compare_v5_runs "$truth_run" "$new_run" > "${logs_dir}/compare_v5_runs.log" 2>&1
+    ${jobs_dir}/compare_v5_runs "${truth_run}" "${new_run}" > "${logs_dir}/compare_v5_runs.log" 2>&1
 
     info "Executing diff_v5_COLO829v003_runs"
-    ${jobs_dir}/diff_v5_COLO829v003_runs "$truth_run" "$new_run" > "${logs_dir}/diff_v5_COLO829v003_runs.log" 2>&1
+    ${jobs_dir}/diff_v5_COLO829v003_runs "${truth_run}" "${new_run}" > "${logs_dir}/diff_v5_COLO829v003_runs.log" 2>&1
 
     info "TODO NEXT:"
     info " 1) Inspect log files in ${logs_dir}"
@@ -118,8 +118,8 @@ download_run_from_gcp() {
     local log_file=$1 && shift
     local check_log="${log_file}.check"
     
-    touch $log_file
-    touch $check_log
+    touch ${log_file}
+    touch ${check_log}
     
     info "Starting download from GCP (you can track progress in log ${log_file})"
     gsutil -m rsync -r "${gcp_url}/" "${run_dir}/" > "${log_file}" 2>&1
