Check pipeline.version file to fail early in case of incomplete run

diff --git a/validation/verify_pipeline_run b/validation/verify_pipeline_run
--- a/validation/verify_pipeline_run
+++ b/validation/verify_pipeline_run
@@ -78,6 +78,19 @@ main() {
         copy_file "${job_file_path}" "${jobs_dir}"
     done
 
+    ## early fail in case pipeline.version does not exist
+    file_to_check="pipeline.version"
+    url_to_check="${gcp_url}/${file_to_check}"
+    gsutil -q stat "${url_to_check}"
+    if [[ $? -eq 1 ]]; then
+        msg=$(gsutil -q stat "${url_to_check}" 2>&1)
+        echo "[ERROR] Cannot access file (${url_to_check})"
+        echo "[ERROR] ErrCode=${?} ErrMsg=\"${msg}\""
+        echo "[ERROR] Check run contents with: gsutil ls ${gcp_url}"
+        exit 1
+    fi
+
+    info "File ${file_to_check} found. Moving to actual download."
     download_run_from_gcp "${gcp_url}" "${run_dir}" "${download_log}"
 
     new_run="${run_dir}"
