Make it possible to provide a sample ID file manually + add param checks

diff --git a/hmftools/idgenerator/do_run_hmf_id_generator b/hmftools/idgenerator/do_run_hmf_id_generator
--- a/hmftools/idgenerator/do_run_hmf_id_generator
+++ b/hmftools/idgenerator/do_run_hmf_id_generator
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
 run_mode=$1 && shift
+
+if [ -z "${run_mode}" ]; then
+    echo "[ERROR] Please provide a run mode! Exiting"
+    exit 1
+fi
+
 id_generator_jar=/data/common/tools/hmf-id-generator_v2.0/hmf-id-generator.jar
 
 java -jar ${id_generator_jar} \
diff --git a/hmftools/idgenerator/run_hmf_id_generator b/hmftools/idgenerator/run_hmf_id_generator
--- a/hmftools/idgenerator/run_hmf_id_generator
+++ b/hmftools/idgenerator/run_hmf_id_generator
@@ -2,6 +2,11 @@
 
 run_mode=$1 && shift
 
+if [ -z "${run_mode}" ]; then
+    echo "[ERROR] Please provide a run mode! Exiting"
+    exit 1
+fi
+
 input_dir=/data/common/dbs/idgenerator/input
 output_dir=/data/common/dbs/idgenerator/output
 input_samples=${input_dir}/samples.csv
diff --git a/hmftools/idgenerator/single_hmf_hash_for_sample b/hmftools/idgenerator/single_hmf_hash_for_sample
--- a/hmftools/idgenerator/single_hmf_hash_for_sample
+++ b/hmftools/idgenerator/single_hmf_hash_for_sample
@@ -3,5 +3,15 @@
 password=$1 && shift
 sample=$1 && shift
 
+if [ -z "${password}" ]; then
+    echo "[ERROR] Please provide a password! Exiting"
+    exit 1
+fi
+
+if [ -z "${sample}" ]; then
+    echo "[ERROR] Please provide a sample! Exiting"
+    exit 1
+fi
+
 do_run_hmf_id_generator -create_single_hash -password ${password} -sample_id ${sample}
 
diff --git a/hmftools/idgenerator/update_hmf_id_generation_password b/hmftools/idgenerator/update_hmf_id_generation_password
--- a/hmftools/idgenerator/update_hmf_id_generation_password
+++ b/hmftools/idgenerator/update_hmf_id_generation_password
@@ -3,5 +3,15 @@
 password=$1 && shift
 new_password=$1 && shift
 
+if [ -z "${password}" ]; then
+    echo "[ERROR] Please provide a password! Exiting"
+    exit 1
+fi
+
+if [ -z "${new_password}" ]; then
+    echo "[ERROR] Please provide a new password! Exiting"
+    exit 1
+fi
+
 run_hmf_id_generator -update_ids -password ${password} -new_password ${new_password}
 
diff --git a/hmftools/idgenerator/update_hmf_ids b/hmftools/idgenerator/update_hmf_ids
--- a/hmftools/idgenerator/update_hmf_ids
+++ b/hmftools/idgenerator/update_hmf_ids
@@ -2,5 +2,9 @@
 
 password=$1 && shift
 
-run_hmf_id_generator --update_ids -password ${password}
+if [ -z "${password}" ]; then
+    echo "[ERROR] Please provide a password! Exiting"
+    exit 1
+fi
 
+run_hmf_id_generator --update_ids -password ${password}
