DEV-1240: changes to prepare for removal of sbpext user

diff --git a/sbpext/manual_fastq_register b/sbpext/manual_fastq_register
--- a/sbpext/manual_fastq_register
+++ b/sbpext/manual_fastq_register
@@ -1,51 +1,53 @@
 #!/usr/bin/env bash
 
-scriptName=$(basename $0)
-apiUrl="https://api.hartwigmedicalfoundation.nl"
-apiKey="/home/sbpext/bcl-upload-prod/api.key"
-apiCrt="/home/sbpext/bcl-upload-prod/api.crt"
+script_name=$(basename $0)
+
+api_cred_dir="/data/common/dbs/api_credentials"
+api_crt_file="${api_cred_dir}/api.crt"
+api_key_file="${api_cred_dir}/api.key"
+api_url='https://api.hartwigmedicalfoundation.nl/hmf/v1'
 
 hmfapi () {
-    http --ignore-stdin --cert="${apiCrt}" --cert-key="${apiKey}" "$@"
+    http --ignore-stdin --cert="${api_crt}" --cert-key="${api_key}" "$@"
 }
 
 if [[ -z $1 || $1 == "-h" || $1 == "--help" ]]; then
     echo "---"
-    echo " Usage: $scriptName \${barcode} \${fastqDir}"
-    echo "        $scriptName FR12345678 /path/to/fastq/files/"
+    echo " Usage: $script_name \${barcode} \${fastqDir}"
+    echo "        $script_name FR12345678 /path/to/fastq/files/"
     echo "---"
     exit 1
 fi
 
-BARCODE=$1
-FASTQ_DIR=$2
+barcode=$1
+fastq_dir=$2
 
-SAMPLE_NAME=""
-SAMPLE_ID=$(curl -s --cert-type pem --cert "${apiCrt}" --key "${apiKey}" "${apiUrl}/hmf/v1/samples?barcode=${BARCODE}" | jq '.[].id')
+sample_name=""
+sample_id=$(curl -s --cert-type pem --cert "${api_crt}" --key "${api_key}" "${api_url}/samples?barcode=${barcode}" | jq '.[].id')
 
-if [[ -z "$SAMPLE_ID" ]]; then
-    echo "[ERROR] Barcode not found at SBP ($BARCODE)" && exit 1
+if [[ -z "$sample_id" ]]; then
+    echo "[ERROR] Barcode not found at API (${barcode})" && exit 1
 fi
 
 ## make sure the FASTQ files contain only ONE sample
-SAMPLE_COUNT=$(find ${FASTQ_DIR} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq | wc -l)
-if [[ $SAMPLE_COUNT -ne 1 ]]; then 
-    echo "[ERROR] FASTQ files in dir should be from one sample (found $SAMPLE_COUNT samples in dir \"$FASTQ_DIR\")" && exit 1;
+sample_count=$(find ${fastq_dir} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq | wc -l)
+if [[ $sample_count -ne 1 ]]; then
+    echo "[ERROR] FASTQ files in dir should be from one sample (found ${sample_count} samples in dir \"${fastq_dir}\")" && exit 1;
 else
-    SAMPLE_NAME=$(find ${FASTQ_DIR} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq)
+    sample_name=$(find ${fastq_dir} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq)
 fi
 
 ## find all R1 fastq files -> check R2 presence -> register pair
-echo "[INFO] Starting with sample $SAMPLE_NAME barcode:$BARCODE id:$SAMPLE_ID"
-find ${FASTQ_DIR} -name "*_R1_*.fastq.gz" -exec basename {} \; | while read R1; do
+echo "[INFO] Starting with sample name:${sample_name} barcode:${barcode} id:${sample_id}"
+find ${fastq_dir} -name "*_R1_*.fastq.gz" -exec basename {} \; | while read R1; do
     R2=$( echo "$R1" | sed 's/_R1_/_R2_/' )
     if [[ -z "$R1" || -z "$R2" ]]; then
         echo "[WARN] Somehow R1 found but R2 file does not exist ($R2) so SKIPPING this pair."
     else
         echo "[INFO] Registering fastq R1/R2 pair (name_r1=$R1)"
-        hmfapi --print=b POST "${apiUrl}/hmf/v1/fastq" name_r1="${R1}" name_r2="${R2}" bucket="hmf-fastq-storage" sample_id="${SAMPLE_ID}"
+        hmfapi --print=b POST "${api_url}/fastq" name_r1="${R1}" name_r2="${R2}" bucket="hmf-fastq-storage" sample_id="${sample_id}"
     fi
 done
 
 echo "[INFO] Registering sample"
-curl -s --header "Content-type: application/json" --cert-type pem -X PATCH --cert "${apiCrt}" --key "${apiKey}" -d '{"name": "'${SAMPLE_NAME}'", "status": "Pending_QC"}' "${apiUrl}/hmf/v1/samples/${SAMPLE_ID}"
+curl -s --header "Content-type: application/json" --cert-type pem -X PATCH --cert "${api_crt}" --key "${api_key}" -d '{"name": "'${sample_name}'", "status": "Pending_QC"}' "${api_url}/samples/${sample_id}"
diff --git a/sbpext/register_set_by_json_to_prod b/sbpext/register_set_by_json_to_prod
--- a/sbpext/register_set_by_json_to_prod
+++ b/sbpext/register_set_by_json_to_prod
@@ -1,10 +1,15 @@
 #!/usr/bin/env bash
 
-JSON_FILE=$1
-CRT_FILE='/home/sbpext/bcl-upload-prod/api.crt'
-KEY_FILE='/home/sbpext/bcl-upload-prod/api.key'
-API_URL='https://api.hartwigmedicalfoundation.nl/hmf/v1/action/register'
+json=$1
 
-if [[ -z ${JSON_FILE+x} ]]; then echo "[ERROR] No json given" && exit 1; fi
+api_cred_dir="/data/common/dbs/api_credentials"
+api_crt_file="${api_cred_dir}/api.crt"
+api_key_file="${api_cred_dir}/api.key"
+api_url='https://api.hartwigmedicalfoundation.nl/hmf/v1/action/register'
 
-/usr/bin/curl -s -v --cert-type pem --cert ${CRT_FILE} --key ${KEY_FILE} ${API_URL} -XPOST -H "Content-Type: application/json" -d @${JSON_FILE}
+if [[ -z ${json+x} ]]; then echo "[ERROR] No json given" && exit 1; fi
+if [[ ! -f ${api_crt_file} ]]; then echo "[ERROR] File does not exist (${api_crt_file})" && exit 1; fi
+if [[ ! -f ${api_key_file} ]]; then echo "[ERROR] File does not exist (${api_key_file})" && exit 1; fi
+if [[ ! -f ${json} ]]; then echo "[ERROR] File does not exist (${json})" && exit 1; fi
+
+/usr/bin/curl -s -v --cert-type pem --cert ${api_crt_file} --key ${api_key_file} ${api_url} -XPOST -H "Content-Type: application/json" -d @${json}
