Add extra check to do_run_sv_loader_gridss

diff --git a/hmftools/svloader/do_run_sv_loader_gridss b/hmftools/svloader/do_run_sv_loader_gridss
--- a/hmftools/svloader/do_run_sv_loader_gridss
+++ b/hmftools/svloader/do_run_sv_loader_gridss
@@ -6,15 +6,20 @@ run_dir=$1 && shift
 
 credentials=/data/common/dbs/mysql_credentials/gridss_test
 sv_jar=/data/common/tools/variantannotator_pilot/variant-annotator.jar
-ref_genome=/data/common/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
 
 sample=$(load_tumor_sample_from_metadata ${run_dir})
+
+gridss_filtered_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
+if [ -z ${gridss_filtered_vcf} ]; then
+    echo "[ERROR] No GRIDSS filtered somatic vcf found. Exiting."
+    exit 1
+fi
 
 structural_vcf=$(find -L ${run_dir}/purple/ -type f -name *.purple.sv.vcf.gz)
 if [ -z ${structural_vcf} ]
 then
-    echo "Unable to locate gridss structural variants. Exiting."
+    echo "[ERROR] Unable to locate gridss structural variants. Exiting."
     exit 1
 fi
 
-${prefix}/do_run_sv_loader ${sample} ${structural_vcf} ${credentials} ${sv_jar} -ref_genome ${ref_genome} $@
+${prefix}/do_run_sv_loader ${sample} ${structural_vcf} ${credentials} ${sv_jar} $@
