Add additional check on having GRIDSS output when running latest sv loader

diff --git a/hmftools/svloader/do_run_sv_loader_prod b/hmftools/svloader/do_run_sv_loader_prod
--- a/hmftools/svloader/do_run_sv_loader_prod
+++ b/hmftools/svloader/do_run_sv_loader_prod
@@ -8,6 +8,12 @@ credentials=/data/common/dbs/mysql_credentials/prod
 sv_jar=/data/common/tools/variantannotator_v1.6/variant-annotator.jar
 sample=$(load_tumor_sample_from_metadata ${run_dir})
 
+gridss_filtered_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *.gridss.somatic.vcf.gz)
+if [ -z ${gridss_filtered_vcf} ]; then
+    echo "[ERROR] No GRIDSS filtered somatic vcf found. Exiting."
+    exit 1
+fi
+
 structural_vcf=$(find -L ${run_dir}/purple/ -type f -name *.purple.sv.vcf.gz)
 if [ -z ${structural_vcf} ]
 then
