Update actin_functions hash reversal function
Now just uses the datasource for the lookup.

diff --git a/actin/actin_functions b/actin/actin_functions
--- a/actin/actin_functions
+++ b/actin/actin_functions
@@ -1,29 +1,16 @@
 #!/usr/bin/env bash
 
+source actin_config || exit 1
+
 find_nki_actin_id_from_hash() {
-    # TODO (KD) Can be simplified using something like
-    # gsutil cat gs://actin-nki-id-state/id.state | jq '.' | grep $hash
+    gcp_project=$(production_actin_nki_project)
+    gs_url="gs://${gcp_project}-id-state/id.state"
 
-    hashed_id_to_find=$1 && shift
-    actin_id=""
-    i=30
-    while [[ i -lt 100 && -z "${actin_id}" ]]; do
-        potential_actin_id=""
-        if [[ $i -lt 10 ]]; then
-            potential_actin_id="NKI-LUNG-0000${i}"
-        elif [[ i -lt 100 ]]; then
-            potential_actin_id="NKI-LUNG-000${i}"
-        elif [[ i -lt 1000 ]]; then
-            potential_actin_id="NKI-LUNG-00${i}"
-        elif [[ i -lt 10000 ]]; then
-            potential_actin_id="NKI-LUNG-0${i}"
-        fi
-        hashed_id=$(lookup_nki_hash_for_actin_id ${potential_actin_id})
-        if [[ ${hashed_id} == ${hashed_id_to_find} ]]; then
-            actin_id="${potential_actin_id}"
-        fi
-        i=$((i + 1))
-    done
+    [[ $# -ne 1 ]] && echo "Provide the hashed NKI id" >&2 && exit 1
+    gsutil -q stat ${gs_url}
 
-    echo ${actin_id}
+    [[ $? -ne 0 ]] && echo "Cannot find ${gs_url}" >&2 && exit 1
+    gsutil cat ${gs_url} | jq -er ".[\"$1\"]"
+
+    [[ $? -ne 0 ]] && echo "Could not find mapping for $1" >&2 && exit 1
 }
