Added sanity checks to prevent GRIDSS scripts running if the inputs are not present

diff --git a/hmftools/gridss/do_run_gridss_preprocess b/hmftools/gridss/do_run_gridss_preprocess
--- a/hmftools/gridss/do_run_gridss_preprocess
+++ b/hmftools/gridss/do_run_gridss_preprocess
@@ -26,6 +26,12 @@ if [[ ! -f $insert_size_metrics ]] ; then
 	echo "Missing insert size metrics file $insert_size_metrics. Aborting" 1>&2
 	exit 1
 fi
+
+if [[ ! -f "$bam" ]] ; then
+	echo "Missing input bam $bam. Aborting" 1>&2
+	exit 1
+fi
+
 working_dir=$gridss_dir/$(basename $bam).gridss.working
 mkdir -p $working_dir
 sv_bam=$working_dir/$(basename $bam).sv.bam
