revert change

diff --git a/hmftools/gridss/do_run_gridss_somatic_filter b/hmftools/gridss/do_run_gridss_somatic_filter
--- a/hmftools/gridss/do_run_gridss_somatic_filter
+++ b/hmftools/gridss/do_run_gridss_somatic_filter
@@ -8,7 +8,12 @@ prefix=`dirname $(readlink $0 || echo $0)`
 run_dir=$1 && shift
 tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
 
-original_vcf=$(locate_gridss_structural_variants ${run_dir})
+original_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.vcf.gz)
+if [ -z ${original_vcf} ]
+then
+    echo "Unable to locate raw gridss structural variants. Exiting."
+    exit 1
+fi
 
 output_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.vcf
 full_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.full.vcf
