Refactored gridss viral annotation step to a) work with both prod & pilot and b) be optional

diff --git a/hmftools/gridss/do_run_gridss_viral_annotate b/hmftools/gridss/do_run_gridss_viral_annotate
--- a/hmftools/gridss/do_run_gridss_viral_annotate
+++ b/hmftools/gridss/do_run_gridss_viral_annotate
@@ -4,17 +4,20 @@
 #
 source do_run_gridss_lib
 
+input_vcf=$1 && shift
+
 PICARD_JAR=$base_path/tools/picard-tools_v1.135/picard.jar
-
 ref_genome=$base_path/refgenomes/human_virus/human_virus.fa
-
-input_vcf=${run_dir}/purple/${tumor_sample}.purple.sv.vcf.gz
 output_vcf=${input_vcf/.vcf.gz/.ann.vcf.gz}
-
 input_decompressed=${input_vcf/.gz/}
 withBEALN=$output_vcf.withbealn.vcf
 missingBEALN=$output_vcf.missingbealn.vcf
 annotatedBEALN=$output_vcf.withannotation.vcf
+
+if [[ ! -f $input_vcf ]] ; then
+	echo "[ERROR] Missing input VCF $input_vcf"
+	exit 1
+fi
 
 if [[ $(gunzip -c $input_vcf | grep -E "^#" | grep BPI_AF | wc -l) -gt 0 ]] ; then
 	# headers not missing - just decompress as normal
diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -18,24 +18,29 @@ locate_somatics() {
 
 locate_purple_structural_variants() {
     local run_dir=$1
-    local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.vcf.gz")
-    if [ -z ${structural_vcf} ]; then
-        echo "[ERROR] Unable to locate PURPLE structural variants. Exiting."
-        exit 1
-    fi
+    local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.ann.vcf.gz")
+	if [ -z ${structural_vcf} ]; then
+		structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.vcf.gz")
+		if [ -z ${structural_vcf} ]; then
+			echo "[ERROR] Unable to locate PURPLE structural variants. Exiting."
+			exit 1
+		fi
+	fi
     echo ${structural_vcf}
 }
 
 locate_purple_pilot_structural_variants() {
     local run_dir=$1
-    local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.vcf.gz")
-    if [ -z ${structural_vcf} ]; then
-        echo "[ERROR] Unable to locate PURPLE structural variants. Exiting."
-        exit 1
-    fi
+	local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.ann.vcf.gz")
+	if [ -z ${structural_vcf} ]; then
+		structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.vcf.gz")
+		if [ -z ${structural_vcf} ]; then
+			echo "[ERROR] Unable to locate PURPLE structural variants. Exiting."
+			exit 1
+		fi
+	fi
     echo ${structural_vcf}
 }
-
 
 locate_gridss_structural_variants() {
     local run_dir=$1
