Explicitly use pre-viral-annotate SV vcf plus formatting changes

diff --git a/hmftools/gridss/do_run_gridss_2_1_0_breakpoint_position_backport b/hmftools/gridss/do_run_gridss_2_1_0_breakpoint_position_backport
--- a/hmftools/gridss/do_run_gridss_2_1_0_breakpoint_position_backport
+++ b/hmftools/gridss/do_run_gridss_2_1_0_breakpoint_position_backport
@@ -1,7 +1,5 @@
-#!/bin/bash
-#
-# Adjusts the breakpoint position to match GRIDSS 2.1.0 calling positions
-#
+#!/usr/bin/env bash
+
 source do_run_gridss_lib
 
 export PATH=${base_path}/tools/bedops_v2.4.30/:$PATH
@@ -28,22 +26,22 @@ fi
 
 # check that the assembly actually exists
 if [ ! -f ${assembly_sv_bam} ] ; then
-	echo "Missing $assembly_sv_bam"
-	exit 1
+	  echo "Missing $assembly_sv_bam"
+	  exit 1
 fi
 
 if [ -z ${original_vcf} ]; then
-	echo "Unable to locate raw gridss structural variants. Exiting."
-	exit 1
+	  echo "Unable to locate raw gridss structural variants. Exiting."
+	  exit 1
 fi
 
 if [ -d "$out_dir" ] ; then
-	echo "Backport processing directory $out_dir found."
+	  echo "Backport processing directory $out_dir found."
 else
-	echo "Creating ${out_dir}"
-	mkdir -p ${out_dir}/tmp
-	chmod 775 ${out_dir}
-	rsync -r --exclude=*.bam --exclude=*.bai --exclude=breakpoint_position_backport --exclude=*vcf* --exclude=jobs --exclude=logs $(dirname ${full_vcf})/ ${out_dir}
+	  echo "Creating ${out_dir}"
+	  mkdir -p ${out_dir}/tmp
+	  chmod 775 ${out_dir}
+	  rsync -r --exclude=*.bam --exclude=*.bai --exclude=breakpoint_position_backport --exclude=*vcf* --exclude=jobs --exclude=logs $(dirname ${full_vcf})/ ${out_dir}
 fi
 
 normal_bam=${out_dir}/$(basename ${normal_bam})
@@ -59,7 +57,8 @@ gridss_jvm_args="
 		-Dsamjdk.use_async_io_write_tribble=true
 		-Dsamjdk.buffer_size=2097152
 		-cp $gridss_jar "
-	gridss_common_args="
+
+gridss_common_args="
 		TMP_DIR=$out_dir/tmp
 		WORKING_DIR=$out_dir
 		REFERENCE_SEQUENCE=$ref_genome "
@@ -75,14 +74,15 @@ ln -s empty.bam ${tumor_bam}
 mkdir -p ${normal_bam}.gridss.working/ ${tumor_bam}.gridss.working/
 ln -s ../empty.bam ${normal_bam}.gridss.working/$(basename ${normal_bam}).sv.bam
 ln -s ../empty.bam ${tumor_bam}.gridss.working/$(basename ${tumor_bam}).sv.bam
-if [[ ! -f ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}) ]] ; then
-	# Mock input files because GRIDSS needs these as positional arguments even though the reads are ignored
-	echo "Generating empty bam from $assembly_sv_bam"
-	samtools view -H ${assembly_sv_bam} | samtools view -b - > ${out_dir}/empty.bam
-	
-	gunzip -c ${raw_somatic_vcf} | vcf2bed | cut -f 1-3 | bedops --range 2000 --everything /dev/stdin > ${region_bed}
 
-	java -Xmx2G ${gridss_jvm_args} gridss.ExtractFullReads \
+if [[ ! -f ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}) ]] ; then
+	  # Mock input files because GRIDSS needs these as positional arguments even though the reads are ignored
+	  echo "Generating empty bam from $assembly_sv_bam"
+	  samtools view -H ${assembly_sv_bam} | samtools view -b - > ${out_dir}/empty.bam
+	
+	  gunzip -c ${raw_somatic_vcf} | vcf2bed | cut -f 1-3 | bedops --range 2000 --everything /dev/stdin > ${region_bed}
+
+	  java -Xmx2G ${gridss_jvm_args} gridss.ExtractFullReads \
 		 I=${assembly_sv_bam} \
 		 O=${assembly_bam} \
 		 R=${ref_genome} \
@@ -90,45 +90,46 @@ if [[ ! -f ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${as
 		 TMP_DIR=${out_dir} \
 		 REGION_BED=${region_bed} | exit 1
 
-	java -Xmx6G ${gridss_jvm_args} \
-		-Dgridss.async.buffersize=16 \
-		-Dgridss.output_to_temp_file=true \
-		gridss.SoftClipsToSplitReads \
-		${gridss_common_args} \
-		I=${assembly_bam} \
-		O=${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}) \
-		REALIGN_EXISTING_SPLIT_READS=true \
-		REALIGN_ENTIRE_READ=true \
-		WRITE_OA=false \
-		WORKER_THREADS=${threads} | exit 1
+	  java -Xmx6G ${gridss_jvm_args} \
+        -Dgridss.async.buffersize=16 \
+        -Dgridss.output_to_temp_file=true \
+        gridss.SoftClipsToSplitReads \
+        ${gridss_common_args} \
+        I=${assembly_bam} \
+        O=${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}) \
+        REALIGN_EXISTING_SPLIT_READS=true \
+        REALIGN_ENTIRE_READ=true \
+        WRITE_OA=false \
+        WORKER_THREADS=${threads} | exit 1
 fi
-if [[ ! -f ${corrected_vcf}.gz ]] ; then
-	if [[ ! -f ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}).full.bam ]]; then
-		mv ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}) ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}).full.bam
-		rm ${out_dir}/$(basename ${assembly_bam}).gridss.working/*.bai
-	fi
-	gunzip -c ${raw_somatic_vcf} | tr ';' '\n' | grep BEID= | cut -b 6- | tr ',' '\n' | sort | uniq > ${out_dir}/assembly_ids.txt
-	echo "@HD" >> ${out_dir}/assembly_ids.txt
-	echo "@SQ" >> ${out_dir}/assembly_ids.txt
-	samtools view -h ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}).full.bam | fgrep -f ${out_dir}/assembly_ids.txt | samtools view -b - > ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam})
-	samtools index ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam})
-	unadjusted_vcf=${out_dir}/$(basename ${somatic_vcf}).unadjusted.vcf
-	java -Xmx4G ${gridss_jvm_args} gridss.AllocateEvidence \
-		ALLOCATE_READS=false \
-		I=${normal_bam} \
-		I=${tumor_bam} \
-		ASSEMBLY=${assembly_bam} \
-		INPUT_VCF=${raw_somatic_vcf} \
-		OUTPUT_VCF=${unadjusted_vcf} \
-		${gridss_common_args} \
-		CONFIGURATION_FILE=${gridss_config_file} \
-		WORKER_THREADS=${threads} | exit 1
 
-	# Need to feed back to R to adjust nominal homology call position back to match gridss_somatic_filter
-	Rscript ${libgridss}/gridss_adjust_call_positions.R -i ${unadjusted_vcf} -o ${corrected_vcf} -s ${libgridss}
-	rm ${unadjusted_vcf}
-	mv ${corrected_vcf}.bgz ${corrected_vcf}.gz
-	mv ${corrected_vcf}.bgz.tbi ${corrected_vcf}.gz.tbi
+if [[ ! -f ${corrected_vcf}.gz ]] ; then
+	  if [[ ! -f ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}).full.bam ]]; then
+		    mv ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}) ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}).full.bam
+		    rm ${out_dir}/$(basename ${assembly_bam}).gridss.working/*.bai
+	  fi
+    gunzip -c ${raw_somatic_vcf} | tr ';' '\n' | grep BEID= | cut -b 6- | tr ',' '\n' | sort | uniq > ${out_dir}/assembly_ids.txt
+    echo "@HD" >> ${out_dir}/assembly_ids.txt
+    echo "@SQ" >> ${out_dir}/assembly_ids.txt
+    samtools view -h ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam}).full.bam | fgrep -f ${out_dir}/assembly_ids.txt | samtools view -b - > ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam})
+    samtools index ${out_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_sv_bam})
+    unadjusted_vcf=${out_dir}/$(basename ${somatic_vcf}).unadjusted.vcf
+    java -Xmx4G ${gridss_jvm_args} gridss.AllocateEvidence \
+        ALLOCATE_READS=false \
+        I=${normal_bam} \
+        I=${tumor_bam} \
+        ASSEMBLY=${assembly_bam} \
+        INPUT_VCF=${raw_somatic_vcf} \
+        OUTPUT_VCF=${unadjusted_vcf} \
+        ${gridss_common_args} \
+        CONFIGURATION_FILE=${gridss_config_file} \
+        WORKER_THREADS=${threads} | exit 1
+
+    # Need to feed back to R to adjust nominal homology call position back to match gridss_somatic_filter
+    Rscript ${libgridss}/gridss_adjust_call_positions.R -i ${unadjusted_vcf} -o ${corrected_vcf} -s ${libgridss}
+    rm ${unadjusted_vcf}
+    mv ${corrected_vcf}.bgz ${corrected_vcf}.gz
+    mv ${corrected_vcf}.bgz.tbi ${corrected_vcf}.gz.tbi
 fi
 
 
diff --git a/hmftools/gridss/do_run_gridss_lib b/hmftools/gridss/do_run_gridss_lib
--- a/hmftools/gridss/do_run_gridss_lib
+++ b/hmftools/gridss/do_run_gridss_lib
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ulimit -n $(ulimit -Hn)
 
@@ -7,18 +7,18 @@ gridss_jar=$1 && shift
 threads=$1 && shift
 
 if [[ ! -f ${gridss_jar} ]] ; then
-	echo "Missing GRIDSS jar $gridss_jar. Aborting" 1>&2
-	exit 1
+	  echo "Missing GRIDSS jar $gridss_jar. Aborting" 1>&2
+	  exit 1
 fi
 
 if [[ "$threads" == "" ]] ; then
-	threads=$(nproc)
+	  threads=$(nproc)
 fi
 
 base_path="/data/common"
-if [ -z "`hostname | grep datastore`" ]; then
-	# Common folder does not exist on crunches...
-	base_path="/data"
+if [ -z "$(hostname | grep datastore)" ]; then
+	  # Common folder does not exist on crunches...
+	  base_path="/data"
 fi
 
 config_dir=${base_path}/dbs/gridss
@@ -27,16 +27,16 @@ export PATH=${base_path}/tools/bwa_v0.7.17/:$PATH
 export PATH=$PATH:${base_path}/tools/samtools_v1.2/
 
 if which bwa > /dev/null ; then
-	echo -n
+	  echo -n
 else
-	echo "Missing bwa. Aborting"
-	exit 1
+	  echo "Missing bwa. Aborting"
+	  exit 1
 fi
 if which samtools > /dev/null ; then
-	echo -n
+	  echo -n
 else
-	echo "Missing samtools. Aborting"
-	exit 1
+	  echo "Missing samtools. Aborting"
+	  exit 1
 fi
 
 ref_genome=${base_path}/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
@@ -63,46 +63,48 @@ log_dir=${gridss_dir}/logs/
 log_prefix=${log_dir}/$HOSTNAME.$$
 blacklist=${config_dir}/ENCFF001TDO.bed
 
-prefix=`dirname $(readlink $0 || echo $0)`
+prefix=$(dirname $(readlink $0 || echo $0))
 gridss_config_file=${prefix}/gridss.properties
 
 gridss_threshold_coverage=10000
 gridss_jvm_args="
-	-ea
-	-Dsamjdk.create_index=true
-	-Dsamjdk.use_async_io_read_samtools=true
-	-Dsamjdk.use_async_io_write_samtools=true
-	-Dsamjdk.use_async_io_write_tribble=true
-	-Dsamjdk.buffer_size=2097152
-	-cp $gridss_jar "
+	  -ea
+	  -Dsamjdk.create_index=true
+	  -Dsamjdk.use_async_io_read_samtools=true
+	  -Dsamjdk.use_async_io_write_samtools=true
+	  -Dsamjdk.use_async_io_write_tribble=true
+	  -Dsamjdk.buffer_size=2097152
+	  -cp $gridss_jar "
 gridss_common_args="
-	TMP_DIR=$gridss_dir 
-	WORKING_DIR=$gridss_dir
-	REFERENCE_SEQUENCE=$ref_genome "
+	  TMP_DIR=$gridss_dir
+	  WORKING_DIR=$gridss_dir
+	  REFERENCE_SEQUENCE=$ref_genome "
 
 mkdir -p ${gridss_dir} ${log_dir}
 
 function assert_preprocessing_complete() {
-	if [[ ! -f ${gridss_dir}/$(basename ${normal_bam}).gridss.working/$(basename ${normal_bam}).sv.bam ]] ; then
-		echo "Normal bam preprocessing not complete. Terminating." 1>&2
-		exit 1
-	fi
-	if [[ ! -f ${gridss_dir}/$(basename ${tumor_bam}).gridss.working/$(basename ${tumor_bam}).sv.bam ]] ; then
-		echo "Tumor bam preprocessing not complete. Terminating." 1>&2
-		exit 1
-	fi
+	  if [[ ! -f ${gridss_dir}/$(basename ${normal_bam}).gridss.working/$(basename ${normal_bam}).sv.bam ]] ; then
+		    echo "Normal bam preprocessing not complete. Terminating." 1>&2
+		    exit 1
+	  fi
+	  if [[ ! -f ${gridss_dir}/$(basename ${tumor_bam}).gridss.working/$(basename ${tumor_bam}).sv.bam ]] ; then
+		    echo "Tumor bam preprocessing not complete. Terminating." 1>&2
+		    exit 1
+	  fi
 }
+
 function assert_assembly_complete() {
-	if [[ ! -f ${gridss_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_bam}).sv.bam ]] ; then
-		echo "Assembly not complete. Terminating." 1>&2
-		exit 1
-	fi
+	  if [[ ! -f ${gridss_dir}/$(basename ${assembly_bam}).gridss.working/$(basename ${assembly_bam}).sv.bam ]] ; then
+		    echo "Assembly not complete. Terminating." 1>&2
+		    exit 1
+	  fi
 }
+
 function assert_calling_complete() {
-	if [[ ! -f ${gridss_raw_vcf}.unannotated.vcf ]] ; then
-		echo "Variant calling not complete. Terminating." 1>&2
-		exit 1
-	fi
+	  if [[ ! -f ${gridss_raw_vcf}.unannotated.vcf ]] ; then
+		    echo "Variant calling not complete. Terminating." 1>&2
+		    exit 1
+	  fi
 }
 
 
diff --git a/hmftools/gridss/do_run_gridss_preprocess b/hmftools/gridss/do_run_gridss_preprocess
--- a/hmftools/gridss/do_run_gridss_preprocess
+++ b/hmftools/gridss/do_run_gridss_preprocess
@@ -1,25 +1,23 @@
-#!/bin/bash
-#
-# Performs GRIDSS preprocessing
-#
+#!/usr/bin/env bash
+
 source do_run_gridss_lib
 
 # BAM to process. "normal" and "tumor"
 tum_normal_arg=$1 && shift
 
 if [[ "$tum_normal_arg" == "normal" ]] ; then
-	bam_sample=${ref_sample}
+	  bam_sample=${ref_sample}
 elif [[ "$tum_normal_arg" == "tumor" ]] ; then
-	bam_sample=${tumor_sample}
+	  bam_sample=${tumor_sample}
 else
-	echo "Please specify \"normal\" or \"tumor\" to indicate which BAM to preprocessing. Aborting" 1>&2
-	exit 1
+	  echo "Please specify \"normal\" or \"tumor\" to indicate which BAM to preprocessing. Aborting" 1>&2
+	  exit 1
 fi
 bam=${run_dir}/${bam_sample}/mapping/${bam_sample}_dedup.realigned.bam
 insert_size_metrics=${run_dir}/QCStats/${bam_sample}_dedup/${bam_sample}_dedup_MultipleMetrics.txt.insert_size_metrics
 
 if [[ ! ${bam}.bai ]] ; then
-	samtools index ${bam}
+	  samtools index ${bam}
 fi
 
 if [[ ! -f ${insert_size_metrics} ]] ; then
@@ -28,8 +26,8 @@ if [[ ! -f ${insert_size_metrics} ]] ; then
 fi
 
 if [[ ! -f "$bam" ]] ; then
-	echo "Missing input bam $bam. Aborting" 1>&2
-	exit 1
+	  echo "Missing input bam $bam. Aborting" 1>&2
+	  exit 1
 fi
 
 working_dir=${gridss_dir}/$(basename ${bam}).gridss.working
@@ -108,8 +106,8 @@ fi
 wait
 
 if [[ ! -f  ${sv_bam} ]] ; then
-	echo "$(date) Preprocessing failed. Missing $sv_bam " 1>&2
-	exit 1
+	  echo "$(date) Preprocessing failed. Missing $sv_bam " 1>&2
+	  exit 1
 else
-	echo "$(date) Preprocessing complete"
+	  echo "$(date) Preprocessing complete"
 fi
diff --git a/hmftools/metadata/locate_files b/hmftools/metadata/locate_files
--- a/hmftools/metadata/locate_files
+++ b/hmftools/metadata/locate_files
@@ -193,11 +193,31 @@ locate_purple_structural_variants() {
     echo ${structural_vcf}
 }
 
+locate_purple_pre_viral_annotate_structural_variants() {
+    local run_dir=$1
+    local structural_vcf=$(find -L ${run_dir}/purple/ -type f -name "*.purple.sv.vcf.gz")
+    if [ -z ${structural_vcf} ]; then
+        echo "[ERROR] Unable to locate purple pre-viral-annotate structural variants. Exiting." >&2
+        exit 1
+    fi
+    echo ${structural_vcf}
+}
+
 locate_purple_pilot_structural_variants() {
     local run_dir=$1
 	  local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.ann.vcf.gz")
     if [ -z ${structural_vcf} ]; then
         echo "[ERROR] Unable to locate purple pilot structural variants. Exiting." >&2
+        exit 1
+    fi
+    echo ${structural_vcf}
+}
+
+locate_purple_pilot_pre_viral_annotate_structural_variants() {
+    local run_dir=$1
+    local structural_vcf=$(find -L ${run_dir}/purple_pilot/ -type f -name "*.purple.sv.vcf.gz")
+    if [ -z ${structural_vcf} ]; then
+        echo "[ERROR] Unable to locate purple pilot pre-viral-annotate structural variants. Exiting." >&2
         exit 1
     fi
     echo ${structural_vcf}
