Added restart from partial failure capability to do_run_gridss_* Switched to non-streaming realignment since streaming alignment results in high memory usage due to large bwa buffer sizes

diff --git a/hmftools/gridss/do_run_gridss_lib b/hmftools/gridss/do_run_gridss_lib
--- a/hmftools/gridss/do_run_gridss_lib
+++ b/hmftools/gridss/do_run_gridss_lib
@@ -18,7 +18,7 @@ if [[ "$threads" == "" ]] ; then
 	threads=$(nproc)
 fi
 
-export PATH=$PATH:$base_path/tools/bwa_v0.7.5a/
+
 config_dir=$run_dir/../
 
 base_path="/data/common"
@@ -27,9 +27,25 @@ if [ -z "`hostname | grep datastore`" ]; then
 	base_path="/data"
 fi
 
+export PATH=$PATH:$base_path/tools/bwa_v0.7.5a/
+export PATH=$PATH:$base_path/tools/samtools_v1.2/
+
+if which bwa > /dev/null ; then
+	echo -n
+else
+	echo "Missing bwa. Aborting"
+	exit 1
+fi
+if which samtools > /dev/null ; then
+	echo -n
+else
+	echo "Missing bwa. Aborting"
+	exit 1
+fi
+
 ref_genome=$base_path/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
 # TEMP local testing
-ref_genome=/mnt/d/hartwig/refdata/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
+#ref_genome=/mnt/d/hartwig/refdata/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta
 
 source load_metadata
 ref_sample=$(load_ref_sample_from_metadata $run_dir)
diff --git a/hmftools/gridss/do_run_gridss_preprocess b/hmftools/gridss/do_run_gridss_preprocess
--- a/hmftools/gridss/do_run_gridss_preprocess
+++ b/hmftools/gridss/do_run_gridss_preprocess
@@ -6,11 +6,6 @@ source do_run_gridss_lib
 
 # BAM to process. "normal" and "tumor"
 tum_normal_arg=$1 && shift
-threads=$1 && shift
-
-if [[ "$threads" == "" ]] ; then
-	threads=$(nproc)
-fi
 
 if [[ "$tum_normal_arg" == "normal" ]] ; then
 	bam_sample=$ref_sample
@@ -55,53 +50,64 @@ if [[ ! -f $working_dir/$(basename $bam).idsv_metrics ]] ; then
 		PROGRAM=CollectInsertSizeMetrics \
 		2> $log_prefix.$bam_sample.CollectGridssMetrics.log &
 fi
-java -Xmx256M $gridss_jvm_args \
-	gridss.ExtractSVReads \
-	$gridss_common_args \
-	I=$bam \
-	O=/dev/stdout \
-	COMPRESSION_LEVEL=0 \
-	METRICS_OUTPUT=$INPUT_WORKING_PREFIX.sv_metrics \
-	INSERT_SIZE_METRICS=$insert_size_metrics \
-	UNMAPPED_READS=false \
-	MIN_CLIP_LENGTH=5 \
-	INCLUDE_DUPLICATES=true \
-	2> $log_prefix.$bam_sample.ExtractSVReads.log | \
-samtools sort -n -l 0 -@ $threads -o $tmp_bam - && \
-java -Xmx256M $gridss_jvm_args \
-	gridss.ComputeSamTags \
-	$gridss_common_args \
-	COMPRESSION_LEVEL=0 \
-	I=$tmp_bam \
-	O=/dev/stdout \
-	RECALCULATE_SA_SUPPLEMENTARY=true \
-	SOFTEN_HARD_CLIPS=true \
-	FIX_MATE_INFORMATION=true \
-	FIX_DUPLICATE_FLAG=true \
-	TAGS=null \
-	TAGS=NM \
-	TAGS=SA \
-	TAGS=R2 \
-	TAGS=Q2 \
-	TAGS=MC \
-	TAGS=MQ \
-	ASSUME_SORTED=true \
-	2> $log_prefix.$bam_sample.ComputeSamTags.log | \
-java -Xmx3G $gridss_jvm_args \
-	gridss.SoftClipsToSplitReads \
-	$gridss_common_args \
-	COMPRESSION_LEVEL=0 \
-	I=/dev/stdin \
-	O=/dev/stdout \
-	ALIGNER_STREAMING=true \
-	WORKER_THREADS=$threads \
-	2> $log_prefix.$bam_sample.SoftClipsToSplitReads.log | \
-samtools sort -@ $threads -o ${sv_bam} - && \
-rm $tmp_bam
-if [[ ! -f $sv_bam.bai ]] ; then
-	samtools index $sv_bam
+if [[ ! -f $sv_bam ]] ; then
+	if [[ ! -f $tmp_bam ]] ; then
+		echo $(date) ExtractSVReads
+		java -Xmx256M $gridss_jvm_args \
+			gridss.ExtractSVReads \
+			$gridss_common_args \
+			I=$bam \
+			O=/dev/stdout \
+			COMPRESSION_LEVEL=0 \
+			METRICS_OUTPUT=$INPUT_WORKING_PREFIX.sv_metrics \
+			INSERT_SIZE_METRICS=$insert_size_metrics \
+			UNMAPPED_READS=false \
+			MIN_CLIP_LENGTH=5 \
+			INCLUDE_DUPLICATES=true \
+			2> $log_prefix.$bam_sample.ExtractSVReads.log | \
+		samtools sort -O bam -T ${bam_sample}.samtools.sort.tmp. -n -l 0 -@ $threads -o $tmp_bam -  ||
+		exit 1
+	fi
+	if [[ ! -f ${sv_bam}.tmp.bam ]] ; then
+		java -Xmx3G $gridss_jvm_args \
+			gridss.ComputeSamTags \
+			$gridss_common_args \
+			COMPRESSION_LEVEL=0 \
+			I=$tmp_bam \
+			O=/dev/stdout \
+			RECALCULATE_SA_SUPPLEMENTARY=true \
+			SOFTEN_HARD_CLIPS=true \
+			FIX_MATE_INFORMATION=true \
+			FIX_DUPLICATE_FLAG=true \
+			TAGS=null \
+			TAGS=NM \
+			TAGS=SA \
+			TAGS=R2 \
+			TAGS=Q2 \
+			TAGS=MC \
+			TAGS=MQ \
+			ASSUME_SORTED=true \
+			2> $log_prefix.$bam_sample.ComputeSamTags.log | \
+		samtools sort -O bam -T ${bam_sample}.samtools.sort.tmp. -@ $threads -o ${sv_bam}.tmp.bam - ||
+		exit 1
+	fi
+	java -Xmx3G $gridss_jvm_args \
+		-Dgridss.gridss.output_to_temp_file=true \
+		gridss.SoftClipsToSplitReads \
+		$gridss_common_args \
+		I=${sv_bam}.tmp.bam \
+		O=${sv_bam} \
+		WORKER_THREADS=$threads \
+		2> $log_prefix.$bam_sample.SoftClipsToSplitReads.log && \
+	rm $tmp_bam ${sv_bam}.tmp.bam
 fi
+
 # Wait for metric extraction to finish
-if [[ ! -f $working_dir/$(basename $bam).idsv_metrics ]] ; then
-	wait
+wait
+
+if [[ ! -f  $sv_bam ]] ; then
+	echo "$(date) Preprocessing failed. Missing $sv_bam " 1>&2
+	exit 1
+else
+	echo "$(date) Preprocessing complete"
 fi
