Add support for pv5 in gridss somatic filter

diff --git a/hmftools/gridss/do_run_gridss_somatic_filter b/hmftools/gridss/do_run_gridss_somatic_filter
--- a/hmftools/gridss/do_run_gridss_somatic_filter
+++ b/hmftools/gridss/do_run_gridss_somatic_filter
@@ -10,16 +10,18 @@ tumor_sample=$(load_tumor_sample_from_metadata ${run_dir})
 
 # GRIDSS somatic filtering should use the raw GRIDSS VCF.
 original_vcf=$(find -L ${run_dir}/structuralVariants/gridss/*/ -type f -name *gridss.vcf.gz)
-if [ -z ${original_vcf} ]
-then
-    echo "[ERROR] Unable to locate raw gridss structural variants. Exiting."
-    exit 1
+if [ -z ${original_vcf} ]; then
+    # Support for pv5 location of raw GRIDSS VCF.
+    original_vcf=$(find -L ${run_dir}/structural_caller/ -type f -name *.annotated.vcf.gz)
+    if [ -z ${original_vcf} ]; then
+        echo "[ERROR] Unable to locate raw gridss structural variants. Exiting."
+        exit 1
+    fi
 fi
 
 output_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.vcf
 full_vcf=$(dirname ${original_vcf})/${tumor_sample}.gridss.somatic.full.vcf
-if [ -a ${output_vcf}.gz ]
-then
+if [ -a ${output_vcf}.gz ]; then
     echo "[WARN] Already processed gridss structural variants. Exiting."
     exit 1
 fi
