DEV-2182: replace http with curl in manual_fastq_register POST

diff --git a/ops/manual_fastq_register b/ops/manual_fastq_register
--- a/ops/manual_fastq_register
+++ b/ops/manual_fastq_register
@@ -1,46 +1,44 @@
 #!/usr/bin/env bash
 
 source message_functions || exit 1
+command -v hmf_api_get > /dev/null || die "Dependency hmf_api_get not found"
 
-api_url='http://api.prod-1/hmf/v1'
-
-script_name=$(basename "$0")
-
-hmfapi () {
-    http --ignore-stdin "$@"
-}
-
-if [[ -z "$1" || $1 == "-h" || $1 == "--help" ]]; then
+if [[ -z "$1" || -z "$2" || $1 == "-h" || $1 == "--help" ]]; then
+    script=$(basename "$0")
     echo "---"
-    echo " Usage: ${script_name} \${barcode} \${fastqDir}"
-    echo "        ${script_name} FR12345678 /path/to/fastq/files/"
+    echo " Usage: ${script} <barcode> <fastq-dir>"
+    echo "        ${script} FR12345678 /path/to/fastq/files/"
+    echo "        ${script} FR12345678_{sample-name} gs://cram2fastq/{sample-name}"
     echo "---"
     exit 1
 fi
 
 barcode=$1 && shift
 fastq_dir=$1 && shift
+api_url='http://api.prod-1/hmf/v1'
 
 sample_name=""
-sample_id=$(curl -s "${api_url}/samples?barcode=${barcode}" | jq '.[].id')
+sample_id=$(hmf_api_get "samples?barcode=${barcode}" | jq -r '.[-1].id')
 
-if [[ -z "${sample_id}" ]]; then
-    error "Barcode not found at API (${barcode})"
+if [[ -z "${sample_id}" || "$sample_id" == "null" ]]; then
+    die "Barcode not found (${barcode})"
+else
+    info "Barcode found (sample id = ${sample_id})"
 fi
 
 ## find all R1 fastq files
 if [[ ${fastq_dir} == gs://* ]]; then
-  info "FASTQ dir is a bucket"
-  R1_fastq_files=$(gsutil ls "${fastq_dir%/}/*_R1_*" | xargs -I% basename % \;)
+    info "FASTQ dir is a bucket ($fastq_dir)"
+    R1_fastq_files=$(gsutil ls "${fastq_dir%/}/*_R1_*" | xargs -I% basename % \;)
 else
-  info "FASTQ dir is a local dir"
-  R1_fastq_files=$(find "${fastq_dir}" -name "*_R1_*.fastq.gz" -exec basename {} \;)
+    info "FASTQ dir is a local dir ($fastq_dir)"
+    R1_fastq_files=$(find "${fastq_dir}" -name "*_R1_*.fastq.gz" -exec basename {} \;)
 fi
 
 ## make sure the FASTQ files contain only ONE sample
 sample_count=$(echo "${R1_fastq_files}" | cut -d"_" -f1 | sort | uniq | wc -l)
 if [[ ${sample_count} -ne 1 ]]; then
-    error "FASTQ files in dir should be from one sample (found ${sample_count} samples in dir \"${fastq_dir}\")"
+    die "FASTQ files in dir should be from one sample (found ${sample_count} samples in dir \"${fastq_dir}\")"
 else
     sample_name=$(echo "${R1_fastq_files}" | cut -d"_" -f1 | sort | uniq)
 fi
@@ -54,11 +52,12 @@ echo "${R1_fastq_files}" | while read -r R1; do
         warn "Somehow R1 found but R2 file does not exist (${R2}) so SKIPPING this pair."
     else
         info "Registering fastq R1/R2 pair (name_r1=${R1})"
-        hmfapi --print=b POST "${api_url}/fastq" name_r1="${R1}" name_r2="${R2}" bucket="hmf-fastq-storage" sample_id="${sample_id}"
+        data=$(printf '{"name_r1": "%s", "name_r2": "%s", "bucket": "%s", "sample_id": %s}' "$R1" "$R2" "hmf-fastq-storage" "$sample_id" )
+        curl --silent --show-error -H "Content-Type: application/json" -H "Accept: application/json" \
+          -X POST "${api_url}/fastq" --data "${data}" || die "cURL POST of FASTQ failed"
     fi
 done
 
-info "Registering sample"
-curl -s --header "Content-type: application/json" \
-    -X PATCH \
-    -d '{"name": "'${sample_name}'", "status": "Pending_QC"}' "${api_url}/samples/${sample_id}"
+new_sample_status="Pending_QC"
+info "Updating sample status to Pending_QC"
+hmf_api_patch -e -c samples -o "$sample_id" -f "status" -v "$new_sample_status"
