Speed up registration json and log moving

diff --git a/ops/move_registration_jsons_and_logs b/ops/move_registration_jsons_and_logs
--- a/ops/move_registration_jsons_and_logs
+++ b/ops/move_registration_jsons_and_logs
@@ -22,22 +22,15 @@ local_registration_jsons_dir=$(locate_sample_registration_registered_jsons_dir) 
 local_new_jsons_dir=$(locate_sample_registration_unregistered_jsons_dir) || die "Could not find local new jsons dir path"
 local_registration_logs_dir=$(locate_sample_registration_logs_dir) || die "Could not find local registration logs dir path"
 
-relevant_logs=$(find "${local_registration_logs_dir}" -name "${registration_date}*${prefix}*") || die "Cannot find local logs"
-for log in ${relevant_logs}; do
-    log_file_name="${log##*/}"
-    in_bucket_path="${logs_bucket}/${log_file_name}"
-    gsutil cp "${log}" "${in_bucket_path}"
-    gsutil -q stat "${in_bucket_path}" || die "Could not copy log ${log_file_name} to bucket"
-done
+info "Copying all logs to bucket"
+gsutil -mq cp "${local_registration_logs_dir}/${registration_date}*${prefix}*" "${logs_bucket}" \
+    || die "Could not copy all logs to bucket"
 
-new_jsons=$(find "${local_new_jsons_dir}" -maxdepth 1 -name "*.json") || die "Cannot find recently registered jsons"
-for json in ${new_jsons}; do
-    json_file_name="${json##*/}"
-    in_bucket_path="${jsons_bucket}/${json_file_name}"
-    gsutil cp "${json}" "${in_bucket_path}"
-    gsutil -q stat "${in_bucket_path}" || die "Could not copy log ${log_file_name} to bucket"
-    mv "${json}" "${local_registration_jsons_dir}/${json_file_name}" || die "Could not move json ${json_file_name} locally"
-done
+info "Copying all jsons to bucket"
+gsutil -mq cp "${local_new_jsons_dir}/*.json" "${jsons_bucket}" || die "Could not upload all jsons to bucket"
+
+info "Moving all jsons to directory for registered samples"
+mv "${local_new_jsons_dir}"/*.json "${local_registration_jsons_dir}/" || die "Could not move all jsons locally"
 
 info "Finished moving new registration jsons and logs"
 
