Add HPC tsv to paddle app

diff --git a/hmftools/paddle/run_paddle_exonic_variant_application b/hmftools/paddle/run_paddle_exonic_variant_application
--- a/hmftools/paddle/run_paddle_exonic_variant_application
+++ b/hmftools/paddle/run_paddle_exonic_variant_application
@@ -2,13 +2,20 @@
 
 output_dir=$1 && shift
 
-if [[ -z "${output_dir}" ]]; then
-    echo "[ERROR] No output dir provided. Exiting" && exit 1;
+if [[ ! -d "${output_dir}" ]]; then
+    echo "[ERROR] Output dir not a directory. Exiting" && exit 1;
 fi
+
+hpc_tsv=${output_dir}/hpc.tsv
+hpc_create_sql=/data/common/repos/scripts/hmftools/paddle/create_hpc_file.sql
+
+echo "[INFO] Writing HPC file to ${hpc_tsv} using ${hpc_create_sql}"
+execute_sql_on_prod ${hpc_create_sql} > ${hpc_tsv}
 
 paddle_jar=/data/common/tools/paddle_pilot/paddle.jar
 
 echo "[INFO] Running paddle exoniic variant application with output dir '${output_dir}'"
 
 java -cp ${paddle_jar} com.hartwig.hmftools.paddle.PaddleExonicVariantsApplication  \
-    -output_dir ${output_dir}
+    -output_dir ${output_dir} \
+    -hpc_tsv ${hpc_tsv}
