Improve usage message for delete_patients_from_clinical_data_feed

diff --git a/actin/clinical/delete_patients_from_clinical_data_feed b/actin/clinical/delete_patients_from_clinical_data_feed
--- a/actin/clinical/delete_patients_from_clinical_data_feed
+++ b/actin/clinical/delete_patients_from_clinical_data_feed
@@ -9,11 +9,11 @@ patient_ids=$@
 working_dir="$(pwd)/delete_actin_clinical_data"
 
 if [[ -z "${earliest_date}" || -z "${patient_ids}" ]]; then
-    error "Parameters missing. Exiting."
+    error "Usage: $0 <earliest date to clean as YYMMDD> <patientID1> [<patientID2>...]"
 fi
 
 create_or_cleanup_dir ${working_dir}
-cd ${working_dir}
+cd ${working_dir} || { echo "unable to cd to ${working_dir}"; exit 1; }
 
 clinical_data_feed_bucket="$(locate_actin_clinical_data_feed_bucket)"
 reference_string="${clinical_data_feed_bucket}/${earliest_date}/"
@@ -35,7 +35,7 @@ for dir in ${dirs_to_clean}; do
     gsutil -u actin-prod -m cp -r ${dir} ${working_dir}
 
     local_dir=$(basename ${dir})
-    cd ${local_dir}
+    cd ${local_dir} || { echo "unable to cd to ${local_dir}"; exit 1; }
     backup_dir="../${local_dir}.backup"
     create_or_cleanup_dir ${backup_dir}
     for questionnaire in $(ls | grep "${patient_id_grep_pattern}"); do
