update runs seletion panel

diff --git a/gcp/check_panel_runs_status b/gcp/check_panel_runs_status
--- a/gcp/check_panel_runs_status
+++ b/gcp/check_panel_runs_status
@@ -14,9 +14,7 @@ main () {
     # Create all required run collections
     echo "## Retrieving required information from API..."
     ##mapfile -t non_db_entities < <(hmf_api_get "entities" | jq -r '.[] | select(.add_to_db == false) | .name')
-    all_runs=$(hmf_api_get "runs") || die "Unable to retrieve runs from API"
-    runs=$(echo "${all_runs}" | jq '[.[] | select(.ini == "Targeted.ini")]') || die "Unable to select runs by ini"
-
+    runs=$(hmf_api_get "runs?ini=Targeted.ini" | jq '[.[] | select(.context != "RESEARCH")]' | jq -s '.') || die "Unable to retrieve Somatic runs from API"
 
     echo "## Creating run collections to check..."
     all_non_fini_runs=$(echo "${runs}" | jq '[.[] | select(.status == "Pending" or .status == "Processing" or .status == "Failed" or .status == "Invalidated"  or .status == "Waiting")]')
