Some additional error checking in GCP scripts

diff --git a/gcp/do_archive_directory_to_gcp b/gcp/do_archive_directory_to_gcp
--- a/gcp/do_archive_directory_to_gcp
+++ b/gcp/do_archive_directory_to_gcp
@@ -1,12 +1,18 @@
 #!/usr/bin/env bash
 
+source gcp_functions
+
 local_path=$1 && shift
 remote_archive_dir=$1 && shift
 
-gcloud auth activate-service-account --key-file=/data/common/dbs/gcp_credentials/hmf-archive
+if [[ -z "${local_path}" ]] || [[ -z "${remote_archive_dir}" ]]; then
+    echo "[ERROR] Not all input parameters provided to $(basename $0). Exiting"
+    exit 1
+fi
+
+switch_to_hmf_archive_service_account
 
 # -d = delete files on GS that no longer exist on datastore
 # -e = exclude symlinks to go to GS
 # -r = Recursive
-# TODO: consider granting hmf-download read-only access?
 gsutil -u hmf-database -m rsync -d -r -e ${local_path} gs://hmf-archive/${remote_archive_dir}
diff --git a/gcp/do_download_bam_for_sample b/gcp/do_download_bam_for_sample
--- a/gcp/do_download_bam_for_sample
+++ b/gcp/do_download_bam_for_sample
@@ -1,14 +1,21 @@
 #!/usr/bin/env bash
 
+source gcp_functions
+
 set=$1 && shift
 bucket=$1 && shift
 sample_id=$1 && shift
+
+if [[ -z "${set}" ]] || [[ -z "${bucket}" ]] || [[ -z "${sample_id}" ]]; then
+    echo "[ERROR] Not all input parameters provided to $(basename $0). Exiting"
+    exit 1
+fi
 
 gs_path=gs://${bucket}/${set}
 ds_path=/data/gcp/bam_downloads/bams_${set}
 
 echo "[INFO] Downloading bam for ${sample_id} from ${gs_path}"
-gcloud auth activate-service-account --key-file=/data/common/dbs/gcp_credentials/hmf-download
+switch_to_hmf_download_service_account
 
 bam_path=$(gsutil -u hmf-database ls -r ${gs_path} | grep -Po "[^\s]*(mapping|aligner)/${sample_id}(_dedup)?(.realigned)?.bam$")
 
