Added a check for minimal local entries when arching to GCP

diff --git a/gcp/do_archive_directory_to_gcp b/gcp/do_archive_directory_to_gcp
--- a/gcp/do_archive_directory_to_gcp
+++ b/gcp/do_archive_directory_to_gcp
@@ -5,8 +5,19 @@ source gcp_functions
 local_path=$1 && shift
 remote_archive_dir=$1 && shift
 
+minimal_local_entries=0
+if [[ "$#" -gt 2 ]]; then
+    minimal_local_entries=$1 && shift
+fi
+
 if [[ -z "${local_path}" ]] || [[ -z "${remote_archive_dir}" ]]; then
     echo "[ERROR] Not all input parameters provided to $(basename $0). Exiting"
+    exit 1
+fi
+
+local_entry_count=$(ls ${local_path} | wc -l)
+if [[ ${local_entry_count} -lt ${minimal_local_entries} ]]; then
+    echo "[WARN] Number of entries in ${local_path} is ${local_entry_count} which is less than required ${minimal_local_entries}. Exiting"
     exit 1
 fi
 
