More usage of message functions where appropriate

diff --git a/gcp/do_download_cram_for_sample b/gcp/do_download_cram_for_sample
--- a/gcp/do_download_cram_for_sample
+++ b/gcp/do_download_cram_for_sample
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
-source gcp_functions
+source gcp_functions || exit 1
+source message_functions || exit 1
 
 biopsy=$1 && shift
 set=$1 && shift
 sample=$1 && shift
 
 if [[ -z "${biopsy}" ]] || [[ -z "${sample}" ]]; then
-    echo "[ERROR] Not all input parameters provided to $(basename $0). Exiting"
-    exit 1
+    error "Not all input parameters provided to $(basename $0). Exiting"
 fi
 
 ds_path="/data/gcp/cram_downloads/${sample}_cram"
@@ -21,12 +21,11 @@ api_request+="&datatype=aligned_reads"
 cram_url=$(hmf_api_get "${api_request}" | jq -r ".${sample}.path")
 
 if [[ -z "${cram_url}" ]]; then
-    echo "[ERROR] $(basename $0) unable to construct gs URL to cram. Exiting"
-    exit 1
+    error "$(basename $0) unable to construct gs URL to cram. Exiting"
 fi
 
-echo "[INFO] API provided CRAM URL: ${cram_url}"
-echo "[INFO] Downloading cram to ${ds_path}"
+info "API provided CRAM URL: ${cram_url}"
+info "Downloading cram to ${ds_path}"
 mkdir -p "${ds_path}"
 switch_to_hmf_ops_service_account
 gsutil -u hmf-database cp "${cram_url}" "${ds_path}/"
diff --git a/gcp/upload_bcl_gcp b/gcp/upload_bcl_gcp
--- a/gcp/upload_bcl_gcp
+++ b/gcp/upload_bcl_gcp
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 source slack_functions || exit 1
+source message_functions || exit 1
 
 flowcells_dir="/data1/illumina_data"
 bucket="bcl-input-prod"
@@ -29,9 +30,9 @@ hmfapi () {
 
 ## Run once at a time
 if [[ -f "${tmp_upload_file}" ]]; then
-    echo "[INFO] Uploading in progress, exiting" && exit 0
+    info "Uploading in progress, exiting" && exit 0
 else
-    echo "[INFO] Creating tmp file (${tmp_upload_file}) to avoid simultaneous uploads"
+    info "Creating tmp file (${tmp_upload_file}) to avoid simultaneous uploads"
     touch "${tmp_upload_file}"
 fi
 
@@ -45,18 +46,18 @@ find "${flowcells_dir}" -mindepth 1 -maxdepth 1 -type d -not -name "TestRuns" -n
     log_file="${log_dir}/${flowcell_name}_${log_suffix}"
 
     if [[ -f "${log_file}" ]]; then
-        echo "[INFO] Flowcell ${flowcell_name} already uploaded: skipping"
+        info "Flowcell ${flowcell_name} already uploaded: skipping"
         continue
     fi
 
     if [[ ! -f "${runinfoxml_path}" ]]; then
         ## we need the run info xml file to get exact flowcell ID
-        echo "[WARN] Flowcell ${flowcell_name} on ${hostname} is missing RunInfo file (${runinfoxml_path}): skipping"
+        warn "Flowcell ${flowcell_name} on ${hostname} is missing RunInfo file (${runinfoxml_path}): skipping"
         continue
     fi
 
     if [[ ! -f "${samplesheet_path}" ]]; then
-        echo "[WARN] Flowcell ${flowcell_name} on ${hostname} is missing SampleSheet (${samplesheet_path}): skipping"
+        warn "Flowcell ${flowcell_name} on ${hostname} is missing SampleSheet (${samplesheet_path}): skipping"
         continue
     fi
 
@@ -65,12 +66,12 @@ find "${flowcells_dir}" -mindepth 1 -maxdepth 1 -type d -not -name "TestRuns" -n
     index=$(echo "${flowcell_name}" | cut -d '_' -f3)
     experiment_name=$(grep ExperimentName "${samplesheet_path}" | cut -d "," -f2)
 
-    echo "[INFO] Working on path \"${flowcell_path}\""
-    echo "[INFO]   Hostname: ${hostname}"
-    echo "[INFO]   Samplesheet: ${samplesheet_path}"
-    echo "[INFO]   Flowcell ID: ${flowcell_id}"
-    echo "[INFO]   Flowcell Name: ${flowcell_name}"
-    echo "[INFO]   Experiment Name: ${experiment_name}"
+    info "Working on path \"${flowcell_path}\""
+    info "  Hostname: ${hostname}"
+    info "  Samplesheet: ${samplesheet_path}"
+    info "  Flowcell ID: ${flowcell_id}"
+    info "  Flowcell Name: ${flowcell_name}"
+    info "  Experiment Name: ${experiment_name}"
 
     flowcell_info="${experiment_name}|${flowcell_id}"
 
@@ -78,50 +79,50 @@ find "${flowcells_dir}" -mindepth 1 -maxdepth 1 -type d -not -name "TestRuns" -n
     #slack_info "[DEBUG/TEST] Working on flowcell (${flowcell_info})"
 
     if [[ -z "${flowcell_id}" ]]; then
-        msg="[WARN] Flowcell is somehow missing flowcell_id (${flowcell_info})"
-        echo "[WARN] ${msg}"
-        slack_warn "${msg}"
+        msg="Flowcell is somehow missing flowcell_id (${flowcell_info})"
+        warn ${msg}
+        slack_warn "[WARN] ${msg}"
         continue
     fi
 
     if [[ ! -f "${rtacomplete_path}" ]]; then
         # Sequencing not finished yet but do pre-register
-        echo "[INFO] Flowcell ${flowcell_name} has no run complete file yet (${rtacomplete_path}): skipping upload"
+        info "Flowcell ${flowcell_name} has no run complete file yet (${rtacomplete_path}): skipping upload"
         flowcell="$(hmfapi GET "${api_url}/hmf/v1/flowcells?flowcell_id=${flowcell_id}")"
         if [[ $(echo "${flowcell}" | jq length) -eq 0 ]]; then
             flowcell_by_name="$(hmfapi GET "${api_url}/hmf/v1/flowcells?name=${experiment_name}")"
             if [[ $(echo "${flowcell_by_name}" | jq length) -eq 0 ]]; then
-                echo "[INFO] Registering new flowcell in API (${flowcell_info})"
+                info "Registering new flowcell in API (${flowcell_info})"
                 slack_info "Registering new flowcell in API (${flowcell_info})"
                 hmfapi POST "${api_url}/hmf/v1/flowcells" name="${experiment_name}" sequencer="${sequencer}" index="${index}" flowcell_id="${flowcell_id}" status=Sequencing > /dev/null;
             else
                 msg="Unable to POST flowcell because name already exists in API (${flowcell_info})!"
-                echo "[WARN] ${msg}"
-                slack_warn "${msg}"
+                warn "${msg}"
+                slack_warn "[WARN] ${msg}"
             fi
         fi
         continue
     fi
 
-    echo "[INFO] Flowcell is ready for uploading BCL (${flowcell_info})"
+    info "Flowcell is ready for uploading BCL (${flowcell_info})"
     find "${flowcell_path}" -name '*.bcl.gz' -or -name '*.cbcl' -or -name '*.bcl.bgzf' | grep bcl > /dev/null
     if [[ $? -ne 0 ]]; then
         msg="Flowcell is ready but has no BCL files, this probably means that the sequencer has failed (${flowcell_info})"
-        echo "[WARN] ${msg}"
-        slack_warn "${msg}"
+        warn "${msg}"
+        slack_warn "[WARN] ${msg}"
         continue
     fi
 
     ## setup rsync cmd excluding un-used and post-sequencing-generated files
-    echo "[INFO] Starting BCL upload (${flowcell_info})"
+    info "Starting BCL upload (${flowcell_info})"
     slack_info "Starting BCL upload (${flowcell_info})"
     gs_path="gs://${bucket}/${flowcell_name}"
     gcloud auth activate-service-account --key-file "${gcp_cred}"
     gsutil -m -o GSUtil:parallel_process_count=7 -o GSUtil:parallel_thread_count=1 rsync -r -x ".*Fastq.*|.*Logs.*|.*Images.*|.*Config.*|.*PeriodicSaveRates.*|.*fastq\.gz|.*BaseCalls/[^L].*" "${flowcell_path}" "${gs_path}"
     if [[ $? -ne 0 ]]; then
         msg="Something went wrong with BCL upload of '${flowcell_path}' (${flowcell_info})"
-        echo "[WARN] ${msg}"
-        slack_warn "${msg}"
+        warn "${msg}"
+        slack_warn "[WARN] ${msg}"
         continue
     fi
 
@@ -135,29 +136,29 @@ find "${flowcells_dir}" -mindepth 1 -maxdepth 1 -type d -not -name "TestRuns" -n
         api_id=$(echo "${flowcell}" | jq -r .[0].id);
         status=$(echo "${flowcell}" | jq -r .[0].status);
 
-        echo "[INFO] Found existing flowcell at ${api_url} with id ${api_id} and status ${status} (${flowcell_info})"
+        info "Found existing flowcell at ${api_url} with id ${api_id} and status ${status} (${flowcell_info})"
 
         if [[ "${status}" == "Testing" ]]; then
-            echo "[INFO] Flowcell status is Testing"
+            info "Flowcell status is Testing"
         elif [[ "${status}" == "Sequencing" ]]; then
             msg="Patching flowcell (id:${api_id}) status to Pending (${flowcell_info})"
-            echo "[INFO] ${msg}"
+            info "${msg}"
             hmfapi PATCH "${api_url}/hmf/v1/flowcells/${api_id}" status=Pending index="${index}" sequencer="${sequencer}" bucket="${bucket}" > /dev/null;
         else
             msg="SKIPPING. Would do invalid flowcell transition from ${status} to Pending, check flowcell with id ${api_id} (${flowcell_info})"
-            echo "[WARN] ${msg}"
-            slack_warn "${msg}"
+            warn "${msg}"
+            slack_warn "[WARN] ${msg}"
             continue
         fi
     else
-        echo "[INFO] POST flowcell (${flowcell_id}) to ${api_url} and set pending because BCL has been uploaded"
+        info "POST flowcell (${flowcell_id}) to ${api_url} and set pending because BCL has been uploaded"
         hmfapi POST "${api_url}/hmf/v1/flowcells" name="${experiment_name}" sequencer="${sequencer}" index="${index}" flowcell_id="${flowcell_id}" bucket="${bucket}" status=Pending
     fi
 
-    echo "[INFO] BCL of flowcell ${flowcell_name} is uploaded from ${hostname} and is ready for bcl2fastq conversion"
+    info "BCL of flowcell ${flowcell_name} is uploaded from ${hostname} and is ready for bcl2fastq conversion"
     date > "${log_file}"
 done
 
-echo "[INFO] Removing ${tmp_upload_file}"
+info "Removing ${tmp_upload_file}"
 rm -f "${tmp_upload_file}"
-echo "[INFO] Finished with $0"
+info "Finished with $0"
