Changes to downloading ref and tumor bam

diff --git a/gcp/download_tumor_bam b/gcp/download_tumor_bam
--- a/gcp/download_tumor_bam
+++ b/gcp/download_tumor_bam
@@ -1,1 +1,29 @@
 #!/usr/bin/env bash
+
+source sbp_api_functions
+
+set=$1 && shift
+
+if [ -z "${set}" ]; then
+    echo "[ERROR] No set provided. Exiting."
+    exit 1
+fi
+
+bucket=$(load_intial_run_bucket_for_set ${set})
+if [ -z "${bucket}" ]; then
+    echo "[ERROR] No initial run bucket found for set ${set}. Exiting"
+    exit 1
+fi
+
+sample_id=$(load_tumor_sample_id_for_set ${set})
+
+gs_path=gs://${bucket}/${set}
+ds_path=/data/gcp/bam_downloads/bams_${set}
+
+echo "[INFO] Downloading TUMOR bam from ${gs_path}"
+gcloud auth activate-service-account --key-file=/data/common/dbs/gcp_credentials/hmf-download
+
+bam_path=$(gsutil -u hmf-database ls -r ${gs_path} | grep -Po "[^\s]*(mapping|aligner)/${sample_id}(_dedup)?(.realigned)?.bam$")
+
+mkdir -p ${ds_path}
+gsutil -u hmf-database cp ${bam_path} ${ds_path}/
