Consistency improvement

diff --git a/gcp/download_run_by_gcp_url b/gcp/download_run_by_gcp_url
--- a/gcp/download_run_by_gcp_url
+++ b/gcp/download_run_by_gcp_url
@@ -7,7 +7,7 @@ download_path=$1 && shift
 
 if [[ -z "${gcp_url}" ]]; then echo "[ERROR] No URL provided ($(basename $0)). Exiting" && exit 1; fi
 if [[ -z "${download_path}" ]]; then echo "[ERROR] No download path provided ($(basename $0)). Exiting" && exit 1; fi
-if [[ ! "${gcp_url}" =~ ^gs\: ]]; then echo "[ERROR] Url should start with gs ($(basename $0)). Exiting" && exit 1; fi
+if [[ ! "${gcp_url}" =~ ^gs\: ]]; then echo "[ERROR] URL should start with gs ($(basename $0)). Exiting" && exit 1; fi
 
 set_name=$(basename "${gcp_url}")
 dest_path="${download_path}/${set_name}/"
