image retrieval can fail so moved to after help msg

diff --git a/gcp/make_vm b/gcp/make_vm
--- a/gcp/make_vm
+++ b/gcp/make_vm
@@ -13,8 +13,6 @@ extra_params=("--service-account" "hmf-crunch@hmf-crunch.iam.gserviceaccount.com
 family="pipeline5-5-22"
 
 current_project=$(gcloud config get-value project) || die "Unable to get-value project"
-image_name=$(gcloud --project="${image_project}" compute images describe-from-family "${family}" | grep name | cut -d" " -f2) \
-|| die "Unable to describe-from-family from project ${image_project}"
 
 print_usage() {
     script=$(basename "$0")
@@ -25,7 +23,7 @@ print_usage() {
     echo "       ${script} -n ${USER}-test-vm -m n1-standard-16"
     echo "       ${script} -n ${USER}-test-vm -m n1-standard-32 -i my-image-name -p my-image-project"
     echo "Options:"
-    echo "      -i image_name       Image name [${image_name}]"
+    echo "      -i image_name       Image name [default is most recent ${family} image]"
     echo "      -p image_project    Image project [${image_project}]"
     echo "      -m machine_type     VM machine type [${machine_type}]"
     echo "      -s disk_size        VM boot disk size [${disk_size}]"
@@ -59,13 +57,18 @@ if [[ -z "${vm_name}" || "$1" == "-h" || "$1" == "--help" ]]; then
     print_usage
 fi
 
-info "Settings:"
-info "  Config: ${machine_type} ${disk_size}"
+# if no image name provided then try to get newest pipeline image
+if [[ -z "${image_name}" ]]; then
+    image_name=$(gcloud --project="${image_project}" compute images describe-from-family "${family}" | grep name | cut -d" " -f2) \
+    || die "Unable to describe-from-family from project ${image_project}"
+fi
+
+info "VM Details:"
+info "    Name: ${vm_name} (in ${current_project})"
+info "   Image: ${image_name} (from ${image_project})"
+info "  Config: ${machine_type} ${disk_size}" "${extra_params[*]}"
 info "  Access: gcloud compute ssh ${vm_name}"
 info "  Delete: gcloud compute instances delete --zone ${zone} -q ${vm_name}"
-info "  Params: ${extra_params[*]}"
-info "   Image: ${image_name} in ${image_project}"
-info "      VM: ${vm_name} in ${current_project}"
 
 info "Press [ENTER] to start creating VM..."
 read -r -s
