use newest image from family by default

diff --git a/gcp/make_vm b/gcp/make_vm
--- a/gcp/make_vm
+++ b/gcp/make_vm
@@ -3,15 +3,18 @@
 source message_functions || exit 1
 
 vm_name=""
-image_name="pipeline5-5-22-202104121213"
+image_name=""
 image_project="hmf-pipeline-development"
 zone="europe-west4-a"
 machine_type="n1-standard-2"
 disk_type="pd-ssd"
 disk_size="200G"
 extra_params=("--service-account" "hmf-crunch@hmf-crunch.iam.gserviceaccount.com" "--no-address")
+family="pipeline5-5-22"
 
 current_project=$(gcloud config get-value project) || die "Unable to get-value project"
+image_name=$(gcloud --project="${image_project}" compute images describe-from-family "${family}" | grep name | cut -d" " -f2) \
+|| die "Unable to describe-from-family from project ${image_project}"
 
 print_usage() {
     script=$(basename "$0")
@@ -33,7 +36,7 @@ print_usage() {
     echo "      https://cloud.google.com/compute/docs/disks"
     echo "      https://cloud.google.com/compute/docs/machine-types"
     echo "      https://cloud.google.com/sdk/gcloud/reference/compute/instances/create"
-    echo "      gcloud compute images list | grep pipeline"
+    echo "      gcloud --project ${image_project} compute images list | grep pipeline"
     echo ""
     exit 1
 }
