Exit upon failure to execute one of the steps

diff --git a/gcp/make_bucket b/gcp/make_bucket
--- a/gcp/make_bucket
+++ b/gcp/make_bucket
@@ -2,6 +2,8 @@
 
 source message_functions || exit 1
 
+CMEK_KEY="projects/hmf-database/locations/europe-west4/keyRings/hmf-database/cryptoKeys/hmf-database-20191001"
+
 print_usage() {
     echo "Usage: $(basename "$0") [arguments]"
     echo "  -b                  Bucket is for backup (archival) only and is not expected to be read from in normal circumstances"
@@ -32,10 +34,10 @@ if [[ -n $backup_only ]]; then
 fi
 
 info "Creating bucket in GCP. Disregard warnings about KMS permissions, our storage accounts are authorized."
-gsutil mb "$class_args" -b on -l europe-west4 -p "$project_name" "gs://${bucket_name}"
-gsutil kms encryption -w -k projects/hmf-database/locations/europe-west4/keyRings/hmf-database/cryptoKeys/hmf-database-20191001 "gs://${bucket_name}"
-gsutil label ch -l "user:$USER" "gs://${bucket_name}"
-gsutil label ch -l "cost_center:$cost_center" "gs://${bucket_name}"
+gsutil mb "$class_args" -b on -l europe-west4 -p "${project_name}" "gs://${bucket_name}" || die "Unable to exec mb"
+gsutil kms encryption -w -k "${CMEK_KEY}" "gs://${bucket_name}" || die "Unable to set encryption"
+gsutil label ch -l "user:$USER" "gs://${bucket_name}" || die "Unable to set user label"
+gsutil label ch -l "cost_center:${cost_center}" "gs://${bucket_name}" || die "Unable to set cost center label"
 if [[ -z $backup_only ]]; then
     gcloud storage buckets update "gs://${bucket_name}" --autoclass-terminal-storage-class=ARCHIVE
 fi
