DEV-1524: added check on flowcell name

diff --git a/gcp/upload_bcl_gcp b/gcp/upload_bcl_gcp
--- a/gcp/upload_bcl_gcp
+++ b/gcp/upload_bcl_gcp
@@ -31,8 +31,8 @@ tmp_upload_file="/tmp/bcl_uploading"
 
 ## Generic function to use api
 hmfapi () {
-    echo $@ 1>&2
-    http --ignore-stdin --cert="${api_crt}" --cert-key="${api_key}" $@
+    echo "$@" 1>&2
+    http --ignore-stdin --cert="${api_crt}" --cert-key="${api_key}" "$@"
 }
 
 ## Generic function that posts a message to slack channel
@@ -86,10 +86,16 @@ find "${flowcells_dir}" -mindepth 1 -maxdepth 1 -type d -not -name "TestRuns" -n
 
     if [[ ! -f "${rtacomplete_path}" ]]; then
         # Sequencing not finished yet but do pre-register
-        echo "[INFO] Flowcell ${flowcell_name} has no run complete file yet (${rtacomplete_path}): skipping"
-        flowcell="$(hmfapi GET ${api_url}/hmf/v1/flowcells?flowcell_id=${flowcell_id})"
+        echo "[INFO] Flowcell ${flowcell_name} has no run complete file yet (${rtacomplete_path}): skipping upload"
+        flowcell="$(hmfapi GET "${api_url}/hmf/v1/flowcells?flowcell_id=${flowcell_id}")"
         if [[ $(echo "${flowcell}" | jq length) -eq 0 ]]; then
-            hmfapi POST ${api_url}/hmf/v1/flowcells name="${experiment_name}" sequencer="${sequencer}" index="${index}" flowcell_id="${flowcell_id}" status=Sequencing > /dev/null;
+            flowcell_by_name="$(hmfapi GET "${api_url}/hmf/v1/flowcells?name=${experiment_name}")"
+            if [[ $(echo "${flowcell_by_name}" | jq length) -eq 0 ]]; then
+                echo "[INFO] Registering new flowcell in API (${flowcell_id}|${flowcell_name})"
+                hmfapi POST "${api_url}/hmf/v1/flowcells" name="${experiment_name}" sequencer="${sequencer}" index="${index}" flowcell_id="${flowcell_id}" status=Sequencing > /dev/null;
+            else
+                echo "[WARN] Unable to POST flowcell: has new ID (${flowcell_id}) but name already exists in API (${flowcell_name})!"
+            fi
         fi
         continue
     fi
