DEV-2480 Make exit handler check exit code

diff --git a/gcp/upload_bcl_gcp b/gcp/upload_bcl_gcp
--- a/gcp/upload_bcl_gcp
+++ b/gcp/upload_bcl_gcp
@@ -7,7 +7,9 @@ bucket="bcl-input-prod-1"
 gcp_cred="/data/dbs/gcp_credentials/bcl-input-prod"
 
 function exit_handler() {
-    gcloud logging write on_premises "ERROR while uploading flowcells" --severity=ERROR --project=hmf-pipeline-prod-e45b00f2
+    if [[ $? -ne 0 ]]; then
+        gcloud logging write on_premises "ERROR while uploading flowcells" --severity=ERROR --project=hmf-pipeline-prod-e45b00f2
+    fi
 }
 
 function rsync_bcls() {
