added retry in case of GET failure

diff --git a/api/hmf_api_get b/api/hmf_api_get
--- a/api/hmf_api_get
+++ b/api/hmf_api_get
@@ -23,13 +23,25 @@ if [[ -z "${api_query}" || "${api_query}" == "-h" || "${api_query}" == "--help" 
     exit 1
 fi
 
-# With --fail curl exits with error code upon finish
-curl --fail --silent --show-error --cert "${api_crt}" --key "${api_key}" \
-    -H "Content-Type: application/json" -X GET "${api_url}/${api_query}" 2>/dev/null
+main () {
+    request="${api_url}/${api_query}"
+    api_curl "${request}" 2>/dev/null
+    
+    # if first time failed: rerun 
+    if [[ ! $? -eq 0 ]]; then
+        api_curl "${request}" 2>/dev/null
+    fi
 
-# Rerun in case of error to capture API message
-if [[ ! $? -eq 0 ]]; then
-    api_result_msg=$(curl --silent --show-error --cert "${api_crt}" --key "${api_key}" \
-      -H "Content-Type: application/json" -X GET "${api_url}/${api_query}")
-    die "GET failed for query '${api_query}' (${api_result_msg})"
-fi
+    # if second time failed: give up
+    if [[ ! $? -eq 0 ]]; then
+        die "GET query failed '${api_query}'"
+    fi
+}
+
+api_curl () {
+    local url=$1 && shift
+    curl --fail --silent --show-error --cert "${api_crt}" --key "${api_key}" \
+    -H "Content-Type: application/json" -X GET "${url}"
+}
+
+main
