use hmf_api_patch in qc pass flowcell with sample yield recalculation

diff --git a/api/hmf_api_patch b/api/hmf_api_patch
--- a/api/hmf_api_patch
+++ b/api/hmf_api_patch
@@ -61,25 +61,32 @@ else
 fi
 
 main () {
-    info "Searching api of for object (class=${class}|id=${oid}|env=${environment})"
-    object_url="${api_url}/${class}/${oid}"
+    info "Checking api for object (class=${class}|id=${oid}|env=${environment})"
+    object_location="${class}/${oid}"
 
     # TODO: use hmf_api_get once acceptance environment supported
-    json=$(get_with_curl "${object_url}") || die "API GET failed for ${object_url}. Exit."
+    json=$(get_with_curl "${object_location}") || die "API GET failed for ${object_location}. Exit."
     name=$(get_name_from_object "${class}" "${json}") || die "Unable to get name from object json. Exit."
     data=$(construct_data_json "${field}" "${value}") || die "Unable to construct the patch json. Exit."
 
-    info "Config: name=${name} patch=${data}"
+    info_string="name=${name}|class=${class}|id=${oid}|env=${environment}"
+    info "About to patch object (${info_string}) with '${data}'"
     if [[ "${confirmation}" == "true" ]]; then
         current_value=$(jq --arg key "${field}" '.[$key]' <<< "${json}")
         info "Will replace ${current_value} with ${value}"
         info "Press [ENTER] to apply..."
-        read -r
-        patch_with_curl "${object_url}" "${data}" || die "API PATCH failed"
+        read -r -s
+        patch_with_curl "${object_location}" "${data}" || die "API PATCH failed"
     elif [[ "${confirmation}" == "false" ]]; then
-        patch_with_curl "${object_url}" "${data}" || die "API PATCH failed"
+        patch_with_curl "${object_location}" "${data}" || die "API PATCH failed"
     else
         die "Unexpected: param confirmation should always be either true or false"
+    fi
+
+    # Handle special cases
+    if [[ "${class}" == "flowcells" && "${field}" == "undet_rds_p_pass" ]]; then
+        info "Recalculating sample yields for flowcell (${info_string})"
+        post_with_curl_without_data "flowcells/${oid}/recalculate"
     fi
 }
 
@@ -108,25 +115,31 @@ get_name_from_object () {
     local class=$1 && shift
     local json=$1 && shift
     if [[ "${class}" == "fastq" ]]; then
-        echo "${json}" | jq '.name_r1'
+        jq -r '.name_r1' <<< "${json}"
     elif [[ "${class}" == "runs" ]]; then
-        echo "${json}" | jq '.set.name'
+        jq -r '.set.name' <<< "${json}"
     else
-        echo "${json}" | jq '.name'
+        jq -r '.name' <<< "${json}"
     fi
 }
 
 get_with_curl () {
-    local url=$1 && shift
+    local object_location=$1 && shift
     curl -f --silent --show-error -H "Content-Type: application/json" \
-    --cert-type pem --cert "${api_crt}" --key "${api_key}" -X GET "${url}"
+    --cert-type pem --cert "${api_crt}" --key "${api_key}" -X GET "${api_url}/${object_location}"
 }
 
 patch_with_curl () {
-    local url=$1 && shift
+    local object_location=$1 && shift
     local data=$1 && shift
     curl --silent --show-error -H "Content-Type: application/json" -H "Accept: application/json" \
-     --cert-type pem --cert "${api_crt}" --key "${api_key}" -X PATCH "${url}" --data "${data}" > /dev/null
+     --cert-type pem --cert "${api_crt}" --key "${api_key}" -X PATCH "${api_url}/${object_location}" --data "${data}" > /dev/null
+}
+
+post_with_curl_without_data () {
+    local object_location=$1 && shift
+    curl --silent --show-error \
+     --cert-type pem --cert "${api_crt}" --key "${api_key}" -X POST "${api_url}/${object_location}" > /dev/null
 }
 
 main
diff --git a/api/patch_api_qc_pass_flowcell b/api/patch_api_qc_pass_flowcell
--- a/api/patch_api_qc_pass_flowcell
+++ b/api/patch_api_qc_pass_flowcell
@@ -12,25 +12,18 @@ if [[ -z "$1" || $1 == "-h" || $1 == "--help" ]]; then
     exit 1
 fi
 
-api_url="https://api.hartwigmedicalfoundation.nl/hmf/v1"
-api_dir="/data/common/dbs/api_credentials"
-api_key="${api_dir}/api.key"
-api_crt="${api_dir}/api.crt"
-
 info "Searching flowcell by flowcell id ${flowcell_id}"
 flowcell="$(hmf_api_get "flowcells?flowcell_id=${flowcell_id}")"
 
-if [[ $(echo "${flowcell}" | jq length) -eq 1 ]]; then
-    obj_id=$(echo "${flowcell}" | jq -r .[0].id)
-    obj_name=$(echo "${flowcell}" | jq -r .[0].name)
-    obj_status=$(echo "${flowcell}" | jq -r .[0].status)
-    obj_qc_status=$(echo "${flowcell}" | jq -r .[0].undet_rds_p_pass)
-    if [[ "${obj_qc_status}" == "true" ]]; then
-        warn "QC status is already true. Proceed with care."
-    fi
-    info "Execute following to QC PASS flowcell ${flowcell_id} (id:${obj_id} name:${obj_name} status=${obj_status} qc_pass=${obj_qc_status})"
-    echo " http --ignore-stdin --cert=${api_crt} --cert-key=${api_key} PATCH ${api_url}/flowcells/${obj_id} undet_rds_p_pass:=true"
-    echo " http --ignore-stdin --cert=${api_crt} --cert-key=${api_key} POST ${api_url}/flowcells/${obj_id}/recalculate"
-else
-    die "Unable to retrieve flowcell with provided flowcell_id (${flowcell_id})"
-fi
+[[ $(echo "${flowcell}" | jq length) -eq 1 ]] || die "Unable to find exactly one flowcell with provided flowcell_id (${flowcell_id})"
+
+oid=$(echo "${flowcell}" | jq -r .[0].id)
+name=$(echo "${flowcell}" | jq -r .[0].name)
+status=$(echo "${flowcell}" | jq -r .[0].status)
+qc_status=$(echo "${flowcell}" | jq -r .[0].undet_rds_p_pass)
+info_string="${name}|${flowcell_id}|${status}|${qc_status}|${oid}"
+
+[[ "${status}" == "Converted" ]] || die "Cannot qc pass flowcell because status is not 'Converted' (${info_string})"
+
+info "Setting flowcell QC to PASS (${info_string})"
+hmf_api_patch -c "flowcells" -o "${oid}" -f "undet_rds_p_pass" -v "true"
