Consistency cleanups

diff --git a/api/update_api_db_jsons b/api/update_api_db_jsons
--- a/api/update_api_db_jsons
+++ b/api/update_api_db_jsons
@@ -12,8 +12,8 @@ SCRIPT=$(basename $0)
 
 DB_TYPES=( fastq entities runs samples sets flowcells inis shares stacks )
 
-if [[ ! -f $CRT_FILE ]]; then echo "[ERROR] CRT file not found ($CRT_FILE)" && exit 1; fi
-if [[ ! -f $KEY_FILE ]]; then echo "[ERROR] KEY file not found ($KEY_FILE)" && exit 1; fi
+if [[ ! -f "${CRT_FILE}" ]]; then echo "[ERROR] CRT file not found (${CRT_FILE})" && exit 1; fi
+if [[ ! -f "${KEY_FILE}" ]]; then echo "[ERROR] KEY file not found (${KEY_FILE})" && exit 1; fi
 
 for TYPE in "${DB_TYPES[@]}"; do
     API_URL="${BASE_URL}/${TYPE}"
@@ -38,7 +38,7 @@ for TYPE in "${DB_TYPES[@]}"; do
         cp ${OUTPUT_FILE_TMP} ${OUTPUT_FILE}
         echo "[INFO] Written to ${OUTPUT_FILE}"
     else
-        echo "${DATETIME} WARNING retrieval of $TYPE failed so stopping" && exit 1
+        echo "${DATETIME} WARN retrieval of $TYPE failed so stopping" && exit 1
     fi
 done
 
diff --git a/ascat/ascat_for_paper b/ascat/ascat_for_paper
--- a/ascat/ascat_for_paper
+++ b/ascat/ascat_for_paper
@@ -11,15 +11,13 @@ sample=$(load_tumor_sample_from_metadata ${run_dir})
 normal=$(load_ref_sample_from_metadata ${run_dir})
 
 amber=${run_dir}/amber_v2/${sample}.amber.baf
-if [[ ! -f ${amber} ]]; then
-    echo "[ERROR] Unable to locate AMBER file: ${amber}"
-    exit 1
+if [[ ! -f "${amber}" ]]; then
+    echo "[ERROR] Unable to locate AMBER file: ${amber}" && exit 1
 fi
 
 amber_column_count=$(head -1 ${amber} | wc -w)
 if [[ ${amber_column_count} -ne 8 ]]; then
-    echo "[ERROR] ASCAT requires latest AMBER output"
-    exit 1
+    echo "[ERROR] ASCAT requires latest AMBER output" && exit 1
 fi
 
 echo "[INFO] Running ASCAT on ${sample}"
diff --git a/chord/run_chord_prod b/chord/run_chord_prod
--- a/chord/run_chord_prod
+++ b/chord/run_chord_prod
@@ -5,9 +5,8 @@ source metadata_functions
 
 run_dir=$1 && shift
 
-if [[ ! -d ${run_dir} ]]; then
-    echo "[ERROR] ${run_dir} does not exist!"
-    exit 1
+if [[ ! -d "${run_dir}" ]]; then
+    echo "[ERROR] ${run_dir} does not exist!" && exit 1
 fi
 
 sample=$(load_tumor_sample_from_metadata ${run_dir})
diff --git a/hmftools/sage/do_run_sage_experiment_pon b/hmftools/sage/do_run_sage_experiment_pon
--- a/hmftools/sage/do_run_sage_experiment_pon
+++ b/hmftools/sage/do_run_sage_experiment_pon
@@ -14,19 +14,16 @@ normal_bam=/data/experiments/191119_sage_panel_slices/bams/${normal}.panel.bam
 
 final_vcf=${out_dir}/${sample}.pon.vcf
 
-if [[ ! -f ${normal_bam} ]]; then
-    echo "[ERROR] BAM download failed"
-    exit 1
+if [[ ! -f "${normal_bam}" ]]; then
+    echo "[ERROR] BAM download failed" && exit 1
 fi
 
-if [[ ! -f ${sample_bam} ]]; then
-    echo "[ERROR] BAM download failed"
-    exit 1
+if [[ ! -f "${sample_bam}" ]]; then
+    echo "[ERROR] BAM download failed" && exit 1
 fi
 
-if [[ -f ${final_vcf} ]]; then
-    echo "[ERROR] Output already created"
-    exit 1
+if [[ -f "${final_vcf}" ]]; then
+    echo "[ERROR] Output already created" && exit 1
 fi
 
 mkdir -p ${out_dir}
diff --git a/lims/api_functions_test b/lims/api_functions_test
--- a/lims/api_functions_test
+++ b/lims/api_functions_test
@@ -5,8 +5,7 @@ source api_functions
 set=$1
 
 if [[ -z "${set}" ]]; then
-    echo "[ERROR] Provide a set. Exiting"
-    exit 1
+    echo "[ERROR] Provide a set. Exiting" && exit 1
 fi
 
 run_info=$(load_run_info_for_set ${set})
diff --git a/lims/check_submission_status b/lims/check_submission_status
--- a/lims/check_submission_status
+++ b/lims/check_submission_status
@@ -3,8 +3,7 @@
 submission=$1
 
 if [[ -z "${submission}" ]]; then
-    echo "[ERROR] Provide a submission (eg HMFreg0001). Exiting"
-    exit 1
+    echo "[ERROR] Provide a submission (eg HMFreg0001). Exiting" && exit 1
 fi
 
 submission_dir="/data/submissions/${submission}"
@@ -43,7 +42,7 @@ echo "  gather_submission ${submission}"
 echo ""
 
 ## print warnings last
-if [[ -d ${submission_dir} ]]; then echo "[WARN] Submission directory already exists (${submission_dir})"; fi
+if [[ -d "${submission_dir}" ]]; then echo "[WARN] Submission directory already exists (${submission_dir})"; fi
 if [[ ! "${rns_api_val}" -eq "${rns_api_tot}" ]]; then echo "[WARN] Not all runs in API are status Validated!"; fi
 echo "${lms_smp_jsn}" | jq -r '.[].lab_sop_versions' | while read smp_sop_str; do
     ## Note to self: no quoted regex since bash 3.2
diff --git a/lims/sync_lab_lims_from_nas b/lims/sync_lab_lims_from_nas
--- a/lims/sync_lab_lims_from_nas
+++ b/lims/sync_lab_lims_from_nas
@@ -25,49 +25,49 @@ PROC_NAS_PATH_2019="${NAS_DIR}/${PROC_FILE_2019}"
 
 ## File and dir sanity checks
 if ssh nas "[[ ! -d "${NAS_DIR}" ]]"; then echo "[ERROR] Dir does not exist (nas:${NAS_DIR})" && exit 1; fi
-for nasFilePath in "$TEST_NAS_PATH" "$CPCT_NAS_PATH" "$SAMP_NAS_PATH" "$PROC_NAS_PATH" "$SAMP_NAS_PATH_2019" "$PROC_NAS_PATH_2019"; do
-    if ssh nas "[[ ! -f '${nasFilePath}' ]]"; then echo "[ERROR] File does not exist (nas:${nasFilePath})" && exit 1; fi
+for nas_file_path in "${TEST_NAS_PATH}" "${CPCT_NAS_PATH}" "${SAMP_NAS_PATH}" "${PROC_NAS_PATH}" "${SAMP_NAS_PATH}_2019" "${PROC_NAS_PATH}_2019"; do
+    if ssh nas "[[ ! -f '${nas_file_path}' ]]"; then echo "[ERROR] File does not exist (nas:${nas_file_path})" && exit 1; fi
 done
-for outdir in $OUT_DIR $LAB_DIR $SYM_DIR; do
-    if [[ ! -d ${outdir} ]]; then echo "[ERROR] Dir does not exist (${outdir})" && exit 1; fi
-    if [[ ! -w ${outdir} ]]; then echo "[ERROR] No write permission (${outdir})" && exit 1; fi
+for outdir in ${OUT_DIR} ${LAB_DIR} ${SYM_DIR}; do
+    if [[ ! -d "${outdir}" ]]; then echo "[ERROR] Dir does not exist (${outdir})" && exit 1; fi
+    if [[ ! -w "${outdir}" ]]; then echo "[ERROR] No write permission (${outdir})" && exit 1; fi
 done
 mkdir -p ${DAY_DIR}
 
 ## Setup file variables
-testSource="${DAY_DIR}/${TEST_FILE}"
-testTarget="${DAY_DIR}/${DATESTR}_LimsCPCTtrackPilot.accdb"
-testTxt="${testTarget}.csv"
-testLatest="${SYM_DIR}/lims_test"
+test_source="${DAY_DIR}/${TEST_FILE}"
+test_target="${DAY_DIR}/${DATESTR}_LimsCPCTtrackPilot.accdb"
+test_txt="${test_target}.csv"
+test_latest="${SYM_DIR}/lims_test"
 
-cpctSource="${DAY_DIR}/${CPCT_FILE}"
-cpctTarget="${DAY_DIR}/${DATESTR}_LimsCPCTtrack.accdb"
-cpctTxt="${cpctTarget}.csv"
-cpctLatest="${SYM_DIR}/lims_cpct"
+cpct_source="${DAY_DIR}/${CPCT_FILE}"
+cpct_target="${DAY_DIR}/${DATESTR}_LimsCPCTtrack.accdb"
+cpct_txt="${cpct_target}.csv"
+cpct_latest="${SYM_DIR}/lims_cpct"
 
-sampSource="${DAY_DIR}/${SAMP_FILE}"
-sampTarget="${DAY_DIR}/${DATESTR}_LimsReceived.xlsx"
-sampTxt="${sampTarget}_samp.tsv"
-sampLatest="${SYM_DIR}/lims_samp"
-submTxt="${sampTarget}_subm.tsv"
-submLatest="${SYM_DIR}/lims_subm"
-contTxt="${sampTarget}_cont.tsv"
-contLatest="${SYM_DIR}/lims_cont"
-procSource="${DAY_DIR}/${PROC_FILE}"
-procTarget="${DAY_DIR}/${DATESTR}_LimsInProcess.xlsx"
-procTxt="${procTarget}.tsv"
-procLatest="${SYM_DIR}/lims_proc"
+samp_source="${DAY_DIR}/${SAMP_FILE}"
+samp_target="${DAY_DIR}/${DATESTR}_LimsReceived.xlsx"
+samp_txt="${samp_target}_samp.tsv"
+samp_latest="${SYM_DIR}/lims_samp"
+subm_txt="${samp_target}_subm.tsv"
+subm_latest="${SYM_DIR}/lims_subm"
+cont_txt="${samp_target}_cont.tsv"
+cont_latest="${SYM_DIR}/lims_cont"
+proc_source="${DAY_DIR}/${PROC_FILE}"
+proc_target="${DAY_DIR}/${DATESTR}_LimsInProcess.xlsx"
+proc_txt="${proc_target}.tsv"
+proc_latest="${SYM_DIR}/lims_proc"
 
-sampSource2019="${DAY_DIR}/${SAMP_FILE_2019}"
-sampTarget2019="${DAY_DIR}/${DATESTR}_LimsReceived_2019.xlsx"
-sampTxt2019="${sampTarget2019}_samp_2019.tsv"
-sampLatest2019="${SYM_DIR}/2019_samp"
-submTxt2019="${sampTarget2019}_subm_2019.tsv"
-submLatest2019="${SYM_DIR}/2019_subm"
-procSource2019="${DAY_DIR}/${PROC_FILE_2019}"
-procTarget2019="${DAY_DIR}/${DATESTR}_LimsInProcess_2019.xlsx"
-procTxt2019="${procTarget2019}.tsv"
-procLatest2019="${SYM_DIR}/2019_proc"
+samp_source_2019="${DAY_DIR}/${SAMP_FILE_2019}"
+samp_target_2019="${DAY_DIR}/${DATESTR}_LimsReceived_2019.xlsx"
+samp_txt_2019="${samp_target_2019}_samp_2019.tsv"
+samp_latest_2019="${SYM_DIR}/2019_samp"
+subm_txt_2019="${samp_target_2019}_subm_2019.tsv"
+subm_latest_2019="${SYM_DIR}/2019_subm"
+proc_source_2019="${DAY_DIR}/${PROC_FILE_2019}"
+proc_target_2019="${DAY_DIR}/${DATESTR}_LimsInProcess_2019.xlsx"
+proc_txt_2019="${proc_target_2019}.tsv"
+proc_latest_2019="${SYM_DIR}/2019_proc"
 
 ## Retrieve files from NAS
 echo "[INFO] Syncing LIMS files from NAS to DATASTORE"
@@ -83,83 +83,83 @@ rsync -s "nas:${PROC_NAS_PATH_2019}" ${DAY_DIR}
 ## Make sure all required files are present
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] Error with RSYNC from NAS, please check " && exit 1; fi
 
-for inputFile in "${testSource}" "${cpctSource}" "${sampSource}" "${procSource}"; do
-    if [[ ! -f "${inputFile}" ]]; then
-        echo "[ERROR] Input file from NAS not present (${inputFile})" && exit 1;
+for input_file in "${test_source}" "${cpct_source}" "${samp_source}" "${proc_source}"; do
+    if [[ ! -f "${input_file}" ]]; then
+        echo "[ERROR] Input file from NAS not present (${input_file})" && exit 1;
     fi
 done
 
 ## Symlink LIMS files to create stable naming for downstream work
-ln -sfn "${testSource}" "${testTarget}"
-ln -sfn "${cpctSource}" "${cpctTarget}"
-ln -sfn "${sampSource}" "${sampTarget}"
-ln -sfn "${procSource}" "${procTarget}"
+ln -sfn "${test_source}" "${test_target}"
+ln -sfn "${cpct_source}" "${cpct_target}"
+ln -sfn "${samp_source}" "${samp_target}"
+ln -sfn "${proc_source}" "${proc_target}"
 
 ## Symlink LIMS files to create stable naming for downstream work 2019
-ln -sfn "${sampSource2019}" "${sampTarget2019}"
-ln -sfn "${procSource2019}" "${procTarget2019}"
+ln -sfn "${samp_source_2019}" "${samp_target_2019}"
+ln -sfn "${proc_source_2019}" "${proc_target_2019}"
 
 ## Convert to text format
 echo "[INFO] Converting input files to CSV/TSV"
 
-echo "[INFO]   Converting $( basename ${testTarget} )"
-${ACC2CSV} --with-header --input "${testTarget}" --output ${DAY_DIR} --table tblSamples --quote-all false
+echo "[INFO]   Converting $(basename ${test_target})"
+${ACC2CSV} --with-header --input "${test_target}" --output ${DAY_DIR} --table tblSamples --quote-all false
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] TEST export to csv FAILED" && exit 1; fi
-mv ${DAY_DIR}/tblSamples.csv ${testTxt}
-echo "[INFO]   Converting $( basename ${cpctTarget} )"
-${ACC2CSV} --with-header --input "${cpctTarget}" --output ${DAY_DIR} --table tblSamples --quote-all false
+mv ${DAY_DIR}/tblSamples.csv ${test_txt}
+echo "[INFO]   Converting $(basename ${cpct_target})"
+${ACC2CSV} --with-header --input "${cpct_target}" --output ${DAY_DIR} --table tblSamples --quote-all false
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] CPCT export to csv FAILED" && exit 1; fi
-mv ${DAY_DIR}/tblSamples.csv ${cpctTxt}
-echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "submissions")"
-xlsx2csv -d "\t" "${sampTarget}" -s 1 | tail -n +5 > ${submTxt}
+mv ${DAY_DIR}/tblSamples.csv ${cpct_txt}
+echo "[INFO]   Converting $(basename ${samp_target}) (sheet "submissions")"
+xlsx2csv -d "\t" "${samp_target}" -s 1 | tail -n +5 > ${subm_txt}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] SUBM export to csv FAILED" && exit 1; fi
-echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "samples")"
-xlsx2csv -d "\t" "${sampTarget}" -s 2 | tail -n +2 > ${sampTxt}
+echo "[INFO]   Converting $(basename ${samp_target}) (sheet "samples")"
+xlsx2csv -d "\t" "${samp_target}" -s 2 | tail -n +2 > ${samp_txt}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] SAMP export to csv FAILED" && exit 1; fi
-echo "[INFO]   Converting $( basename ${sampTarget} ) (sheet "Contact")"
-xlsx2csv -d "\t" "${sampTarget}" -s 3 | tail -n +1 > ${contTxt}
+echo "[INFO]   Converting $(basename ${samp_target}) (sheet "Contact")"
+xlsx2csv -d "\t" "${samp_target}" -s 3 | tail -n +1 > ${cont_txt}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] CONT export to csv FAILED" && exit 1; fi
-echo "[INFO]   Converting $( basename ${procTarget} )"
-xlsx2csv -d "\t" "${procTarget}" -s 1 | tail -n +5 > ${procTxt}
+echo "[INFO]   Converting $(basename ${proc_target})"
+xlsx2csv -d "\t" "${proc_target}" -s 1 | tail -n +5 > ${proc_txt}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] PROC export to csv FAILED" && exit 1; fi
 
 ## Convert to text format for 2019 files
-echo "[INFO]   Converting $( basename ${sampTarget2019} ) (sheet "submissions")"
-xlsx2csv -d "\t" "${sampTarget2019}" -s 1 | tail -n +5 > ${submTxt2019}
+echo "[INFO]   Converting $(basename ${samp_target_2019}) (sheet "submissions")"
+xlsx2csv -d "\t" "${samp_target_2019}" -s 1 | tail -n +5 > ${subm_txt_2019}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] SUBM export to csv FAILED" && exit 1; fi
-echo "[INFO]   Converting $( basename ${sampTarget2019} ) (sheet "samples")"
-xlsx2csv -d "\t" "${sampTarget2019}" -s 2 | tail -n +2 > ${sampTxt2019}
+echo "[INFO]   Converting $(basename ${samp_target_2019}) (sheet "samples")"
+xlsx2csv -d "\t" "${samp_target_2019}" -s 2 | tail -n +2 > ${samp_txt_2019}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] SAMP export to csv FAILED" && exit 1; fi
-echo "[INFO]   Converting $( basename ${procTarget2019} )"
-xlsx2csv -d "\t" "${procTarget2019}" -s 1 | tail -n +5 > ${procTxt2019}
+echo "[INFO]   Converting $(basename ${proc_target_2019})"
+xlsx2csv -d "\t" "${proc_target_2019}" -s 1 | tail -n +5 > ${proc_txt_2019}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] PROC export to csv FAILED" && exit 1; fi
 
 ## Create latest symlinks
 echo "[INFO] Symlinking to latest files (to ${SYM_DIR})"
-echo "[INFO]   $testLatest"
-ln -sfn $testTxt $testLatest
-echo "[INFO]   $cpctLatest"
-ln -sfn $cpctTxt $cpctLatest
-echo "[INFO]   $submLatest"
-ln -sfn $submTxt $submLatest
-echo "[INFO]   $sampLatest"
-ln -sfn $sampTxt $sampLatest
-echo "[INFO]   $contLatest"
-ln -sfn $contTxt $contLatest
-echo "[INFO]   $procLatest"
-ln -sfn $procTxt $procLatest
+echo "[INFO]   ${test_latest}"
+ln -sfn ${test_txt} ${test_latest}
+echo "[INFO]   ${cpct_latest}"
+ln -sfn ${cpct_txt} ${cpct_latest}
+echo "[INFO]   ${subm_latest}"
+ln -sfn ${subm_txt} ${subm_latest}
+echo "[INFO]   ${samp_latest}"
+ln -sfn ${samp_txt} ${samp_latest}
+echo "[INFO]   ${cont_latest}"
+ln -sfn ${cont_txt} ${cont_latest}
+echo "[INFO]   ${proc_latest}"
+ln -sfn ${proc_txt} ${proc_latest}
 
 ## Create latest symlinks for 2019 files
-echo "[INFO]   $submLatest2019"
-ln -sfn $submTxt2019 $submLatest2019
-echo "[INFO]   $sampLatest2019"
-ln -sfn $sampTxt2019 $sampLatest2019
-echo "[INFO]   $procLatest2019"
-ln -sfn $procTxt2019 $procLatest2019
+echo "[INFO]   ${subm_latest}2019"
+ln -sfn ${subm_txt}2019 ${subm_latest}2019
+echo "[INFO]   ${samp_latest}2019"
+ln -sfn ${samp_txt}2019 ${samp_latest}2019
+echo "[INFO]   ${proc_latest}2019"
+ln -sfn ${proc_txt}2019 ${proc_latest}2019
 
 ## Gather some metrics
 echo "[INFO] Stats:"
-for latestFile in $testLatest $cpctLatest $submLatest $sampLatest $contLatest $procLatest; do
-    totalLines=$(cat $latestFile | wc -l)
-    echo "[INFO]   LineCount of ${latestFile} = ${totalLines}"
+for latest_file in ${test_latest} ${cpct_latest} ${subm_latest} ${samp_latest} ${cont_latest} ${proc_latest}; do
+    total_lines=$(cat ${latest_file} | wc -l)
+    echo "[INFO]   LineCount of ${latest_file} = ${total_lines}"
 done
diff --git a/ops/create_set_jsons_for_samplesheets_on_date b/ops/create_set_jsons_for_samplesheets_on_date
--- a/ops/create_set_jsons_for_samplesheets_on_date
+++ b/ops/create_set_jsons_for_samplesheets_on_date
@@ -10,8 +10,8 @@ registerLog="/data/ops/api/prod/logs/${currDate}_register_sets_from_${ssheetDate
 
 ## Sanity checks
 if [[ ! ${ssheetDate} =~ ^[0-9]{6}$ ]]; then echo "[ERROR] Wrong input date: run with \"$(basename $0) YYMMDD\"" && exit 1; fi
-if [[ -f ${createLog} ]]; then echo "[ERROR] Log already exists: ${createLog}" && exit 1; fi
-if [[ -f ${registerLog} ]]; then echo "[ERROR] Log already exists: ${registerLog}" && exit 1; fi
+if [[ -f "${createLog}" ]]; then echo "[ERROR] Log already exists: ${createLog}" && exit 1; fi
+if [[ -f "${registerLog}" ]]; then echo "[ERROR] Log already exists: ${registerLog}" && exit 1; fi
 echo "[INFO] JsonCreation started with input date: ${ssheetDate}"
 
 ## Actual work
@@ -33,8 +33,8 @@ fi
 for dupBc in $( cat ${JSONS_LOC}/*json | jq -r '.samples[].barcode' | sort | uniq -d ); do
    echo "[WARN] Found duplicate barcode ($dupBc): make sure the use_existing flag is set correctly on second one:"; 
    find ${JSONS_LOC} -maxdepth 1 -name "*json" | while read readyJson; do
-       if [[ $(grep -c "${dupBc}" $readyJson) -gt 0 ]]; then
-           echo "[WARN]   $readyJson"
+       if [[ $(grep -c "${dupBc}" ${readyJson}) -gt 0 ]]; then
+           echo "[WARN]   ${readyJson}"
        fi
    done
 done
diff --git a/utilityscripts/create_aria2_config_by_set_name b/utilityscripts/create_aria2_config_by_set_name
--- a/utilityscripts/create_aria2_config_by_set_name
+++ b/utilityscripts/create_aria2_config_by_set_name
@@ -3,7 +3,7 @@
 set_name=$1
 cmd_date=$(date)
 
-if [[ -z "$set_name" ]]; then
+if [[ -z "${set_name}" ]]; then
     echo "[ERROR] No set provided. Exiting" && exit 1
 fi
 
@@ -19,30 +19,30 @@ gcp_key_file="${gcp_cred_dir}/hmf-download"
 gcp_project="hmf-database"
 gcp_account="hmf-download"
 
-echo "[INFO] Start of $0 ($cmd_date)"
+echo "[INFO] Start of $0 (${cmd_date})"
 msg=$(gcloud config set account "${gcp_account}@${gcp_project}.iam.gserviceaccount.com" 2>&1)
-echo "[INFO] $msg"
+echo "[INFO] ${msg}"
 
 function main() {
     ## check that only one run exists for the set
-    runs_json=$(query_api.pl -type runs -filter "name=$set_name" -exact -json | jq '.')
-    runs_count=$(echo "$runs_json" | jq '. | length')
-    if [[ "$runs_count" -ne 1 ]]; then
-        echo "[ERROR] Only sets supported with exactly one run (found $runs_count). Exiting" && exit 1
+    runs_json=$(query_api.pl -type runs -filter "name=${set_name}" -exact -json | jq '.')
+    runs_count=$(echo "${runs_json}" | jq '. | length')
+    if [[ "${runs_count}" -ne 1 ]]; then
+        echo "[ERROR] Only sets supported with exactly one run (found ${runs_count}). Exiting" && exit 1
     fi
-    run_json=$(echo "$runs_json" | jq -r '.[-1]')
+    run_json=$(echo "${runs_json}" | jq -r '.[-1]')
 
     ## setup all variables
-    cluster=$(echo "$run_json" | jq -r '.cluster')
-    bucket=$(echo "$run_json" | jq -r '.bucket')
-    entity=$(echo "$run_json" | jq -r '.entity')
-    status=$(echo "$run_json" | jq -r '.status')
-    name=$(echo "$run_json" | jq -r '.name')
-    pip=$(echo "$run_json" | jq -r '.pipeline')
-    ini=$(echo "$run_json" | jq -r '.ini')
-    ref=$(echo "$run_json" | jq -r '.ref_sample')
-    tum=$(echo "$run_json" | jq -r '.tumor_sample')
-    oid=$(echo "$run_json" | jq -r '.id') # object id
+    cluster=$(echo "${run_json}" | jq -r '.cluster')
+    bucket=$(echo "${run_json}" | jq -r '.bucket')
+    entity=$(echo "${run_json}" | jq -r '.entity')
+    status=$(echo "${run_json}" | jq -r '.status')
+    name=$(echo "${run_json}" | jq -r '.name')
+    pip=$(echo "${run_json}" | jq -r '.pipeline')
+    ini=$(echo "${run_json}" | jq -r '.ini')
+    ref=$(echo "${run_json}" | jq -r '.ref_sample')
+    tum=$(echo "${run_json}" | jq -r '.tumor_sample')
+    oid=$(echo "${run_json}" | jq -r '.id') # object id
 
     files_api_url="${api_url}/files?run_id=${oid}"
     out_jsn_all="${name}_runfiles.json"
@@ -51,26 +51,26 @@ function main() {
     out_md5="${name}.md5"
     out_url="${name}.url"
 
-    echo "[INFO] RunName: $name"
-    echo "[INFO] RunStat: $status"
-    echo "[INFO] IniName: $ini"
-    echo "[INFO] TumName: $tum"
-    echo "[INFO] RefName: $ref"
-    echo "[INFO] PipeVsn: $pip"
-    echo "[INFO] Cluster: $cluster"
-    echo "[INFO] Bucket:  $bucket"
-    echo "[INFO] Entity:  $entity"
+    echo "[INFO] RunName: ${name}"
+    echo "[INFO] RunStat: ${status}"
+    echo "[INFO] IniName: ${ini}"
+    echo "[INFO] TumName: ${tum}"
+    echo "[INFO] RefName: ${ref}"
+    echo "[INFO] PipeVsn: ${pip}"
+    echo "[INFO] Cluster: ${cluster}"
+    echo "[INFO] Bucket:  ${bucket}"
+    echo "[INFO] Entity:  ${entity}"
     
     ## sanity check on data location in API
     ## TODO once all at gcp then remove the ini check
-    if [[ $cluster != "gcp" && $ini != "FastQ.ini" ]]; then
-       echo "[ERROR] Error: unexpected cluster ($cluster)." && exit 1
+    if [[ ${cluster} != "gcp" && ${ini} != "FastQ.ini" ]]; then
+        echo "[ERROR] Error: unexpected cluster (${cluster})." && exit 1
     fi
 
     ## cleanup existing files
-    for output_file in "$out_jsn_all" "$out_md5_all" "$out_aria" "$out_md5" "$out_url"; do
-        if [[ -f $output_file ]]; then
-            echo "[INFO] Deleting existing file ($output_file)" && rm $output_file;
+    for output_file in "${out_jsn_all}" "${out_md5_all}" "${out_aria}" "${out_md5}" "${out_url}"; do
+        if [[ -f "${output_file}" ]]; then
+            echo "[INFO] Deleting existing file (${output_file})" && rm ${output_file};
         fi
     done
 
@@ -78,27 +78,27 @@ function main() {
     files_json=$(/usr/bin/curl --silent --cert-type pem \
         --cert ${api_crt_file} --key ${api_key_file} -X GET \
         -H "Accept: application/json" -H "Content-Type: application/json" \
-        "$files_api_url")
+        "${files_api_url}")
 
     ## create run type agnostic info files
-    create_json_file "$files_json" "$out_jsn_all"
-    create_md5sums_file "$files_json" "$out_md5_all"
+    create_json_file "${files_json}" "${out_jsn_all}"
+    create_md5sums_file "${files_json}" "${out_md5_all}"
 
     ## create the run type specific subset files
-    if [[ $ini == "FastQ.ini" ]]; then
-        create_run_specific_files "$files_json" "$out_md5" "$out_aria" "$out_url" "$name" "$bucket" "$ref" "$tum" "$pip" "Fastq"
-    elif [[ $ini == "Somatic.ini" ]]; then 
-        create_run_specific_files "$files_json" "$out_md5" "$out_aria" "$out_url" "$name" "$bucket" "$ref" "$tum" "$pip" "Somatic"
-    elif [[ $ini == "SingleSample.ini" ]]; then
-        create_run_specific_files "$files_json" "$out_md5" "$out_aria" "$out_url" "$name" "$bucket" "$ref" "$tum" "$pip" "SingleSample"
+    if [[ ${ini} == "FastQ.ini" ]]; then
+        create_run_specific_files "${files_json}" "${out_md5}" "${out_aria}" "${out_url}" "${name}" "${bucket}" "${ref}" "${tum}" "${pip}" "Fastq"
+    elif [[ ${ini} == "Somatic.ini" ]]; then 
+        create_run_specific_files "${files_json}" "${out_md5}" "${out_aria}" "${out_url}" "${name}" "${bucket}" "${ref}" "${tum}" "${pip}" "Somatic"
+    elif [[ ${ini} == "SingleSample.ini" ]]; then
+        create_run_specific_files "${files_json}" "${out_md5}" "${out_aria}" "${out_url}" "${name}" "${bucket}" "${ref}" "${tum}" "${pip}" "SingleSample"
     else
-        echo "[ERROR] Unknown ini ($ini)" && exit 1
+        echo "[ERROR] Unknown ini (${ini})" && exit 1
     fi
 
     ## sanity checks on final files
-    for output_file in "$out_jsn_all" "$out_md5_all" "$out_aria" "$out_md5" "$out_url"; do
-        line_count=$(cat "$output_file" | wc -l)
-        echo "[INFO] Output file $output_file contains $line_count lines"
+    for output_file in "${out_jsn_all}" "${out_md5_all}" "${out_aria}" "${out_md5}" "${out_url}"; do
+        line_count=$(cat "${output_file}" | wc -l)
+        echo "[INFO] Output file ${output_file} contains ${line_count} lines"
     done
 }
 
@@ -144,7 +144,7 @@ create_run_specific_files () {
         tumor_bam_bai="${tum}/cram/${tum}.cram.crai"
     fi
 
-    mapfile -t all_files < <( echo $json | jq -r '.[].filename' )
+    mapfile -t all_files < <( echo ${json} | jq -r '.[].filename' )
 
     local single_files=(
         "${ref_bam}"
@@ -176,29 +176,29 @@ create_run_specific_files () {
     )
 
     ## select file collection
-    if [[ $run_type == "Somatic" ]]; then
+    if [[ ${run_type} == "Somatic" ]]; then
         file_selection="${somatic_files[@]}"
-    elif [[ $run_type == "SingleSample" ]]; then
+    elif [[ ${run_type} == "SingleSample" ]]; then
         file_selection="${single_files[@]}"
-    elif [[ $run_type == "Fastq" ]]; then
+    elif [[ ${run_type} == "Fastq" ]]; then
         file_selection="${all_files[@]}"
     else
-        echo "[ERROR] Unknown run type ($run_type)" && exit 1
+        echo "[ERROR] Unknown run type (${run_type})" && exit 1
     fi
 
     ## output aria2 config file
-    echo "[INFO] Creating $out_aria (and selection tmp files)"
+    echo "[INFO] Creating ${out_aria} (and selection tmp files)"
     for file_path in ${file_selection[@]}; do
         file_name=$(basename "${file_path}")
         file_in_bucket="${bucket}/${name}/${file_path}"
         ## Fastq files are at main level in the bucket
-        if [[ $run_type == "Fastq" ]]; then
+        if [[ ${run_type} == "Fastq" ]]; then
             file_in_bucket="${bucket}/${file_path}"
         fi
         internal_url="gs://${file_in_bucket}"
-        md5_string=$(echo "$json" | jq -r '.[] | .hash + "\t" + .directory + "/" + .filename' | grep -P "${file_path}$")
-        md5sum=$(echo "$md5_string" | cut -f1)
-        echo "${md5_string}" >> $out_md5
+        md5_string=$(echo "${json}" | jq -r '.[] | .hash + "\t" + .directory + "/" + .filename' | grep -P "${file_path}$")
+        md5sum=$(echo "${md5_string}" | cut -f1)
+        echo "${md5_string}" >> ${out_md5}
 
         ## sanity check on existance of file in bucket
         gsutil -u "${gcp_project}" -q stat "${internal_url}"
@@ -212,27 +212,27 @@ create_run_specific_files () {
         ## get actual pre-signed URL
         external_url=$( "${gcp_url_sign_script}" "${gcp_key_file}" "${file_in_bucket}" 604800)
 
-        echo "${external_url}" >> $out_aria
-        echo "  dir=${name}" >> $out_aria
-        echo "  checksum=md5=${md5sum}" >> $out_aria
-        echo "" >> $out_aria
-        echo -e "${file_name}\t${external_url}" >> $out_url
+        echo "${external_url}" >> ${out_aria}
+        echo "  dir=${name}" >> ${out_aria}
+        echo "  checksum=md5=${md5sum}" >> ${out_aria}
+        echo "" >> ${out_aria}
+        echo -e "${file_name}\t${external_url}" >> ${out_url}
     done
 }
 
 create_json_file () {
     local json_text=$1 && shift
     local out_file=$1 && shift
-    echo "[INFO] Creating $out_file"
-    echo "$json_text" | jq '.' > $out_file
+    echo "[INFO] Creating ${out_file}"
+    echo "${json_text}" | jq '.' > ${out_file}
 }
 
 create_md5sums_file () {
     local json_text=$1 && shift
     local out_file=$1 && shift
-    echo "[INFO] Creating $out_file"
-    echo "$json_text" | jq -r '.[] | select(.directory == "") | .hash + "  " + .filename' > $out_file
-    echo "$json_text" | jq -r '.[] | select(.directory != "") | .hash + "  " + .directory + "/" + .filename' >> $out_file
+    echo "[INFO] Creating ${out_file}"
+    echo "${json_text}" | jq -r '.[] | select(.directory == "") | .hash + "  " + .filename' > ${out_file}
+    echo "${json_text}" | jq -r '.[] | select(.directory != "") | .hash + "  " + .directory + "/" + .filename' >> ${out_file}
 }
 
 main
diff --git a/utilityscripts/inspect_header b/utilityscripts/inspect_header
--- a/utilityscripts/inspect_header
+++ b/utilityscripts/inspect_header
@@ -3,8 +3,7 @@
 input_file=$1
 
 if [[ -z "${input_file}" ]]; then
-    echo "[ERROR] No input file provided. Exiting"
-    exit 1
+    echo "[ERROR] No input file provided. Exiting" && exit 1
 fi
 
 delim_char=${2:-"\t"}
@@ -17,5 +16,5 @@ header_fields=(${field_string})
 
 ## print to screen
 for i in "${!header_fields[@]}"; do
-    printf "%s\t%s\n" "$(expr $i + 1)" "${header_fields[$i]}"
+    printf "%s\t%s\n" "$(expr ${i} + 1)" "${header_fields[${i}]}"
 done
diff --git a/validation/validate_giab_mixin b/validation/validate_giab_mixin
--- a/validation/validate_giab_mixin
+++ b/validation/validate_giab_mixin
@@ -19,9 +19,9 @@ truth_vcf_path="${truth_dir_path}/${truth_vcf_name}"
 truth_bed_path="${truth_dir_path}/${truth_bed_name}"
 
 ## init checks
-if [[ ! -w ${val_base} ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
-if [[ ! -f ${truth_vcf_path} ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
-if [[ ! -f ${truth_bed_path} ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
+if [[ ! -w "${val_base}" ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
+if [[ ! -f "${truth_vcf_path}" ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
+if [[ ! -f "${truth_bed_path}" ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
 if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     echo "-----"
     echo " Descr: Validate GIAB run"
diff --git a/validation/validate_giab_pipeline_run b/validation/validate_giab_pipeline_run
--- a/validation/validate_giab_pipeline_run
+++ b/validation/validate_giab_pipeline_run
@@ -34,12 +34,12 @@ run_path=$1 && shift
 ## -----
 ## Checks and Setup
 ## -----
-if [[ ! -d $run_path ]]; then echo "[ERROR] Provided run path does not exist?"; exit 1; fi
+if [[ ! -d "${run_path}" ]]; then echo "[ERROR] Provided run path does not exist?"; exit 1; fi
 
 ## Name of germline VCF differs betwee Pv4 and Pv5
 input_vcf_path=$(find ${run_path} -wholename "*/germline_caller/*.germline.vcf.gz")
 if [[ ! -f "${input_vcf_path}" ]]; then input_vcf_path=$(find ${run_path} -maxdepth 1 -name "*.annotated.vcf.gz"); fi
-if [[ ! -f "${input_vcf_path}" ]]; then echo "[ERROR] No germline VCF found ($run_path)" && exit 1; fi
+if [[ ! -f "${input_vcf_path}" ]]; then echo "[ERROR] No germline VCF found (${run_path})" && exit 1; fi
 
 run_name=$(basename ${run_path})
 output_dir="${val_base}/${run_name}_Validation"
@@ -82,16 +82,24 @@ rtg index -f vcf ${start_vcf_path}
 snp_vcf_path="${output_dir}/SNP_${start_vcf_name}"
 snp_vcf_name=$(basename ${snp_vcf_path})
 
-if [[ -f $snp_vcf_path ]]; then
+if [[ -f "${snp_vcf_path}" ]]; then
     echo "[INFO] SNP vcf already exist, skipping (${snp_vcf_path})"
 else
     echo "[INFO] Running GATK to create SNP vcf (${snp_vcf_name})"
-    java -Djava.io.tmp_dir=${tmp_dir} -jar ${gatk_path} -T SelectVariants -R ${ref_genome_fasta} -L ${truth_bed_path} --excludeNonVariants --removeUnusedAlternates -V ${start_vcf_path} -selectType SNP -o ${snp_vcf_path}
+    java -Djava.io.tmp_dir=${tmp_dir} -jar ${gatk_path} \
+        -T SelectVariants \
+        -R ${ref_genome_fasta} \
+        -L ${truth_bed_path} \
+        --excludeNonVariants \
+        --removeUnusedAlternates \
+        -V ${start_vcf_path} \
+        -selectType SNP \
+        -o ${snp_vcf_path}
     if [[ $? -ne 0 ]]; then { echo "[ERROR] GATK SelectVariants Failed"; exit 1; } fi
 fi
 
 ## no INDELs for now
-#if [[ -f ${indVcfPath} ]]; then
+#if [[ -f "${indVcfPath}" ]]; then
 #    echo "[INFO] INDEL vcf already exist, skipping (${indVcfPath})"
 #else
 #    echo "[INFO] Running GATK to create INDEL vcf (${indVcfName})"
