add help message

diff --git a/api/update_ptum_doids_in_api b/api/update_ptum_doids_in_api
--- a/api/update_ptum_doids_in_api
+++ b/api/update_ptum_doids_in_api
@@ -2,6 +2,14 @@
 
 source message_functions || exit 1
 
+if [[ ! -z "${1}" || "${1}" == "-h" || "${1}" == "--help" ]]; then
+    echo "-----"
+    echo " Descr: Creates a job file with API patches for samples DIODs"
+    echo " Usage: $(basename $0)"
+    echo "-----"
+    exit 1
+fi
+
 out_dir="/data/ops/logs/ptum_doid_update"
 doid_file="/data/common/dbs/clinical_data/curated_primary_tumor.tsv"
 field_idx='7'
@@ -30,16 +38,16 @@ main () {
         sample_info="${api_barcode} (name:${api_name} id:${api_id})"
         info "Checking ${sample_info}"
         if [[ "${count}" -eq 0 ]]; then
-            warn "  SKIPPING ${sample_info}: not found in curated doid file (${doid_file})"
+            warn "  SKIPPING ${sample_info}: not found in file (${doid_file})"
         elif [[ "${count}" -eq 1 ]]; then
             file_doids=$(get_doids "${patient}")
             file_doids=$(sort_csv_string "${file_doids}")
             if [[ "${file_doids}" == "" ]]; then
-                warn "  SKIPPING ${sample_info}: no doids present in curated doid file (${doid_file})"
+                warn "  SKIPPING ${sample_info}: no doids in file (${doid_file})"
             elif [[ "${file_doids}" == "${api_doids}" ]]; then
-                info "  SKIPPING ${sample_info}: file doids identical to api"
+                info "  SKIPPING ${sample_info}: file doids identical to api content"
             else
-                info "OK ${sample_info}: doid update found ('${api_doids}' to '${file_doids}')"
+                info "OK ${sample_info}: doid update ('${api_doids}' to '${file_doids}')"
                 echo "echo '[INFO] Updating ${sample_info}'" >> "${job_file}"
                 echo "hmf_api_patch -c samples -o '${api_id}' -f primary_tumor_doids -v '${file_doids}'" >> "${job_file}"
             fi
