prepare doid update to run as cronjob

diff --git a/api/update_ptum_doids_in_api b/api/update_ptum_doids_in_api
--- a/api/update_ptum_doids_in_api
+++ b/api/update_ptum_doids_in_api
@@ -2,40 +2,46 @@
 
 source message_functions || exit 1
 
-out_dir="/data/ops/recurrent/ptum_doid_update"
+print_usage(){
+    echo "-----"
+    echo " Descr: Patches tumor sample DIOD info in API"
+    echo " Usage: nohup $(basename "$0") -m dryrun > /path/to/log &"
+    echo "        nohup $(basename "$0") -m patch > /path/to/log &"
+    echo "-----"
+    exit 1
+}
+[[ $# -gt 0 ]] || print_usage
+
 doid_file="/data/common/dbs/clinical_data/curated_primary_tumor.tsv"
 status_file="/data/common/dbs/clinical_data/patient_tumor_curation_status.tsv"
 field_idx='7'
 
-yymmdd=$(date +'%y%m%d')
-job_file="${out_dir}/${yymmdd}_update_doids_in_api.job"
-log_file="${out_dir}/${yymmdd}_update_doids_in_api.log"
-
-if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
-    echo "-----"
-    echo " Descr: Creates a job file with API patches for samples DIODs"
-    echo " Usage: nohup $(basename "$0") > /path/to/log &"
-    echo " Notes: "
-    echo "   * Commands written to ${job_file}"
-    echo "   * Log written to STDOUT"
-    echo "-----"
-    exit 1
-fi
+mode='undefined'
+while getopts ':m:' flag; do
+    case "${flag}" in
+        m) mode=${OPTARG} ;;
+        *) print_usage >&2
+        exit 1 ;;
+    esac
+done
 
 main () {
-    # sanity checks
-    doid_file_is_ok || exit 1
-    [[ ! -f "${job_file}" ]] || die "File exists: ${job_file}"
-    [[ ! -f "${log_file}" ]] || die "File exists: ${log_file}"
+    info "Starting with $(basename "$0")"
 
-    samples_considered=0
-    samples_to_update=0
+    [[ -f "${doid_file}" ]] || die "Missing file (${doid_file})"
+    [[ -f "${status_file}" ]] || die "Missing file (${status_file})"
+    [[ "${mode}" =~ ^(dryrun|patch)$ ]] || die "Unknown mode (${mode})"
+    doid_file_is_ok || die "Something wrong with ${doid_file}"
 
-    # action: visit each target sample in API and check for potential updates in doid file
+    info "Using input file: ${doid_file}"
+    info "Using input file: ${status_file}"
+
+    total_considered=0
+    total_updated=0
+
     samples_json=$(hmf_api_get "samples?type=tumor")
     sample_count=$(jq 'length' <<< "${samples_json}")
-
-    info "Will process ${sample_count} samples and write cmds to ${job_file}"
+    info "Will check a total of ${sample_count} tumor samples"
 
     while read -r line; do
         api_barcode=$(echo "${line}" | cut -f1)
@@ -43,58 +49,53 @@ main () {
         api_id=$(echo "${line}" | cut -f3)
         api_doids=$(sort_csv_string "$(echo "${line}" | cut -f4)")
 
+        # do not consider test samples
         if [[ "${api_name}" == "CPCT12345678T" || "${api_name}" == "CPCT11111111T" ]]; then
-            # do not consider test samples
-            continue
-        elif [[ ! "${api_name}" =~ ^(CPCT|DRUP|WIDE|CORE) ]]; then
-            # only consider samples meant for OncoAct
+            info "SKIPPING: sample is a test sample (${api_name})"
             continue
         fi
-        samples_considered=$((samples_considered+1))
 
+        # only consider samples meant for OncoAct
+        if [[ ! "${api_name}" =~ ^(CPCT|DRUP|WIDE|CORE|ACTN) ]]; then
+            #info "SKIPPING: sample is not an OncoAct sample (${api_name})"
+            continue
+        fi
+
+        total_considered=$((total_considered+1))
         patient=${api_name:0:12}
         count=$(grep -cP "^${patient}" "${doid_file}")
         curation_status=$(grep -P "^${patient}" "${status_file}" | cut -f2 | tail -1)
         sample_info="${api_barcode} (name:${api_name} id:${api_id} status:${curation_status})"
 
-        # TODO make status check work
-        #
-        #if [[ "${curation_status}" =~ ^(NOT_RESOLVED|ALREADY_REPORTED)$ ]]; then
-        #    info "SKIPPING: patient has status ${curation_status} in ${status_file} for ${sample_info}"
-        #    continue
-        #fi
-
         if [[ "${count}" -eq 0 ]]; then
-            warn "SKIPPING: patient ID missing in file (${doid_file}) for ${sample_info}"
+            warn "SKIPPING: patient ID missing in doid file for ${sample_info}"
         elif [[ "${count}" -gt 1 ]]; then
-            warn "SKIPPING: multiple matches in doid file (${doid_file}) for ${sample_info}"
+            warn "SKIPPING: multiple matches in doid file for ${sample_info}"
         elif [[ "${count}" -eq 1 ]]; then
             file_doids=$(get_doids "${patient}")
             file_doids=$(sort_csv_string "${file_doids}")
-            if [[ "${file_doids}" == "" ]]; then
-                warn "SKIPPING: no doids present in file (${doid_file}) for ${sample_info}"
-            elif [[ "${file_doids}" == "${api_doids}" ]]; then
-                info "SKIPPING: identical doids for ${sample_info}"
+            if [[ "${file_doids}" == "${api_doids}" ]]; then
+                continue
+            elif [[ "${file_doids}" == "" ]]; then
+                warn "SKIPPING: no doids present in doid file for ${sample_info}"
             else
-                info "OK: doid update possible ('${api_doids}' to '${file_doids}') for ${sample_info}"
-                echo "echo '[INFO] Updating ${sample_info}'" >> "${job_file}"
-                # The -e allows execution without pressing a key
-                echo "hmf_api_patch -e -c samples -o '${api_id}' -f primary_tumor_doids -v '${file_doids}'" >> "${job_file}"
-                samples_to_update=$((samples_to_update+1))
+                if [[ "${mode}" == "patch" ]]; then
+                    info "OK: updating ('${api_doids}' to '${file_doids}') for ${sample_info}"
+                    hmf_api_patch -e -c samples -o "${api_id}" -f primary_tumor_doids -v "${file_doids}"
+                elif [[ "${mode}" == "dryrun" ]]; then
+                    info "OK: would update ('${api_doids}' to '${file_doids}') for ${sample_info}"
+                else
+                    warn "Param mode has unexpected value (${mode})"
+                fi
+                total_updated=$((total_updated+1))
             fi
         else
-            die "Impossible state reached in if/else: check conditions!"
+            die "Impossible state reached in if/else: check conditions! (${sample_info})"
         fi
     done < <(echo "$samples_json" | jq -cr '.[] | [.barcode,.name,.id,(.primary_tumor_doids | join(","))] | @tsv')
 
-    info "${samples_to_update} samples found to be updated of ${samples_considered} considered"
-    if [[ "${samples_to_update}" -gt 0 ]]; then
-        echo "echo '[INFO] Finished with patching primary_tumor_doids'" >> "${job_file}"
-        info "Making job file executable (${job_file})"
-        chmod +x "${job_file}"
-        info "TODO: Check ${job_file} and execute patches with:"
-        info "  nohup ${job_file} > ${log_file} &"
-    fi
+    info "A total of ${total_updated} samples were updated of ${total_considered} considered"
+    info "Finished with $(basename "$0")"
 }
 
 sort_csv_string () {
