Use message functions where appropriate

diff --git a/api/update_api_db_jsons_acc b/api/update_api_db_jsons_acc
--- a/api/update_api_db_jsons_acc
+++ b/api/update_api_db_jsons_acc
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 JSON_DIR="/data/ops/api/acc/database"
 CRED_DIR="/data/common/dbs/api_credentials/acc"
 CRT_FILE="${CRED_DIR}/api.crt"
@@ -10,13 +12,13 @@ DATETIME=$(date)
 
 DB_TYPES=( fastq entities runs samples sets flowcells inis shares stacks platforms sequencers biopsies )
 
-if [[ ! -f "${CRT_FILE}" ]]; then echo "[ERROR] CRT file not found (${CRT_FILE})" && exit 1; fi
-if [[ ! -f "${KEY_FILE}" ]]; then echo "[ERROR] KEY file not found (${KEY_FILE})" && exit 1; fi
+if [[ ! -f "${CRT_FILE}" ]]; then error "CRT file not found (${CRT_FILE})"; fi
+if [[ ! -f "${KEY_FILE}" ]]; then error "KEY file not found (${KEY_FILE})"; fi
 
 ## In case tmp files do exist but are older than 30 min (cmin param)
 ## then assume previous execution to have timed out and continue anyway
 if [[ $(find "${JSON_DIR}" -maxdepth 1 -name "*.tmp" -cmin -30 | wc -l) -gt 0  ]]; then
-    echo "[INFO] Tmp files younger than 30 min found. Skipping." | tee -a ${LOG_FILE}
+    info "Tmp files younger than 30 min found. Skipping." | tee -a ${LOG_FILE}
     exit 0
 fi
 
@@ -37,9 +39,9 @@ for TYPE in "${DB_TYPES[@]}"; do
 
     if [[ 0 -eq $? ]]; then
         cp ${OUTPUT_FILE_TMP} ${OUTPUT_FILE}
-        echo "[INFO] Written to ${OUTPUT_FILE}"
+        info "Written to ${OUTPUT_FILE}"
     else
-        echo "${DATETIME} WARN retrieval of $TYPE failed so stopping" && exit 1
+        error "${DATETIME} Retrieval of $TYPE failed so stopping"
     fi
 done
 
diff --git a/bam/cram2bam b/bam/cram2bam
--- a/bam/cram2bam
+++ b/bam/cram2bam
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
     echo "-----"
     echo " Usage: $(basename $0) <CRAM file>"
@@ -24,9 +26,9 @@ main() {
     info "Starting with $(basename $0)"
     
     ## sanity checks
-    command -v "${samtools}" >/dev/null 2>&1 || die "${samtools} not found"
-    [[ -f "${cram}" ]] || die "File not found (${cram})"
-    [[ "${cram}" =~ cram$ ]] || die "Not a CRAM file (${cram})"
+    command -v "${samtools}" >/dev/null 2>&1 || error "${samtools} not found"
+    [[ -f "${cram}" ]] || error "File not found (${cram})"
+    [[ "${cram}" =~ cram$ ]] || error "Not a CRAM file (${cram})"
 
     ## variables setup
     bam=$(echo "${cram}" | sed 's/cram$/bam/')
@@ -57,19 +59,6 @@ main() {
     fi
 
     info "Finished with $(basename $0)"
-}
-
-die() { 
-    echo "[ERROR] $(date +"%y%m%d %T") $@" >&2
-    exit 1 
-}
-
-warn() { 
-    echo "[WARN] $(date +"%y%m%d %T") $@" >&2
-}
-
-info() { 
-    echo "[INFO] $(date +"%y%m%d %T") $@"
 }
 
 main
diff --git a/crunch/perform_bcl2fastq_qc b/crunch/perform_bcl2fastq_qc
--- a/crunch/perform_bcl2fastq_qc
+++ b/crunch/perform_bcl2fastq_qc
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 HOSTNAME=$(hostname)
 PARSE_SCRIPT="check_bcl2fastq_conversion.pl"
 ERRLOG_FILE="conversionError.txt"
@@ -48,13 +50,13 @@ for seq_dir in "${seq_dirs[@]}"; do
     
     ## If anything not ok: exit
     if [[ ! -d "${seq_dir}" ]]; then
-        echo "[ERROR] dir does not exist (${seq_dir})" && exit 1; 
+        error "dir does not exist (${seq_dir})"
     elif [[ ! -f "${errlog_path}" ]]; then
-        echo "[ERROR] Errlog does not exist (${errlog_path})" && exit 1;
+        error "Errlog does not exist (${errlog_path})"
     elif [[ ! $(cat ${errlog_path} | tail -1 | grep "with 0 errors and") ]]; then
-        echo "[ERROR] Errlog does not say 0 errors (${errlog_path})" && exit 1; 
+        error "Errlog does not say 0 errors (${errlog_path})"
     elif [[ -z "${hmfrun_name}" ]]; then
-        echo "[ERROR] Have not been able to parse hmfrun_name from sheet (${ssheet_path})" && exit 1; 
+        error "Have not been able to parse hmfrun_name from sheet (${ssheet_path})"
     fi
     
     ## store further cmds so we can print all together at the end
diff --git a/crunch/perform_shallow_qc b/crunch/perform_shallow_qc
--- a/crunch/perform_shallow_qc
+++ b/crunch/perform_shallow_qc
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 run_paths=("$@")
 
 if [[ ${#run_paths[@]} -eq 0 || $1 == "-h" || $1 == "--help" ]]; then
@@ -67,14 +69,14 @@ for run_dir in "${run_paths[@]}"; do
     all_files_ok="yes"
     for required_file in "${aqc_file}" "${pqc_file}" "${ppu_file}" "${vsn_file}" "${wgs_file_r}"; do
         if [[ -z "${required_file}" ]]; then
-            echo "[WARN] One of the required file variables is empty!!"
+            warn "One of the required file variables is empty!!"
             all_files_ok="no"
         elif [[ ! -f "${required_file}" ]]; then
-            echo "[WARN] File does not exist (${required_file})"
+            warn "File does not exist (${required_file})"
             all_files_ok="no"
         fi
     done
-    if [[ ! ${all_files_ok} == "yes" ]]; then echo "[ERROR] Something wrong with required files" && exit 1; fi
+    if [[ ! ${all_files_ok} == "yes" ]]; then error "Something wrong with required files"; fi
 
     ## gather WgsMetrics
     head=$(cat ${wgs_file_r} | grep GENOME_T)
diff --git a/datarequest/databaseloading/load_run_into_test_db b/datarequest/databaseloading/load_run_into_test_db
--- a/datarequest/databaseloading/load_run_into_test_db
+++ b/datarequest/databaseloading/load_run_into_test_db
@@ -1,20 +1,19 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 run_dir=$1
 
 if [[ -z "${run_dir}" ]]; then
-    echo "[ERROR] No run dir provided. Exiting"
-    exit 1
+    error "No run dir provided. Exiting"
 fi
 
 if [[ ! -d "${run_dir}" ]]; then
-    echo "[ERROR] Not a dir as run dir provided (maybe file?). Exiting"
-    exit 1
+    error "Not a dir as run dir provided (maybe file?). Exiting"
 fi
 
 if [[ ! -f "${run_dir}"*.purple.purity.tsv ]]; then
-    echo "[ERROR] Not the correct run dir provided (important file missing in run dir). Exiting"
-    exit 1
+    error "Not the correct run dir provided (important file missing in run dir). Exiting"
 fi
 
 # Configuration of paths
diff --git a/gcp/do_archive_directory_to_gcp b/gcp/do_archive_directory_to_gcp
--- a/gcp/do_archive_directory_to_gcp
+++ b/gcp/do_archive_directory_to_gcp
@@ -3,31 +3,30 @@
 # Note: This script assumes an account is active in gcloud which has the privileges to make backups in GS.
 #  A service account with this privileges is hmf-ops@hmf-database.iam.gserviceaccount.com
 
+source message_functions || exit 1
+
 local_path=$1 && shift
 remote_archive_dir=$1 && shift
 
 minimal_local_entries=0
 if [[ "$#" -gt 0 ]]; then
     minimal_local_entries=$1 && shift
-    echo "[DEBUG] Setting minimal local entries to ${minimal_local_entries} for ${local_path}"
+    info "Setting minimal local entries to ${minimal_local_entries} for ${local_path}"
 fi
 
 if [[ -z "${local_path}" ]] || [[ -z "${remote_archive_dir}" ]]; then
-    echo "[ERROR] Not all input parameters provided to $(basename $0). Exiting"
-    exit 1
+    error "Not all input parameters provided to $(basename $0). Exiting"
 fi
 
 if [[ ! -d "${local_path}" ]]; then
-    echo "[ERROR] ${local_path} is not a directory. Exiting"
-    exit 1
+    error "${local_path} is not a directory. Exiting"
 fi
 
 local_entry_count=$(ls ${local_path} | wc -l)
 if [[ ${local_entry_count} -lt ${minimal_local_entries} ]]; then
-    echo "[WARN] Number of entries in ${local_path} is ${local_entry_count} which is less than required ${minimal_local_entries}. Exiting"
-    exit 1
+    error "Number of entries in ${local_path} is ${local_entry_count} which is less than required ${minimal_local_entries}. Exiting"
 else
-    echo "[DEBUG] Number of entries ${local_entry_count} is equal or larger than minimum required of ${minimal_local_entries}"
+    info "Number of entries ${local_entry_count} is equal or larger than minimum required of ${minimal_local_entries}"
 fi
 
 # -d = delete files on GS that no longer exist on datastore
diff --git a/lims/gather_submission_aria_config b/lims/gather_submission_aria_config
--- a/lims/gather_submission_aria_config
+++ b/lims/gather_submission_aria_config
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 CREATE_ARIA_SCRIPT="create_aria2_config_by_set_name"
 
 if [[ $# -eq 0 ]]; then echo "Usage: $(basename $0) HMFreg0000"; exit 1; fi
@@ -14,57 +16,57 @@ out_config="${output_dir}/${submission}.aria.txt"
 out_gcp_du="${output_dir}/${submission}_disk_usage_gcp.txt"
 
 ## sanity checks
-if [[ ! -d "${submission_dir}" ]] ; then echo "[ERROR] Submission dir does not exist (${submission_dir})"; exit 1; fi
-if [[ ! -w "${submission_dir}" ]] ; then echo "[ERROR] Submission dir is not writable (${submission_dir})"; exit 1; fi
-if [[ ! -f "${runs_json}" ]] ; then echo "[ERROR] Runs json does not exist (${runs_json})"; exit 1; fi
-if [[   -d "${output_dir}" ]] ; then echo "[ERROR] Output dir already exists (${output_dir})"; exit 1; fi
+if [[ ! -d "${submission_dir}" ]] ; then error "Submission dir does not exist (${submission_dir})"; fi
+if [[ ! -w "${submission_dir}" ]] ; then error "Submission dir is not writable (${submission_dir})"; fi
+if [[ ! -f "${runs_json}" ]] ; then error "Runs json does not exist (${runs_json})"; fi
+if [[   -d "${output_dir}" ]] ; then error "Output dir already exists (${output_dir})"; fi
 
-echo "[INFO] Creating aria output dir (${output_dir})"
+info "Creating aria output dir (${output_dir})"
 mkdir "${output_dir}" || exit 1
 
-echo "[INFO] Changing dir to output dir (${output_dir})"
+info "Changing dir to output dir (${output_dir})"
 cd "${output_dir}" || exit 1
 
 non_val_count=$(jq '[select(.[].status != "Validated")] | length' "${runs_json}")
 if [[ "${non_val_count}" -gt 0 ]]; then
-    echo "[WARN] There are ${non_val_count} runs that will be missing in config because status != Validated"
+    warn "There are ${non_val_count} runs that will be missing in config because status != Validated"
 fi
 
-echo "[INFO] Creating job file (${create_job})"
+info "Creating job file (${create_job})"
 for run_name in $(jq -r '.[] | select(.status == "Validated") | .name' "${runs_json}"); do
     echo "${CREATE_ARIA_SCRIPT} ${run_name}"
 done > "${create_job}"
 chmod +x "${create_job}"
 
-echo "[INFO] Executing job script (runtime depends on amount of samples, check progress in log '${create_log}')"
+info "Executing job script (runtime depends on amount of samples, check progress in log '${create_log}')"
 parallel -j5 -I% --max-args 1 % < "${create_job}" > "${create_log}" 2>&1
 
-echo "[INFO] Printing any non INFO lines from log"
+info "Printing any non INFO lines from log"
 grep -v '\[INFO\]' "${create_log}"
 non_info_count=$(grep -vc '\[INFO\]' "${create_log}")
 
-echo "[INFO] Double checking log for errors with check_log_file (will print if any found)"
+info "Double checking log for errors with check_log_file (will print if any found)"
 check_log_file "${create_log}"
 
-echo "[INFO] Joining all run aria.txt files to ${out_config}"
+info "Joining all run aria.txt files to ${out_config}"
 find "${output_dir}" -mindepth 1 -maxdepth 1 -type f -name "*_*.aria.txt" -exec cat {} \+ > "${out_config}"
 
-echo "[INFO] Writing file sizes to ${out_gcp_du}"
+info "Writing file sizes to ${out_gcp_du}"
 if [[ "$(find "${output_dir}" -name "*_internal_urls.txt" | wc -l)" -lt 1 ]]; then
-    echo "[ERROR] No internal urls files found (should not happen)." && exit 1
+    error "No internal urls files found (should not happen)."
 else
     # Intellij wants you to quote the find cmd: don't do this as du will work only on first file
     # shellcheck disable=SC2046
     gsutil du -shc $(find "${output_dir}" -name "*_internal_urls.txt" -exec cat {} +) > "${out_gcp_du}"
 fi
 
-echo "[INFO] Action: Check one URL manually in browser"
+info "Action: Check one URL manually in browser"
 grep https "${out_config}" | tail -1
 
-echo "[INFO] Action: If all OK you can upload final config to Nextcloud with:"
-echo " upload_files_to_nextcloud_research ${out_config}"
+info "Action: If all OK you can upload final config to Nextcloud with:"
+info " upload_files_to_nextcloud_research ${out_config}"
 
 if [[ "${non_info_count}" -gt 0 ]]; then
-    echo "[WARNING] Non-info lines were encountered in log. Proceed with caution!!"
+    warn "Non-info lines were encountered in log. Proceed with caution!!"
 fi
 echo ""
diff --git a/ops/manual_fastq_register b/ops/manual_fastq_register
--- a/ops/manual_fastq_register
+++ b/ops/manual_fastq_register
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 api_url='http://api.prod-1/hmf/v1'
 
 hmfapi () {
@@ -21,30 +23,30 @@ sample_name=""
 sample_id=$(curl -s "${api_url}/samples?barcode=${barcode}" | jq '.[].id')
 
 if [[ -z "${sample_id}" ]]; then
-    echo "[ERROR] Barcode not found at API (${barcode})" && exit 1
+    error "Barcode not found at API (${barcode})"
 fi
 
 ## make sure the FASTQ files contain only ONE sample
 sample_count=$(find ${fastq_dir} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq | wc -l)
 if [[ ${sample_count} -ne 1 ]]; then
-    echo "[ERROR] FASTQ files in dir should be from one sample (found ${sample_count} samples in dir \"${fastq_dir}\")" && exit 1;
+    error "FASTQ files in dir should be from one sample (found ${sample_count} samples in dir \"${fastq_dir}\")"
 else
     sample_name=$(find ${fastq_dir} -name "*_R1_*.fastq.gz" -exec basename {} \; | cut -d"_" -f1 | sort | uniq)
 fi
 
 ## find all R1 fastq files -> check R2 presence -> register pair
-echo "[INFO] Starting with sample name:${sample_name} barcode:${barcode} id:${sample_id}"
+info "Starting with sample name:${sample_name} barcode:${barcode} id:${sample_id}"
 find ${fastq_dir} -name "*_R1_*.fastq.gz" -exec basename {} \; | while read R1; do
     R2=$( echo "${R1}" | sed 's/_R1_/_R2_/' )
     if [[ -z "${R1}" || -z "${R2}" ]]; then
-        echo "[WARN] Somehow R1 found but R2 file does not exist (${R2}) so SKIPPING this pair."
+        warn "Somehow R1 found but R2 file does not exist (${R2}) so SKIPPING this pair."
     else
-        echo "[INFO] Registering fastq R1/R2 pair (name_r1=${R1})"
+        info "Registering fastq R1/R2 pair (name_r1=${R1})"
         hmfapi --print=b POST "${api_url}/fastq" name_r1="${R1}" name_r2="${R2}" bucket="hmf-fastq-storage" sample_id="${sample_id}"
     fi
 done
 
-echo "[INFO] Registering sample"
+info "Registering sample"
 curl -s --header "Content-type: application/json" \
     -X PATCH \
     -d '{"name": "'${sample_name}'", "status": "Pending_QC"}' "${api_url}/samples/${sample_id}"
diff --git a/utilityscripts/tar_flowcell_bcl b/utilityscripts/tar_flowcell_bcl
--- a/utilityscripts/tar_flowcell_bcl
+++ b/utilityscripts/tar_flowcell_bcl
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 path_of_dir_to_tar=$1
 out_root="${2:-/data2/processed}"
 
@@ -29,7 +31,7 @@ if [[ -f "${sample_sheet}" ]]; then
         grep -vP "^[\,\s]+$" | cut -d"," -f "${col_idx}" | sort | uniq)")
     out_tar_name="${tar_dir_name}_${projects}_BCL.tar"
 else
-    echo "[WARN] SampleSheet.csv not found (${sample_sheet}) so unable to add project ID to tar name"
+    warn "SampleSheet.csv not found (${sample_sheet}) so unable to add project ID to tar name"
     out_tar_name="${tar_dir_name}_BCL.tar"
 fi
 
@@ -39,16 +41,19 @@ out_md5_path="${out_tar_path}.md5"
 
 ## sanity checks
 if [[ ! -d "${out_root}" ]]; then
-    echo "[ERROR] Output root dir does not exist (${out_root})" && exit 1
+    error "Output root dir does not exist (${out_root})"
 fi
+
 if [[ -e "${out_tar_path}" ]]; then
-    echo "[ERROR] Provided output tar file already exists (${out_tar_path})" && exit 1
+    error "Provided output tar file already exists (${out_tar_path})"
 fi
+
 if [[ ! -e "${path_of_dir_to_tar}" ]]; then
-    echo "[ERROR] Provided dir to tar does not exist (${path_of_dir_to_tar})" && exit 1
+    error "Provided dir to tar does not exist (${path_of_dir_to_tar})"
 fi
+
 if [[ $(find ${path_of_dir_to_tar} -type f -name "*.bcl.bgzf" -or -name "*.cbcl" | wc -l) -lt 1 ]]; then
-    echo "[ERROR] Provided dir to tar does not contain BCL or CBCL files (${path_of_dir_to_tar})" && exit 1
+    error "Provided dir to tar does not contain BCL or CBCL files (${path_of_dir_to_tar})"
 fi
 
 ## construct tar command
@@ -62,26 +67,26 @@ tar_cmd+=" -cf ${out_tar_path}"
 tar_cmd+=" ${tar_dir_name}"
 
 ## create output files
-echo "[INFO] Changing dir to in root (${in_root})"
+info "Changing dir to in root (${in_root})"
 cd ${in_root} || exit 1
 
-echo "[INFO] Creating tar file (${out_tar_path})"
+info "Creating tar file (${out_tar_path})"
 ${tar_cmd} || exit 1
 du_of_tar=$(du -h "${out_tar_path}" | cut -f1)
 
-echo "[INFO] Creating content file (${out_cnt_path})"
+info "Creating content file (${out_cnt_path})"
 tar -tf "${out_tar_path}" > "${out_cnt_path}"
 
-echo "[INFO] Changing dir to out root (${out_root})"
+info "Changing dir to out root (${out_root})"
 cd ${out_root} || exit 1
 
-echo "[INFO] Creating md5 file (${out_md5_path})"
+info "Creating md5 file (${out_md5_path})"
 md5sum "${out_tar_name}" > "${out_md5_path}"
 
-echo "[INFO] Output files ready:"
-echo "[INFO]  ${out_tar_path} (${du_of_tar})"
-echo "[INFO]  ${out_cnt_path}"
-echo "[INFO]  ${out_md5_path}"
-echo "[INFO] Cmd to sync output files to datastore:"
-echo "  rsync -ahP --stats ${out_tar_path} ${out_cnt_path} ${out_md5_path} ds:/data/tmp/"
-echo ""
+info "Output files ready:"
+info " ${out_tar_path} (${du_of_tar})"
+info " ${out_cnt_path}"
+info " ${out_md5_path}"
+info "Cmd to sync output files to datastore:"
+info "  rsync -ahP --stats ${out_tar_path} ${out_cnt_path} ${out_md5_path} ds:/data/tmp/"
+info ""
diff --git a/validation/validate_giab_mixin_sage b/validation/validate_giab_mixin_sage
--- a/validation/validate_giab_mixin_sage
+++ b/validation/validate_giab_mixin_sage
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 source locate_files || exit 1
+source message_functions || exit 1
 
 run_dir=$1 && shift
 out_name=$1 && shift # optional
@@ -20,9 +21,9 @@ truth_vcf_path="${truth_dir_path}/${truth_vcf_name}"
 truth_bed_path="${truth_dir_path}/${truth_bed_name}"
 
 ## init checks
-if [[ ! -w "${val_base}" ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
-if [[ ! -f "${truth_vcf_path}" ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
-if [[ ! -f "${truth_bed_path}" ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
+if [[ ! -w "${val_base}" ]]; then error "validation base not writable (${val_base})"; fi
+if [[ ! -f "${truth_vcf_path}" ]]; then error "truth VCF not available (${truth_vcf_path})"; fi
+if [[ ! -f "${truth_bed_path}" ]]; then error "truth BED not available (${truth_bed_path})"; fi
 if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     echo "-----"
     echo " Descr: Validate GIAB run"
@@ -34,7 +35,7 @@ if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     exit 1
 fi
 
-echo "[INFO] START with $(basename $0)"
+info "START with $(basename $0)"
 
 ## -----
 ## Find somatic VCF
@@ -52,14 +53,14 @@ else
     elif [[ -f "${pv5_path}" ]]; then
         run_som_vcf_path=${pv5_path}
     else
-        echo "[ERROR] Unable to find somatic VCF" && exit 1;
+        error "Unable to find somatic VCF"
     fi
 fi
 run_som_vcf_name=$(basename ${run_som_vcf_path})
 
 ## -----
 ## Prepare
-echo "[INFO] Using input VCF (${run_som_vcf_name})"
+info "Using input VCF (${run_som_vcf_name})"
 run_name="$(basename ${run_dir} )"
 if [[ ! -z "${out_name}" ]]; then
     out_name="${truth_version}__vs__${out_name}"
@@ -70,9 +71,9 @@ fi
 out_path="${val_base}/${out_name}"
 tmp_path="${out_path}/vcfeval"
 if [[ -e "${out_path}" ]]; then
-    echo "[ERROR] Output dir exists remove first: ${out_path}" && exit 1
+    error "Output dir exists remove first: ${out_path}"
 else 
-    echo "[INFO] Using output dir (${out_path})"
+    info "Using output dir (${out_path})"
     mkdir ${out_path}
 fi
 
@@ -81,16 +82,16 @@ fi
 cp "${run_som_vcf_path}"* ${out_path}
 run_som_vcf_path="${out_path}/${run_som_vcf_name}"
 if [[ ${run_som_vcf_path} =~ .vcf$ ]]; then
-    echo "[INFO] Running bgzip"
+    info "Running bgzip"
     bgzip ${run_som_vcf_path}
-    echo "[INFO] Running tabix"
+    info "Running tabix"
     tabix "${run_som_vcf_path}.gz"
     run_som_vcf_path="${run_som_vcf_path}.gz"
 fi 
 
 ## -----
 ## Run variant evaluation
-echo "[INFO] Running RTGtools vcfeval"
+info "Running RTGtools vcfeval"
 ${rtg_exec} vcfeval \
     --template=${rtg_sdf_path} \
     --threads=${rtg_threads} \
@@ -119,7 +120,7 @@ for call_type in "${call_classes[@]}"; do
     call_type_sum=0
     for variant_type in "${variant_types[@]}"; do
         out_vcf="${tmp_path}/${variant_type}_${call_type}.vcf.gz"
-        echo "[INFO] Creating $call_type $variant_type sub VCF"
+        info "Creating $call_type $variant_type sub VCF"
         java -jar ${gatk_jar} -T SelectVariants --variant ${rtg_vcf} -o ${out_vcf} -R ${ref_genome_fasta} -selectType ${variant_type}
         variant_count=$(zcat ${out_vcf} | grep -cv "^#")
         call_type_sum=$((call_type_sum + variant_count))
@@ -144,7 +145,7 @@ cat ${tmp_path}/summary.txt | sed 's/  */ /g' | sed 's/^ *//' | grep None | whil
         "${thres}" "${tp}" "${fp}" "${fn}" "${prec}" "${sens}" "${score}"
 done > ${out_path}/rtg_summary.tsv
 
-echo "[INFO] Output in ${out_path}"
-echo "[INFO] Counts in ${metrics_out_file}"
-echo "[INFO] DONE with $(basename $0)"
+info "Output in ${out_path}"
+info "Counts in ${metrics_out_file}"
+info "DONE with $(basename $0)"
 
diff --git a/validation/validate_giab_pipeline_run b/validation/validate_giab_pipeline_run
--- a/validation/validate_giab_pipeline_run
+++ b/validation/validate_giab_pipeline_run
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
-source locate_files
+source locate_files || exit 1
+source message_functions || exit 1
 
 val_base='/data/giab/validation/sets'
 gatk_path='/data/common/tools/gatk_v3.8.0/GenomeAnalysisTK.jar'
@@ -15,14 +16,14 @@ truth_vcf_name='NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2
 truth_vcf_path="${truth_dir_path}/${truth_vcf_name}"
 truth_vcf_path_snv=$(echo ${truth_vcf_path} | sed 's/\.vcf\.gz/_SNP\.vcf.\gz/')
 
-if [[ ! -w "${val_base}" ]]; then echo "[ERROR] validation base not writable (${val_base})"; exit 1; fi
-if [[ ! -f "${gatk_path}" ]]; then echo "[ERROR] GATK JAR not available (${gatk_path})"; exit 1; fi
-if [[ ! -f "${ref_genome_fasta}" ]]; then echo "[ERROR] Ref fasta not available (${ref_genome_fasta})"; exit 1; fi
-if [[ ! -f "${truth_vcf_path}" ]]; then echo "[ERROR] truth VCF not available (${truth_vcf_path})"; exit 1; fi
-if [[ ! -f "${truth_bed_path}" ]]; then echo "[ERROR] truth BED not available (${truth_bed_path})"; exit 1; fi
-if [[ ! -d "${rtg_sdf_path}" ]]; then echo "[ERROR] RTG SDF directory not found (${rtg_sdf_path})"; exit 1; fi
-if [[ ! $(command -v datamash) ]]; then echo "[ERROR] Dependency 'datamash' not found"; exit 1; fi
-if [[ ! $(command -v rtg) ]]; then echo "[ERROR] Dependency 'rtg' not found"; exit 1; fi
+if [[ ! -w "${val_base}" ]]; then error "validation base not writable (${val_base})"; fi
+if [[ ! -f "${gatk_path}" ]]; then error "GATK JAR not available (${gatk_path})"; fi
+if [[ ! -f "${ref_genome_fasta}" ]]; then error "Ref fasta not available (${ref_genome_fasta})"; fi
+if [[ ! -f "${truth_vcf_path}" ]]; then error "truth VCF not available (${truth_vcf_path})"; fi
+if [[ ! -f "${truth_bed_path}" ]]; then error "truth BED not available (${truth_bed_path})"; fi
+if [[ ! -d "${rtg_sdf_path}" ]]; then error "RTG SDF directory not found (${rtg_sdf_path})"; fi
+if [[ ! $(command -v datamash) ]]; then error "Dependency 'datamash' not found"; fi
+if [[ ! $(command -v rtg) ]]; then error "Dependency 'rtg' not found"; fi
 
 if [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
     echo "-----"
@@ -38,22 +39,22 @@ run_path=$1 && shift
 ## -----
 ## Checks and Setup
 ## -----
-if [[ ! -d "${run_path}" ]]; then echo "[ERROR] Provided run path does not exist?"; exit 1; fi
+if [[ ! -d "${run_path}" ]]; then error "Provided run path does not exist?"; fi
 
 ## find input VCF
 input_vcf_path=$(find "${run_path}" -wholename "*/germline_caller/*.germline.vcf.gz")
-if [[ ! -f "${input_vcf_path}" ]]; then echo "[ERROR] No germline VCF found (${run_path})" && exit 1; fi
+if [[ ! -f "${input_vcf_path}" ]]; then error "No germline VCF found (${run_path})"; fi
 
 run_name=$(basename "${run_path}")
 output_dir="${val_base}/${run_name}_Validation"
 tmp_dir="${output_dir}/tmp"
 
-if [[ -d "${output_dir}" ]]; then echo "[ERROR] output_dir already exists (${output_dir})"; exit 1; fi
+if [[ -d "${output_dir}" ]]; then error "output_dir already exists (${output_dir})"; fi
 
-echo "[INFO] Creating output dir (${output_dir})"
+info "Creating output dir (${output_dir})"
 mkdir -p "${output_dir}"
 mkdir -p "${tmp_dir}"
-echo "[INFO] Copying germline vcf (${input_vcf_path})"
+info "Copying germline vcf (${input_vcf_path})"
 cp ${input_vcf_path}* "${output_dir}"
 
 ## -----
@@ -63,20 +64,20 @@ start_vcf_path="${output_dir}/input.vcf"
 start_vcf_name="$(basename "${start_vcf_path}")"
 
 if [[ ${input_vcf_path} =~ .vcf$ ]]; then
-    echo "[INFO] Copying Germline VCF to ${start_vcf_path}"
+    info "Copying Germline VCF to ${start_vcf_path}"
     cp "${input_vcf_path}" "${start_vcf_path}"
 elif [[ ${input_vcf_path} =~ .gz$ ]]; then
-    echo "[INFO] Germline VCF is compressed: gunzippig to ${start_vcf_path}"
+    info "Germline VCF is compressed: gunzippig to ${start_vcf_path}"
     gunzip -c "${input_vcf_path}" > "${start_vcf_path}"
 else
-    echo "[ERROR] Germline VCF of unsupported extension" && exit 1
+    error "Germline VCF of unsupported extension"
 fi
 
-echo "[INFO] Running RTGTools bgzip on ${start_vcf_name}"
+info "Running RTGTools bgzip on ${start_vcf_name}"
 rtg bgzip "${start_vcf_path}"
 start_vcf_path="${start_vcf_path}.gz"
 start_vcf_name="${start_vcf_name}.gz"
-echo "[INFO] Running RTGTools index on ${start_vcf_name}"
+info "Running RTGTools index on ${start_vcf_name}"
 rtg index -f vcf "${start_vcf_path}"
 
 ## -----
@@ -86,9 +87,9 @@ snp_vcf_path="${output_dir}/SNP_${start_vcf_name}"
 snp_vcf_name=$(basename "${snp_vcf_path}")
 
 if [[ -f "${snp_vcf_path}" ]]; then
-    echo "[INFO] SNP vcf already exist, skipping (${snp_vcf_path})"
+    info "SNP vcf already exist, skipping (${snp_vcf_path})"
 else
-    echo "[INFO] Running GATK to create SNP vcf (${snp_vcf_name})"
+    info "Running GATK to create SNP vcf (${snp_vcf_name})"
     java -Djava.io.tmp_dir="${tmp_dir}" -jar "${gatk_path}" \
         -T SelectVariants \
         -R "${ref_genome_fasta}" \
@@ -98,7 +99,7 @@ else
         -V "${start_vcf_path}" \
         -selectType SNP \
         -o "${snp_vcf_path}"
-    if [[ $? -ne 0 ]]; then { echo "[ERROR] GATK SelectVariants Failed"; exit 1; } fi
+    if [[ $? -ne 0 ]]; then { error "GATK SelectVariants Failed"; } fi
 fi
 
 ## no INDELs for now
@@ -133,10 +134,10 @@ if [[ "${wgs_metrics_count}" -eq 1 ]]; then
     cat "${wgs_metrics_path}" | grep -A1 GENOME | datamash transpose -W > "${wgs_tsv_out_path}"
     cat "${wgs_metrics_path}" | grep -A1 GENOME | datamash transpose -W --output-delimiter "," > "${wgs_csv_out_path}"
 else
-    echo "[WARN] Search for wgsmetrics found ${wgs_metrics_count} files"
+    warn "Search for wgsmetrics found ${wgs_metrics_count} files"
 fi
 
-echo "[INFO] Running RTGtools vcfeval (${rtg_out_name})"
+info "Running RTGtools vcfeval (${rtg_out_name})"
 rtg vcfeval \
     --template "${rtg_sdf_path}" \
     --threads=8 \
@@ -145,11 +146,11 @@ rtg vcfeval \
     --bed-regions="${truth_bed_path}" \
     --output "${rtg_out_path}"
 
-echo "[INFO] Reformatting RTGtools vcfeval results into csv/tsv"
+info "Reformatting RTGtools vcfeval results into csv/tsv"
 cat "${sum_out_path}" | grep -P "Threshold|None" | datamash transpose --whitespace > "${rtg_tsv_out_path}"
 cat "${sum_out_path}" | grep -P "Threshold|None" | datamash transpose --whitespace --output-delimiter "," > "${rtg_csv_out_path}"
 
-echo "[INFO] Final output written to:"
-echo "[INFO]   WGSMetrics: ${wgs_tsv_out_path}"
-echo "[INFO]   RTGTools: ${rtg_tsv_out_path}"
-echo "[INFO] Finished with $(basename $0)"
+info "Final output written to:"
+info "  WGSMetrics: ${wgs_tsv_out_path}"
+info "  RTGTools: ${rtg_tsv_out_path}"
+info "Finished with $(basename $0)"
diff --git a/validation/verify_pipeline_run b/validation/verify_pipeline_run
--- a/validation/verify_pipeline_run
+++ b/validation/verify_pipeline_run
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source message_functions || exit 1
+
 print_usage(){
     echo "-----"
     echo " Descr: Verifies a new COLO829T Somatic pipeline run"
@@ -90,9 +92,9 @@ main() {
     url_to_check="${gcp_url}/${file_to_check}"
     msg=$(gsutil ls "${url_to_check}" 2>&1)
     if [[ $? -eq 1 ]]; then
-        echo "[ERROR] Cannot access file (${url_to_check})"
-        echo "[ERROR] ErrCode=${?} ErrMsg=\"${msg}\""
-        echo "[ERROR] Check run contents with: gsutil ls ${gcp_url}"
+        warn "Cannot access file (${url_to_check})"
+        warn "ErrCode=${?} ErrMsg=\"${msg}\""
+        warn "Check run contents with: gsutil ls ${gcp_url}"
         exit 1
     else
         info "File ${file_to_check} found in bucket so assuming run is complete."
@@ -192,17 +194,6 @@ print_sql_code() {
     echo "  echo \"[INFO] Executing \$sql_file_name (log: \$log_file)\" "
     echo "  execute_sql_on_ds_prod \"\$sql_file\" > \"\${log_file}\" "
     echo "done"
-}
-
-die() { 
-    echo "[ERROR] $(date +"%y%m%d %T")" "$@" >&2
-    exit 1 
-}
-warn() { 
-    echo "[WARN] $(date +"%y%m%d %T")" "$@" >&2
-}
-info() { 
-    echo "[INFO] $(date +"%y%m%d %T")" "$@"
 }
 
 main
