DEV-1272: Remove old api database location.

diff --git a/api/update_api_db_jsons_acc b/api/update_api_db_jsons_acc
--- a/api/update_api_db_jsons_acc
+++ b/api/update_api_db_jsons_acc
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 
 JSON_DIR="/data/ops/api/acc/database"
-JSON_DIR_OLD="/data/lims/api_files/acc"
 CRED_DIR="/data/common/dbs/api_credentials/acc"
 CRT_FILE="${CRED_DIR}/api.crt"
 KEY_FILE="${CRED_DIR}/api.key"
@@ -33,14 +32,10 @@ for TYPE in "${DB_TYPES[@]}"; do
         cp ${OUTPUT_FILE_TMP} ${OUTPUT_FILE}
         echo "[INFO] Written to ${OUTPUT_FILE}"
     else
-        echo "${DATETIME} WARNING retrieval of $TYPE failed so stopping" && exit 1
+        echo "${DATETIME} WARN retrieval of $TYPE failed so stopping" && exit 1
     fi
 done
 
 rm ${JSON_DIR}/tmp_*.tmp
-
-# TODO remove once /data/lims/api_files no longer needed
-# TODO and then do not forget JSON_DIR_OLD variable on top
-find ${JSON_DIR} -mindepth 1 -maxdepth 1 -type f -exec cp {} ${JSON_DIR_OLD} \;
 
 echo "${DATETIME} Script $(basename $0) has finished" | tee -a ${LOG_FILE}
