Better formatting

diff --git a/lims/fetch_register_json b/lims/fetch_register_json
--- a/lims/fetch_register_json
+++ b/lims/fetch_register_json
@@ -57,12 +57,12 @@ fi
 
 
 # Standard
-info "Fetching data for ${barcode}\n"
+info "Fetching data for ${barcode}"
 ask_request_body=$(echo -e "{\"isolationBarcode\": \"${barcode}\"}")
 register_json=$(curl -X 'POST' 'http://lama.prod-1/api/registration/hartwig-api/show' \
                   -H 'accept: */*' \
                   -H 'Content-Type: application/json' \
-                  -d "${ask_request_body}") || die "Could not fetch registration json for ${barcode}\n"
+                  -d "${ask_request_body}") || die "Could not fetch registration json for ${barcode}"
 setname=$(echo "${register_json}" | jq -r '.sampleSetName')
 
 
@@ -73,19 +73,19 @@ if [[ ! ${hmf_api_sample_json} == "[]" ]]; then
     status=$(echo "${hmf_api_sample_json}" | jq '.[].status')
     if [[ ${status} == "Deleted" ]]; then
         c2f_override="true"
-        warn "The sample ${barcode} has the DELETED status in the Hartwig API, set cram2fastq. Check if correct\n"
+        warn "The sample ${barcode} has the DELETED status in the Hartwig API, set cram2fastq. Check if correct"
     else
-        warn "The sample ${barcode} already exist with status ${status}\n"
+        warn "The sample ${barcode} already exist with status ${status}"
     fi
 fi
 
-info "Check Hartwig API runs on ${barcode}\n"
+info "Check Hartwig API runs on ${barcode}"
 setname_without_date=$(echo "${setname}" | cut -d_ -f2-)
 hmf_api_run_json=$(hmf_api_get "runs?context=DIAGNOSTIC&set_name_contains=${setname_without_date}")
 run_count=$(echo ${hmf_api_run_json} | jq 'map(select(.status != "Invalidated")) | length' | tr -d '"\n')
 if [[ ${run_count} > 0 ]]; then
     check="false"
-    warn "There already exist runs for ${barcode}: ${setname_without_date}\n"
+    warn "There already exist runs for ${barcode}: ${setname_without_date}"
 fi
 
 # VHIO checks
@@ -94,10 +94,10 @@ tum_reporting_id=$(echo "${register_json}" | jq -r '.sample.reportingId')
 ini=$(echo "${register_json}" | jq -r '.ini')
 if [[ ${ini} == "RNA.ini" && ${submission} =~ ^Diagnostic* && ${tum_reporting_id} =~ ^CUP*|^TIL*|^VDH*|^BRIOME* ]]; then
      ini_override="FASTQ.ini"
-     warn "RNA sample from VHIO (${barcode}) detected, changed to FASTQ output. Remember to send data out after sequencing\n"
+     warn "RNA sample from VHIO (${barcode}) detected, changed to FASTQ output. Remember to send data out after sequencing"
 elif [[ ${ini} == "Somatic.ini" && ${submission} =~ ^Diagnostic* && ${tum_reporting_id} =~ ^CUP*|^BRIOME* && ${run_count} == 0 ]]; then
      ini_override="ShallowSeq.ini"
-     warn "Sample from VHIO (${barcode}) detected with Somatic output, but no runs. Changed to ShallowSeq output\n"
+     warn "Sample from VHIO (${barcode}) detected with Somatic output, but no runs. Changed to ShallowSeq output"
 fi
 
 # HSS checks
@@ -116,15 +116,15 @@ request_body="{${request_body}}"
 
 # Check force option
 if [[ ${force} == "true" ]]; then
-   warn "Force option used, overwriting any possible issues to write request body for registration\n"
+   warn "Force option used, overwriting any possible issues to write request body for registration"
    check="true"
 fi
 
 
 # Output request body (or not)
 if [[ ${check} == "true" ]]; then
-    info "Writing registration request json for LAMA to ${out_path}${setname}.json\n"
+    info "Writing registration request json for LAMA to ${out_path}${setname}.json"
     echo -e ${request_body} > "${out_path}${setname}.json"
 else
-    die "Not writing registration request json for barcode ${barcode}\n"
+    die "Not writing registration request json for barcode ${barcode}"
 fi
