Code style improvements in lims functions

diff --git a/lims/gather_submission b/lims/gather_submission
--- a/lims/gather_submission
+++ b/lims/gather_submission
@@ -101,12 +101,11 @@ echo "[INFO] Or get reporting info (for ${pdfName}):"
 echo " cat ${repFile} | cut -f1 --complement"
 echo "[INFO] If you finish the submission then please also chown:"
 echo " sudo chown -R root:root ${outPath}"
-  
 
 ## warn if not complete
 if [[ ${hmfCount} -ne ${sbpCount} ]]; then 
-  echo "[WARNING] There might be missing samples!" 
-  exit 1
+    echo "[WARNING] There might be missing samples!"
+    exit 1
 fi
 
 exit 0
