get disk usage of all files in aria config and refactor

diff --git a/lims/gather_submission_aria_config b/lims/gather_submission_aria_config
--- a/lims/gather_submission_aria_config
+++ b/lims/gather_submission_aria_config
@@ -11,6 +11,7 @@ runs_json="${submission_dir}/runs.json"
 create_job="${output_dir}/create_aria_configs.sh"
 create_log="${output_dir}/create_aria_configs.log"
 out_config="${output_dir}/${submission}.aria.txt"
+out_gcp_du="${output_dir}/${submission}_disk_usage_gcp.txt"
 
 ## sanity checks
 if [[ ! -d "${submission_dir}" ]] ; then echo "[ERROR] Submission dir does not exist (${submission_dir})"; exit 1; fi
@@ -22,7 +23,7 @@ echo "[INFO] Creating aria output dir (${output_dir})"
 mkdir "${output_dir}" || exit 1
 
 echo "[INFO] Changing dir to output dir (${output_dir})"
-cd ${output_dir} || exit 1
+cd "${output_dir}" || exit 1
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] Unable to change dir to ${output_dir}" && exit 1; fi
 
 non_val_count=$(cat "${runs_json}" | jq '[select(.[].status != "Validated")] | length')
@@ -37,16 +38,20 @@ done > "${create_job}"
 chmod +x "${create_job}"
 
 echo "[INFO] Executing job script (runtime depends on amount of samples, check progress in log '${create_log}')"
-cat ${create_job} | parallel -j5 -I% --max-args 1 % > ${create_log} 2>&1
+cat "${create_job}" | parallel -j5 -I% --max-args 1 % > "${create_log}" 2>&1
 
 echo "[INFO] Printing any non INFO lines from log"
-cat ${create_log} | grep -v '\[INFO\]'
+cat "${create_log}" | grep -v '\[INFO\]'
 
-echo "[INFO] Checking log for errors with check_log_file (will print if any found)"
+echo "[INFO] Double checking log for errors with check_log_file (will print if any found)"
 check_log_file "${create_log}"
 
 echo "[INFO] Joining all run aria.txt files to ${out_config}"
-find ${output_dir} -mindepth 1 -maxdepth 1 -type f -name "*_*.aria.txt" -exec cat {} \+ > "${out_config}"
+find "${output_dir}" -mindepth 1 -maxdepth 1 -type f -name "*_*.aria.txt" -exec cat {} \+ > "${out_config}"
+
+echo "[INFO] Joining all run aria.txt files to ${out_config}"
+# Intellij wants you to quote the find cmd: do not do this because du will see all files as one string
+gsutil du -shc $(find "${output_dir}" -name "*.url" -exec cut -f1 {} \;) > "${out_gcp_du}"
 
 echo "[INFO] Action: Check one URL manually in browser"
 cat "${out_config}" | grep https | tail -1
