DEV-1277: various changes to support LIMS v4.4

diff --git a/lims/sync_lab_lims_from_nas b/lims/sync_lab_lims_from_nas
--- a/lims/sync_lab_lims_from_nas
+++ b/lims/sync_lab_lims_from_nas
@@ -2,29 +2,29 @@
 
 ## setup main variables
 DATESTR="$(date '+%y%m%d')"
-NAS_DIR="/volume1/machines/LIMS"
-OUT_DIR="/data/lims"
-LAB_DIR="${OUT_DIR}/labfiles"
+NAS_DIR="/volume1/sync_from_infracom"
+OUT_DIR="/data/ops/lims/"
+LAB_DIR="${OUT_DIR}/lab_files"
 DAY_DIR="${LAB_DIR}/${DATESTR}"
-SYM_DIR="${OUT_DIR}/latest"
+SYM_DIR="${LAB_DIR}/latest"
 ACC2CSV="/data/common/tools/access2csv_v190415/target/appassembler/bin/access2csv"
 
 TEST_FILE='LIMS_pilot_be.accdb'
-CPCT_FILE='LIMS_v4.3_be.accdb'
+CPCT_FILE='LIMS_v4.4_be.accdb'
 SAMP_FILE='HMF-FOR-001 Received Samples 2020 v5.6.xlsx'
 PROC_FILE='HMF-FOR-002 Sample in process 2020 v4.2.xlsx'
 SAMP_FILE_2019='HMF-FOR-001 Received Samples 2019 v5.5.xlsx'
 PROC_FILE_2019='HMF-FOR-002 Sample in process 2019 v4.1.xlsx'
 
-TEST_NAS_PATH="${NAS_DIR}/${TEST_FILE}"
-CPCT_NAS_PATH="${NAS_DIR}/${CPCT_FILE}"
+TEST_NAS_PATH="${NAS_DIR}/04 Current backend/${TEST_FILE}"
+CPCT_NAS_PATH="${NAS_DIR}/04 Current backend/${CPCT_FILE}"
 SAMP_NAS_PATH="${NAS_DIR}/${SAMP_FILE}"
 PROC_NAS_PATH="${NAS_DIR}/${PROC_FILE}"
 SAMP_NAS_PATH_2019="${NAS_DIR}/${SAMP_FILE_2019}"
 PROC_NAS_PATH_2019="${NAS_DIR}/${PROC_FILE_2019}"
 
 ## File and dir sanity checks
-if ssh nas "[[ ! -d ${NAS_DIR} ]]"; then echo "[ERROR] Dir does not exist (nas:${NAS_DIR})" && exit 1; fi
+if ssh nas "[[ ! -d "${NAS_DIR}" ]]"; then echo "[ERROR] Dir does not exist (nas:${NAS_DIR})" && exit 1; fi
 for nasFilePath in "$TEST_NAS_PATH" "$CPCT_NAS_PATH" "$SAMP_NAS_PATH" "$PROC_NAS_PATH" "$SAMP_NAS_PATH_2019" "$PROC_NAS_PATH_2019"; do
     if ssh nas "[[ ! -f '${nasFilePath}' ]]"; then echo "[ERROR] File does not exist (nas:${nasFilePath})" && exit 1; fi
 done
@@ -36,7 +36,7 @@ mkdir -p ${DAY_DIR}
 
 ## Setup file variables
 testSource="${DAY_DIR}/${TEST_FILE}"
-testTarget="${DAY_DIR}/${DATESTR}_LimsCPCTtrackTest.accdb"
+testTarget="${DAY_DIR}/${DATESTR}_LimsCPCTtrackPilot.accdb"
 testTxt="${testTarget}.csv"
 testLatest="${SYM_DIR}/lims_test"
 
@@ -135,7 +135,7 @@ xlsx2csv -d "\t" "${procTarget2019}" -s 1 | tail -n +5 > ${procTxt2019}
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] PROC export to csv FAILED" && exit 1; fi
 
 ## Create latest symlinks
-echo "[INFO] Symlinking to latest files"
+echo "[INFO] Symlinking to latest files (to ${SYM_DIR})"
 echo "[INFO]   $testLatest"
 ln -sfn $testTxt $testLatest
 echo "[INFO]   $cpctLatest"
