one cp cmd per lama json to avoid issues when export is running

diff --git a/lims/sync_lab_lims_from_nas b/lims/sync_lab_lims_from_nas
--- a/lims/sync_lab_lims_from_nas
+++ b/lims/sync_lab_lims_from_nas
@@ -58,7 +58,9 @@ main() {
     done
 
     info "Retrieving LAMA input files from bucket (${LAMA_BUCKET})"
-    echo "${LAMA_FILES[@]}" | tr " " "\n" | gsutil -m cp -I "${DAY_DIR}"
+    for lama_json_file in "${LAMA_FILES[@]}"; do
+      gsutil cp "$lama_json_file" "${DAY_DIR}" || die "Unable to copy file ($lama_json_file)"
+    done
 
     info "Converting input files to text formats"
     excel_sheet_to_tsv "${for001_source}" "${for001_subm_txt}" "1" "5"
@@ -82,7 +84,7 @@ excel_sheet_to_tsv() {
     local excel_name=""
     excel_name=$(basename "${input_excel_file}")
 
-    info "  Converting '${excel_name}' sheet ${sheet_index} with ${skip_rows} header rows"
+    info "  Converting '${excel_name}' sheet ${sheet_index} with ${skip_rows} header rows (${output_tsv})"
     xlsx2csv -d "\t" "${input_excel_file}" -s "${sheet_index}" | tail -n +"${skip_rows}" > "${output_tsv}"
     [[ $? -eq 0 ]] || die "Excel conversion to tsv FAILED (${sheet_index})"
 }
diff --git a/lims/sync_lab_lims_from_nas_pilot b/lims/sync_lab_lims_from_nas_pilot
--- a/lims/sync_lab_lims_from_nas_pilot
+++ b/lims/sync_lab_lims_from_nas_pilot
@@ -59,7 +59,9 @@ main() {
     done
 
     info "Retrieving LAMA input files from bucket (${LAMA_BUCKET})"
-    echo "${LAMA_FILES[@]}" | tr " " "\n" | gsutil -m cp -I "${DAY_DIR}"
+    for lama_json_file in "${LAMA_FILES[@]}"; do
+      gsutil cp "$lama_json_file" "${DAY_DIR}" || die "Unable to copy file ($lama_json_file)"
+    done
 
     info "Converting input files to text formats"
     excel_sheet_to_tsv "${for001_source}" "${for001_subm_txt}" "1" "5"
