Added retrieval of pilot/test lims

diff --git a/lims/sync_lab_lims_from_nas b/lims/sync_lab_lims_from_nas
--- a/lims/sync_lab_lims_from_nas
+++ b/lims/sync_lab_lims_from_nas
@@ -9,12 +9,14 @@ DAY_DIR="${LAB_DIR}/${DATESTR}"
 SYM_DIR="${OUT_DIR}/latest"
 ACC2CSV="/data/common/tools/access2csv_v190415/target/appassembler/bin/access2csv"
 
+TEST_FILE='LIMS_pilot_be.accdb'
 CPCT_FILE='LIMS_v4.3_be.accdb'
 SAMP_FILE='HMF-FOR-001 Received Samples 2020 v5.6.xlsx'
 PROC_FILE='HMF-FOR-002 Sample in process 2020 v4.2.xlsx'
 SAMP_FILE_2019='HMF-FOR-001 Received Samples 2019 v5.5.xlsx'
 PROC_FILE_2019='HMF-FOR-002 Sample in process 2019 v4.1.xlsx'
 
+TEST_NAS_PATH="${NAS_DIR}/${TEST_FILE}"
 CPCT_NAS_PATH="${NAS_DIR}/${CPCT_FILE}"
 SAMP_NAS_PATH="${NAS_DIR}/${SAMP_FILE}"
 PROC_NAS_PATH="${NAS_DIR}/${PROC_FILE}"
@@ -23,7 +25,7 @@ PROC_NAS_PATH_2019="${NAS_DIR}/${PROC_FILE_2019}"
 
 ## File and dir sanity checks
 if ssh nas "[[ ! -d ${NAS_DIR} ]]"; then echo "[ERROR] Dir does not exist (nas:${NAS_DIR})" && exit 1; fi
-for nasFilePath in "$CPCT_NAS_PATH" "$SAMP_NAS_PATH" "$PROC_NAS_PATH" "$SAMP_NAS_PATH_2019" "$PROC_NAS_PATH_2019"; do
+for nasFilePath in "$TEST_NAS_PATH" "$CPCT_NAS_PATH" "$SAMP_NAS_PATH" "$PROC_NAS_PATH" "$SAMP_NAS_PATH_2019" "$PROC_NAS_PATH_2019"; do
     if ssh nas "[[ ! -f '${nasFilePath}' ]]"; then echo "[ERROR] File does not exist (nas:${nasFilePath})" && exit 1; fi
 done
 for outdir in $OUT_DIR $LAB_DIR $SYM_DIR; do
@@ -33,6 +35,11 @@ done
 mkdir -p ${DAY_DIR}
 
 ## Setup file variables
+testSource="${DAY_DIR}/${TEST_FILE}"
+testTarget="${DAY_DIR}/${DATESTR}_LimsCPCTtrackTest.accdb"
+testTxt="${testTarget}.csv"
+testLatest="${SYM_DIR}/lims_test"
+
 cpctSource="${DAY_DIR}/${CPCT_FILE}"
 cpctTarget="${DAY_DIR}/${DATESTR}_LimsCPCTtrack.accdb"
 cpctTxt="${cpctTarget}.csv"
@@ -66,6 +73,7 @@ procLatest2019="${SYM_DIR}/2019_proc"
 echo "[INFO] Syncing LIMS files from NAS to DATASTORE"
 echo "[INFO]   SourceDir: nas:${NAS_DIR}"
 echo "[INFO]   TargetDir: ${DAY_DIR}"
+rsync -s "nas:${TEST_NAS_PATH}" ${DAY_DIR}
 rsync -s "nas:${CPCT_NAS_PATH}" ${DAY_DIR}
 rsync -s "nas:${SAMP_NAS_PATH}" ${DAY_DIR}
 rsync -s "nas:${PROC_NAS_PATH}" ${DAY_DIR}
@@ -75,13 +83,14 @@ rsync -s "nas:${PROC_NAS_PATH_2019}" ${DAY_DIR}
 ## Make sure all required files are present
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] Error with RSYNC from NAS, please check " && exit 1; fi
 
-for inputFile in "${cpctSource}" "${sampSource}" "${procSource}"; do
+for inputFile in "${testSource}" "${cpctSource}" "${sampSource}" "${procSource}"; do
     if [[ ! -f "${inputFile}" ]]; then
         echo "[ERROR] Input file from NAS not present (${inputFile})" && exit 1;
     fi
 done
 
 ## Symlink LIMS files to create stable naming for downstream work
+ln -sfn "${testSource}" "${testTarget}"
 ln -sfn "${cpctSource}" "${cpctTarget}"
 ln -sfn "${sampSource}" "${sampTarget}"
 ln -sfn "${procSource}" "${procTarget}"
@@ -92,6 +101,11 @@ ln -sfn "${procSource2019}" "${procTarget2019}"
 
 ## Convert to text format
 echo "[INFO] Converting input files to CSV/TSV"
+
+echo "[INFO]   Converting $( basename ${testTarget} )"
+${ACC2CSV} --with-header --input "${testTarget}" --output ${DAY_DIR} --table tblSamples --quote-all false
+if [[ ! $? -eq 0 ]]; then echo "[ERROR] TEST export to csv FAILED" && exit 1; fi
+mv ${DAY_DIR}/tblSamples.csv ${testTxt}
 echo "[INFO]   Converting $( basename ${cpctTarget} )"
 ${ACC2CSV} --with-header --input "${cpctTarget}" --output ${DAY_DIR} --table tblSamples --quote-all false
 if [[ ! $? -eq 0 ]]; then echo "[ERROR] CPCT export to csv FAILED" && exit 1; fi
@@ -122,6 +136,8 @@ if [[ ! $? -eq 0 ]]; then echo "[ERROR] PROC export to csv FAILED" && exit 1; fi
 
 ## Create latest symlinks
 echo "[INFO] Symlinking to latest files"
+echo "[INFO]   $testLatest"
+ln -sfn $testTxt $testLatest
 echo "[INFO]   $cpctLatest"
 ln -sfn $cpctTxt $cpctLatest
 echo "[INFO]   $submLatest"
@@ -143,7 +159,7 @@ ln -sfn $procTxt2019 $procLatest2019
 
 ## Gather some metrics
 echo "[INFO] Stats:"
-for latestFile in $cpctLatest $submLatest $sampLatest $contLatest $procLatest; do
+for latestFile in $testLatest $cpctLatest $submLatest $sampLatest $contLatest $procLatest; do
     totalLines=$(cat $latestFile | wc -l)
     echo "[INFO]   LineCount of ${latestFile} = ${totalLines}"
 done
