extend verify_lims with counts and barcodes

diff --git a/lims/verify_lims b/lims/verify_lims
--- a/lims/verify_lims
+++ b/lims/verify_lims
@@ -5,33 +5,47 @@ source message_functions || exit 1
 JSON1=${1:-"/data/ops/lims/prod/lims.json"}
 JSON2=${2:-"/data/ops/lims/pilot/lims.json"}
 
+COUNT_TYPES=(contact_groups submissions samples)
+BARCODES=(FR16602097 FR16602093 FR30694896)
 SUBMISSIONS=(HMFreg0481 HMFreg1511 HMFreg1527)
 CONTACT_GROUPS=(PT-003-102 EMC-003-103-PTO UMCU-003-101-PTO)
 
 main (){
     info "Verifying a selection of object between two JSONs"
-    info "  LIMS json 1: $JSON1"
-    info "  LIMS json 2: $JSON2"
+    info "  LIMS json 1: ${JSON1}"
+    info "  LIMS json 2: ${JSON2}"
+
+    info "Verifying counts per type"
+    for count_type in "${COUNT_TYPES[@]}"; do
+        count_records_by_type "${count_type}"
+    done
 
     info "Verifying submissions"
     for submission_id in "${SUBMISSIONS[@]}"; do
-        diff_submission "$submission_id"
+        diff_submission "${submission_id}"
     done
 
     info "Verifying contact groups"
     for contact_id in "${CONTACT_GROUPS[@]}"; do
-        diff_contact "$contact_id"
+        diff_contact "${contact_id}"
+    done
+
+    info "Verifying samples (by barcode)"
+    for barcode in "${BARCODES[@]}"; do
+        diff_barcode "${barcode}"
     done
 }
 
+diff_barcode() {
+    diff_object samples barcode "$1"
+}
+
 diff_submission() {
-    local submission_id=$1 && shift
-    diff_object submissions submission "$submission_id"
+    diff_object submissions submission "$1"
 }
 
 diff_contact() {
-    local group_id=$1 && shift
-    diff_object contact_groups group_id "$group_id"
+    diff_object contact_groups group_id "$1"
 }
 
 diff_object() {
@@ -39,19 +53,32 @@ diff_object() {
     local id_field=$1 && shift
     local id=$1 && shift
 
-    info_string="type=$type, field=$id_field, id=$id"
+    info_string="type=${type}, field=${id_field}, id=${id}"
 
-    one=$(query_lims.pl -lims "$JSON1" -type "$type" -filter "${id_field}=${id}" -exact -json) \
+    one=$(query_lims.pl -lims "${JSON1}" -type "${type}" -filter "${id_field}=${id}" -exact -json) \
       || die "Querying LIMS JSON 1 failed ($info_string)"
 
-    two=$(query_lims.pl -lims "$JSON2" -type "$type" -filter "${id_field}=${id}" -exact -json) \
-      || die "Querying LIMS JSON 2 failed ($info_string)"
+    two=$(query_lims.pl -lims "${JSON2}" -type "${type}" -filter "${id_field}=${id}" -exact -json) \
+      || die "Querying LIMS JSON 2 failed (${info_string})"
 
-    diff_count=$(diff <(jq -S <<< "$one") <(jq -S <<< "$two") | wc -l)
-    if [[ "$diff_count" -eq 0 ]]; then
-        info "  OK ($info_string)"
+    diff_count=$(diff <(jq -S <<< "${one}") <(jq -S <<< "${two}") | wc -l)
+    if [[ "${diff_count}" -eq 0 ]]; then
+        info "  OK (${info_string})"
     else
-        warn "  FAIL ($info_string)"
+        warn "  FAIL (${info_string})"
+    fi
+}
+
+count_records_by_type() {
+    local type=$1 && shift
+    info_string="type=${type}"
+    one=$(query_lims.pl -lims "${JSON1}" -type "${type}" | grep -cv '^#') || die "Querying LIMS JSON 1 failed ($info_string)"
+    two=$(query_lims.pl -lims "${JSON2}" -type "${type}" | grep -cv '^#') || die "Querying LIMS JSON 2 failed ($info_string)"
+    count_diff=$((two - one))
+    if [[ "${count_diff}" -eq 0 ]]; then
+        info "  OK ($one records found in both for type ${info_string})"
+    else
+        warn "  FAIL ($one vs $two records found for type ${info_string})"
     fi
 }
 
